### ISSUE TITLE
[FEATURE]知识库增加URL导入

### ISSUE THREAD

**Issue by AAEE86** [1Panel-dev/MaxKB#1003]
### MaxKB 版本

1.4.1

### 请描述您的需求或者改进建议

希望增加可以从网页导入的功能

**Comment by baixin513** [comment]
感谢反馈，您可以使用web站点知识库
<img width="999" alt="image" src="https://github.com/user-attachments/assets/74776f8a-e864-405a-b981-d2dfd750f47b">
