### ISSUE TITLE
[BUG] 修改了网站名称，但每次刷新网页的时候，还会显示默认的maxkb的名字。

### ISSUE THREAD

**Issue by hao65103940** [1Panel-dev/MaxKB#1010]
### MaxKB 版本

 v1.4.1 

### 问题描述

专业版 修改了网站名称，但每次刷新网页的时候，还会显示默认的maxkb的名字。
![image](https://github.com/user-attachments/assets/ed96dc32-5ebe-44a0-9299-2dacf82db9be)

https://github.com/user-attachments/assets/781f2f88-7821-49fa-bd29-1105057e51a7

### 重现步骤

同上

### 期待的正确结果

再刷新页面的时候，显示自定义的名字

**Comment by baixin513** [comment]
感谢反馈，我们排查一下。
