### ISSUE TITLE
[FEATURE]小窗口打开 太慢了

### ISSUE THREAD

**Issue by sakura1412** [1Panel-dev/MaxKB#102]
### MaxKB 版本

1.0

### 请描述您的需求或者改进建议

抛开事实和网速不提

**Comment by sakura1412** [comment]
小窗口打开 太慢了

**Comment by baixin513** [comment]
麻烦给个操作的视频，或详细一点的操作步骤截图来排查一下。

**Comment by sakura1412** [comment]
![WeChat3fa7a35bc453acdf2c2efbe90c922af3](https://github.com/1Panel-dev/MaxKB/assets/37284969/d991b266-2c1e-41d2-9ec1-bb56f4dc7b16)
我觉得这种加载慢的问题，不是我的问题

**Comment by baixin513** [comment]
这就是网速慢导致的。
