### ISSUE TITLE
[FEATURE]能否增加视频文件上传本地知识库

### ISSUE THREAD

**Issue by dlluckboy** [1Panel-dev/MaxKB#1027]
### MaxKB 版本

v1.4.1

### 请描述您的需求或者改进建议

希望能支持上传视频文件到本地知识库，可以支持查询类似拆装录像视频。

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，目前还没有计划呢。
不过你可以在知识库中嵌入视频链接。
