### ISSUE TITLE
[FEATURE]【知识库】分段管理页面支持批量删除段落

### ISSUE THREAD

**Issue by luyang351** [1Panel-dev/MaxKB#103]
### MaxKB 版本

v1.0.0

### 请描述您的需求或者改进建议

建议支持批量删除段落。
场景：当同步在线文档后，自动拉取的多个子页面均存在相同的段落块，是无用的，想删除时需要一个一个删，较麻烦。
![image](https://github.com/1Panel-dev/MaxKB/assets/48945409/fb260d11-018a-4357-b38f-6ff227f7ee2b)

### 请描述你建议的实现方案

支持勾选多个段落后批量删除。

**Comment by baixin513** [comment]
感谢反馈，后面排期优化，请关注后期版本更新。
