### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AIMO3D-ob** [1Panel-dev/MaxKB#1035]
### MaxKB 版本

1.4

### 问题描述

通過API創建一個對話成功后，用瀏覽器携帶鑒權信息，打開會顯示這個
![image](https://github.com/user-attachments/assets/607d445a-d9bb-49bd-911e-727a478e8e76)

代碼如下： 

### 重现步骤

 private void OpenChatInBrowser(string appId, string chatId)
    {
        try
        {
            string baseUrl = "https://db.zhai-zhai.com";
            string uiUrl = $"{baseUrl}/ui/chat/{appId}";

            string htmlContent = $@"
<html>
<head>
    <title>正在重定向...</title>
    <script>
        console.log('开始执行脚本');
        
        // 设置认证信息
        localStorage.setItem('AUTHORIZATION', '{ApiKey}');
        localStorage.setItem('APPLICATION_ID', '{appId}');
        localStorage.setItem('CHAT_ID', '{chatId}');
        console.log('已设置认证信息');

        // 直接重定向到聊天页面
        window.location.href = '{uiUrl}';
    </script>
</head>
<body>
    正在重定向到聊天页面，请稍候...
</body>
</html>";

### 期待的正确结果

可以用API生成對話，然後瀏覽器打開對話歷史

**Comment by shaohuzhang1** [comment]
你的操作错误，你自己排查一下
