### ISSUE TITLE
[FEATURE] 小助手气泡投影有点显脏，可以再调整一下哟

### ISSUE THREAD

**Issue by fanfan1233** [1Panel-dev/MaxKB#105]
### MaxKB 版本

v2

### 请描述您的需求或者改进建议

小助手气泡投影有点显脏，可以再调整一下哟·

### 附加信息

<img width="1727" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/135687942/233e3f9e-36f1-46fe-b302-59084d70f557">

**Comment by baixin513** [comment]
感谢反馈，我们调干净一些。
