### ISSUE TITLE
[FEATURE]集成商用MaxKB集成交付，需要隐藏掉 右上角 “项目地址” “用户手册”  “论坛求助” 等信息

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1053]
### MaxKB 版本

v.1.4.1

### 请描述您的需求或者改进建议

集成商用MaxKB集成交付，需要隐藏掉 右上角 “项目地址” “用户手册”  “论坛求助” 等信息。
对集成商来说是合理需求。
<img width="178" alt="1724809364751" src="https://github.com/user-attachments/assets/3a14fb62-554f-4efb-a7ca-06a6fd962c70">

### 请描述你建议的实现方案

把 右上角 “项目地址” “用户手册”  “论坛求助” ，关于授权页面，做成可配置选项，集成商可以配置不显示。

**Comment by xusongtao** [comment]
老师，同场景下还有一个衍生的需求，每次新建应用时默认的“应用描述”、“提示词”、“开场白”中也有MaxKB的字眼，能否考虑自定义默认配置
