### ISSUE TITLE
[FEATURE]目前支持纯文字的回答，希望可以支持带图片的回答，更加直观

### ISSUE THREAD

**Issue by yayanpei-fit2cloud** [1Panel-dev/MaxKB#106]
### MaxKB 版本

v1.0

### 请描述您的需求或者改进建议

<img width="442" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/84168063/09023fe0-cbb8-40c4-8b18-3236c85e0df2">

**Comment by baixin513** [comment]
感谢反馈，回答内容是否有图片取决于以下两点：
1、知识库中维护的内容是否有图片。目前 MaxKB 是支持在线图片，也支持输出图片。
2、还取决于LLM模型，一般 LLM 模型会把图片过滤不返回，可以研究一下通过调整提示词来输出在线图片。
