### ISSUE TITLE
[FEATURE]建议增加追问功能

### ISSUE THREAD

**Issue by xusongtao** [1Panel-dev/MaxKB#1066]
### MaxKB 版本

1.5.0

### 请描述您的需求或者改进建议

在用户问完一个问题并得到答案后，增加追问的功能，列出几个对方可能关心的问题，用户点击问题能继续问答

### 请描述你建议的实现方案

在用户问完一个问题并得到答案后，增加追问的功能，列出几个对方可能关心的问题，用户点击问题能继续问答

**Comment by baixin513** [comment]
感谢反馈，当前高级编排应用中可以实现你想要的效果。

在每条工作流的末尾，增加一个生成追问的AI对话节点，注意该节点的返回内容也要打开，提示词如下（可根据效果自行调整）：
用户问题：{{开始.question}}
回答：{{AI 对话.answer}}
根据这段内容推测用户接下来想要问的3个问题，要求只输出问题，并将问题放在<quick_question></quick_question>标签中


工作流编排如下图：
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/35f626c8-d658-4caa-a02b-552a24334905">

提问效果如下图：
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/6eb1b508-3f9b-4568-894e-2c722ce9c940">
