### ISSUE TITLE
[FEATURE] 【AI高级编排】增加变量聚合

### ISSUE THREAD

**Issue by mingdiantianxia** [1Panel-dev/MaxKB#1068]
### MaxKB 版本

1.5.0

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/334854fb-1085-4f72-87ef-827e4a3b69e8)

### 请描述你建议的实现方案

多个分支的结果，最终输出同一个变量，简化ai编排流程

**Comment by baixin513** [comment]
感谢反馈，多路聚合会增大变量引用错误几率，出错率太高，暂时还不考虑呢。

**Comment by mingdiantianxia** [comment]
多路聚合，最终的结果也只是一个列表，只需要按顺序取第一个非none的值不就行了，怎么就会不行了呢？
最实用的功能之一了。想象一下，一个文本要建立几十个重复的流程组件？而用dify的聚合器，参数复用，工作流更容易管理和编辑，真实的生产场景置之不理，无法理解。
