### ISSUE TITLE
[FEATURE]模型设置优化

### ISSUE THREAD

**Issue by AAEE86** [1Panel-dev/MaxKB#1069]
### MaxKB 版本

1.5.0

### 请描述您的需求或者改进建议

将模型类型和基础模型下拉样式改成多选框，这样可以一次添加多个模型非常方便！（记得加上全选按钮）

**Comment by baixin513** [comment]
感谢反馈，添加模型表单无法批量添加模型。同一用户下模型名称不能重复。

**Comment by AAEE86** [comment]
> 感谢反馈，添加模型表单无法批量添加模型。同一用户下模型名称不能重复。

模型名称直接使用模型本身的名称就可以

单供应商的Url和Key都是一样的，不能批量添加很麻烦

还是说有其他优化方案？@baixin513

**Comment by baixin513** [comment]
模型名称自动用基础模型会有另外的问题啊，如果已存在这个模型，不同的URL和key，也会冲突啊。

**Comment by AAEE86** [comment]
> 模型名称自动用基础模型会有另外的问题啊，如果已存在这个模型，不同的URL和key，也会冲突啊。

好吧，我的想是既然已经内置了模型供应商，那应该尽可能方便的添加供应商下的所有模型，而不是一个个添加。参考Dify那样。
