### ISSUE TITLE
一个很成熟的优化建议

### ISSUE THREAD

**Issue by sakura1412** [1Panel-dev/MaxKB#107]
### MaxKB 版本

1

### 请描述您的需求或者改进建议

![WeChat26246d69da3624dcb2974dbbc964350b](https://github.com/1Panel-dev/MaxKB/assets/37284969/54a1b308-2e18-4a72-9ab5-fda4006e49fc)   其他产品的这种小窗口，打开以后，图标变成了“X” 如果用户不像用小窗，关闭操作的提示很直观。

### 请描述你建议的实现方案

建议未打开的时候，是机器人图标，打开以后，机器人图标变成“X”

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by baixin513** [comment]
已经在 V1.2.0 版本优化
