### ISSUE TITLE
[BUG]异常get_num_tokens_from_messages()

### ISSUE THREAD

**Issue by zy84338719** [1Panel-dev/MaxKB#1070]
### MaxKB 版本

 v1.5.0

### 问题描述

"content": "异常get_num_tokens_from_messages() is not presently implemented for model cl100k_base. See https://platform.openai.com/docs/guides/text-generation/managing-tokens for information on how messages are converted to tokens.",

### 重现步骤

请求api 接口返回数据如下

### 期待的正确结果

正确返回

**Comment by baixin513** [comment]
感谢反馈，确认bug， 今天修复。
