### ISSUE TITLE
[BUG] 高级编排时，有成功命中数据，但是回答仍然有误

### ISSUE THREAD

**Issue by 1Yunzong** [1Panel-dev/MaxKB#1079]
### 联系方式

云纵

### MaxKB 版本

v1.5.0

### 问题描述

高级编排
当知识库设置为直接回答时，容易出现三种情况。第一种，阈值设置合适，只有一个分段超过阈值，能正常回答。第二种，阈值过高，没有分段超过阈值，导致AI回答的结果有错误。第三种，多个分段超过阈值，此时回答时仍会出现错误，或者过多引用分段。
此时需要怎么优化呢？
![image](https://github.com/user-attachments/assets/28c727bc-3deb-47af-8846-01c22b1b95ea)
![image](https://github.com/user-attachments/assets/9c9b4a56-c976-44e1-bff5-4b99dad33c48)
![image](https://github.com/user-attachments/assets/29f8ee13-6fa8-46db-86d0-cf4f6cd0a36b)
![image](https://github.com/user-attachments/assets/7de2bc99-5db4-4da2-a141-96edab56831e)
![image](https://github.com/user-attachments/assets/6a4c37ef-4b0d-4e86-b927-766403265aca)

### 重现步骤

知识库

**Comment by 1Yunzong** [comment]
但是如果在简单编排中提相同问题，即使还是存在相同三种情况，但是仍然能正常回答。

**Comment by shaohuzhang1** [comment]
因为在高级编排里面使用的分段是没有标题的,所以你在提示词里面应该这样写
下面是获取知识库检索节点标题加段落内容的文本,把{{ 知识库检索.data}}替换成这个:
```
{% for item in 知识库检索.paragraph_list %}
{{ item['title']+':'+item['content'] }}
{% endfor %}
```

**Comment by 1Yunzong** [comment]
谢谢您的建议。 但是修改提示词后，搭配“知识库 直接回答，可以回答，但是回答的内容有多余部分。请问如何进一步提升回答准确度？
![image](https://github.com/user-attachments/assets/4fcdb3d7-7f52-45a0-8dfc-d1a3295f29ff)


我采取的策略是 改为直接命中，设置为0.87，这样可以保障CH326检索通过
![image](https://github.com/user-attachments/assets/3380eefd-b8c2-4236-81b1-0410dfacaa4d)

但是 当前检索H10682时，仍会出现 之前类似的局面，回答部分有很多余部分。
![image](https://github.com/user-attachments/assets/0f759735-c7fb-4f30-8246-93164b27a9d9)

所以最后还是回答了原始问题，当知识库设置为直接回答，将存在三种情况，当知识库设置为优化，回答质量又不高。

**Comment by shaohuzhang1** [comment]
我的建议是把这些放在一个段落里面,比如10个放在一个段落里面或者20个放在一个段落里面

**Comment by 1Yunzong** [comment]
> 我的建议是把这些放在一个段落里面,比如10个放在一个段落里面或者20个放在一个段落里面
不好意思，没有太理解您的意思。您能再详细介绍下吗？
简单配置 能够正常回答。
![pure简单配置](https://github.com/user-attachments/assets/05021f05-c051-4540-8030-090c6a32338d)

**Comment by shaohuzhang1** [comment]
提示词问题,如果建议配置可以那就是提示词的问题,可以把建议配置的提示词回答要求复制到工作流里面
