### ISSUE TITLE
[BUG]【应用】问答页面用户提问时，只输入空格不能发送

### ISSUE THREAD

**Issue by BBchicken-9527** [1Panel-dev/MaxKB#108]
### MaxKB 版本

1.0

### 问题描述

登录de官网并在输入框输入空格发送
![image](https://github.com/1Panel-dev/MaxKB/assets/84372766/ec7939cf-8b9e-43ff-b08e-06d295be8c5e)

### 重现步骤

登录de官网并在输入框输入空格发送

### 期待的正确结果

期望优化用户输入为空时的现实样式以及优化无空时的回复；

**Comment by baixin513** [comment]
感谢反馈，确认为 BUG，后面版本修复。
