### ISSUE TITLE
[FEATURE]1.5.1版本中的AI模型最大输出token数过小

### ISSUE THREAD

**Issue by gundamwing01** [1Panel-dev/MaxKB#1081]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

1.5开始的新版本中，对AI模型能够设置温度与最大输出token，但目前最大输出token是4096，这个数值偏小。希望能够让用户自定义。因为每个模型的输出token是不同的，例如qwen系列，可以设到8192。Gemini系列的也可以设到8K-16K。输出Token数过小，对于使用来讲会受到制约。
![image](https://github.com/user-attachments/assets/c55aef2f-704f-4d1c-ab64-eb4f068edbbf)

### 请描述你建议的实现方案

希望能够将AI模型的最大输出token数设定为自定义，由用户根据不同AI模型的输出参数来填写，而不是设4096这个上限。目前已知其他平台对输出token的上限基本都设在8K及以上。

### 附加信息

![image](https://github.com/user-attachments/assets/1de13d64-1643-4d99-b3e0-d833dada9d3e)
![image](https://github.com/user-attachments/assets/c4439a15-b99b-4178-9ae1-9535594da832)

**Comment by baixin513** [comment]
感谢反馈，后续版本放大限制。
