### ISSUE TITLE
[FEATURE]是否考虑增加多模态模型的接入

### ISSUE THREAD

**Issue by gundamwing01** [1Panel-dev/MaxKB#1082]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

目前能够添加的模型基本为大语言模型，但现在的对话模式中，无法通过上传附件来对非知识库内的内容进行解析和理解。例如单个文档、图片。

### 请描述你建议的实现方案

所以希望能够增加多模态模型的支持，能够让对话框中增加上传附件选项。通过接入视觉多模态模型，例如通义千问的VL模型，来实现单资料的解析，然后再通过知识库来进行完整对话。

**Comment by baixin513** [comment]
感谢反馈，后续版本会考虑一下。

**Comment by baixin513** [comment]
v1.8.0 已发布！
