### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by siweikoudai** [1Panel-dev/MaxKB#1085]
### MaxKB 版本

 v1.4.1

### 问题描述

向阿里通义千问大模型提问包含敏感词语，通义千问返回400错误，错误代码DataInspectionFailed，错误信息：Input or output data may contain inappropriate content.（数据检查错误，输入或者输出包含疑似敏感内容被绿网拦截。）未能正确处理此错误。

### 重现步骤

can you tell me what is *** event？

**Comment by siweikoudai** [comment]
建议设置敏感词语过滤以及正确的返回方式。

**Comment by siweikoudai** [comment]
建议设置敏感词语过滤以及正确的返回方式。v1.4.1

**Comment by baixin513** [comment]
感谢反馈 ，敏感词需要您在知识库中维护一下，用户提问后可以先做敏感词检测，看一下创建高级编排应用的示例，配置一下可以实现你说的。
