### ISSUE TITLE
[FEATURE]兼容阿里百炼平台使用app_id参数调用通义千问

### ISSUE THREAD

**Issue by siweikoudai** [1Panel-dev/MaxKB#1087]
### MaxKB 版本

v1.4.1

### 请描述您的需求或者改进建议

兼容阿里百炼平台使用app_id参数调用通义千问https://help.aliyun.com/zh/model-studio/developer-reference/call-alibaba-cloud-model-studio-through-sdk?spm=a2c4g.11186623.0.0.274a4d33YPYIzQ
输入参数 app_id
类型 string
说明 应用标识

**Comment by baixin513** [comment]
感谢反馈，暂时没有计划对接。
