### ISSUE TITLE
[FEATURE]演示时，设置了多轮对话，一直连续提问，是多轮状态。但是如果停留一会，30秒以上，就会清空历史对话，从头开始

### ISSUE THREAD

**Issue by Darren-w** [1Panel-dev/MaxKB#1089]
### MaxKB 版本

1.5..1

### 请描述您的需求或者改进建议

在演示时使用，无法正常保存历史信息，如果在页面上停留一会再次提问。页面上显示历史对话信息就为空了。
![image](https://github.com/user-attachments/assets/ffdd0690-899b-4fa8-98fe-c1a6e3880df2)

**Comment by baixin513** [comment]
感谢反馈，你可以看一下工作流中的AI对话节点的历史对话记录数设置是否为0。0代表不携带历史对话记录。

**Comment by Darren-w** [comment]
AI对话节点的历史对话记录数设置为3，下面是一次对话中历史记录。
这是一直连续提问时前一轮的对话记录，这个时候是正常。
![image](https://github.com/user-attachments/assets/451152e9-8e98-46bf-8505-530274252e6e)

这是停留30秒左右后，这个时候历史对话就清空了。
![image](https://github.com/user-attachments/assets/96e72df4-b736-48db-b424-aa0850b85062)


这个是一个必会出现的bug，并不随机，只要模型输出结束后，演示页面中无操作几十秒时间后，历史对话就会清空，再次接着提问就不会带入之前信息，会重新从第0次累加到我设置的3次。

**Comment by baixin513** [comment]
感谢反馈，确认是bug，后续版本修复。
