### ISSUE TITLE
[BUG]【应用】问答页面在回答中...时，点击停止回答不生效

### ISSUE THREAD

**Issue by BBchicken-9527** [1Panel-dev/MaxKB#109]
### MaxKB 版本

1.0

### 问题描述

在现实回答中...时点击停止回答不生效
![image](https://github.com/1Panel-dev/MaxKB/assets/84372766/829862fc-3611-48b0-b8c8-276c0ee94a89)

### 重现步骤

在现实回答中...时点击停止回答不生效
可以尝试输入一段内容点击重新生成，这时比较好复现；

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。
