### ISSUE TITLE
[FEATURE]函数库获取会话的上下文信息

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1094]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

在函数中希望能获取当前会话的chat_id，client_id、历史消息等上下文信息

### 请描述你建议的实现方案

希望可以作为变量的方式进行读取

**Comment by baixin513** [comment]
感谢反馈，后续版本增加。
