### ISSUE TITLE
[FEATURE]API异步调用和回调

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1096]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

AI回答时间较长，建议API调用支持异步调用，AI执行结束后再回调进行通知，每个支持”返回内容“的消息都可进行回调，这样可以使用更丰富和高效的互动

**Comment by liqiang-fit2cloud** [comment]
后面会支持兼容openai的websocket API。

**Comment by xxyj6450** [comment]
websocket API不适用于许多场景（例如与企微对接）还是麻烦打开这个issue，继续希望有回调功能

**Comment by xxyj6450** [comment]
> 后面会支持兼容openai的websocket API。

websocket API不适用于许多场景（例如与企微对接）还是麻烦打开这个issue，继续希望有回调功能
