### ISSUE TITLE
[FEATURE]流程编排界面的添加函数库列表顶部增加搜索功能

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1097]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

函数多了以后，函数列表很长，需要流程编排界面的添加函数库列表顶部增加搜索功能，可以快速搜索函数名称或描述

**Comment by baixin513** [comment]
感谢反馈，后续版本优化。

**Comment by baixin513** [comment]
v1.7.0已经发布。
