### ISSUE TITLE
[FEATURE]Ollama中能否新增llama-chinese:7b，小主机运行不起来13b

### ISSUE THREAD

**Issue by pre-e** [1Panel-dev/MaxKB#11]
### MaxKB 版本

1

### 请描述您的需求或者改进建议

Ollama中能否新增llama-chinese:7b，小主机运行不起来13b

**Comment by wanghe-fit2cloud** [comment]
基础模型支持用户自定义输入，但需要与供应商的模型名称保持一致，否则会校验失败。

**Comment by m1234ilu** [comment]
感谢，已解决
