### ISSUE TITLE
[FEATURE] 流程编排增加API调用节点

### ISSUE THREAD

**Issue by Monkey-chao** [1Panel-dev/MaxKB#1104]
### MaxKB 版本

1.51

### 请描述您的需求或者改进建议

流程编排能否增加API调用节点，用于对接第三方业务的系统，类似阿里云百炼中的

### 附加信息

![微信截图_20240902225950](https://github.com/user-attachments/assets/11d55ba2-61f1-45fd-8990-d71e5478d642)
![image](https://github.com/user-attachments/assets/6ef026ee-0cd4-4776-b24b-73322a0e91fc)

**Comment by liqiang-fit2cloud** [comment]
目前可以用函数库调用api。
