### ISSUE TITLE
[FEATURE]变量定义、设置和存储、传入、读取功能

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1107]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

在流程编排时支持更丰富的变量功能
1、变量定义与赋值，支持临时变量、持久变量，以使得ai具备更好的记忆力
2、变量的传入，支持接口和嵌入时传入变量

**Comment by baixin513** [comment]
感谢反馈，同issue #1101 ，规划在1.6版本。
