### ISSUE TITLE
[BUG]开启新线程报错

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1110]
### 联系方式

18688639997

### MaxKB 版本

1.5.1

### 问题描述

我希望通过函数节点执行回调并且不阻断流程执行，因此开启了一个新线程，示例代码如下：
`
import threading
import time

def thread_function():
    print("Thread started, sleeping for 5 seconds...")
    time.sleep(5)  # 休眠5秒
    print("Thread finished sleeping.")

# 创建并启动新线程
new_thread = threading.Thread(target=thread_function)
new_thread.start()
`
但该节点执行报错：
![image](https://github.com/user-attachments/assets/daecd589-0ffc-4ade-a835-4d5cdddf171a)

### 重现步骤

添加一个自定义函数节点，粘贴入以上代码，执行工作流调试

### 期待的正确结果

期待以上代码被正确地异步执行，且工作流未被阻断

**Comment by liqiang-fit2cloud** [comment]
由于每个人编程能力和开发环境的差异，开发者在二开过程中遇到的问题项目组没有精力一一协助分析解决，感谢理解。
