### ISSUE TITLE
[FEATURE] 转人工

### ISSUE THREAD

**Issue by maninhill** [1Panel-dev/MaxKB#1113]
### MaxKB 版本

v1.5.1

### 请描述你建议的实现方案

1. 问题输入框上面有个「转人工」提示

<img width="505" alt="image" src="https://github.com/user-attachments/assets/19e26e5a-0ee2-4153-886f-5e025fdb2cfa">

2. 用户点击「转人工」提示后，可以回复：400电话、或者二维码（微信、钉钉、企业微信等的二维码），取决于后台设置人工客服的信息。

**Comment by baixin513** [comment]
感谢反馈，当前版本可以实现上面效果，操作步骤如下：
1、 在应用的开场白 增加一个 【- 我需要人工服务 】的快捷问题 ；
2、 在知识库中配置一个转人工的分段 内容包含二维码图片；
3、 给分段增加关联问题：我需要人工服务。
 
配置后在对话打开对话页面进行提问，效果如下图：
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/4a0119aa-1d48-40d6-90ae-240204b4d6a0">
