### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xgzyyds** [1Panel-dev/MaxKB#1114]
### 联系方式

674232565@qq.com

### MaxKB 版本

社区版v1.5.1

### 问题描述

我在上传的文档内容中，添加了'###'标识符想作为分段标识。上传文档后，我在选择高级分段的分段标识中，选择'###'后，发现系统无法按照'###'进行分段。

### 重现步骤

![QQ截图20240904100234](https://github.com/user-attachments/assets/673b5e47-8f78-4d2d-9d8c-7e0f156c2113)

**Comment by liqiang-fit2cloud** [comment]
把能重现问题的文档贴出来看看。

**Comment by baixin513** [comment]
分段标识是按照md标题的格式进行分段的， 对应文档中的标识是 ###空格 的标识。  如果只用### 需要您写正则表达式。
