### ISSUE TITLE
[BUG] name 'datetime' is not defined

### ISSUE THREAD

**Issue by master1517** [1Panel-dev/MaxKB#1115]
### MaxKB 版本

1.5.1

### 问题描述

将 检索结果分段列表 作为函数参数输入时，会遇到这么一个错误
name 'datetime' is not defined

### 重现步骤

函数参数类型设置为array，来源是 知识库.检索结果的分段列表

### 期待的正确结果

函数内部能够获取到对应的输入
[
	{
		'create_time': datetime.datetime(2024, 8, 26, 12, 39, 32, 879723), 
		'update_time': datetime.datetime(2024, 8, 26, 12, 39, 32, 879724), 
		'id': UUID('30857bce-6365-11ef-a1a7-0242ac110002'), 
		'content': '测试', 
		'title': ' 测试title', 
		'status': '1', 
		'hit_num': 0, 
		'is_active': True, 
		'dataset_id': UUID('8be55614-6361-11ef-a1a7-0242ac110002'), 
		'document_id': UUID('308560c6-6365-11ef-a1a7-0242ac110002'), 
		'dataset_name': '测试dataset', 
		'document_name': '测试文件.md', 
		'hit_handling_method': 'optimization', 
		'directly_return_similarity': 0.9, 
		'similarity': 0.7859833964119332, 
		'is_hit_handling_method': False
	}
]

**Comment by liqiang-fit2cloud** [comment]
把完整的函数贴出来看看。

**Comment by master1517** [comment]
> 把完整的函数贴出来看看。

`
import datetime
from uuid import UUID

def test_func(rag_list):
       return rag_list
`

**Comment by shaohuzhang1** [comment]
输入只能是json字符串,datetime.datetime(2024, 8, 26, 12, 39, 32, 879723)无法被解析

**Comment by YuZiY** [comment]
我目前是使用这个方法来解决的。
![image](https://github.com/user-attachments/assets/80453a5e-9c0d-4ca7-8cb1-3e41fda27513)

**Comment by cksdxz1007** [comment]
所以这个Bug到现在没有修复吗

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
So has this bug not been fixed yet

**Comment by cksdxz1007** [comment]
我即使是用 dateutil 也会报错` Exception:name 'datetime' is not defined`

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Even if I use dateutil, I will report an error ` Exception:name 'datetime' is not defined`
