### ISSUE TITLE
小助手问答区域的宽度不能调整

### ISSUE THREAD

**Issue by Carl-Yao1975** [1Panel-dev/MaxKB#1118]
### MaxKB 版本

 v1.5.1 (build at 2024-08-29T17:29, commit: 30b1bdfe)

### 请描述您的需求或者改进建议

在问答区域，答案以表格形势呈现，但是当字段比较多的时候，因为答案区域的总宽度是固定的，导致字段内容会挤在一起，希望可以增加一个水平滚动条，当内容比较多的时候，可以滚动查看，避免一个单元格里的内容被这行，影响美观。

### 请描述你建议的实现方案

增加水平滚动条。

**Comment by baixin513** [comment]
感谢反馈，对话窗口右上角有个放大的按钮。
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/493e59d9-9098-4e67-bf42-d7c4b437e97f">
