### ISSUE TITLE
[FEATURE]【命中测试】优化未命中分段时的提示内容

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#112]
### MaxKB 版本

1.0.0

### 请描述您的需求或者改进建议
<img width="2169" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/40552640/faaa6d66-88ff-4051-ade0-1fafdd198358">

建议命中测试未命中任何文档时给出合理的提示，这样能确定是未命中而不是网络出问题了

### 请描述你建议的实现方案

提出合理的提示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by baixin513** [comment]
v1.0.3版本已优化。
