### ISSUE TITLE
[BUG] 高级编排中添加多个问题优化组件后报错

### ISSUE THREAD

**Issue by spritelyl** [1Panel-dev/MaxKB#1126]
### 联系方式

14707070227

### MaxKB 版本

 v1.5.1

### 问题描述

高级编排中添加多个问题优化组件后报错

### 重现步骤

1. 高级编排中添加多个问题优化组件
2. 
![image](https://github.com/user-attachments/assets/e65d0d1b-0c55-4776-9aad-1c9af6c97e69)
3. 第三个问题优化组件执行报错
![image](https://github.com/user-attachments/assets/43df8976-ac7c-4b9d-b8d5-36c694d94069)

### 期待的正确结果

执行多个问题优化组件不报错

### 相关日志输出

```shell
Error code: 429 - {'error': {'message': 'Your account cqplliphd0n53l3jurn0<ak-etsooux9zaji11a9sowi> request reached max request: 3, please try again after 1 seconds', 'type': 'rate_limit_reached_error'}}
```

**Comment by liqiang-fit2cloud** [comment]
你这是大模型服务商返回的错误，调用太频繁触发阀值报错了，错误信息里不是写了么，每秒达到3次了，rate_limit_reached_error。
