### ISSUE TITLE
[FEATURE]ISV集成MaxKB到自研系统，对应的邮件模板内容需要可编辑，现在的模板内容是写死了。

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1132]
### MaxKB 版本

v1.5.1

### 请描述您的需求或者改进建议

ISV集成MaxKB到自研系统，对应的邮件模板内容需要可编辑，现在的模板内容是写死了。
见下图：
<img width="389" alt="97cbfed31b58dd3ccc670e1cad37ee6" src="https://github.com/user-attachments/assets/6356ddeb-a30a-4ac1-a440-d599620fe66b">

### 请描述你建议的实现方案

ISV可以安装自己的需要编辑邮件模板。

### 附加信息

<img width="389" alt="97cbfed31b58dd3ccc670e1cad37ee6" src="https://github.com/user-attachments/assets/53c60137-b829-4fdb-bc5e-e0d2166b975c">

**Comment by baixin513** [comment]
修改邮箱模版文件：email_template.html，然后重启容器。

**Comment by 35plus** [comment]
![846ee7bee6e784fb4dc905123046a02](https://github.com/user-attachments/assets/83a14cd3-a995-4dc6-8847-03bc27c2f948)

邮件标题被写死了。
