### ISSUE TITLE
[FEATURE]  知识库 文档片段编辑优化建议：期望只能点保存或者关闭退出

### ISSUE THREAD

**Issue by xhy12** [1Panel-dev/MaxKB#1134]
### MaxKB 版本

1.5

### 请描述您的需求或者改进建议

目前点击编辑区域空白处回关闭窗口， 期望只能点保存或者关闭退出

![image](https://github.com/user-attachments/assets/7f32da1a-cf68-4eb9-9e75-ab84ad02d7da)

### 请描述你建议的实现方案

 期望只能点保存或者关闭退出

**Comment by baixin513** [comment]
感谢反馈，后续版本优化
