### ISSUE TITLE
[FEATURE]显示知识来源的引用分段 中点击文档名称可以跳转。

### ISSUE THREAD

**Issue by wangchuancao** [1Panel-dev/MaxKB#1137]
### MaxKB 版本

 v1.5.1

### 请描述您的需求或者改进建议

![dedf8d866c58a566e1924842420c98a](https://github.com/user-attachments/assets/9f8b8c9c-d754-49e6-8d0c-889aaeeb36d9)
这里显示知识来源的时候，可以显示在线文档直接的url地址吗，我的知识库用的是在线文档爬取的

### 请描述你建议的实现方案

可以加一个设置，在知识来源后面的引用分段这里，直接显示原始url标题，点击这个标题就可以跳转原始url页面，或者引用分段，

**Comment by baixin513** [comment]
感谢反馈，后续迭代可以加个跳转。

**Comment by baixin513** [comment]
当前v1.8中 ，web站点知识库的文档有URL的，点击后可以跳转。可以升级到最新版本试用一下。
离线文档无法支持跳转。
