### ISSUE TITLE
[FEATURE]希望在对话日志中编辑回答的答案时支持显示图片且可以再次添加图片

### ISSUE THREAD

**Issue by xusongtao** [1Panel-dev/MaxKB#1140]
### MaxKB 版本

v1.5.1

### 请描述您的需求或者改进建议

管理员在应用的历史对话中查看问题的回答内容时需要再次修改，涉及到图文返回时，在对话日志中直接编辑问题的答案时只显示markdown格式的图片、且无法再次添加图片。希望能在这里显示图片且可以再次添加新图片

### 附加信息

![image](https://github.com/user-attachments/assets/4259a891-ce1e-4369-b78d-a30e4b92e0fe)

**Comment by baixin513** [comment]
感谢反馈，后续版本支持一下。

**Comment by baixin513** [comment]
该功能在V1.6.0中支持。
