### ISSUE TITLE
[FEATURE] 最新版本是否支持自由更换嵌入模型？

### ISSUE THREAD

**Issue by DirtyKnightForVi** [1Panel-dev/MaxKB#1141]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

最新版本是否支持自由更换嵌入模型？

**Comment by liqiang-fit2cloud** [comment]
支持。

**Comment by DirtyKnightForVi** [comment]
> 支持。
离线部署你们的离线包，只有默认的向量模型。更换其他的似乎要访问huggingface。
基于这个包，离线更换向量模型是怎样的步骤？

**Comment by liqiang-fit2cloud** [comment]
https://maxkb.cn/docs/user_manual/model/model/?h=%E5%90%91%E9%87%8F%E6%A8%A1%E5%9E%8B#2
