### ISSUE TITLE
[BUG]MaxKB卸载问题

### ISSUE THREAD

**Issue by binbin0406** [1Panel-dev/MaxKB#1143]
### 联系方式

张树彬

### MaxKB 版本

1.5.1

### 问题描述

之前安装在/soft目录下，然后这次升级，解压离线包后，修改了install.conf里的目录，执行/bin/bash install.sh 然后还是/opt目录，再kbctl uninstall进行卸载，再执行/bin/bash install.sh 还是装到/opt目录。install.conf里配置的路径不生效。
后面执行mkctl uninstall后，再执行rm -rf /usr/local/bin/mkctl 和 rm -rf /usr/bin/mkctl，之后再去执行安装/bin/bash install.sh ，才装到install.conf里配置的路径下

### 重现步骤

1. 将MaxKB安装在/soft目录下
2. 升级，解压离线包后，修改了install.conf里的目录，执行/bin/bash install.sh ，未生效
3. 然后kbctl uninstall进行卸载
4. 再执行/bin/bash install.sh 还是装到/opt目录
5. 执行mkctl uninstall后，再执行rm -rf /usr/local/bin/mkctl 和 rm -rf /usr/bin/mkctl，
6. 再去执行安装/bin/bash install.sh ，才装到install.conf里配置的路径下

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
使用kbctl uninstall进行卸载是不会删除文件的，可以使用uninstall.sh脚本进行卸载，然后再安装就可以了
