### ISSUE TITLE
[BUG]MaxTokens 参数描述错误

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#1144]
### MaxKB 版本

 1.5.1

### 问题描述

maxtokens 参数描述错误
<img width="794" alt="image" src="https://github.com/user-attachments/assets/0138990e-e228-4af7-8e76-e48d50987f4d">

### 重现步骤

如图片位置所示

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
