### ISSUE TITLE
[BUG]语雀文章导出的为 word OR md 格式无法在 MK 中进行分段

### ISSUE THREAD

**Issue by gaohonghai** [1Panel-dev/MaxKB#1148]
### 联系方式

18159668371

### MaxKB 版本

1.5.1

### 问题描述

语雀中的文章导出的为 word OR md 格式无法在 MK 中进行分段

### 重现步骤

1、在语雀中随意到处文章为 docx 或者 md 文档；
2、在知识库中导入文档；
3、docx 文档无法被识别到；md 的格式无法被正确解析。

### 期待的正确结果

1、md 在 MK 的预览效果
![image](https://github.com/user-attachments/assets/97c38e8c-1332-4dd4-90b4-79c0444347d9)
2、md 在 md编辑器的预览效果
![image](https://github.com/user-attachments/assets/5667acc4-4d44-478b-a7f1-4dc2fadf79de)

语雀导出 word
![image](https://github.com/user-attachments/assets/e32405b4-e08a-471c-b028-cbe9c1f5e254)

电脑打开 word
![image](https://github.com/user-attachments/assets/95edba33-3d14-45a0-beb6-659effe83cf7)

MK 导入 word 
![image](https://github.com/user-attachments/assets/f0859762-b973-417a-8331-c461553df3e7)

### 附加信息

[语雀导出docx (3).docx](https://github.com/user-attachments/files/16943770/docx.3.docx)
[redis缓存.md](https://github.com/user-attachments/files/16943772/redis.md)

**Comment by zyyfit** [comment]
word导入是有问题的，后面的版本修复
md格式导入是因为你设置了高级分段，分段符号是一个井号，所以就分成这样了，智能分段是正常的
![图片](https://github.com/user-attachments/assets/bfd384a7-883f-4459-aff8-a15499103dde)
