### ISSUE TITLE
[BUG]start启动UI无法正常使用，dev方式启动一切正常。

### ISSUE THREAD

**Issue by zhoumzh** [1Panel-dev/MaxKB#1150]
### 联系方式

879035413@qq.com

### MaxKB 版本

社区版，版本号序列号全是  -

### 问题描述

![image](https://github.com/user-attachments/assets/1baff473-55bf-418f-a5ea-b567c3cb6dbe)
这是dev模式启动的一切正常

### 重现步骤

![image](https://github.com/user-attachments/assets/9cd5e9ea-17b9-4857-862f-35ff673b5c28)
这是start模式启动服务后的效果，任何接口都超时

**Comment by liqiang-fit2cloud** [comment]
本地开发遇到的问题自己看看吧，每个人的环境和水平都不同，没有精力给大家一一检查。实在搞不定的就用官方版本吧。
