### ISSUE TITLE
[BUG]tokens异常，导致模型无法答复

### ISSUE THREAD

**Issue by dlluckboy** [1Panel-dev/MaxKB#1151]
### MaxKB 版本

1.5.1

### 问题描述

tokens异常，导致模型无法答复

### 重现步骤

tokens异常，导致模型无法答复
我上传了一个文档，大概内容如下
<img width="473" alt="image" src="https://github.com/user-attachments/assets/d397babb-c16e-4075-bca1-a6b51dde8c92">
我将内容从excel中拷贝到word中，然后上传到maxkb，使用的智能分段，生成了26个段落
<img width="911" alt="68f52b01bb532d3607f1ed253add7ab8_" src="https://github.com/user-attachments/assets/2f5702c6-0a99-4055-908d-8bdf62d4b25f">
但是如果我传的这个文档，只分两段
<img width="769" alt="257dc99c06c5f03dd080f1ea69b012dc_" src="https://github.com/user-attachments/assets/209981b8-e0e4-4c39-af3f-f6d5cd79a171">
进行提问的时候，就会出现之前我说的不回答的现象，而且显示使用的tokens数特别大，模型无法答复出结果。
<img width="450" alt="f5903ec765f64a89c778ceb9c5c2dd2d_" src="https://github.com/user-attachments/assets/17ae5141-86fb-45cf-87e4-79bad776f9db">

**Comment by zyyfit** [comment]
这可能是由于携带的内容过多导致模型无法回答，建议根据模型能接收的字符数进行分段或者更换处理能力更好的模型

**Comment by dlluckboy** [comment]
我用的GLM4-CHAT-1m，上下文长度应该都够用啊

**Comment by baixin513** [comment]
执行详情每个节点的 输入输出先看一下

**Comment by dlluckboy** [comment]
下面是所有节点的解雇
<img width="458" alt="image" src="https://github.com/user-attachments/assets/c50417cd-6ecb-46b5-8ea1-4112b8e9c45c">
<img width="460" alt="image" src="https://github.com/user-attachments/assets/13d2e1a0-b72a-4ac8-9e9d-563e469faa25">
<img width="458" alt="image" src="https://github.com/user-attachments/assets/a1da9bf8-dbfe-4fcc-8c4c-86f5493fc334">
<img width="461" alt="image" src="https://github.com/user-attachments/assets/e538c84a-9e27-4ed4-8a14-ff190b5292eb">
<img width="459" alt="image" src="https://github.com/user-attachments/assets/51244f94-9f16-430a-a161-d0ece14d9d32">
<img width="459" alt="image" src="https://github.com/user-attachments/assets/8dbbd5ad-9788-4afb-bb19-68039b13e7f8">
<img width="458" alt="image" src="https://github.com/user-attachments/assets/78354a8a-7c56-4005-8521-8e4979c1eda0">
<img width="446" alt="image" src="https://github.com/user-attachments/assets/d46a412f-5926-43bc-9e93-a8c2d5526619">
<img width="443" alt="image" src="https://github.com/user-attachments/assets/4c807bfc-16b2-45a4-b0a8-4cb0704604ee">
<img width="449" alt="image" src="https://github.com/user-attachments/assets/21a25e58-b7ee-4fbb-b3dd-bf1b891498eb">
<img width="448" alt="image" src="https://github.com/user-attachments/assets/ebd97410-6579-4f79-805a-cb9061462b07">
<img width="434" alt="image" src="https://github.com/user-attachments/assets/5b62d5fd-a529-43a2-9d7f-05ab77c720a6">

**Comment by dlluckboy** [comment]
> 执行详情每个节点的 输入输出先看一下

能分析出是什么问题吗？

**Comment by baixin513** [comment]
看执行详情中最后一次AI对话的提示词太长了，像是模型推理不出来，没有返回内容。

**Comment by dlluckboy** [comment]
> 看执行详情中最后一次AI对话的提示词太长了，像是模型推理不出来，没有返回内容。

如果分段多一些就没问题，分两个分段就这样。

**Comment by baixin513** [comment]
建议你换个模型再试试，目前我们的测试环境上无法复现该问题。
