### ISSUE TITLE
[FEATURE] 应用嵌入第三方页面 机器人 的位置，期望可以由管理员自定义

### ISSUE THREAD

**Issue by xhy12** [1Panel-dev/MaxKB#1152]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

将应用嵌入第三方页面，mk机器人图标默认再左下角， 我需要的业务期望展示在右上角这样，不够灵活
期望：应用嵌入第三方机器人 的位置，期望可以由管理员自定义

### 请描述你建议的实现方案

应用嵌入第三方机器人 的位置，期望可以由管理员自定义

**Comment by baixin513** [comment]
感谢反馈，后续版本迭代。

**Comment by baixin513** [comment]
v1.7.0已经发布。
