### ISSUE TITLE
maxkb xinference、ollama支持模型也太少了吧，关于qwen2、llama3.1之类都没有很不方便、

### ISSUE THREAD

**Issue by dingidng** [1Panel-dev/MaxKB#1153]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

maxkb xinference、ollama支持模型也太少了吧，关于qwen2、llama3.1之类都没有很不方便、

### 请描述你建议的实现方案

参考一下dify最新版本

**Comment by baixin513** [comment]
感谢反馈，由于各供应商支持的模型太多，且名称可一自定义，无法列全所有模型， 
我们在添加模型时，基础模型 支持自定义输入模型名称，然后回车即可。 
<img width="408" alt="image" src="https://github.com/user-attachments/assets/f8621d65-beef-43f5-8d75-db89631f9181">
