### ISSUE TITLE
功能需求：希望支持串行和并行两种编排设计模式，任务管理希望可以添加文件夹

### ISSUE THREAD

**Issue by dingidng** [1Panel-dev/MaxKB#1154]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

功能需求：希望支持串行和并行两种编排设计模式

允许多个节点在同一时间内共同执行，前置节点可以同时触发位于并行结构内的多个节点。并行结构内的节点不存在依赖关系，能够同时执行任务，更好地提升**节点的任务执行效率**

### 请描述你建议的实现方案

并行编排参考一下dify，文件项目管理参考fastgpt

**Comment by jstbw** [comment]
附议

**Comment by baixin513** [comment]
v1.7.0已经发布。
