### ISSUE TITLE
[BUG]高级编排模式下，对话生成快捷问题闭合不全

### ISSUE THREAD

**Issue by bingshan2024** [1Panel-dev/MaxKB#1170]
### MaxKB 版本

v1.5.1

### 问题描述

高级编排模式里面的快捷问题的提示词是从社区复制官方的：
用户问题：{{开始.question}}
回答：{{AI 对话.answer}}
根据这段内容推测用户接下来想要问的3个问题，要求只输出问题，并将问题放在<quick_question></quick_question>标签中

使用时正常的快捷问题截图：
![微信图片_20240912172016](https://github.com/user-attachments/assets/91e7fffa-01f1-4f60-9a50-2bad7cd9056e)

偶尔会出现的问题的快捷问题截图：
![微信图片_20240912171947](https://github.com/user-attachments/assets/59aa06d9-dbc1-479d-a3af-7660f485961c)
![微信图片_20240912171954](https://github.com/user-attachments/assets/25ba78d1-6b50-459a-ad0d-8d1e1dd5f33f)

### 重现步骤

如上所述

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
经过排查，这个应该是模型回答的问题，我们只处理标签包裹的字符串，如果模型回答的内容中没有正确输出标签，我们是处理不了的

**Comment by baixin513** [comment]
模型没有按照要求格式返回，你可以写个函数处理一下，把生成的问题放到 快捷问题标签中。

**Comment by baixin513** [comment]
这个是模型返回的问题，如果是按照要求返回的标签，maxkb会正常显示快捷问题，如果模型没有正常返回我们也无法处理，一般参数多的在线模型能正常返回。
