### ISSUE TITLE
[FEATURE] 高级应用流程编排，存在多人编辑自动保存覆盖内容的情况，期望加个编辑预览态或版本控制，避免被修改内容覆盖

### ISSUE THREAD

**Issue by xhy12** [1Panel-dev/MaxKB#1178]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

高级应用流程编排，存在多人编辑自动保存覆盖内容的情况，期望加个编辑预览态

![image](https://github.com/user-attachments/assets/bb935212-f5bd-4960-84d7-ba0036d08fce)

### 请描述你建议的实现方案

例如：有人在编辑时 提示xxx正在修改，查看的人预览不可修改

或者：建议  用户修改的时候，拉一下最新的版本对比，如果是旧版本了提示用户版本已经落后可以刷新下

**Comment by liqiang-fit2cloud** [comment]
可以考虑：1.加个查看功能，点开之后只读，2.加个限制，一个账号只允许同一时间在一个客户端登录，每次登录把其他客户端的登录退出。

**Comment by baixin513** [comment]
1.7版本中会进行如下调整：
1、进入工作流编排页面默认不会自动保存，需要手动保存。
2、增加自动保存开关设置，该设置仅保存在客户端，勾选后则5分钟自动保存一次
