### ISSUE TITLE
[FEATURE]【模型管理】支持对接 KIMI 模型

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#118]
### MaxKB 版本

1.0.0

### 请描述您的需求或者改进建议

 希望可以支持对接 KIMI 模型，最近国内比较火的模型

**Comment by baixin513** [comment]
感谢反馈，我们后面版本持续迭代，请关注后续版本。

**Comment by HayGry** [comment]
get_num_tokens_from_messages() is not presently implemented for model cl100k_base. 

Moonshot 模型 会出现这个问题

**Comment by baixin513** [comment]
是添加 kimi供应商的模型么？
v1.0.3 之前的版本添加模型时选择 OpenAI 供应商会有这个问题，该问题在 v1.0.3 已解决。可以更新一下在试试。
