### ISSUE TITLE
[BUG]知识库分段布局乱

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1183]
### 联系方式

xuwei5188916@yeah.net

### MaxKB 版本

v1.5.1

### 问题描述

知识库分段完成后，分的段落布局不是按照顺序的，混乱的。
![image](https://github.com/user-attachments/assets/6f7207f2-b438-4cd6-b9e3-29845d15333e)

### 重现步骤

上传文档，高级分段。

**Comment by baixin513** [comment]
感谢反馈，分段是批量插入的，页面按照创建时间显示的，无法按文档显瘦顺序显示
