### ISSUE TITLE
[FEATURE]关联问题增加下拉选择

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1184]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

文档上传知识库后，关联问题目前是输入形式的。是否可以增加下拉选择的功能。下拉的内容可以来源于以下：
1.用户基于该知识库回答发出的问题
2.用户基于该知识库回答发出的问题，并且这些问题的答案是不满意（不满意定义：用户对回复的问题进行踩操作）
![image](https://github.com/user-attachments/assets/e5d4d83b-a5be-4917-a1c9-60a0d8383ee0)

**Comment by baixin513** [comment]
感谢反馈， 关联问题当前就是支持下拉的，默认可选当前知识库中问题。 输入文字后会自动筛选当前知识库中的问题。
