### ISSUE TITLE
[FEATURE] 系统维护使用需要管理员做监管，希望有超管这样一个角色，可以看到、维护当前系统下的知识库、应用。

### ISSUE THREAD

**Issue by xhy12** [1Panel-dev/MaxKB#1185]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

问题：目前 知识库和应用的管理都精确到账号，按用户权限隔离。但是公司内使用系统需要一个超管的角色管理应用和知识库，应用出问题了需要担责，目前管理员没有权限管理看到其他账号的 应用、知识库情况不方便管理

期望：系统维护使用需要管理员做监管，希望有超管这样一个角色，默认可以看到、维护当前系统下的知识库、应用（包括关联知识库？）。

### 请描述你建议的实现方案

系统增加一个超管的角色，可以看到各账户 创建引用、知识库的情况。

**Comment by baixin513** [comment]
感谢反馈， 目前没有特权账户，近期内不会支持。
