### ISSUE TITLE
[FEATURE] 当前账号能看到 他人创建知识库，但是创建应用不能关联。期望能有一个授权动作，授权后他人引用可以关联知识库

### ISSUE THREAD

**Issue by xhy12** [1Panel-dev/MaxKB#1186]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

问题：当前账号能看到 他人创建知识库，但是创建应用不能关联。场景是不同账号 a b  协同维护 一个应用，a创建知识库且授权了【管理】【使用】，b 能看到维护，但是创建知识库时b 无法关联。

![image](https://github.com/user-attachments/assets/d02ebcab-625d-43f9-988f-6af69cc1c106)

期望：目前账户间 知识库 应用权限隔离， 。但是此处有授权的话是不是应该，勾选后授权后他人可以关联知识库

### 请描述你建议的实现方案

期望能 有一个授权动作，授权后他人应用可以关联知识库

**Comment by baixin513** [comment]
感谢反馈，目前应用和知识库是按用户隔离，不能跨用户关联， 建议由同一账号创建应用和知识库，然后授权给成员使用。
