### ISSUE TITLE
[FEATURE] 让 AI 在上个回答基础上进行更详细地回答

### ISSUE THREAD

**Issue by qingad** [1Panel-dev/MaxKB#119]
### MaxKB 版本

1.0.1

### 请描述您的需求或者改进建议

<img width="645" alt="0bf84a0ed825d726843a0bb1d2d037b" src="https://github.com/1Panel-dev/MaxKB/assets/165115917/a92ab1b5-f4d0-49c4-bdf9-05e6acc875b4">

### 请描述你建议的实现方案

<img width="637" alt="a2611cbf2230c0a5768a3869919eae3" src="https://github.com/1Panel-dev/MaxKB/assets/165115917/313d3919-90a6-4ccb-b6d7-f8e150897b43">

**Comment by baixin513** [comment]
感谢反馈，您可以开启多轮对话，开启后会携带历史 3 次对话提交给 LLM模型。
另外不同模型回答效果不同，哪个模型的效果好您可以选择使用哪个模型。

**Comment by baixin513** [comment]
您还可以再开启一下 问题优化功能，系统会先把用户的问题发给LLM模型进行完善确认用户的真实问题。
获取优化后的问题后再到知识库中进行向量召回分段内容，再生成 prompt 发送给 LLM 模型。

**Comment by qingad** [comment]
已经是全部开启状态啦

**Comment by chendongde310** [comment]
确有这个问题，不会有历史上下文的关联，建议排查下
