### ISSUE TITLE
[BUG]优化团队成员在大于17人时会出现超出边界的问题

### ISSUE THREAD

**Issue by B14Lettingo** [1Panel-dev/MaxKB#1199]
### 联系方式

1812951966@qq.com

### MaxKB 版本

v1.5.1 (build at 2024-08-29T18:55, commit: 17f41b6b)

### 问题描述

【系统设置-团队管理】中当人数过多时会产生越界的问题

### 重现步骤

在团队管理中添加人数超过17人时会出现越界的问题。

### 附加信息

![image](https://github.com/user-attachments/assets/826b165e-12a1-4891-ad5d-1cb163858652)

**Comment by baixin513** [comment]
感谢反馈，应该前端样式bug，后续版本修复
