### ISSUE TITLE
[BUG]修改admin邮箱时，提示默认admin用户名长度不够

### ISSUE THREAD

**Issue by beijingtl** [1Panel-dev/MaxKB#12]
### 联系方式

517699029@qq.com

### MaxKB 版本

版本号：v0.9.0 (build at 2024-03-21T18:39, commit: 96a0e4bc)

### 问题描述

尝试修改当前admin用户的密码，提示报错：admin（默认名称）的长度不足。具体截图。

![修改密码报错](https://github.com/1Panel-dev/MaxKB/assets/5467039/3e4dbf36-3645-4966-8399-ab7439b880bf)

### 重现步骤

用户管理界面，点击“编辑”。

- 输入新的邮箱。
- 点击保存。

### 期待的正确结果

保存新的邮箱信息。

### 相关日志输出

```shell
默认的用户名是：admin
提示的长度是 5-20 个字符串。
校验时，最短字符串规则是：最小6个。
```

**Comment by baixin513** [comment]
感谢反馈，此为 bug，下个版本更新。

**Comment by wanghe-fit2cloud** [comment]
v0.9.1 版本已发布。

**Comment by wanghe-fit2cloud** [comment]
v0.9.1 版本已发布。
