### ISSUE TITLE
[BUG]知识库导出问题sheet名称错误、内容缺失

### ISSUE THREAD

**Issue by winslis2** [1Panel-dev/MaxKB#1200]
### 联系方式

1362330842@qq.com

### MaxKB 版本

 v1.4.0

### 问题描述

测试线V1.4.0的知识库整理完毕后导出到生产环境V1.5.1后，文档名称部分变为Sheet+数字的名字，重要的是文档有缺失内容，具体表现为分段内文本缺少，文档是在测试线一条一条整理的，这个问题挺恼火的，因为不确定是哪个文档，段落有缺失，还有一个知识库导出没数据，请问有好的解决办法吗？
<img width="1457" alt="Snipaste_2024-09-18_11-15-07" src="https://github.com/user-attachments/assets/1000fa1b-846f-495c-a97f-6ab74a80150c">

![WechatIMG292](https://github.com/user-attachments/assets/ad20bbfa-cef4-4987-950c-2a7565f5305c)
![Snipaste_2024-09-18_11-44-53](https://github.com/user-attachments/assets/8b07003a-a9d2-42fa-86fc-e2d9af77451b)

### 重现步骤

导出文档后在导入

**Comment by winslis2** [comment]
<img width="931" alt="Snipaste_2024-09-18_11-27-09" src="https://github.com/user-attachments/assets/9d63406d-1c23-435c-a8ed-e4928658d96d">

**Comment by zyyfit** [comment]
您好，我复现了一下
1、问题1，文档名称带特殊字符的，如空格、斜杠等，导出后sheet名称会不显示，请确认一下您的文档sheet是不是这个原因
2、问题2已复现
![图片](https://github.com/user-attachments/assets/2440ac45-e466-46f7-a3d4-3b80341e888d)

**Comment by winslis2** [comment]
问题三：导出知识库为空，应该是文档过大的原因导致的
![image](https://github.com/user-attachments/assets/837b169a-3b48-4974-9763-62ee975f3e9c)
去除到这个文档就可以导出了

**Comment by zyyfit** [comment]
您好，第一个sheet名称的问题，是因为excel创建sheet名称有些字符不允许使用，所以就变成默认名称了
第二个问题已修复，1.6.0版本发布
第三个问题没有复现，我找了一个119k的文档导出，并没有出现内容空白的情况，方便提供一下您的原始文档数据给我们排查一下吗？
![image](https://github.com/user-attachments/assets/6f32c314-4afb-44dc-84aa-06154354ef8d)

**Comment by winslis2** [comment]
第三个问题复现步骤

**Comment by winslis2** [comment]
第三个问题复现步骤：
1、打开链接https://dev.vivo.com.cn/documentCenter/doc/236   F12选择html内容粘贴到html转化markdown中
![image](https://github.com/user-attachments/assets/24040e65-8259-4e3a-9c69-6e1972bd2eeb)
转化工具地址：https://d1tools.com/tools/convert-html-to-markdown/
2、新建知识库并通过创建文档的方式填充markdown文本，文档大概47.0k
3、选择导出知识库或直接导出文档都能复现

**Comment by zyyfit** [comment]
您好，单独导出文档没有出现导出为空的情况，导出整个知识库倒是出现了一个报错（我的知识库里有个很大的文档），请确认一下您导出为空的情况是不是这一种

![图片](https://github.com/user-attachments/assets/a8e861b0-a948-44f8-9d55-b2ffc2bb540c)

**Comment by zyyfit** [comment]
问题3  1.6.1 版本已修复
