### ISSUE TITLE
[BUG]上传pdf文档出现Cannot open empty file:filename='/tmp/tmp7gun1tbm. （上传word没问题）

### ISSUE THREAD

**Issue by armored-glitch** [1Panel-dev/MaxKB#1204]
### 联系方式

389443982@qq.com

### MaxKB 版本

v1.5.1 

### 问题描述

目前已上传5000份左右PDF文档，出现无法再上传，上传出现错误
![b8339539abe844ab9e9c94d7f4bd017](https://github.com/user-attachments/assets/1e3b3ad4-c21b-400d-a85a-e95cb7a5509d)

### 重现步骤

再次上传pdf 就会出现

**Comment by zyyfit** [comment]
您好，看这个报错像是上传了一个空白的pdf文件，请您检查一下上传的文件中是否有空白文件
