### ISSUE TITLE
[BUG] 在ollama中能本地下载chatglm4，但是maxkb中导入ollama后没有这个大模型

### ISSUE THREAD

**Issue by MrSu3364** [1Panel-dev/MaxKB#1207]
### 联系方式

18713158902@163.com

### MaxKB 版本

1.5.1

### 问题描述

ollama版本：0.3.10
maxkb版本：1.5.1
在系统管理→模型设置→添加模型→ollama中，点击基础模型只有ollama与千问系列，没有ollama已经支持的chatglm3  chatglm4
![image](https://github.com/user-attachments/assets/75510250-d5fd-4b5a-88d1-e1a361a1cd25)
![image](https://github.com/user-attachments/assets/6785b542-8074-4732-b978-cf890caee19e)
![image](https://github.com/user-attachments/assets/1862175d-3b61-42e8-8808-7ffa9fbce95b)

### 重现步骤

创建新模型即可发现

### 期待的正确结果

能够创建基于本地ollama的chatglm模型

**Comment by baixin513** [comment]
感谢反馈，基础模型没法列全所有模型，支持自定义输入，可以手动输入 glm4:latest 然后回车。
