### ISSUE TITLE
[BUG] 应用关联知识库显示不全

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1210]
### 联系方式

xuwei5188916@yeah.net

### MaxKB 版本

v1.5.1

### 问题描述

创建应用，关联知识库，显示不全
![image](https://github.com/user-attachments/assets/ed9483c2-e5ec-4546-9af1-2301e5f5e6f9)
![关联知识库](https://github.com/user-attachments/assets/8ad8128e-8fea-4a19-9132-fb10434f5e9e)

### 重现步骤

创建应用

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
