### ISSUE TITLE
[FEATURE] 登录认证增加OAuth2或JWT

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1212]
### MaxKB 版本

v1.5.1

### 请描述您的需求或者改进建议

希望maxkb登录认证（单点登录）支持 OAuth2或JWT认证。

**Comment by liqiang-fit2cloud** [comment]
专业版可以考虑支持OAuth2，JWT没有计划。

**Comment by xuwei999-NT** [comment]
> 专业版可以考虑支持OAuth2，JWT没有计划。

何时发布OAuth2

**Comment by liqiang-fit2cloud** [comment]
刚开始考虑，做不做什么时候做都不确定。

**Comment by baixin513** [comment]
v1.8.0 已发布！
