### ISSUE TITLE
[FEATURE] 应用设置，显示只是来源勾选知识来源 期望能看到引用的具体文章，而不是执行过程

### ISSUE THREAD

**Issue by opopjasica** [1Panel-dev/MaxKB#1216]
### MaxKB 版本

1.51.

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/3865a86c-a054-4b2d-8513-33e94a7ce5a8)
应用设置，显示只是来源勾选知识来源 期望能看到引用的具体文章，而不是执行过程

### 请描述你建议的实现方案

应用设置，显示只是来源勾选知识来源 期望能看到引用的具体文章，而不是执行过程

**Comment by baixin513** [comment]
感谢反馈，高级编排应用中会有多个知识库检索节点，多个节点会引用不同的知识库分段，执行详情中可以查看每个节点具体的引用详情。
