### ISSUE TITLE
[BUG] 知识库分段1级标题单独一段不合适

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1226]
### 联系方式

xuwei5188916@yeah.net

### MaxKB 版本

v1.5.1

### 问题描述

对知识库分段的时候，一级标题单独分为一段感觉没有意义。如果一级分段下面没有问题，能否剔除呢。
![image](https://github.com/user-attachments/assets/cfdc3caa-5dfb-44ba-96d0-189bb2c8372d)
知识库附件：
[测试知识库.docx](https://github.com/user-attachments/files/17061585/default.docx)
[测试知识库.zip](https://github.com/user-attachments/files/17061607/default.zip)

### 重现步骤

知识库分段，高级分段，如下：
![image](https://github.com/user-attachments/assets/aa454583-ede4-467e-b96d-3fb2a3e3f2e1)

**Comment by liqiang-fit2cloud** [comment]
对于不同文章有不同的效果吧，你这个文章的1级标题没有意义，别的文章可能有意义。
而且你也可以跟据你文章的实际情况修改分段标识。
