### ISSUE TITLE
[FEATURE]【应用】对话日志详情中修正答案时，保存到文档下拉选项支持搜索

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#123]
### MaxKB 版本

关联问题界面可以支持搜索

### 请描述您的需求或者改进建议

当文档比较多的时候比较难选到自己想选的文档
<img width="749" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/40552640/ecc0d6b5-95da-436a-b2ca-6a59940465b6">

### 请描述你建议的实现方案

希望这个页面能支持搜索，可以快速定位到想选择的文档

**Comment by baixin513** [comment]
感谢反馈，后面版本优化一下，增加搜索功能。

**Comment by Mandeep0001** [comment]
?

**Comment by baixin513** [comment]
该需求在 v1.0.4中已完成
