### ISSUE TITLE
[FEATURE]支持应用间引用

### ISSUE THREAD

**Issue by jstbw** [1Panel-dev/MaxKB#1230]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

当前应用间都是相互隔离的，最多支持复制应用，有的场景会需要应用间引用嵌套，直接复制的话，编排步骤多，会比较繁琐，使用体验不是很好

**Comment by liqiang-fit2cloud** [comment]
暂时没有计划。
