### ISSUE TITLE
[BUG]高级编排展示异常

### ISSUE THREAD

**Issue by jstbw** [1Panel-dev/MaxKB#1231]
### 联系方式

bowen.tang@fit2cloud.com

### MaxKB 版本

1.5.1

### 问题描述

![image](https://github.com/user-attachments/assets/a0e9fdfb-94e2-4e8c-a00d-155828b375e6)
高级编排会出现上述页面，缩放页面也不能正常显示

### 重现步骤

用户环境打开高级编排即会出现，用的chrome浏览器

**Comment by liqiang-fit2cloud** [comment]
升级chrome到最新版本。
