### ISSUE TITLE
[BUG] 配置网络代理后，知识库向量化失败，配置前是OK的

### ISSUE THREAD

**Issue by zhenzhen-wang** [1Panel-dev/MaxKB#1260]
### 联系方式

bonnie.wang2@cn.bosch.com

### MaxKB 版本

v1.5.1

### 问题描述

公司内网cocker容器部署的maxkb，当给docker容器配置网络代理后，在知识库中向量化模型显示失败。
向量化失败日志如下：
https://bbs.fit2cloud.com/uploads/default/optimized/2X/0/0ae22741929b31fd6b88f21bfd817134c2c45ba2_2_690x396.png
配置proxy方式是在容器的环境变量中加：https_proxy和http_proxy
但是，不配置代理向量化是ok的
退回1.4.1版本后，配置代理也可以正常向量化

### 重现步骤

升级到1.5.1后，配置代理，向量化失败

**Comment by zyyfit** [comment]
请问使用的向量模型是本地模型吗？如果不是本地模型的话请检查一下是不是配置代理后向量模型无法连接了，如果是本地模型，请看一下有没有报错日志，提供一下错误日志等信息

**Comment by zhenzhen-wang** [comment]
上图的链接就是日志信息啊，刚试了版本1.61也还是不行。只有1.41的是好的

**Comment by zhenzhen-wang** [comment]
[celery_default.log](https://github.com/user-attachments/files/17485672/celery_default.log)
[gunicorn.log](https://github.com/user-attachments/files/17485674/gunicorn.log)
从容器内拷贝过来的log，第一个里有写道向量化失败

**Comment by zyyfit** [comment]
应该是网络问题，我们1.5及更高版本中做了服务拆分，向量化需要访问这个local_model这个服务，配置了http_proxy后应该就访问不到local_model这个服务了，您可以看一下 local_model 日志中有没有网络方面的报错
![图片](https://github.com/user-attachments/assets/c4facff1-ef41-4990-a58f-e1f9746fbe6e)

**Comment by zhenzhen-wang** [comment]
新增了一个本地模型m3e-base，依然显示向量化失败。应该不是网络异常导致的吧，而且其他方面网络都是正常的，可以正常添加在线的一些LLM模型。
如下是local_model的log：
[local_model.log](https://github.com/user-attachments/files/17540018/local_model.log)

**Comment by zhenzhen-wang** [comment]
访问local_model这个服务做向量化，那这个服务不是本地的服务吗？加代理会产生什么影响呢？
而且看log里面的向量化失败记录：2024-10-28 14:45:44 向量化文档:82d2e20a-8a10-11ef-ae8d-0242ac110005出现错误Expecting value: line 1 column 1 (char 0)Traceback (most recent call last):  应该是在读取db数据做向量化时，读取到的是空导致的

**Comment by zhenzhen-wang** [comment]
配置代理之前向量化是好的，配置网络代理是为了访问公有云的AI模型，有没有其他方式设置网络代理，目前maxkb是发布在docker容器中的，是在容器的环境变量中配置了http_proxy，是否有其他方式可以让chatbot使用公有云的AI模型。

**Comment by shaohuzhang1** [comment]
目前默认的向量化默认是调用127.0.0.1:11636的local_model服务 因为你使用了http_proxy 所有应该无法访问到这个服务 你可以尝试修改docker的环境变量:
MAXKB_LOCAL_MODEL_HOST
MAXKB_LOCAL_MODEL_PORT
MAXKB_LOCAL_MODEL_PROTOCOL
