### ISSUE TITLE
[FEATURE] 权限问题

### ISSUE THREAD

**Issue by Aidenjoy** [1Panel-dev/MaxKB#1273]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

admin给别人开账户之后，别人自己创建的应用admin看不到，这个就没办法管理了。
也不能关闭其他人的创建应用和知识库的功能，让其他人不能创建。

### 请描述你建议的实现方案

admin是最高权限，能看到系统所有人创建的所有信息。其次增加admin管理其他人创建应用、知识库、模型的功能。

**Comment by liqiang-fit2cloud** [comment]
同https://github.com/1Panel-dev/MaxKB/issues/1185
