### ISSUE TITLE
[FEATURE] 用户使用链接访问应用限制

### ISSUE THREAD

**Issue by Aidenjoy** [1Panel-dev/MaxKB#1275]
### MaxKB 版本

1.5.1

### 请描述您的需求或者改进建议

现在只限制了用户访问次数，而不能做到用户需要登录才能使用分享出去的链接。

### 请描述你建议的实现方案

添加用户分享链接之后的登录注册功能，这样可以管理第三方用户，把用户沉淀下来。而且用户提出的问题可以看到用户名，这样有助于知识库数据的优化。分析哪写用户喜欢哪些问题，以及哪些用户提的问题涉嫌违法，并给对方禁用账号等。否则系统中存在用户提问的违法信息就会存在安全风险。

**Comment by liqiang-fit2cloud** [comment]
感谢关注，目前系统不支持系统外的用户、认证、权限管理，也没有计划支持。
建议你自己定制chat页面并加上自己的权限控制，后端调用MaxKB的chat API。
