### ISSUE TITLE
[FEATURE]专业领域（如医药、半导体、电子、系统）需要应用鉴权

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1280]
### MaxKB 版本

v1.5.1

### 请描述您的需求或者改进建议

专业领域（如医药、半导体、电子、系统）需要应用鉴权

### 请描述你建议的实现方案

缺陷1275里说不做鉴权，但是从用户实际使用来看，需要这个选项，尤其是专业版用户。

专业领域（如医药、半导体、电子、专业系统）：
1. 用户搭建的知识库如果内部使用，这种情况不需要鉴权
2. 有的知识库给到客户这边的技术人员使用，但是知识库里面信息 仅限于客户知道，不能让友商知道，半导体和医药行业我们都有收到过客户类似的诉求。昨天一家做医院系统的系统开发厂商也提到这点。医药行业的销售分布在全国各地，他们可能也会访问知识库，客户希望能提供URL和账号的形式 给到业务人员。
3. 上面这些这是我个人拜访遇到的。我也看到 其他人提了类似的需求。

### 附加信息

缺陷1275里提到说让用户自己去控制鉴权，在医药、半导体、电子等研发类的公司里，有的IT人员少，创业类的公司里就更少了，通常也就几个人做各类系统的运维，如果专业版里有个鉴权选项，对客户来说是个很好的选择。

**Comment by liqiang-fit2cloud** [comment]
嗯，没有计划做鉴权。
