### ISSUE TITLE
[BUG] 利用api接口调用bug

### ISSUE THREAD

**Issue by Aidenjoy** [1Panel-dev/MaxKB#1283]
### MaxKB 版本

1.5.1

### 问题描述

利用api接口调用maxkb之后，在对话日志里面没有保存下来内容。

### 重现步骤

使用接口收发消息即可，必现

### 期待的正确结果

所有的交互都应该留存到消息日志里面

**Comment by zyyfit** [comment]
您好，没有复现这个问题
![图片](https://github.com/user-attachments/assets/3cffa507-601d-4522-9efe-c8af88b2f1e2)
![图片](https://github.com/user-attachments/assets/ffc191fa-72ec-43fd-bcb1-554efa68a431)
