### ISSUE TITLE
[BUG]利用api接口调用bug

### ISSUE THREAD

**Issue by ayue870729** [1Panel-dev/MaxKB#1284]
### MaxKB 版本

main

### 问题描述

使用接口chat_message进行对话时报错，{"code": 500, "message": "Expected a dictionary of items but got type \"list\".", "data": null}

### 重现步骤

使用接口进行对话

**Comment by shaohuzhang1** [comment]
已修复

**Comment by zyyfit** [comment]
1.6.0版本已修复，请更新到最新版使用
