### ISSUE TITLE
[FEATURE]能否在创建知识库中增加建立文件夹选项

### ISSUE THREAD

**Issue by dlluckboy** [1Panel-dev/MaxKB#1293]
### MaxKB 版本

v1.5.1

### 请描述您的需求或者改进建议

能否在创建知识库中增加建立文件夹选项，现在建立知识库，只能建立一个目录，能否改进在当前目录下，可以建立其他目录。

**Comment by baixin513** [comment]
感谢反馈，暂时没有计划增加目录管理功能
