### ISSUE TITLE
[BUG]应用API key 使用接口chat_message显示 "content": "异常'NoneType' object has no attribute 'get'",

### ISSUE THREAD

**Issue by gjr666** [1Panel-dev/MaxKB#1294]
### 联系方式

2357439380@qq.com

### MaxKB 版本

1.5.1

### 问题描述

![image](https://github.com/user-attachments/assets/0cf49384-eb33-48d9-9cf3-f6159c93e3bd)

### 重现步骤

只有输入“你好”这种回答很少的，能正确显示

### 附加信息

![image](https://github.com/user-attachments/assets/6c475e7a-c626-4320-949e-d02afd2b6f2b)

**Comment by baixin513** [comment]
感谢反馈，该问题已在1.6版本修复，等发版后更新。
