### ISSUE TITLE
[FEATURE]优化一下输出结果

### ISSUE THREAD

**Issue by jxyk2007** [1Panel-dev/MaxKB#1297]
### MaxKB 版本

 v1.5.1 (build at 2024-08-29T17:29, commit: 30b1bdfe)

### 请描述您的需求或者改进建议

ai整理好的信息，直接输即可，无需在把函数输出的结果一并输出
![微信图片_20240926135109](https://github.com/user-attachments/assets/63e484ae-b687-4a6e-bb71-ba6855f98b65)
![微信图片_20240926135150](https://github.com/user-attachments/assets/74b79638-9bc1-4441-929f-91880252ffbd)

### 请描述你建议的实现方案

ai整理好的信息，直接输即可，无需在把函数输出的结果一并输出

**Comment by baixin513** [comment]
函数节点的返回内容关闭就不输出了
