### ISSUE TITLE
[FEATURE]能显示知识库以及应用的创建者

### ISSUE THREAD

**Issue by armored-glitch** [1Panel-dev/MaxKB#1304]
### MaxKB 版本

v1.5.1 

### 请描述您的需求或者改进建议

尊敬的MaxKB团队：
    针对集团公司，知识库的应用的创建者是比较多的，不知道针对这种情况我们要怎么区分知识库是哪位同事创建，不知道后续会考虑添加这个功能吗，或者我们有更加好的实现方式。

**Comment by baixin513** [comment]
感谢反馈，后续版本考虑增加

**Comment by baixin513** [comment]
v1.8.0 已发布！
