### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by najsword** [1Panel-dev/MaxKB#1307]
### MaxKB 版本

 v1.5.1 (build at 2024-08-29T17:29, commit: 30b1bdfe)

### 问题描述

问题：
vllm方式部署openai的接口方式，请求接口需要使用/v1/chat/completions 接口
但是测试mk对话应用时，返回404,。  查看原因是mk发送传了 /chat/completions，少了/v1.  
尝试解决：
在urls.py里添加类似一行代码，加个/v1，导致容器启动失败
希望：
能够直接支持/v1 带版本的openai接口请求，使得应用返回正常，而不是404查询结果

### 重现步骤

问题：
vllm方式部署openai的接口方式，请求接口需要使用/v1/chat/completions 接口
但是测试mk对话应用时，返回404,。  查看原因是mk发送传了 /chat/completions，少了/v1.  
尝试解决：
在urls.py里添加类似一行代码，加个/v1，导致容器启动失败
希望：
能够直接支持/v1 带版本的openai接口请求，使得应用返回正常，而不是404查询结果

**Comment by baixin513** [comment]
感谢反馈，API域名后面 加上/v1 就行了。
https://maxkb.cn/docs/user_manual/model/model/#112-vllm
<img width="906" alt="image" src="https://github.com/user-attachments/assets/e534a558-3cf0-4e5e-b20c-9d0bcd7e1513">

**Comment by aasfefdg** [comment]
@baixin513 好像还是不行哦

![Image](https://github.com/user-attachments/assets/88839333-b274-4a6a-9c52-0be1a544b702)

![Image](https://github.com/user-attachments/assets/5b4be046-16f2-43ca-84f2-848fa90c626e)
