### ISSUE TITLE
[BUG] 修改密码的逻辑调整，先验证两次密码是否匹配，再发邮件验证码

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1311]
### MaxKB 版本

v1.6.0

### 问题描述

修改密码的逻辑调整，先验证两次密码是否匹配，再发邮件验证码
![image](https://github.com/user-attachments/assets/a3da920f-e79d-47a6-bca1-0208dc9c886f)

### 重现步骤

无

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by baixin513** [comment]
v1.7.0已经发布。
