### ISSUE TITLE
[FEATURE] 注册功能+权限

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1312]
### MaxKB 版本

v1.6.0

### 请描述您的需求或者改进建议

希望未来的版本提供注册功能，增强权限（组织、部门）。
另外注册功能可以更加灵活：提供可以注册功能和禁止注册功能开关按钮。

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，目前没有计划支持。
