### ISSUE TITLE
[BUG] 知识库图片无法正常返回

### ISSUE THREAD

**Issue by Larson13** [1Panel-dev/MaxKB#1313]
### MaxKB 版本

v1.6.0

### 问题描述

知识库维护的分段中包含文字描述和图片，在应用中问答只返回文字描述，未返回图片

### 重现步骤

1、在知识库中上传doc 文档，文档中分段包含文字描述、图片
2、在应用中调试，看是否返回图片

### 附加信息

1、知识库维护
![image](https://github.com/user-attachments/assets/2da625e1-8f4b-4cb0-b918-925c8c031fe0)
2、应用只返回了文字，未返回图片
![image](https://github.com/user-attachments/assets/d8c71f66-6bf1-437f-a990-356f5f3f3d3a)

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme

you may need to install the c compiler

**Comment by zyyfit** [comment]
您好，如果这个文档没有设置命中处理方式的话，是ai根据检索到的内容来组织语言回答的，如果想一定要回复图片，可以设置命中处理方式为相似度xxx以上直接返回分段内容
![图片](https://github.com/user-attachments/assets/ee9513a6-0c4e-4049-aced-402ec5a445eb)

**Comment by BerminBruce** [comment]
我也发现了相同的问题，之前1.5.1版本前端是能输出显示召回知识库内容中的图片的，现在1.6.0的版本，前端已经显示不了图片内容了。

**Comment by BerminBruce** [comment]
是不是现在1.6.0版本的知识库图片存储方式或者路径和之前1.5.1有差别，导致前端渲染时找不到实际图片，所以展示不了？
![Uploading 8F0C7F11-7590-4033-85BE-03BBCACFFF32.png…]()

**Comment by BerminBruce** [comment]
是不是现在1.6.0版本的知识库图片存储方式或者路径和之前1.5.1有差别，导致前端渲染时找不到实际图片，所以展示不了？
![Uploading 8F0C7F11-7590-4033-85BE-03BBCACFFF32.png…]()

**Comment by BerminBruce** [comment]
是不是现在1.6.0版本的知识库图片存储方式或者路径和之前1.5.1有差别，导致前端渲染时找不到实际图片，所以展示不了？
![8F0C7F11-7590-4033-85BE-03BBCACFFF32](https://github.com/user-attachments/assets/495d3ecc-3dd9-453d-bc8f-ccfbf6bd7483)

**Comment by baixin513** [comment]
调一下模型的温度试试
