### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by zero-ligg** [1Panel-dev/MaxKB#1317]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

<img width="380" alt="maxkb" src="https://github.com/user-attachments/assets/f4f2cb09-2c7d-432c-b115-df508d6a8f85">
OPENAI的调用新版本较老版本多了一个API_VERSION，这个应该怎么填，辛苦帮忙看看

**Comment by shaohuzhang1** [comment]
升级版本到最新

**Comment by zero-ligg** [comment]
> 升级版本到最新

升级后还是不行哦，api_version这个值是取得哪一个啊
![Uploading maxkb.png…]()

**Comment by shaohuzhang1** [comment]
你版本不对

**Comment by zero-ligg** [comment]
> 你版本不对

把maxkb更新到了1.6.0还是不行哦，上面那个截图就是，好像没发出来

**Comment by baixin513** [comment]
看截图你的api_version 没有写对，如下图：
<img width="852" alt="image" src="https://github.com/user-attachments/assets/7eeedfb4-6766-420b-8984-6371c935cc96">

**Comment by zero-ligg** [comment]
<img width="688" alt="maxkb2" src="https://github.com/user-attachments/assets/3607a1c8-8cf7-47b8-a784-dac9e7fff9fb">
<img width="383" alt="maxkb1" src="https://github.com/user-attachments/assets/20cd5791-017d-45ee-92bf-b3d7fb3a8d56">
我这个应该是没有问题的，辛苦各位再指导一下啊
