### ISSUE TITLE
[FEATURE] 【问答页面】希望AI 回答时后台运行也能一直输出答案

### ISSUE THREAD

**Issue by qingad** [1Panel-dev/MaxKB#132]
### MaxKB 版本

1.0.1

### 请描述您的需求或者改进建议

现在的模式，机器人的页面不在电脑屏幕最前端时将不会输出任何信息，对于大量信息来说很浪费时间，现在主流的 AI 助手都有优化信息输出的模式，变成了能后台输出。希望 KB 也能跟进呦~

**Comment by baixin513** [comment]
感谢反馈，我们后期优化，请关注后期版本更新。
