### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by asanguosha4252** [1Panel-dev/MaxKB#1320]
### 联系方式

425202395@qq.com

### MaxKB 版本

1.6

### 问题描述

调试，选完弹窗就没了。用户输入 是非必填

### 重现步骤

调试，选完弹窗就没了。用户输入 是非必填

### 附加信息

https://github.com/user-attachments/assets/ba3efb86-6c8c-4003-a4da-373626292481

**Comment by zyyfit** [comment]
1.6.1 版本已修复，请等待今天版本发布后升级
