### ISSUE TITLE
[BUG]没有为cl100k base实现get_num_tokens_from_messages这个方法

### ISSUE THREAD

**Issue by kd-taiziye** [1Panel-dev/MaxKB#1322]
### MaxKB 版本

v1.5.0 (build at 2024-08-28T17:41, commit: 07555ec2)

### 问题描述

知识库高级编排调试提问回答。get_num_tokens_from_messages() is not presently implemented for model cl100k_base. See https://platform.openai.com/docs/guides/text-generation/managing-tokens for information on how messages are converted to tokens.

### 重现步骤

知识库高级编排调试提问回答。get_num_tokens_from_messages() is not presently implemented for model cl100k_base. See https://platform.openai.com/docs/guides/text-generation/managing-tokens for information on how messages are converted to tokens.

**Comment by shaohuzhang1** [comment]
升级到最新版本试试
