### ISSUE TITLE
[FEATURE]区分平台用户创建知识库以及应用

### ISSUE THREAD

**Issue by what-isusername** [1Panel-dev/MaxKB#1327]
### MaxKB 版本

v.1.6

### 请描述您的需求或者改进建议

公司内部有比较多同事会上传知识库文档或者对应用做一些操作，希望能够查看到具体的上传或者操作的用户是谁

**Comment by baixin513** [comment]
感谢反馈，后续版本迭代

**Comment by baixin513** [comment]
在1.8中的应用、知识库、函数库会支持按创建者查询资源。

**Comment by baixin513** [comment]
v1.8.0 已发布！
