### ISSUE TITLE
[是否考虑简单的web登录页面可以爬取吗？不带验证码]

### ISSUE THREAD

**Issue by ocean0551** [1Panel-dev/MaxKB#133]
### MaxKB 版本

1.0.1

### 请描述您的需求或者改进建议

简单的web登录页面可以爬取吗？不带验证码

**Comment by baixin513** [comment]
感谢反馈，由于不同的Web页面认证方式不同，认证也是有时效性的，当前先不考虑。
后期做的话也会考虑做一些主流的。
