### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jayden-leo** [1Panel-dev/MaxKB#1331]
### 联系方式

1263346845@qq.com

### MaxKB 版本

1.6.1

### 问题描述

词嵌入模型配置成功后，显示排队中，之前无相关操作。而不是索引中。

### 重现步骤

上传文件，向量化，显示排队中。

### 期待的正确结果

索引并且成功将文本嵌入成向量

**Comment by lvrui-code** [comment]
我也有同样的问题，请问你目前解决了么？

**Comment by baixin513** [comment]
感谢反馈，你是本地启动的项目跑的么？

**Comment by baixin513** [comment]
本地源码启动的看一下这个帖子：https://bbs.fit2cloud.com/t/topic/7840
