### ISSUE TITLE
[BUG]知识库文档中若图片不存，前端渲染失败导致显示页面异常

### ISSUE THREAD

**Issue by B14Lettingo** [1Panel-dev/MaxKB#1336]
### 联系方式

1812951966@qq.com

### MaxKB 版本

v1.6.1 (build at 2024-09-29T19:20, commit: 0bc093e6)

### 问题描述

在知识库中对新导入的文件中若存在.png格式的图片，但图片实际并不存在于MK数据库中时会导致输出对应分段时页面抽搐。

### 重现步骤

[4008技术手册.md.xlsx](https://github.com/user-attachments/files/17303231/4008.md.xlsx)
下载上述文档，并导入知识库中，使用MK内置向量模型进行向量化知识库文档。建立简单配置应用，使用豆包LLM（参数：温度0.45，tokens：4000），关联对应知识库，并设置对应参数为：无知识库引用时继续向大模型提问。完成配置后在右侧测试页面输入问题：" P.C.B. Lp 645 Position Sensor Membrane Pump - Description"。

### 期待的正确结果

页面显示无抽搐

### 附加信息

https://github.com/user-attachments/assets/e715df45-3ac6-4390-a524-73a6b7cc45fe

**Comment by baixin513** [comment]
感谢反馈，可以在AI回答时使用F12检查一下 模型返回的图片链接是否正确？

**Comment by B14Lettingo** [comment]
异常图片调用的URL：http://${IP}/ui/chat/481_image_0.png 在知识库文档分段中显示的内容： ![480_image_0.png](480_image_0.png)
正常图片调用的URL：http://${IP}/api/application/chat_message/70a55454-86b5-11ef-a7ff-0242ac120004 在知识库文档分段中显示的内容： ![](/api/image/0e9145ec-7f13-11ef-bc81-0242ac120004)

**Comment by baixin513** [comment]
好的，后续版本优化一下。

**Comment by baixin513** [comment]
v1.7.0已经发布。
