### ISSUE TITLE
【应用】希望只回答知识库中的内容 同需求#56

### ISSUE THREAD

**Issue by wangxexplorer** [1Panel-dev/MaxKB#134]
### MaxKB 版本

v1.0.1

### 请描述您的需求或者改进建议

请问目前数据是私有化的吗
另外我不想用配置的后台大模型回答问题，只想让我上传的文档回答，怎么处理呢

**Comment by baixin513** [comment]
感谢反馈。
1、数据是私有化的。
2、问答不走大模型 预计下个功能版本支持。
