### ISSUE TITLE
[BUG] error when adding jina-embeddings-v3 as a local model

### ISSUE THREAD

**Issue by linxiaohui** [1Panel-dev/MaxKB#1341]
### MaxKB 版本

commit 2c3fecf1cc137fba8fed4a80e873ec7733f7476a

### 问题描述

I had downloaded `jinaai/jina-embeddings-v3` from huggingface, saved in a local dir, named `/home/xxx/jinaai/jina-embeddings-v3/`

when I create a new `local model` and the `base model` set to `/home/xxx/jinaai/jina-embeddings-v3/`, when saving, it shows a error message

```
校验失败,请检查参数是否正确: [Errno 2] No such file or directory: '/home/xxx/jinaai/jina-embeddings-v3/sentence_xlnet_config.json'
```

BUT when I create `moka-ai/m3e-large/` or `jinaai/jina-embeddings-v2-base-zh/` using the same procedure, it is OK

### 重现步骤

see above 

### 期待的正确结果

create the local model successfully.

**Comment by zyyfit** [comment]
您好，这个模型可能是还不支持，我们先研究一下再给您回复

**Comment by shaohuzhang1** [comment]
目前暂不支持此模型jina-embeddings-v3这个模型 你可以通过xinference对接
