### ISSUE TITLE
[FEATURE]语音输入时，希望不要在控制台输出调试信息

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1345]
### MaxKB 版本

v1.16.1

### 请描述您的需求或者改进建议

语音输入时，希望不要在控制台输出调试信息
![8778a04e-b71a-4a60-9698-12fa7d3b397f](https://github.com/user-attachments/assets/724d4ac2-859e-434b-ad4a-a9fb81f55858)

**Comment by baixin513** [comment]
v1.7.0已经发布。
