### ISSUE TITLE
[BUG]创建知识库后，上传文档时，选择文件夹，弹出的文件夹选择框中的所有文件夹都是灰色的，不可选

### ISSUE THREAD

**Issue by linxiaohui** [1Panel-dev/MaxKB#1348]
### MaxKB 版本

commit e253637ae33ed55ee2253013bb1f957197bc8790

### 问题描述

使用Chrome浏览器，创建知识库后，上传文档时，选择文件夹，弹出的文件夹选择框中的所有文件夹都是灰色的，不可选。

### 重现步骤

使用Chrome浏览器，创建知识库后，上传文档时，选择文件夹，弹出的文件夹选择框中的所有文件夹都是灰色的，不可选。

### 期待的正确结果

使用Chrome浏览器，创建知识库后，上传文档时，选择文件夹，弹出的文件夹选择框中可以选择一个文件夹上传，或者进入一个文件夹选择其子目录

### 相关日志输出

```shell
无
```

### 附加信息

1. 同样的环境下，使用RAGFlow没有该问题。
2. 使用Firefox浏览器没有出现该问题。

**Comment by zyyfit** [comment]
您好，最新版v1.6.1 没有复现这个问题，请详细描述一下电脑操作系统，浏览器版本，maxkb版本等信息
![图片](https://github.com/user-attachments/assets/5f990857-4e06-4547-9845-2634df913fd3)

**Comment by linxiaohui** [comment]
操作系统 Linux Mint
Chrome版本 129.0.6668.100（正式版本） （64 位）

**Comment by linxiaohui** [comment]
确认Mac、Windows系统中Chrome没有该问题。 

在Linux Mint中，ragflow使用Chrome浏览器访问，上传文件夹也是没有问题的。

MaxKB版本测试过 v1.6.1 docker，也测试过本地启动git中最新的源代码版本。

> 您好，最新版v1.6.1 没有复现这个问题，请详细描述一下电脑操作系统，浏览器版本，maxkb版本等信息 !

**Comment by baixin513** [comment]
可否录制个操作视频 ？
想选的文件夹下面是否有符合条件的文件？

**Comment by zyyfit** [comment]
请检查一下 linux 中的文件是不是没有显示后缀，如果文件没有后缀的话目前是无法上传这个文件的，在文件夹中如果都是不能上传的文件，文件夹就是不可选中的状态

**Comment by zyyfit** [comment]
您好，由于您长时间没有回复，我们先对issue进行关闭，如有其他问题请提交一个新的issue
