### ISSUE TITLE
[BUG] 对接oneapi的时候不管模型是什么请求都是gpt-3.5-turbo模型

### ISSUE THREAD

**Issue by bboysoulcn** [1Panel-dev/MaxKB#135]
### MaxKB 版本

v1.0.1 

### 问题描述

对接oneapi的时候不管模型是什么请求都是gpt-3.5-turbo模型

### 重现步骤

对接oneapi的时候不管模型是什么请求都是gpt-3.5-turbo模型

**Comment by baixin513** [comment]
感谢反馈，当前还不支持对接 oneapi 呢， 请提供下具体的操作和截图排查一下问题。
