### ISSUE TITLE
[BUG] 在配置API域名是显示api域名无效

### ISSUE THREAD

**Issue by bnxydx** [1Panel-dev/MaxKB#1350]
### 联系方式

1123520338@qq.com

### MaxKB 版本

1.6.1

### 问题描述

在添加ollama模型时显示
api 域名无效

### 重现步骤

正常操作后，在配置API域名是显示api域名无效

**Comment by zyyfit** [comment]
请访问 ollama 的 /api/tags 地址查看服务是否正常，然后如果服务正常的话，请检查API域名格式是否正确，填写到端口号就可以了
![图片](https://github.com/user-attachments/assets/da3c19f1-6a4f-441d-b368-ea5b2fc2db4f)

**Comment by bnxydx** [comment]
服务正常呀，域名也是直接复制过来的

**Comment by baixin513** [comment]
可以参考一下论坛上的解决方案：https://bbs.fit2cloud.com/t/topic/4165/5
