### ISSUE TITLE
[BUG]  MaxKB 飞书回调地址报错

### ISSUE THREAD

**Issue by hao65103940** [1Panel-dev/MaxKB#1351]
### MaxKB 版本

v1.6.1

### 问题描述

MaxKB 飞书回调地址报错
![image](https://github.com/user-attachments/assets/a7ab31fe-ed1f-4939-9c0c-cadc7536a585)
![image](https://github.com/user-attachments/assets/d2303058-2964-41e3-8968-56effc4e2f30)

### 重现步骤

随便打开一个应用的飞书链接，在浏览器当中访问，就报错了。

**Comment by zyyfit** [comment]
这个地址是要填到飞书应用里的，不是在浏览器中访问用的

**Comment by baixin513** [comment]
对接飞书应用可以按照文档进行操作：https://maxkb.cn/docs/user_manual/X-Pack/app/#4
