### ISSUE TITLE
[FEATURE]支持上传文件，包括文档和图片等

### ISSUE THREAD

**Issue by Annlee71** [1Panel-dev/MaxKB#1352]
### MaxKB 版本

1.6.1

### 请描述您的需求或者改进建议

支持上传文件，包括文档和图片等

**Comment by liqiang-fit2cloud** [comment]
感谢关注，目前没有计划。

**Comment by Annlee71** [comment]
这是自动回复邮件，您的邮件已收悉，我会尽快给您回复，谢谢！                                                   李远辉  即日
