### ISSUE TITLE
[BUG]显示知识来源

### ISSUE THREAD

**Issue by Annlee71** [1Panel-dev/MaxKB#1353]
### MaxKB 版本

1.6.1

### 问题描述

目前显示知识来源显示的是执行情况，
![image](https://github.com/user-attachments/assets/33656d5c-3eba-43de-8124-f9fea720235b)
这是非常不合理的。
应该是显示检索结果下面的知识来源

### 重现步骤

目前显示知识来源显示的是执行情况，
![image](https://github.com/user-attachments/assets/33656d5c-3eba-43de-8124-f9fea720235b)
这是非常不合理的。
应该是显示检索结果下面的知识来源

**Comment by baixin513** [comment]
感谢反馈， 高级编排的应用会有多个知识库检索节点或多路召回节点，不同的应用不同的工作流编排，所以这里只能显示执行详情，用户可以在执行详情中看到每个节点的详情。

若不想让用户提问时看到可以选择不显示，或者使用简易应用。
