### ISSUE TITLE
[FEATURE]v1.6.1, SAAS厂商ISV提到想要 在 面向用户的  应用窗口 添加一个 下载 对话记录的 功能。

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1354]
### MaxKB 版本

v2.10

### 请描述您的需求或者改进建议

SAAS厂商ISV提到想要 在 面向用户的  应用窗口 添加一个 下载 对话记录的 功能。

### 请描述你建议的实现方案

具体实现效果如下：

<img width="344" alt="1728637640922" src="https://github.com/user-attachments/assets/a340969e-b1f3-4428-8cd0-d95219c10292">

在圈圈这里，能不能加载下载会话记录功能。 
该ISV已经是专业版用户。

**Comment by liqiang-fit2cloud** [comment]
实现不了，客户端没有身份，跟后台的对话记录对应不上。
