### ISSUE TITLE
[BUG]只有我一个人登录不上去吗 Invalid username or password

### ISSUE THREAD

**Issue by yanzhao77** [1Panel-dev/MaxKB#1356]
### MaxKB 版本

v1.6.1

### 问题描述

Invalid username or password，输入的账号密码是 # 用户名: admin
# 密码: MaxKB@123..

### 重现步骤

登录页面登录，

### 期待的正确结果

请提供可用的账号密码

### 附加信息

![image](https://github.com/user-attachments/assets/5858a7ab-feef-48a8-b88e-4532632ed71e)

**Comment by baixin513** [comment]
感谢反馈，您截图这个界面不是MaxKB ，是否反馈错产品了？
