### ISSUE TITLE
[FEATURE]知识库导出后，再上传文件显示不对的问题

### ISSUE THREAD

**Issue by zwjzxh520** [1Panel-dev/MaxKB#1357]
### MaxKB 版本

 v1.6.1 (build at 2024-09-29T19:14, commit: 81ffe59c)

### 请描述您的需求或者改进建议

excel知识库文件导出的时候，导出的格式是这样的：
![image](https://github.com/user-attachments/assets/d1800815-a32b-4c09-a63f-d8118b962e4a)

但是当用这样的格式导入的时候，内容变成了这样：
![Clip_2024-10-12_10-24-06](https://github.com/user-attachments/assets/eeacef1b-9eb3-4e0b-b12b-6815d2667376)

也就是说，在导入的时候，标题、内容、问题仍然被系统混合在了一起。

我了解默认情况下的行为就是这样的，这是没有问题的，但是在对于 MaxKB 导出的知识库文档，能不能将分段标题、分段内容、问题做单独的解析，放到分段详情的对应属性里。

### 请描述你建议的实现方案

估计在实现上比较麻烦的是，不敢确定excel中首行，如何对应分段详情中的标题、内容、问题，个人的建议是，可以添加一个特殊字符来识别，比如：  #标题  #内容 #问题，代表是分段详情对应的属性。

**Comment by baixin513** [comment]
感谢反馈，导出知识库是QA问答格式，所以导入的时候上选文件也选择QA 问答对。
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/4afb3c47-b8b2-4b4d-bf4e-5674ddab8688">

**Comment by zwjzxh520** [comment]
导出的文档是“表格”，导入选择的也是“表格”，这块有保持一致的。
