### ISSUE TITLE
[BUG]简单配置中关联的知识库名称过长时当鼠标移到该名称上时会无法显示全部名称

### ISSUE THREAD

**Issue by B14Lettingo** [1Panel-dev/MaxKB#1361]
### 联系方式

1812951966@qq.com

### MaxKB 版本

v1.6.1 (build at 2024-09-29T19:20, commit: 0bc093e6)

### 问题描述

简单配置中关联的知识库名称过长时当鼠标移到该名称上时会无法显示全部名称

### 重现步骤

定义多个名称过长的知识库，然后在简单配置中进行关联。

### 附加信息

https://github.com/user-attachments/assets/2507435a-1f15-474a-bd98-1965db2a072b

**Comment by baixin513** [comment]
感谢反馈，后续版本优化。
