### ISSUE TITLE
[BUG]pdf 文件高级分段默认分段长度为500，但生成的段落长度超过29000字符

### ISSUE THREAD

**Issue by Andyguo5891** [1Panel-dev/MaxKB#1363]
### 联系方式

19924537486

### MaxKB 版本

1.6.1

### 问题描述

pdf 文件高级分段默认分段长度为500，但生成的段落长度超过29000字符，应该和pdf文件兼容性有关
<img width="2559" alt="image" src="https://github.com/user-attachments/assets/ee2258ed-6d4a-4e15-876a-92739be0d72e">
[盛裕集团：2024产业园区可持续发展实践白皮书 从苏州工业园区三十年展望未来产业园区新路径.pdf](https://github.com/user-attachments/files/17354919/2024.pdf)

### 重现步骤

文档知识库上传附件的文档文件，然后默认高级分段即可出现。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by baixin513** [comment]
v1.7.0已经发布
