### ISSUE TITLE
[FEATURE] Suggestion for Adding an Offline Deployment Guide

### ISSUE THREAD

**Issue by Sanjeever** [1Panel-dev/MaxKB#137]
### MaxKB 版本

1.0.1

### 请描述您的需求或者改进建议

Hello! First of all, thank you very much for developing the "knowledge base Q&A system based on the LLM large language model". This project is very helpful and appealing to me. I've noticed that the current deployment documentation focuses on Docker deployment. In some cases, due to network restrictions or security policies, there might be a need for offline deployment. So, I was wondering if it would be possible to consider adding a guide for offline deployment?

I understand this might require additional effort and time, but even simple step-by-step instructions or basic directional guidance would be incredibly helpful for users like me. Of course, if there’s any way I can assist, I’m more than happy to offer my help or feedback.

Thank you again for your hard work, looking forward to your reply.

**Comment by liqiang-fit2cloud** [comment]
Hi,
MaxKB is a dockerized application and it's very easy to deploy. 
For offline deployment you can simply save the container image into a file and load the file in your local server by command docker save and docker load, then run it.
```
docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb
```
