### ISSUE TITLE
[BUG]知识库片段中插入markdown流程图，图中不显示文本内容

### ISSUE THREAD

**Issue by linfengjjj** [1Panel-dev/MaxKB#1373]
### 联系方式

蒋林峰

### MaxKB 版本

v1.6.1

### 问题描述

知识库片段中插入markdown流程图，图中不显示文本内容

### 重现步骤

1、知识库中创建一个空白文档
2、将如下的markdown流程图插入到片段中
![image](https://github.com/user-attachments/assets/ab2f7216-0efd-424e-848d-3edf17b07ace)
3、插入后显示的流程图中没有文本内容
![image](https://github.com/user-attachments/assets/3ecb48d7-b097-4f64-9eeb-49e32072483f)
![image](https://github.com/user-attachments/assets/ac1b0b88-6eac-479c-988a-3e63ebdd9bc0)

### 期待的正确结果

显示文本内容

**Comment by baixin513** [comment]
感谢反馈没有复现，请检查一下是否有多余空格。
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/ea61e76a-5b95-4b09-82d4-df7da1f18007">
<img width="1398" alt="image" src="https://github.com/user-attachments/assets/3053d3e0-05fe-45da-b9ac-4697329489ad">

**Comment by kaozb** [comment]
![image](https://github.com/user-attachments/assets/15dd5a6d-b6ed-40c8-afcb-5e002f6f7898) @baixin513  我也遇到了
```mermaid
graph TD;
    A[报告bug] --> B{收集信息}
    B -->|信息完整| C[提交反馈]
    B -->|信息不完整| D[请求补充信息]
    D --> E[等待用户回复]
    E --> F{是否收到回复}
    F -->|是| B
    F -->|否| G[记录未回复状态]
    G --> H[结束流程]
    C --> I[分配修复任务]
    I --> J[开发人员修复bug]
    J --> K[测试修复效果]
    K --> L{修复成功}
    L -->|是| M[更新状态]
    L -->|否| N[重新评估bug]
    M --> O[通知用户修复完成]
    N --> I
    O --> P[结束流程]
```

**Comment by kaozb** [comment]
![image](https://github.com/user-attachments/assets/6bae3a3c-d947-4771-803b-ffa53203cc31)

**Comment by baixin513** [comment]
> ![image](https://private-user-images.githubusercontent.com/85659592/377299658-6bae3a3c-d947-4771-803b-ffa53203cc31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzMwMjYsIm5iZiI6MTcyOTIzMjcyNiwicGF0aCI6Ii84NTY1OTU5Mi8zNzcyOTk2NTgtNmJhZTNhM2MtZDk0Ny00NzcxLTgwM2ItZmZhNTMyMDNjYzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA2MjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkODEyYTNiOTU2ZDk1MjU3ZDBkNjk0MmNmMDM5NTAyMTM4MmZhYjQ5MmNmOTdhYjgyNmFmOGQwODBmZmNiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CuDbTr4J10cOBiv4tF38KZBYU1Kl5TuWKle77QD4JQU)

你这个是AI回复的，AI返回的内容可能就有问题，这种流程不建议让模型回答，建议设置为直接回答。

**Comment by kaozb** [comment]
> > ![image](https://private-user-images.githubusercontent.com/85659592/377299658-6bae3a3c-d947-4771-803b-ffa53203cc31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzMwMjYsIm5iZiI6MTcyOTIzMjcyNiwicGF0aCI6Ii84NTY1OTU5Mi8zNzcyOTk2NTgtNmJhZTNhM2MtZDk0Ny00NzcxLTgwM2ItZmZhNTMyMDNjYzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA2MjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkODEyYTNiOTU2ZDk1MjU3ZDBkNjk0MmNmMDM5NTAyMTM4MmZhYjQ5MmNmOTdhYjgyNmFmOGQwODBmZmNiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CuDbTr4J10cOBiv4tF38KZBYU1Kl5TuWKle77QD4JQU)
> 
> 你这个输入输出是什么节点？ 如果这个流程图经过模型处理返回的，格式上可能就有问题，这种流程不建议让模型回答，建议设置为直接回答。
### ----------------------


上一个版本是正常的，有文字，更新了之后特地看了之前的历史记录，文字也没了，再回复的md也没有文字里，应该是前端的问题  
@baixin513

**Comment by zyyfit** [comment]
感谢反馈，在1.6.1版本复现了，1.7.0版本已经修复了，请等待版本发布后升级

**Comment by baixin513** [comment]
v1.7.0已经发布
