### ISSUE TITLE
[BUG]【大模型】豆包模型对接企业微信，可以正常询问问题。对接豆包智能体大模型，在企业微信询问问题，后台日志报错

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1374]
### MaxKB 版本

v1.6.1

### 问题描述

【豆包智能体】豆包模型对接企业微信，可以正常询问问题。对接豆包智能体大模型，在企业微信询问问题，后台日志报错
![03281d4030076f0d50e8fb8282a1f23](https://github.com/user-attachments/assets/7aa1e9ab-98f9-4e51-b6a4-f6910fc05001)

### 重现步骤

【豆包智能体】豆包模型对接企业微信，可以正常询问问题。对接豆包智能体大模型，在企业微信询问问题，后台日志报错
![f7141dd2-004c-4863-b13c-1acea502c51c](https://github.com/user-attachments/assets/4f82b51d-7661-4ce2-8f8a-6db9490a59bb)
![6cddfba514b343da0277847859bf0cf](https://github.com/user-attachments/assets/b60368d5-8b8b-47af-9df2-d59ab251cd79)
![819df83e9afd2e0a7134868da9958d8](https://github.com/user-attachments/assets/cfc3bae8-7f31-4f07-8fdb-aec17a5987e9)
![03281d4030076f0d50e8fb8282a1f23](https://github.com/user-attachments/assets/7b1a8e8b-22be-4106-91fb-4d20f8d59283)

**Comment by baixin513** [comment]
感谢反馈，豆包智能体返回的格式有些特殊，需要处理

**Comment by baixin513** [comment]
v1.7.0已经发布。
