### ISSUE TITLE
[BUG]【模型配置】在模型处配置了语言输入和语言合成两个模型后，在应用处开启后再关闭，不使用这个模型了，去模型处删除，提示关联了一个应用，无法删除该模型。

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1376]
### MaxKB 版本

v1.6.1

### 问题描述

【模型配置】在模型处配置了语言输入和语言合成两个模型后，在应用处开启后再关闭，不使用这个模型了，去模型处删除，提示关联了一个应用，无法删除该模型。
![9a64d28f93be046dae29ac4a14e0cc6](https://github.com/user-attachments/assets/10c901fc-ada7-4b0d-ae65-0e53c717a64f)

### 重现步骤

【模型配置】在模型处配置了语言输入和语言合成两个模型后，在应用处开启后再关闭，不使用这个模型了，去模型处删除，提示关联了一个应用，无法删除该模型。
![1def3e3c302d3b3963f35db5288a59f](https://github.com/user-attachments/assets/04ce6c30-299d-4182-af56-a8c5b28c1479)
![85e9ca571a5b6805d69b160d41a28c4](https://github.com/user-attachments/assets/64f9c619-54c1-4a46-ad5a-cd0b75836dc4)
![9a64d28f93be046dae29ac4a14e0cc6](https://github.com/user-attachments/assets/235d608a-4acc-4872-b1f6-b4f3cd23177c)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by baixin513** [comment]
v1.7.0已经发布
