### ISSUE TITLE
[BUG]引用分段界面，文件名过长会导致显示混乱

### ISSUE THREAD

**Issue by xusongtao** [1Panel-dev/MaxKB#1381]
### 联系方式

song

### MaxKB 版本

1.6.1

### 问题描述

引用分段界面，文件名过长会导致显示混乱
![image](https://github.com/user-attachments/assets/772942d4-674a-4985-ac9e-92f24b083b5b)

### 重现步骤

在引用分段界面，文件名过长会导致显示混乱

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请详细描述一下复现设备，使用的浏览器等信息
![图片](https://github.com/user-attachments/assets/deac1938-9a18-4830-812c-8ef739ad0e66)

**Comment by baixin513** [comment]
v1.7.0已经发布。
