### ISSUE TITLE
[FEATURE] 可以设置多选工作流

### ISSUE THREAD

**Issue by kaozb** [1Panel-dev/MaxKB#1383]
### MaxKB 版本

 v1.6.1 (build at 2024-09-29T19:14, commit: 81ffe59c)

### 请描述您的需求或者改进建议

我们的工作流如下图所示：

![image](https://github.com/user-attachments/assets/68a11b4b-7618-44ed-8bc0-6d9dc2fb14d3)

又是处理中我们需要搜索材料、有时不用，有时又有很多其他的流程

现阶段走指定的流只能要求用户在自己的输入中加以关键字判断。使用起来非常不便，希望能够在前端增加一个如下图所示的功能 
![image](https://github.com/user-attachments/assets/6155ee61-92cd-4f92-900b-cc986ca12aed)

# 万分感谢 ！

**Comment by baixin513** [comment]
感谢反馈，亲你可以把想要用户提问的放置开场白的快捷问题中。是否可以解决你的问题？
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/ba1f8c70-b322-45f6-8196-67baf97faef6">
