### ISSUE TITLE
[BUG] maxkb对接inference模型

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1389]
### 联系方式

xuwei5188916@yeah.net

### MaxKB 版本

v1.6.1

### 问题描述

maxkb对接inference模型 填写页面：基础模型填写xinference的model id 也无法添加模型，必须model id和NAME一致，才能添加。这个逻辑是有问题的。
![图片](https://github.com/user-attachments/assets/8b5cd92e-4a96-480d-8c8e-85e9fdffa1c8)

### 重现步骤

maxkb对接inference模型 填写页面：基础模型填写xinference的model id 也无法添加模型，必须model id和NAME一致，才能添加。这个逻辑是有问题的

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请检查一下inference的服务是否正常，模型是否已成功启动
![图片](https://github.com/user-attachments/assets/0c6ac60c-9d5c-47c0-95e5-c7ee41631fc7)
![图片](https://github.com/user-attachments/assets/b270abe7-f7e8-4d8d-9c11-811345c3a086)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by maninhill** [comment]
v1.7 已发布。
