### ISSUE TITLE
[FEATURE]希望可以对上传的知识库文档手工打标签

### ISSUE THREAD

**Issue by jacbo0112** [1Panel-dev/MaxKB#1391]
### MaxKB 版本

1.6.1

### 请描述您的需求或者改进建议

希望可以对上传的知识库文档手工打标签。这样可以人工的加一些比较准确的信息，提问的时候如果标签命中，可以增加准确性。

**Comment by baixin513** [comment]
感谢反馈，从上述描述来看，您应该是要给文档的分段添加标签，来提高提问时分段的命中。这个目前是支持人工给分段添加关联问题标签的。
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/9ead7a29-002f-4a14-a2ce-c3cd5bcd67e7">

**Comment by jacbo0112** [comment]
可以对整个文档加吗，我看这个是加在每个分段上的

**Comment by jacbo0112** [comment]
还没测试过，不清楚关联问题和打标签是不是同样的作用。因为打标签不一定对应问题。他主要是对应问题中的一些关键字

**Comment by baixin513** [comment]
不可以，当前知识库检索的是文档中分段，给文档分段添加问题关键字会提高命中的。
知识库打标签知识库方便人工维护查找，不会涉及到提问的命中。
