### ISSUE TITLE
[FEATURE]希望支持自定义字典

### ISSUE THREAD

**Issue by xusongtao** [1Panel-dev/MaxKB#1397]
### MaxKB 版本

v1.6.1

### 请描述您的需求或者改进建议

检索模式支持“全文检索”，全文检索的逻辑是根据关键词去检索，能否支持自定义字典词库呢。比如“我喜欢买小米手机”，理应拆成“我”、“喜欢”、“买”、“小米手机”，避免被拆成“我”、“喜欢”、“买”、“小米”、“手机”

### 请描述你建议的实现方案

支持自定义字典

**Comment by liqiang-fit2cloud** [comment]
你这是传统的中文分词和全文检索，目前没有计划。
