### ISSUE TITLE
[BUG] 添加讯飞星火模型添加失败

### ISSUE THREAD

**Issue by GoodTime0313** [1Panel-dev/MaxKB#1411]
### MaxKB 版本

 社区版 v1.6.1 (build at 2024-09-29T19:14, commit: 81ffe59c)

### 问题描述

添加讯飞星火模型添加失败，设置的是HTTP请求地址 https://spark-api-open.xf-yun.com/v1，请求超时报错:校验失败,请检查参数是否正确: SparkLLMClient wait LLM api response timeout 30 seconds。
[官方文档](https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html#_3-%E8%AF%B7%E6%B1%82%E8%AF%B4%E6%98%8E)
需要在请求头设置APIPassword

### 重现步骤

/

**Comment by baixin513** [comment]
感谢反馈，请参考官方文档中的添加讯飞模型：https://maxkb.cn/docs/user_manual/model/model/#15
