### ISSUE TITLE
函数库的在应用的使用，希望能够支持多条件

### ISSUE THREAD

**Issue by wucanhong** [1Panel-dev/MaxKB#1418]
### MaxKB 版本

1.6

### 请描述您的需求或者改进建议

目前如果想通过问题优化，实现多个条件去函数库查询是无法实现的，只能实现单条件，希望能够函数库的组局，按照入参数量，增加关联线

### 附加信息

![微信图片_20241021174950](https://github.com/user-attachments/assets/5c5e1554-b00c-4632-9725-7d3f45e35619)

**Comment by wucanhong** [comment]
![Uploading 微信图片_20240315165226.jpg…]()

**Comment by baixin513** [comment]
感谢反馈，1.7版本中应用的节点支持多出多进。
同 issue #801
