### ISSUE TITLE
[FEATURE]OpenAI 格式模型添加报错

### ISSUE THREAD

**Issue by ChrisKimZHT** [1Panel-dev/MaxKB#142]
### MaxKB 版本

v1.0.1

### 请描述您的需求或者改进建议

很多模型 API 格式与 OpenAI ChatGPT 相同，我称之 OpenAI 兼容模型。希望能够支持 OpenAI 兼容模型，这样相当于一次性兼容了非常多大模型种类，可以接入更多本地或远程模型。

### 请描述你建议的实现方案

将 OpenAI 模型的相关代码复制一份为 OpenAI 兼容模型，提供自定义模型名称字段的功能，这样应该就能实现模型兼容了。

**Comment by baixin513** [comment]
感谢反馈，选择OpenAI 供应商，添加 API 格式相同模型，基础模型自定义输入后回车即可。
当前该操作存在 bug，在1.0.3 版本中修复后便可添加。
