### ISSUE TITLE
[BUG]windows wsl ubuntu docker安装后每次电脑重启知识库内容丢失

### ISSUE THREAD

**Issue by lonngxiang** [1Panel-dev/MaxKB#1421]
### MaxKB 版本

1.6.1

### 问题描述

windows wsl ubuntu docker安装后每次电脑重启知识库内容丢失

### 重现步骤

windows wsl ubuntu docker安装后每次电脑重启知识库内容丢失

**Comment by baixin513** [comment]
感谢反馈，需要挂在数据目录
例如：数据目录是：/var/lib/postgresql/data ，那把这个目录挂载到本windows具体目录中
可参考论坛解决方案：https://bbs.fit2cloud.com/t/topic/5701/4
