### ISSUE TITLE
[BUG]不支持IE浏览器

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1422]
### MaxKB 版本

1.6.1

### 问题描述

智能助手以悬浮窗或全屏模式嵌入第三方系统时，在IE浏览器中无法使用

### 重现步骤

使用IE6~IE11任意版本运行嵌入的智能助手，包括maxkb均无法运行

### 期待的正确结果

期待在IE8~IE11上可以正常运行和显示智能助手（maxkb后台可以不支持ie)

**Comment by liqiang-fit2cloud** [comment]
没有计划支持IE，微软已经停止支持IE，建议使用Edge。
