### ISSUE TITLE
[FEATURE]开场白，常见问题，多个客户提出需要多个tab场景

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1426]
### MaxKB 版本

v1.6.1

### 请描述您的需求或者改进建议

开场白，常见问题，多个客户提出需要多个tab场景。

尤其是专业领域，高频次问题。 比如高校（上海某高校提出了该需求），还有面向公众的，某客户也提出了。 

### 请描述你建议的实现方案

下面这个是客户之前用的，想淘汰的。
<img width="243" alt="1729587068432" src="https://github.com/user-attachments/assets/fb46162d-91bb-4d58-a804-24808d50e84a">

**Comment by baixin513** [comment]
感谢反馈，后续版本考虑一下。

**Comment by baixin513** [comment]
后续开场白支持渲染html

**Comment by baixin513** [comment]
v1.8.0 已发布！

**Comment by lianxintao** [comment]
想问一下，社区版v1.8.0版本中开场白支持渲染html吗？如果支持的话该怎么使用呢，直接将html代码放入开场白中吗
