### ISSUE TITLE
[BUG]公众号对接，答案里面涉及图片的话， 微信公众号只收到 一串ID , 无法返回图片

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [1Panel-dev/MaxKB#1427]
### 联系方式

zaopeng.guo@fit2cloud.com

### MaxKB 版本

1.6.1

### 问题描述

公众号对接，答案里面涉及图片的话， 微信公众号只收到 一串ID , 无法返回图片

### 重现步骤

1、应用对接公众号，问一个问题返回的结果有图片的。
2、公众号回复一串 ID 
![image](https://github.com/user-attachments/assets/3e225e23-3071-4920-a8ed-1953182e8eef)
这是对话日志：
![image](https://github.com/user-attachments/assets/419196f4-a7bc-453e-8c55-7cdf0d96d6bf)
这是后台的报错日志：
![image](https://github.com/user-attachments/assets/e9452973-9f8f-4249-94dc-72244779a7da)

**Comment by fit2cloud-zaopengguo** [comment]
补充：回答里面包含图片的话，后端报错，没有内容返回。但是对话日志是有记录的。
<img width="897" alt="image" src="https://github.com/user-attachments/assets/beaacc1f-736b-41dd-b15d-679796283b8a">
<img width="838" alt="image" src="https://github.com/user-attachments/assets/a8d54787-7e95-4755-be5f-6ad24a42ee31">
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/b6791896-789b-4e1b-9ccb-1861a7d349b7">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by maninhill** [comment]
v1.7 已发布。
