### ISSUE TITLE
[BUG]qwen-max 输出最大tokens参数超过8192，报错

### ISSUE THREAD

**Issue by Andyguo5891** [1Panel-dev/MaxKB#1439]
### 联系方式

19924537486

### MaxKB 版本

1.6.1

### 问题描述

应用配置 qwen-max 大语言模型，设置输出最大tokens参数超过8192，问答时报错

### 重现步骤

![image](https://github.com/user-attachments/assets/b3b4b38d-c409-40cf-8bae-9e38685b1903)

**Comment by baixin513** [comment]
配置错误，非bug,  设置的最大输出tokens 不要超过所选模型的限制。
