### ISSUE TITLE
Ollama模型添加失败的问题

### ISSUE THREAD

**Issue by BruceHaw** [1Panel-dev/MaxKB#144]
### MaxKB 版本

latest

### 请描述您的需求或者改进建议

[BUG] openai类接口域名（string报错）和ollama接口域名（域名不存在）均添加失败。macos，本地ollama可正常运行，论坛中的方法也没不起作用，请给出api格式或者建议修复，bug解决后可删除该issue。

**Comment by baixin513** [comment]
感谢反馈，Ollama 服务需要使用宿主机的 IP 地址，排查一下网络问题，要保证在 maxkb 容器中能访问Ollama 服务。
如果还不行，请提供一下表单截图及运行环境截图。

**Comment by Gitreceiver** [comment]
openai类的模型可以导入了，域名结尾需要加v1

**Comment by baixin513** [comment]
如果没有问题，该 issue 先关闭了。

**Comment by zmalibaba** [comment]
如果你想调用本地的ollama 中的大模型，域名aip试试：http://host.docker.internal:11434/
我的是这样成功的。

**Comment by Gitreceiver** [comment]
> 如果你想调用本地的ollama 中的大模型，域名aip试试：http://host.docker.internal:11434/ 我的是这样成功的。

是的，后来改成这个：http://host.docker.internal:11434/

**Comment by Gitreceiver** [comment]
> 如果没有问题，该 issue 先关闭了。

没问题
