### ISSUE TITLE
[FEATURE]希望对接的 cas 能支持返回 text/html 类型

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1455]
### MaxKB 版本

v1.6.1

### 请描述您的需求或者改进建议

希望对接的 cas 能支持返回 text/html 类型
![1729841705359](https://github.com/user-attachments/assets/0dcef2a0-855e-4c9f-8f43-a8781cea10f7)

**Comment by liqiang-fit2cloud** [comment]
只支持标准cas的xml格式，特殊格式的请自行处理。
