### ISSUE TITLE
[BUG]导入PDF文档，报错：Null characters are not allowed.

### ISSUE THREAD

**Issue by Wangqiubao** [1Panel-dev/MaxKB#1468]
### 联系方式

2630060044@qq.com

### MaxKB 版本

 v1.6.1 (build at 2024-09-29T19:14, commit: 81ffe59c)

### 问题描述

我导入文档，弹窗提示:Null characters are not allowed.
我尝试删除部分段落后就可以导入

### 重现步骤

我把pdf发给你

### 期待的正确结果

直接导入

### 附加信息

[kutz大神贝叶斯自编码.pdf](https://github.com/user-attachments/files/17536179/kutz.pdf)

**Comment by lhchong** [comment]
好奇试了一下，估计是里面的公式这种特殊符号识别不到。 补充一张图
![image](https://github.com/user-attachments/assets/e557a86a-1076-490f-beb5-a0c0d9c731d3)

**Comment by baixin513** [comment]
感谢反馈，我们排查一下。

**Comment by yanyu2015** [comment]
现在依然有这个问题

**Comment by Feng-key** [comment]
![屏幕截图 2024-11-14 180639](https://github.com/user-attachments/assets/448ef746-60cc-4726-b765-a7a6f6005eaa)
我的也是PDF一上传就出BUG 完全分不了段
