### ISSUE TITLE
[BUG] 密码不支持分号

### ISSUE THREAD

**Issue by ChrisKimZHT** [1Panel-dev/MaxKB#147]
### MaxKB 版本

v1.0.1 (build at 2024-04-15T17:30, commit: b43b8ec8)

### 问题描述

我的常用密码内含有分号，但密码不支持分号

### 重现步骤

TESTTEST0;

![QQ截图20240417183425](https://github.com/1Panel-dev/MaxKB/assets/49368462/7048258f-7e0e-4e97-b4c3-ac3ba2b2a4a8)

**Comment by baixin513** [comment]
是的，当前限制了。
