### ISSUE TITLE
[FEATURE] 开场白设计能够丰富些吗？

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1493]
### MaxKB 版本

v1.6.1

### 请描述您的需求或者改进建议

开场白的题目能够设计丰富些吗？同一个分类可以分类，然后可以折叠。
![图片](https://github.com/user-attachments/assets/6d19fbfc-5be8-4b8d-8924-5bdbc08ad47a)

**Comment by liqiang-fit2cloud** [comment]
同 https://github.com/1Panel-dev/MaxKB/issues/1426
