### ISSUE TITLE
[FEATURE]知识库，上传Excel文件优化建议，让用户可以选择“|” 方式处理

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1495]
### MaxKB 版本

v1.6.1

### 请描述您的需求或者改进建议

v1.6.1的Excel上传后 处理效果 如下：
ID: 100728; 用例名称: 场景编辑-批量操作-数据勾选&展开; 所属模块: /接口测试/接口自动化; 前置条件: 步骤大于等于2条; 备注: ; 步骤描述: 步骤下含有子节点; 预期结果: 点击步骤可展开显示子节点; 编辑模式: STEP; 标签: ; 责任人: Administrator; 用例等级: P0; 用例状态: 未开始

这个完全没问题。

### 请描述你建议的实现方案

我自己在多个客户那里测试下来，发现 Excel文件放到word里后，再上传，在知识库里是下面这个效果：
<img width="637" alt="1730194221588" src="https://github.com/user-attachments/assets/1bef9f6c-8b54-4778-90e9-143257e3d631">

这样的分段给到模型，进行提问，效果不错，这个是LLM模型的通用处理办法。

希望知识库可以直接将Excel进行上传，上传后 用"|" 隔离标注每列， 让用户有这个选择。

现在的Excel设计也是OK的，但是"|"方案，是LLM里面处理表格的通用做法，我测下来也是如此。

**Comment by baixin513** [comment]
没太看懂。

word文档是转为MD格式处理的，word中的表格自然也会转为MD格式。  
Excel表格文档是按照标题：记录值的格式处理。
用户想要什么格式就选择相应的文件类型。
