### ISSUE TITLE
[FEATURE] 高级编排的应用，在对话反馈的结果中希望可以像简单编排那样展示出引用分段。

### ISSUE THREAD

**Issue by huskiesir** [1Panel-dev/MaxKB#1515]
### MaxKB 版本

1.6.0

### 请描述您的需求或者改进建议

高级编配的对话结果是这样：
<img width="1954" alt="image" src="https://github.com/user-attachments/assets/c7b33b1a-009b-4d70-9421-c5db0d781815">

希望做到像简单编排这种：
<img width="1955" alt="image" src="https://github.com/user-attachments/assets/7864acb2-5e12-4705-9b5f-1b7777cdc7b3">

**Comment by baixin513** [comment]
感谢反馈， 高级编排的应用会有多个知识库检索节点或多路召回节点，不同的应用不同的工作流编排，所以这里只能显示执行详情，用户可以在执行详情中看到每个节点的详细输出。

若不想让用户提问时看到可以选择不显示，或者使用简易应用。
