### ISSUE TITLE
[FEATURE在docker-compose.yml加了环境变量添加HTTPS PRoxY 文档向量化失败

### ISSUE THREAD

**Issue by armored-glitch** [1Panel-dev/MaxKB#1519]
### MaxKB 版本

 v1.6.1 

### 请描述您的需求或者改进建议

您好，我们公司时纯内网环境，没办法使用公网大模型所以就添加了socket5代理，但是这样的话会导致向量化失败，不知道后期会支持吗嘛
![image](https://github.com/user-attachments/assets/7fa69b1d-c18e-4b8b-aa8d-561774ac757b)

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，目前没有计划支持。
