### ISSUE TITLE
[BUG] 知识库添加分段，手动添加关联问题，鼠标点击会直接被清掉。

### ISSUE THREAD

**Issue by hao65103940** [1Panel-dev/MaxKB#1520]
### MaxKB 版本

v1.6.1

### 问题描述

知识库添加分段，手动添加关联问题，鼠标点击会直接被清掉。

https://github.com/user-attachments/assets/11d0111d-f555-4ed6-85c6-89d7c7cc7d74

### 重现步骤

同上步骤

**Comment by zyyfit** [comment]
您好，这里输入框手动输入后需要点击下面的下拉框才是添加关联问题，只是输入不点击下面的下拉框的话是搜索已经有的关联问题，如果没有搜到也是支持添加新问题的，就是需要手动点一下弹出的下拉框

![图片](https://github.com/user-attachments/assets/5f4065a9-0187-4a85-924f-044fe523e4c0)
