### ISSUE TITLE
[BUG]知识库上传pdf有时不能正常识别

### ISSUE THREAD

**Issue by Liamskey** [1Panel-dev/MaxKB#1524]
### 联系方式

19177391086@163.com

### MaxKB 版本

1.6.1

### 问题描述

有些pdf文件无法正常识别

### 重现步骤

上传扫描版书籍pdf

### 期待的正确结果

正常识别并切片

### 相关日志输出

```shell
无日志
```

### 附加信息

![捕获](https://github.com/user-attachments/assets/2f2eeab5-447b-4213-8ec9-0f21bae3e793)

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，目前没有计划在pdf识别上投入，需要的话你可以自己用其他工具把pdf解析成markdown之后再上传到MaxKB。
