### ISSUE TITLE
[FEATURE]建议升级知识库部分内容，有时pdf无法正常识别

### ISSUE THREAD

**Issue by Liamskey** [1Panel-dev/MaxKB#1525]
### MaxKB 版本

1.6.1

### 请描述您的需求或者改进建议

有时知识库上传pdf无法正常识别，建议学习ragflow的方法，预先用模型ocr理解后再导入
![捕获](https://github.com/user-attachments/assets/d1df2e80-2c72-4fb8-b3c0-a89e2989993c)

### 请描述你建议的实现方案

建议学习ragflow的方法，预先用模型ocr理解后再导入
![捕获2](https://github.com/user-attachments/assets/a3a69900-66a2-4703-aa68-13f5eb5c130e)
![捕获3](https://github.com/user-attachments/assets/64bc2454-ac33-45c9-8957-baf3478da7ce)

### 附加信息

![捕获3](https://github.com/user-attachments/assets/d35f2114-16d8-4d9d-ab7f-9ca2c06db6f6)
![捕获2](https://github.com/user-attachments/assets/6f502f32-7980-439d-bde7-7c402ac57082)
![捕获](https://github.com/user-attachments/assets/ce7e1b9a-fda1-46f8-bbb3-9f9e046d6f85)

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，目前没有计划在pdf识别上投入，需要的话你可以自己用其他工具把pdf解析成markdown之后再上传到MaxKB。
