### ISSUE TITLE
[BUG] docker 版本放错了大哥

### ISSUE THREAD

**Issue by kaozb** [1Panel-dev/MaxKB#1529]
### MaxKB 版本

1.6

### 问题描述

![image](https://github.com/user-attachments/assets/90a77c49-f7cb-4179-a763-b219aee80a35)
写的1.7 下载下来是1.6

### 重现步骤

无

**Comment by liqiang-fit2cloud** [comment]
<img width="727" alt="image" src="https://github.com/user-attachments/assets/f50277b6-52cf-4065-92ee-1e8ba39c385d">

没问题
