### ISSUE TITLE
[FEATURE]希望能够新增应用导出和导入功能

### ISSUE THREAD

**Issue by hello1534** [1Panel-dev/MaxKB#1532]
### MaxKB 版本

1.6.1

### 请描述您的需求或者改进建议

在maxkb中创建了一个复杂编排的应用后想要分享给别人，由于不在一个局域网中不能够使用同一个系统，所以别人只能照着在自己系统中再创建一次，这样当应用比较复杂时需要浪费大量时间，希望能够有一个导入导出应用的功能，将应用导出后其他人导入就能够复制一份一样的应用到系统中。

**Comment by baixin513** [comment]
感谢反馈，暂时没有计划。
