### ISSUE TITLE
[BUG] 仍旧复现上传docx文件后，图片未正常识别导入

### ISSUE THREAD

**Issue by Henry-Shaw** [1Panel-dev/MaxKB#1533]
### MaxKB 版本

1.7.0

### 问题描述

问题同 #1380 
BUG修复已在PR #1382 进行修复，但是在PR #1482 中对代码进行了覆盖，未调用函数image_to_mode为修复添加的额外处理参数，导致BUG仍旧存在

### 重现步骤

操作同 #1380

**Comment by shaohuzhang1** [comment]
并没有覆盖代码,提供一下你的doc文件

**Comment by shaohuzhang1** [comment]
sorry 没注意看 pic和pict的逻辑处理也不一样

**Comment by Henry-Shaw** [comment]
是的，pic和pict的逻辑处理不太一样。

docx中的document.xml旧版本的pict结构是下面这种，xpath是.//v:imagedata/@r:id，但是namespace中xmlns:v="urn:schemas-microsoft-com:vml"未默认namespace中声明，所以额外加了一个namespace。

不过比较让我觉得也比较困惑的一点是pic标签和pict标签传递给image_to_mode函数的image不是同一个type，pict标签的image是可以用namespaces参数额外指定的，而pic标签的image不能用namespaces额外指定参数。所以image_to_mode函数改的不太优雅
```xml
<w:pict>
	<v:shape id="_x0000_i1025" o:spt="75" type="#_x0000_t75" style="height:125.95pt;width:195.8pt;" filled="f" stroked="f" coordsize="21600,21600">
			<v:path/>
			<v:fill on="f" focussize="0,0"/>
			<v:stroke on="f"/>
			<v:imagedata r:id="rId4" grayscale="f" bilevel="f" o:title=""/>
			<o:lock v:ext="edit" aspectratio="t"/>
			<w10:wrap type="none"/>
			<w10:anchorlock/>
	</v:shape>
</w:pict>
```
