### ISSUE TITLE
[BUG]对话时弹出”对话不存在“

### ISSUE THREAD

**Issue by yjggg** [1Panel-dev/MaxKB#1534]
### 联系方式

2399151171@qq.com

### MaxKB 版本

1.6

### 问题描述

![image](https://github.com/user-attachments/assets/067995c4-7425-4d54-a6d1-5555d03aab6b)
对话时弹出"对话不存在"，但又可以正常问答。

### 重现步骤

![image](https://github.com/user-attachments/assets/a6a42a58-0e81-4222-884f-5f0e832287cc)
做了个问题分类，是分支太多的原因吗

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您的截图点开无法看清楚具体是什么内容，我只是选了相同的组件进行了测试，请您检查一下组件里是否有引用对话ID之类的变量，如果没有的话请贴一下函数内容和报错日志

![图片](https://github.com/user-attachments/assets/f4dedd1a-d5a7-475a-8e87-4617a774f75a)

![图片](https://github.com/user-attachments/assets/57076d47-2bb4-43aa-951c-47392022e9df)

**Comment by yjggg** [comment]
函数里引用了历史变量做分类，日志和调试界面都是正常的，只有演示界面会有"对话不存在"

**Comment by zyyfit** [comment]
> 函数里引用了历史变量做分类，日志和调试界面都是正常的，只有演示界面会有"对话不存在"

历史变量是指在1.6.1版本添加的全局变量吗？

**Comment by yjggg** [comment]
> > 函数里引用了历史变量做分类，日志和调试界面都是正常的，只有演示界面会有"对话不存在"
> 
> 历史变量是指在1.6.1版本添加的全局变量吗？

是的

**Comment by baixin513** [comment]
您使用的是官方镜像么 ？ 如果是官方镜像，你点击新建对话进行提问试一下，如果是二开过的还请自行排查一下原因。

**Comment by baixin513** [comment]
当前在测试环境上没有复现，可以升级到最新版本，再看一下。

**Comment by yjggg** [comment]
> 当前在测试环境上没有复现，可以升级到最新版本，再看一下。

升级版本后问题已解决

**Comment by baixin513** [comment]
好的，该issue先关闭了。
