### ISSUE TITLE
[BUG] 如果知识库是直接命中的，回答输出内容存在问题

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1535]
### 联系方式

xuwei5188916@yeah.net

### MaxKB 版本

v1.7.0

### 问题描述

如果知识库是直接命中的，回答输出内容存在问题 ，现在输出 分段标题：回复内容。如果分段的内容没有标题。就直接开始以冒号输出。
![图片](https://github.com/user-attachments/assets/06c9ac6c-29f7-42bb-90d2-4092a5d70201)

### 重现步骤

如果知识库是直接命中的，回答输出内容存在问题 ，现在输出 分段标题：回复内容。如果分段的内容没有标题。就直接开始以冒号输出。
![图片](https://github.com/user-attachments/assets/06c9ac6c-29f7-42bb-90d2-4092a5d70201)

**Comment by xuwei999-NT** [comment]
v1.6没有这个BUG，今天升级到v1.7才出现的。

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by baixin513** [comment]
v1.7.1已发布
