### ISSUE TITLE
[FEATURE]关于语音合成包含代码很鬼畜的问题

### ISSUE THREAD

**Issue by DDSXIAO** [1Panel-dev/MaxKB#1536]
### MaxKB 版本

1.6.1

### 请描述您的需求或者改进建议

语音合成方面有个问题，不晓得算问题还是算需求。就是如果回答的内容里，包含了HTML标签，语音合成会把这段代码读出来，很鬼畜。能否只读文字内容呢？

**Comment by baixin513** [comment]
感谢反馈，如果回复内容就是各种开发语言的代码也不能直接过滤不读，这块需要考虑一下好的处理方法。

**Comment by baixin513** [comment]
目前看各大模型语音播放时标签内容也都会播放读取。
经讨论后，暂时先不做处理。
