### ISSUE TITLE
[BUG] 浮窗模式乱码:首次进入带浮窗模式的网站会有乱码，另外浮窗模式太高，关闭按钮被隐藏了

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1539]
### 联系方式

xuwei5188916@yeah.net

### MaxKB 版本

v1.7.0

### 问题描述

乱码：
![图片](https://github.com/user-attachments/assets/411e7147-53fc-4eb1-8634-119f8796094e)

浮窗模式太高：
![图片](https://github.com/user-attachments/assets/e1a5fc8d-4072-499d-9107-16c08315055d)

### 重现步骤

乱码：
![图片](https://github.com/user-attachments/assets/411e7147-53fc-4eb1-8634-119f8796094e)

浮窗模式太高：
![图片](https://github.com/user-attachments/assets/e1a5fc8d-4072-499d-9107-16c08315055d)

### 期待的正确结果

不乱码

浮窗模式自适应

**Comment by baixin513** [comment]
感谢反馈，看截图像是显示分辨率问题或浏览器缩放设置，可以调整一下分辨率。

**Comment by baixin513** [comment]
引导图乱码应该是字符编码问题，我们是UTF-8 ，可能和嵌入网站的编码格式不同，你可以确认一下嵌入网站的编码。

**Comment by xuwei999-NT** [comment]
乱码问题解决了，我的浏览器缩放率必须是90%，才能显示。如果是正常100%，上面的关闭按钮就被隐藏。
![图片](https://github.com/user-attachments/assets/20201595-2fce-493e-911c-05a46fd376b1)

**Comment by zyyfit** [comment]
> 乱码问题解决了，我的浏览器缩放率必须是90%，才能显示。如果是正常100%，上面的关闭按钮就被隐藏。 ![图片](https://private-user-images.githubusercontent.com/181533222/382685144-20201595-2fce-493e-911c-05a46fd376b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTU0MjUsIm5iZiI6MTczMDcxNTEyNSwicGF0aCI6Ii8xODE1MzMyMjIvMzgyNjg1MTQ0LTIwMjAxNTk1LTJmY2UtNDkzZS05MTFjLTA1YTQ2ZmQzNzZiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMDEyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjAxOTAzNWM1ZjA4YmE0YTAxYmVmYTJmNzA5Y2M5NTEyMjJiMzM5Y2VmNGVkYmFhMmU4ZDlkMjMyN2QyYzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lD3wrH79ykQpqnmM_AUrVJA9zWRCriKL-Ig47bYFXig)

请问您的电脑分辨率是多少？

**Comment by xuwei999-NT** [comment]
1920*1080
![图片](https://github.com/user-attachments/assets/354ab879-6faf-4782-82f1-86096b9065d6)
