### ISSUE TITLE
[FEATURE]工作流编排应用记住节点的收起/展开状态

### ISSUE THREAD

**Issue by DDSXIAO** [1Panel-dev/MaxKB#1543]
### MaxKB 版本

1.7

### 请描述您的需求或者改进建议

现在的高级编排界面，如果流程少还行。但遇到知识库比较复杂的场景（就比如我这里），高级编排就会异常庞杂。
现在的方式仅仅只是将组件收缩起来的方式，实际上会更乱，因为再次打开编排界面，所有的组件又都会展开。
其实我想表达，现在高级编排的界面的设计模式强烈建议改变一下。
可以参考传统的流程编排界面，或者VS studio的界面设计模式，真的非常经典，也非常适用高级编排的使用场景。
左侧组件栏、中间流程图，右边是组件属性栏，尤其是右边的组件属性，可以根据选择流程上不同的组件，显示不同的属性，这样整个界面使用起来就非常的方便。

### 请描述你建议的实现方案

可以参考传统的流程编排界面，或者VS studio的界面设计模式，真的非常经典，也非常适用高级编排的使用场景。
左侧组件栏、中间流程图，右边是组件属性栏，尤其是右边的组件属性，可以根据选择流程上不同的组件，显示不同的属性，这样整个界面使用起来就非常的方便。

**Comment by baixin513** [comment]
感谢您的反馈，当前每个节点的内容并没有那么多，在画布上可以一下看到所有的设置情况，方便调整，一般属性内容较多的会放到抽屉中，整体交互调整改动比较大，当前暂无计划。

另外，您反馈的将节点收起后 再进入画布还会默认展开这可以优化一下，记住节点的收起/展开状态。

**Comment by baixin513** [comment]
v1.7.1已发布
