### ISSUE TITLE
[BUG] 使用离线安装的方式，由于 docker-compose-pgsql.yml 中 pgsql 容器没有设置 restart：always，导致机器宕机重启后，服务没法自启动

### ISSUE THREAD

**Issue by RedCG** [1Panel-dev/MaxKB#1547]
### 联系方式

18159668371

### MaxKB 版本

1.7

### 问题描述

使用离线安装的方式，由于 docker-compose-pgsql.yml 中 pgsql 容器没有设置 restart：always，导致机器宕机重启后，服务没法自启动

### 重现步骤

1、服务器关机
2、重启查看服务状态，pgsql 已经退出，maxkb 有设置重启参数，所以一直处于 restarting 阶段
![image](https://github.com/user-attachments/assets/393c056f-9404-4183-b83e-a4caae8ec801)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by baixin513** [comment]
v1.7.1已发布
