### ISSUE TITLE
[BUG]docker-compose-pgsql.yml中PGSQL_PORT和/opt/maxkb/.env 里 不一致

### ISSUE THREAD

**Issue by shenkaibo** [1Panel-dev/MaxKB#1548]
### 联系方式

shenkaibo

### MaxKB 版本

1.7.0

### 问题描述

docker-compose-pgsql.yml中PGSQL_PORT和/opt/maxkb/.env 里 不一致

### 重现步骤

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/34cb8a0e-bf40-4c91-b5ca-0c22cef0542f">
<img width="437" alt="image" src="https://github.com/user-attachments/assets/d49dd619-206f-4b03-9037-0766d27b9c2f">
<img width="594" alt="image" src="https://github.com/user-attachments/assets/db7126a8-7d0c-4d58-ad17-a32e4211ec8f">

**Comment by liqiang-fit2cloud** [comment]
。。。

**Comment by baixin513** [comment]
请描述一下升级步骤。

**Comment by baixin513** [comment]
v1.7.1已发布
