### ISSUE TITLE
[BUG] 高级编排——工作流多进多出，两个分支连接到同一个输出节点异常，提示：“Must be a valid UUD“

### ISSUE THREAD

**Issue by lhchong** [1Panel-dev/MaxKB#1550]
### MaxKB 版本

v1.7.0

### 问题描述

高级编排——工作流多进多出，两个分支连接到同一个输出节点异常，提示：“Must be a valid UUD“

## 异常情况1
在判断器后将 **IF**分支连到输出1，将**IF1**分支后增加一个额外节点，再将这个额外节点连到输出1，提示异常.对应图1
![error1](https://github.com/user-attachments/assets/5b5d1f38-fe3d-41b7-8746-09f10c4d872c)

## 异常情况2
在判断器后将 **IF**分支连到输出1，将**IF1**分支连接到**输出2**，再将**输出1**和**输出2**连接到**输出3**， 调试或者运行时，输出3不会被执行，也没有任何异常提示。执行详情中也不展示**输出3**节点的执行记录
![image](https://github.com/user-attachments/assets/d814bb7c-07e6-4c4c-8388-f9e8659874bf)
![image](https://github.com/user-attachments/assets/fcc596fe-fb28-4dbd-a5d0-a32565979525)

## 正常情况
在判断器后将**IF、IF1**两个分支连接到同一个输出，工作流正常运行。对应图2
![errro2](https://github.com/user-attachments/assets/124eec06-7b60-4f69-8120-b23c86eb1bc1)

### 期待的正确结果

多个节点连接同一个输出，能够正常运行

**Comment by zyyfit** [comment]
报错问题已修复，另一个问题没执行输出3，是因为输出3的前置节点没有全部执行完成（else if分支--输出2没有执行），所以输出3不会执行

**Comment by baixin513** [comment]
v1.7.1已发布，另一个问题是正常情况， 执行当前节点的前提是前置所有连线节点都执行完成。
