### ISSUE TITLE
[FEATURE]问题编辑并重新生成

### ISSUE THREAD

**Issue by Virtual1257** [1Panel-dev/MaxKB#1552]
### MaxKB 版本

v1.7

### 请描述您的需求或者改进建议

希望能够支持对当前问题进行编辑，然后再次生成。并支持不同问题和答案之间的切换。这在实际使用过程中非常好用，特别是在问题描述不准确或者回复不好，希望以相同的上下文，重新提问的情况下。
![image](https://github.com/user-attachments/assets/70cbc506-624a-4aca-985c-9e4093f1675c)

**Comment by baixin513** [comment]
当前对话页面支持换个答案，如果答案不准确，可以换一批引用知识库分段进行回答。没有问题重新编辑，你可以复制一下问题编辑后在提问。
<img width="951" alt="image" src="https://github.com/user-attachments/assets/70004d92-007b-4519-acab-023a2dab874a">

**Comment by Virtual1257** [comment]
> 当前对话页面支持换个答案，如果答案不准确，可以换一批引用知识库分段进行回答。没有问题重新编辑，你可以复制一下问题编辑后在提问。 <img alt="image" width="951" src="https://private-user-images.githubusercontent.com/52996290/383453634-70004d92-007b-4519-acab-023a2dab874a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTk4MDUsIm5iZiI6MTczMDk1OTUwNSwicGF0aCI6Ii81Mjk5NjI5MC8zODM0NTM2MzQtNzAwMDRkOTItMDA3Yi00NTE5LWFjYWItMDIzYTJkYWI4NzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA2MDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZDhkZTY5MzZiMjBkMmViMGM1MTRkMTVkNzI4NTA2NzVjNGFjZWE1YWViOGNhNzhiNDg1Mjg3NzQwYTQ1YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BK_Lz8ZxExc0uQR3-Mfk1HQ05DJ5JcngO41M--ohqjU">

复制问题编辑后再提问会导致提问的上下文变了，做不到以相同的上下文再提问
