### ISSUE TITLE
[BUG]有些数学物理文献中的公式写法不支持

### ISSUE THREAD

**Issue by linfengjjj** [1Panel-dev/MaxKB#1556]
### MaxKB 版本

v3.4.0

### 问题描述

有些数学物理文献中的公式写法不支持，例如一些序号和公式引用

### 重现步骤

1、创建知识库片段，使用公式语法填写公式，有的内容不能按预期显示
![image](https://github.com/user-attachments/assets/fbefe9d7-6253-4544-9c41-ccae6487576d)
![image](https://github.com/user-attachments/assets/5e61e987-e1d9-4029-8477-425858e9e308)
![image](https://github.com/user-attachments/assets/875cf1fb-911f-4ba2-a455-86da7a3e3284)
下面是预期展示：
![image](https://github.com/user-attachments/assets/5c38c722-0031-48f3-8644-c01748dd0a2b)
2、还要一些公式写法也识别不了
<img width="569" alt="9e99ea34b7e12ed3729e12184fa26d3" src="https://github.com/user-attachments/assets/a9da7dd3-812a-479b-928e-2577a6999b19">
3、这是部分公式内容
$$
\begin{aligned}
\boldsymbol{P}_{[k]}& =P_{[k]}^{-}-P_{[k]}^{-}H_{m}^{\mathrm{T}}K_{[k]}^{\mathrm{T}}-K_{[k]}H_{m}P_{[k]}^{-}+K_{[k]}H_{m}P_{[k]}^{-}H^{\mathrm{T}}K_{[k]}^{\mathrm{T}}+K_{[k]}R_{\mathrm{c}}K_{[k]}^{\mathrm{T}} \\
&=P_{[k]}^{-}-P_{[k]}^{-}H_{m}^{\mathrm{T}}K_{[k]}^{\mathrm{T}}-K_{[k]}H_{m}P_{[k]}^{-}+\frac{P_{[k]}^{-}H_{m}^{\mathrm{T}}}{H_{m}P_{[k]}^{-}H_{m}^{\mathrm{T}}+R_{c}}(H_{m}P_{[k]}^{-}H_{m}^{\mathrm{T}}+R_{c})K_{[k]}^{\mathrm{T}} \\
&=P_{[k]}^{-}-P_{[k]}^{-}H_{m}^{\mathrm{T}}K_{[k]}^{\mathrm{T}}-K_{[k]}H_{m}P_{[k]}^{-}+P_{[k]}^{-}H_{m}^{\mathrm{T}}K_{[k]}^{\mathrm{T}} \\
&=P_{[k]}^{-}-K_{[k]}H_{\mathrm{m}}P_{[k]}^{-} \\
&=(I-K_{[k]}H_{\mathrm{m}})P_{[k]}^{-}& 
\end{aligned}
\label{eq42}
$$

 代入式 写法：  \refeq{eq38}

### 期待的正确结果

希望可以支持更多的数学物理公式写法

**Comment by baixin513** [comment]
感谢反馈，我们先排查一下

**Comment by zyyfit** [comment]
您好，目前暂时无法支持这类复杂的公式
