### ISSUE TITLE
[BUG]【系统管理-团队成员-权限设置】筛选后，点击全选，选的资源不是筛选后的结果

### ISSUE THREAD

**Issue by hao65103940** [1Panel-dev/MaxKB#1558]
### MaxKB 版本

v1.7

### 问题描述

【系统管理-团队成员-权限设置】当筛选出一些知识库或应用后，在“管理”和“查看”那里选择全选，然后保存。结果发现未筛选到的知识库也被选上了。正确的做法应该是：如果看到的是所有的知识库或应用，点击全选则选择所有；如果是看到的是筛选后的一些知识库或应用，点击全选则只选择这些筛选后的知识库或应用。

![image](https://github.com/user-attachments/assets/259d9aa6-f398-45a6-acf3-594802debe8d)
![image](https://github.com/user-attachments/assets/0a075c0d-c14e-43d6-95b8-2b3f8ec2baf6)

### 重现步骤

同上

**Comment by baixin513** [comment]
感谢反馈，后续版本修复。

**Comment by baixin513** [comment]
v1.7.1已发布
