### ISSUE TITLE
[BUG]知识库支持上传本地图片，同#69

### ISSUE THREAD

**Issue by macaty** [1Panel-dev/MaxKB#156]
### MaxKB 版本

1.0.2

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/16797633/1803d03b-b2e0-422c-a5b2-acaa65cc2dc9)
今天尝试了，做KB创建的时候，上传图片遇到一闪而退，无法上传图片

### 重现步骤

安装最新版KB，创建知识库，导入图片不了

**Comment by baixin513** [comment]
感谢反馈，当前还不支持本地图片上传，该需求已在 #69 中提到。
当前只有在线图片可以通过 markdown 样式插入。
