### ISSUE TITLE
[BUG]聊天窗口展示表格中图片时出现错位,知识库中展示正常

### ISSUE THREAD

**Issue by shenkaibo** [1Panel-dev/MaxKB#1561]
### 联系方式

shenkaibo

### MaxKB 版本

1.7.0

### 问题描述

聊天窗口展示表格中图片时出现错位,知识库中展示正常

### 重现步骤

1.知识库中表格中插入图片。
分段内容如下：
| **xx1展位价格如下：** | **xx2展位价格如下：** |
| - | - |
| ![xx1展位价格](http://xx1.jpg) | ![xx2展位价格](http://xx2.jpg) |

![image](https://github.com/user-attachments/assets/3ef5317e-0410-4c7f-8e26-1e595fa41477)

聊天窗口输出如下（采用直接回答）：
![image](https://github.com/user-attachments/assets/485d8cea-3c94-45b1-9f09-1c2f42ced18a)
出现了错位。

### 期待的正确结果

聊天窗口和知识库中格式展示一致。

**Comment by baixin513** [comment]
是设置的直接回复么？

**Comment by baixin513** [comment]
v1.7.1已发布
