### ISSUE TITLE
[BUG] 在函数库当中设置函数参数引用时，非必填。在工作流当中使用函数，不传值，执行报错。

### ISSUE THREAD

**Issue by hao65103940** [1Panel-dev/MaxKB#1564]
### MaxKB 版本

v1.7

### 问题描述

![image](https://github.com/user-attachments/assets/7c078da2-fa28-4531-b4ff-9874ec2adf20)
![image](https://github.com/user-attachments/assets/fa4a9868-703a-4edd-8b14-572171349e4a)
![image](https://github.com/user-attachments/assets/4d747997-c56a-4dfc-b8fd-9372924056ae)

### 重现步骤

同上

**Comment by baixin513** [comment]
v1.7.1已发布
