### ISSUE TITLE
[FEATURE]根据用户提问或之前的对话上下文，生成相应的问题预测

### ISSUE THREAD

**Issue by hello1534** [1Panel-dev/MaxKB#1567]
### MaxKB 版本

1.7.0

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/7ef7d26b-3958-4a3e-94f6-c03c5820b949)
希望能有类似kimi这种生成预测问题的功能，且可以在应用中配置开关来控制是否启用该功能

**Comment by baixin513** [comment]
感谢反馈，该功能可以使用工作流实现，可以看下这个帖子：https://bbs.fit2cloud.com/t/topic/7753

**Comment by hello1534** [comment]
> 感谢反馈，该功能可以使用工作流实现，可以看下这个帖子：https://bbs.fit2cloud.com/t/topic/7753

使用工作流生成的<quick_question></quick_question>标签中的内容，会对后续对话产生影响这个有好的解决方案吗
