### ISSUE TITLE
[FEATURE] 回答的链接中，期望可以实现图片链接。

### ISSUE THREAD

**Issue by ElvisBluetooth** [1Panel-dev/MaxKB#1568]
### MaxKB 版本

1.7.0

### 请描述您的需求或者改进建议

目前回答的链接，只能实现文字链接，点击文字进行跳转到页面；
期望可以实现图片链接，可以点击图片跳转到页面。

**Comment by shaohuzhang1** [comment]
使用html_rander 可以实现你的想法

**Comment by liqiang-fit2cloud** [comment]
[https://www.baidu.com/s?wd=markdown图片超链接](https://www.baidu.com/s?wd=markdown%E5%9B%BE%E7%89%87%E8%B6%85%E9%93%BE%E6%8E%A5)

**Comment by ElvisBluetooth** [comment]
> [https://www.baidu.com/s?wd=markdown图片超链接](https://www.baidu.com/s?wd=markdown%E5%9B%BE%E7%89%87%E8%B6%85%E9%93%BE%E6%8E%A5)



> 使用html_rander 可以实现你的想法

这两个方法试了一下能实现，但是聊天框始终把这当成图片，会显示放大图标。并且点击后，虽然有跳转，但是把图标放大了。
