### ISSUE TITLE
[FEATURE]Excel类型文档导入自动切分策略

### ISSUE THREAD

**Issue by 2023fan** [1Panel-dev/MaxKB#1573]
### MaxKB 版本

1.7

### 请描述您的需求或者改进建议

现状：
导入Excel文档字段信息
![image](https://github.com/user-attachments/assets/7e22016a-bcca-403b-b153-bed1517024f9)
切分后的分段：所有字段信息都是在同一行
<img width="413" alt="839adaf6759ba86d7189116a9de3bf6" src="https://github.com/user-attachments/assets/8adaf0a2-db9c-402e-9a13-25523ef4fc4d">
全部在同一行，分段检索时，命中率较低。建议改成一下格式：每个字段单独一行，这样可以提升检索分段的名字率
<img width="207" alt="07bb428c05c50b503a8a13a56392554" src="https://github.com/user-attachments/assets/3968382b-add8-4aba-9093-9cb7b99ce030">

**Comment by baixin513** [comment]
感谢反馈，这里分行展示也只是能方便查看，命中率不会变的。
