### ISSUE TITLE
[FEATURE]分段切分处理

### ISSUE THREAD

**Issue by 2023fan** [1Panel-dev/MaxKB#1574]
### MaxKB 版本

1.7

### 请描述您的需求或者改进建议

现状：导入markdown文档，格式如下
![image](https://github.com/user-attachments/assets/beac8eb5-268f-44b8-ac8a-e380cfc95e4f)
根据标题切分，会生成很多无效分段，干扰检索
![image](https://github.com/user-attachments/assets/89ac86c6-b538-49f2-8784-02fc2831d4d1)
![image](https://github.com/user-attachments/assets/25b271e5-0292-4873-a2fa-706b3aaee5eb)

需求1：希望可以自动把这些无限分断删除了，或者添加一个分段最小token的参数，用户可以自定义

需求2：
![image](https://github.com/user-attachments/assets/1fca01b3-e2a4-4cf3-a8c5-a11a10bb0290)
标题一般是概括性语言，复制一份到分段里面，这样可以提升检索命中率

**Comment by baixin513** [comment]
感谢反馈，不需要的分段可以手动删除一下。 
标题不会自动放置分段内容，有些直接回答的分段分段内容就是答案，放入标题不合适。
暂无计划。
