### ISSUE TITLE
[BUG]web站点同步https://www.scsfri.ac.cn/info/1392/26397.htm 时报错

### ISSUE THREAD

**Issue by 2023fan** [1Panel-dev/MaxKB#1577]
### MaxKB 版本

1.7

### 问题描述

web站点，同步：https://www.scsfri.ac.cn/info/1392/26397.htm  时报错
<img width="392" alt="a88fdac0ecf3a10d749f88393465564" src="https://github.com/user-attachments/assets/98eda763-45b5-4b3d-bf93-e5597c9f9a6c">

报错原因：网页里面有特殊字符，导致我们的解析出问题了

### 重现步骤

web站点，同步：https://www.scsfri.ac.cn/info/1392/26397.htm

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by baixin513** [comment]
v1.8.0 已发布！
