### ISSUE TITLE
[BUG] 第三方嵌入 首次进入，开场白的问题加载特别慢。

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1578]
### 联系方式

xuwei5188916@yeah.net

### MaxKB 版本

v1.7.0

### 问题描述

第三方嵌入 首次进入，开场白的问题加载特别慢。或者清除缓存，进入第三方嵌入页面，右下角的弹窗开场白加载特别慢。
![图片](https://github.com/user-attachments/assets/198d125e-cc6d-4961-9e4a-68fcad564946)

### 重现步骤

第三方嵌入 首次进入，开场白的问题加载特别慢。或者清除缓存，进入第三方嵌入页面，右下角的弹窗开场白加载特别慢

### 期待的正确结果

加载正常。

**Comment by baixin513** [comment]
感谢反馈，应该是您的网络问题，您可以检测一下网络。

**Comment by xuwei999-NT** [comment]
是服务器的网络，还是本机的网络呢？我找了maxkb交付团队测试了下，说首次慢。

**Comment by lvshuaigg** [comment]
一样的问题，第一次进入系统会比较慢，清理了缓存也依然很慢，后续再进入正常，应该缓存了一些文件在本地。包括修改了docker-compose.yml文件以及docker-compose-pgsql.yml中的interval: 10s，timeout: 10s，retries: 120参数，第一次进入依然很慢。而且到第二天再次进入也会出现同样的问题。

**Comment by lvshuaigg** [comment]
第一次进入系统或者清理了缓存再进入，大概有15秒的时间，就是生成应用的链接进入。
