### ISSUE TITLE
[BUG]复杂编排获取下一个执行节点的逻辑是不是效率比较低

### ISSUE THREAD

**Issue by hello1534** [1Panel-dev/MaxKB#1579]
### MaxKB 版本

1.7.0

### 问题描述

![image](https://github.com/user-attachments/assets/8ac702a3-d608-4a71-97d6-b4ddc94c4e63)
看代码中目前执行完当前节点，获取下个节点的逻辑，是需要去遍历所有的边，然后判断source_node_id是否是本节点，每次执行完一个节点后都需要去遍历一次，当应用比较复杂时感觉性能会较差。
为什么不在节点上加两个list字段，分别存储节点连接的左边和右边的集合，这样不是性能会更好吗。还是有其他点需要考虑，所以只能够使用遍历这种方法呢。

### 重现步骤

无

**Comment by shaohuzhang1** [comment]
好的，想贡献此增强功能吗？
