### ISSUE TITLE
[BUG]高级编排中知识库检索基础组件收缩后无法发布问题

### ISSUE THREAD

**Issue by xindaodan** [1Panel-dev/MaxKB#1582]
### 联系方式

zscaoxin@163.com

### MaxKB 版本

1.7.1

### 问题描述

收缩图片
![微信截图_20241110211223](https://github.com/user-attachments/assets/ede81fdf-7b64-4a6a-9d0c-c7ff23c3cbdf)
高级编排中知识库检索基础组件收缩这样无法发布可以保存，需要展开后才能发布
![微信图片_20241110210949](https://github.com/user-attachments/assets/681583f8-4b70-4e6e-bd57-635f2324138c)

### 重现步骤

高级编排中知识库检索基础组件收缩这样无法发布可以保存，需要展开后才能发布

**Comment by baixin513** [comment]
感谢反馈，确认为bug

**Comment by baixin513** [comment]
v1.7.2已发布
