### ISSUE TITLE
[FEATURE]应用对话日志检索功能支持更多字段搜索

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1588]
### MaxKB 版本

1.7.1

### 请描述您的需求或者改进建议

用对话日志检索功能支持更多字段搜索，以方便查找对话记录，包括以下字段
1、用户提问
2、AI回答
3、传入参数值

**Comment by liqiang-fit2cloud** [comment]
目前没有计划。
