### ISSUE TITLE
[BUG]使用模糊查询应用，未能将所有符合条件的应用查出来

### ISSUE THREAD

**Issue by Larson13** [1Panel-dev/MaxKB#1590]
### MaxKB 版本

v1.7.1

### 问题描述

MK应用超过20个，使用模糊查询应用时，后端端口应用的数据是正确的，页面上未将符合条件的应用显示出来

### 重现步骤

1、在应用中创建25个应用
2、使用模糊查询应用
3、观察是否将应用全部查出来

### 期待的正确结果

使用模糊查询应用时，可以将所有符合条件的应用显示出来

### 附加信息

1、符合条件的应用有22个
![image](https://github.com/user-attachments/assets/ef87b841-e2c1-4d2e-8ec4-41e4f9e3b633)
![image](https://github.com/user-attachments/assets/9d7b2ba9-dcd0-4279-8b01-aac31611f15a)
![image](https://github.com/user-attachments/assets/d391d390-880d-40dd-a63c-f9a9fd3cc4e1)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by baixin513** [comment]
v1.7.2已发布
