### ISSUE TITLE
[BUG]多出多进的编排方式会导致系统报错，无法发布和调试流程

### ISSUE THREAD

**Issue by DDSXIAO** [1Panel-dev/MaxKB#1591]
### 联系方式

MaxKB交流群4：葡萄DDS

### MaxKB 版本

1.7.1 专业版

### 问题描述

尝试出来的BUG，高级编排时，使用一个指定回复组件，后面分支流程接多个知识库检索，然后汇总到一个多路找回，再接AI。
这样编排的流程，能保存，但是发布时会报错。我把流程图和报错信息贴上来。
![1](https://github.com/user-attachments/assets/e86408c2-fe2d-4de4-894a-85b2170f3787)
![2](https://github.com/user-attachments/assets/53db67b8-2901-4a53-b226-7bd44b8d35c5)

### 重现步骤

高级编排时，使用一个指定回复组件，后面分支流程接多个知识库检索，然后汇总到一个多路找回，再接AI。

**Comment by baixin513** [comment]
感谢反馈， 该问题时由于知识库节点收起后无法校验通过，导致无法发布，展开知识库检索节点即可正常校验和发布。
该问题同issue #1582 ，后续版本修复，请关注issue #1582 的更新。
