### ISSUE TITLE
[BUG]【应用显示设置】上传图片建议64*64，但引用显示处显示的图片不是该尺寸，限制了高度30px，最终尺寸为 53.33*30

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1592]
### MaxKB 版本

v1.7.1

### 问题描述

【应用显示设置】上传图片建议64*64，但引用显示处显示的图片不是该尺寸，限制了高度30px，最终尺寸为 53.33*30

### 重现步骤

【应用显示设置】上传图片建议64*64，但引用显示处显示的图片不是该尺寸，限制了高度30px，最终尺寸为 53.33*30
![42946383e58c4972c869c58a7ab6185](https://github.com/user-attachments/assets/a21d3e9e-b89c-4c1e-90a2-e2f45391de5a)

![71d514d96c3daee4f8d3959c8592163](https://github.com/user-attachments/assets/0c45d14b-7c9c-42f7-aeb9-1cc67cfcf9af)

**Comment by baixin513** [comment]
v1.7.2已发布
