### ISSUE TITLE
[BUG]【高级编排】节点收缩就不能正常调试和发布，出现错误TypeError: Cannot read properties of null (reading 'validate')。

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1594]
### MaxKB 版本

v1.7.1

### 问题描述

【高级编排】节点收缩就不能正常调试和发布，出现错误TypeError: Cannot read properties of null (reading 'validate')。
![image](https://github.com/user-attachments/assets/d68d405f-a9a9-46b5-a05c-e8ecc8e04867)

### 重现步骤

【高级编排】节点收缩就不能正常调试和发布，出现错误TypeError: Cannot read properties of null (reading 'validate')。
![image](https://github.com/user-attachments/assets/d68d405f-a9a9-46b5-a05c-e8ecc8e04867)

节点展开是好使的。
![image](https://github.com/user-attachments/assets/5ca884a7-345b-4a3d-a965-9f436abb3132)

**Comment by baixin513** [comment]
同issue #1582

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

相关问题 https://github.com/1Panel-dev/MaxKB/issues/1582
