### ISSUE TITLE
[BUG]简单配置中对过长名称知识库进行关联时有概率导致无法显示知识库全部名称

### ISSUE THREAD

**Issue by B14Lettingo** [1Panel-dev/MaxKB#1596]
### 联系方式

1812951966@qq.com

### MaxKB 版本

 v1.7.1 (build at 2024-11-07T19:03, commit: 61f1646c)

### 问题描述

当知识库名称过长时，若在简单配置中对其进行关联是，多次刷新后会导致无法显示全部名称

### 重现步骤

简单配置中关联一个过长名称的知识库并对其进行保存刷新，极大概率出现无法显示全部名称

### 附加信息

https://github.com/user-attachments/assets/9885a2a0-0bd5-4d65-9eb3-740ab2822c6a

**Comment by baixin513** [comment]
感谢反馈，后续版本修复

**Comment by baixin513** [comment]
v1.7.2已发布
