### ISSUE TITLE
[FEATURE]高级编排增加一键展开收缩所有组件的功能

### ISSUE THREAD

**Issue by DDSXIAO** [1Panel-dev/MaxKB#1597]
### MaxKB 版本

1.7.1 专业版

### 请描述您的需求或者改进建议

企业级应用一般都会用到高级编排，有一些复杂的场景会需要用到多个组件，能否增加一键展开收缩所有组件的功能类，很需要这个。

**Comment by baixin513** [comment]
感谢反馈，后续版本中迭代

**Comment by baixin513** [comment]
v1.8.0 已发布！
