### ISSUE TITLE
[FEATURE]知识库支持同步confluence空间

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1599]
### MaxKB 版本

1.8

### 请描述您的需求或者改进建议

团队使用conflunece管理知识，已经沉淀有大量的知识。现在通过网站同步的方式只能读取无身份验证的内容，而且读取的内容效果很差。

### 请描述你建议的实现方案

建议支持confluence知识库的空间同步

**Comment by liqiang-fit2cloud** [comment]
同https://github.com/1Panel-dev/MaxKB/issues/1601

**Comment by honyee90** [comment]
同样需要哈~ 建议支持一下

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Also needed ~ I suggest supporting it

**Comment by liqiang-fit2cloud** [comment]
> 同样需要哈~ 建议支持一下

没有计划。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Also needed ~ I suggest supporting it

No plan.
