### ISSUE TITLE
[FEATURE] 文档中表明运行环境硬件需求

### ISSUE THREAD

**Issue by ShinChven** [1Panel-dev/MaxKB#16]
### MaxKB 版本

latest

### 请描述您的需求或者改进建议

第一次尝试部署 maxkb，我用的是一台4G内存的云服务器，发起启动容器以后服务器不响应，发现内存占用率在猛增。

### 请描述你建议的实现方案

希望开发者能在文档中添加一下运行环境的硬件需求信息。

**Comment by baixin513** [comment]
您好，我们测试机器都是 2C4GB 的配置，都能正常运行。
您可具体查看一下机器的可用内存，是否有其他程序占用。

用户手册-安装部署中有写明环境配置要求。
https://github.com/1Panel-dev/MaxKB/wiki/1-%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2

<img width="956" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/db28bc25-cdac-4140-8caf-a8a7cffe80d0">

**Comment by ShinChven** [comment]
感谢
