### ISSUE TITLE
[FEATURE] 【应用编排】对接操作类API接口

### ISSUE THREAD

**Issue by macaty** [1Panel-dev/MaxKB#160]
### MaxKB 版本

1.0.2

### 请描述您的需求或者改进建议

请问可以对接操作类接口吗？我们会开发相关接口API，比如重置密码接口，使用场景：
麻烦帮忙重置我的电脑密码，这个AI直接获取当前用户ID，确认并调用重置接口返回执行结果。

**Comment by baixin513** [comment]
感谢反馈，当前不支持的，这得需要编排每个步骤节点的交互逻辑。

**Comment by baixin513** [comment]
该功能可以使用工作流编排+函数方式实现。
