### ISSUE TITLE
[FEATURE]知识库同步支持微盘/微文档、语雀、FTP、SMB等知识知识库和文档同步

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1601]
### MaxKB 版本

1.8

### 请描述您的需求或者改进建议

知识是企业落地AI很关键的点，企业已经沉淀的知识需要快速导入Maxkb

### 请描述你建议的实现方案

知识库同步支持微盘/微文档、语雀等知识知识库同步

**Comment by liqiang-fit2cloud** [comment]
大部分这种系统都没有api，所以没法同步。即使个别有api也不是统一格式的api，不可能一一对接，所以社区版支持导出的文件再上传到MaxKB，或者以web方式爬取。专业版有上传文件api，你可以自己写段程序批量导出导入。
