### ISSUE TITLE
[FEATURE]提问等待反馈的支持个性化

### ISSUE THREAD

**Issue by DDSXIAO** [1Panel-dev/MaxKB#1603]
### MaxKB 版本

1.7.1 专业版

### 请描述您的需求或者改进建议

我也是收到其他人的需求。
针对复杂编排的流程，提出问题等待的时间比较长，现在MaxKB的方式是“回答中……”
但我们公司的人讨论后希望修改成“思考中……”，这样从用户心理上能够更接受一些。
希望后续版本能够迭代这个内容可以自定义。
不过目前能否告知一下，需要修改哪个文件，能够修改一下这个内容，我想尝试再我当前使用的版本里自行修改一下。

### 请描述你建议的实现方案

希望后续版本能够迭代这个内容可以自定义。

**Comment by liqiang-fit2cloud** [comment]
目前没有计划，你可以在源码中搜一下。
