### ISSUE TITLE
[FEATURE]将MaxKB部署在其他应用的Nginx下

### ISSUE THREAD

**Issue by DDSXIAO** [1Panel-dev/MaxKB#1604]
### MaxKB 版本

1.7.1 专业版

### 请描述您的需求或者改进建议

我在尝试将MaxKB部署在Nginx中启用HTTPS SSL，但由于跨站，集成的网站不支持。
所以引出这样的需求，尝试将MaxKB部署在我的业务系统Nginx下时发现，MaxKB不支持调整网站路径，只能部署在Nginx的根目录下，这样会造成与其他同源网站冲突。有没有更好的方案解决这样的问题呢？
或者后续版本能否改一下代码，MaxKB现在很多路径都是写死了，改成相对路径是否可行。
这样就可以在Nginx中定义MaxKB为子目录，既满足同源访问的需求，又能避免与其他业务系统或网站冲突。

### 请描述你建议的实现方案

举个例子：
将MaxKB部署在https://www.xxxx.com/aaaaa/目录下，这样MaxKB的登录页路径就可以变更为https://www.xxxx.com/aaaaa/ui/login

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，目前技术上不支持子目录。
