### ISSUE TITLE
[BUG]【API】maxkb地址是https,但是swagger里总是生成http，导致在swagger上无法调试通。

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1610]
### MaxKB 版本

v1.7.1

### 问题描述

【API】maxkb地址是https,但是swagger里总是生成http，导致在swagger上无法调试通。

### 重现步骤

【API】maxkb地址是https,但是swagger里总是生成http，导致在swagger上无法调试通。
![https](https://github.com/user-attachments/assets/5f674ef7-a76c-48eb-a366-6cf063175080)

**Comment by liqiang-fit2cloud** [comment]
再试试你截图里的地址。

**Comment by 2lipan** [comment]
现在好使了，感谢大佬。

**Comment by liqiang-fit2cloud** [comment]
这个需要修改代码 https://github.com/1Panel-dev/MaxKB/commit/6f84239e8b8386fe2d2dd2c8e12b8f7ed0ac94e1 下个版本发布。
同时nginx里还要把协议传到后端MaxKB，加配置proxy_set_header X-Forwarded-Proto $scheme;
