### ISSUE TITLE
[BUG]对于Xinference上部署的SenseVoiceSmall语音识别模型报错

### ISSUE THREAD

**Issue by ElvisBluetooth** [1Panel-dev/MaxKB#1615]
### MaxKB 版本

1.7.1

### 问题描述

添加Xinference上部署的SenseVoiceSmall语音识别模型报错，用API的方式都能够调用SenseVoiceSmall.
添加模型时报如下的错误
![d625ef5336af5b37333b07a82062535](https://github.com/user-attachments/assets/d166c6a4-140d-4e23-82a0-fe86172c810f)
![bc031c2dc54acafe4966d392c670620](https://github.com/user-attachments/assets/53964748-0349-4d35-9f84-19eb81904495)

### 重现步骤

添加模型时出现

**Comment by liqiang-fit2cloud** [comment]
@ElvisBluetooth 你确定你deepin.com的地址能正常访问不报404么？

**Comment by ElvisBluetooth** [comment]
> 您好，没有复现这个问题，请问您是安装包部署的吗？ ![image](https://private-user-images.githubusercontent.com/73461316/387261659-f7a75094-92e2-4959-ad41-31f77411f426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTgxNDcsIm5iZiI6MTczMjUxNzg0NywicGF0aCI6Ii83MzQ2MTMxNi8zODcyNjE2NTktZjdhNzUwOTQtOTJlMi00OTU5LWFkNDEtMzFmNzc0MTFmNDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA2NTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTliYzU3ZGNiNjZjN2ExNmQwNjNkMTVlZTNhYWI4NTUwM2Q0NWVkMDU1NDVhODhiYzExNmMwMjQyYjBiZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.beBV7A_tpF1oefc6FGJ1sBTn-zsN6w6FIWDEKWlYZjk)
后来我大概知道了问题了，需要在基础路径上，增加 /v1的路由地址，就能够访问了。

**Comment by ElvisBluetooth** [comment]
> 您好，没有复现这个问题，请问您是安装包部署的吗？ ![image](https://private-user-images.githubusercontent.com/73461316/387261659-f7a75094-92e2-4959-ad41-31f77411f426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTgzNjgsIm5iZiI6MTczMjUxODA2OCwicGF0aCI6Ii83MzQ2MTMxNi8zODcyNjE2NTktZjdhNzUwOTQtOTJlMi00OTU5LWFkNDEtMzFmNzc0MTFmNDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA3MDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNTZiZmU4ODJjNDE1OTdjZDVkNWQ4MThlMjIzMGQxZmIxZDU2NjE2NGYyYzA1NTQ1MzQ0NDlkNDA1MWM1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Bl_PHWgaiB7tsa-ZfK5oCayzUl0wnmXBAzp_6BgQRnk)

后来我大概知道了问题了，需要在基础路径上，增加 /v1的路由地址，就能够访问了。

**Comment by ElvisBluetooth** [comment]
> @ElvisBluetooth 你确定你deepin.com的地址能正常访问不报404么？

是可以访问的，这个是云服务器。不过后面我关了就不能访问了。应该是没有加 /v1 的路由地址导致的。

**Comment by zyyfit** [comment]
好的
