### ISSUE TITLE
[FEATURE]建议函数库可以使用大模型来编写代码

### ISSUE THREAD

**Issue by wxfvf** [1Panel-dev/MaxKB#1627]
### MaxKB 版本

1.7.1

### 请描述您的需求或者改进建议

如题，建议函数库可以直接使用已绑定ai来编写代码，毕竟已经绑定了，完全可以调用ai生成所需的函数库，不然还需要在另外的地方生成再复制过来，比较麻烦。
也就是，ai不止用在流程里面，也可以用在maxkb的操作过程中，作为使用maxkb的使用辅助。

**Comment by liqiang-fit2cloud** [comment]
没有计划支持。
