### ISSUE TITLE
[BUG] 添加 OpenAI 的时候报错

### ISSUE THREAD

**Issue by siyehua** [1Panel-dev/MaxKB#163]
### MaxKB 版本

v1.0.2 (build at 2024-04-17T16:02, commit: 86681d9b)

### 问题描述

添加 openAI 的时候报错

### 重现步骤

我的域名跟 key 都是自定义的，但是肯定是通的，是国内的代理商代理的，而且我用命令行，网页 chatnext 都能用。但是添加的时候报错，404，是什么意思？
<img width="801" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/9376247/5767df46-3f37-4f18-824a-fcf4c2eeb31c">

**Comment by baixin513** [comment]
API域名后面要加上 /v1

**Comment by baixin513** [comment]
OpenAI的改了些问题，建议先更新到最新版本。

**Comment by siyehua** [comment]
已经解决，感谢
