### ISSUE TITLE
[FEATURE]能否在对话日志中显示出提问人ID

### ISSUE THREAD

**Issue by dlluckboy** [1Panel-dev/MaxKB#1630]
### MaxKB 版本

1.7.1

### 请描述您的需求或者改进建议

对话日志中无法看到是哪个用户提问的，能加上这个功能。企业使用的时候，需要此功能来分析员工专注于提问哪些问题，有这个数据，可以分析出员工在哪些方面欠缺，以及专注于哪些问题，通过分析可以针对性的补充对应的本地知识库文档。另外可以通过概览中显示图标，或者加上个功能，可以通过模型进行分析，就像新功能中可以通过模型自动生成关联问题。

**Comment by liqiang-fit2cloud** [comment]
系统里不记录外部用户身份。
