### ISSUE TITLE
[FEATURE]知识库的excel和qa模板，希望可以上传成去掉标识后的模板

### ISSUE THREAD

**Issue by shaohuayangfit2** [1Panel-dev/MaxKB#1637]
### MaxKB 版本

1.7.1

### 请描述您的需求或者改进建议

知识库的excel和qa模板，希望可以上传成去掉标识后的模板
1，企业客户替换maxkb的logo后，开放给用户登录平台使用，但是还可以看到模板里的MaxKB字样；
2，希望增加可以页面上传模板的入口，管理员可以上传带有自己标识的模板；
3，目前可以通过修改docker-compose文件解决，但每次修改模板都需要重启容器；希望在页面上可以增加入口；

### 请描述你建议的实现方案

![1](https://github.com/user-attachments/assets/9e0e16fb-6478-4097-aede-47115540f011)

**Comment by liqiang-fit2cloud** [comment]
模版中去掉MaxKB字符即可，不要开放上传模版入口。 @baixin513
