### ISSUE TITLE
[FEATURE]知识库管理

### ISSUE THREAD

**Issue by 2023fan** [1Panel-dev/MaxKB#1638]
### MaxKB 版本

1.7

### 请描述您的需求或者改进建议

知识库管理界面，建议增加目录，方便知识库归类存放，可参考DataEase的结构
![image](https://github.com/user-attachments/assets/d1b10dd7-a6d8-4c32-89d6-0d97ed846a98)
![image](https://github.com/user-attachments/assets/da860388-b4e4-431d-a02c-e7219ac2182d)

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，没有计划。
