### ISSUE TITLE
[FEATURE]应用-高级编排-支持工作流节点收缩

### ISSUE THREAD

**Issue by 2023fan** [1Panel-dev/MaxKB#1639]
### MaxKB 版本

1.7

### 请描述您的需求或者改进建议

希望应用-高级编排-支持工作流节点收缩，因为一旦场景复杂一点，分支就很多，看得人眼花缭乱
![image](https://github.com/user-attachments/assets/215b2d0b-5113-47b1-a549-5c8398f73698)
建议参考X-mind，可以收缩分支
![image](https://github.com/user-attachments/assets/e11b4fd1-9308-49f6-83bf-0eefdf083a85)

**Comment by liqiang-fit2cloud** [comment]
[v1.7.1已支持。](https://github.com/1Panel-dev/MaxKB/releases/tag/v1.7.1)

**Comment by baixin513** [comment]
工作流是流程图，并且有多出多进的逻辑，不会向思维导图那样。
后续1.8版本支持 一键美化布局，一键收起/展开所有节点。
