### ISSUE TITLE
[FEATURE]本地向量模型支持GPU加速

### ISSUE THREAD

**Issue by armored-glitch** [1Panel-dev/MaxKB#1641]
### MaxKB 版本

 v1.7.1 

### 请描述您的需求或者改进建议

     本地向量模型，向量化的过程是cpu进行处理的，测试下来速度较慢。如果需要GPU则需要使用Xorbits Inference部署，过于繁琐，不知道后续本地向量模型支持GPU加速嘛

**Comment by liqiang-fit2cloud** [comment]
没有计划，用GPU的话请使用外部向量模型。
