### ISSUE TITLE
[FEATURE]高级编排增加提问组件

### ISSUE THREAD

**Issue by zhangdong12306** [1Panel-dev/MaxKB#1643]
### MaxKB 版本

1.5.0

### 请描述您的需求或者改进建议

现在AI很多聊天模式都引入了在回答问题后列举出一些相关的问题点，虽然当前也可以通过问题优化器来返回问题，但是在前端UI的展示页面中是无法直接点击访问的。
希望可以引入一个提问组件，调用后可以把该提问组件的问题反射到UI上且可以直接点击访问，有利于引导用户下一步的提问，提升用户体验，感官上提升软件的智能化

### 附加信息

参考如下方式：
![提问建议](https://github.com/user-attachments/assets/72073bec-8a18-49fc-ab78-7104b4ce3118)

**Comment by liqiang-fit2cloud** [comment]
目前没有计划。
