### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dragon-feng** [1Panel-dev/MaxKB#1648]
### MaxKB 版本

release-v1.7

### 问题描述

开发环境不支持windows环境部署

### 重现步骤

按官网文档部署，windows系统无法启动

### 期待的正确结果

支持windows系统调试运行

**Comment by liqiang-fit2cloud** [comment]
一键安装命令支持windows，启动失败的话看看容器日志，有问题到社区群里交流。

**Comment by dragon-feng** [comment]
是对二次开发用的，不是针对直接安装

**Comment by liqiang-fit2cloud** [comment]
支持windows开发，我们自己也用windows，社区里好多用户都是windows开发，你自己研究一下。

**Comment by dragon-feng** [comment]
那我怎么把改完的提交到分支上，让兼容windows平台

**Comment by liqiang-fit2cloud** [comment]
你不用提交，windows没问题，我们都正常，你自己解决就行了。
