### ISSUE TITLE
[BUG]“显示知识来源”变成了“执行详情”

### ISSUE THREAD

**Issue by jstbw** [1Panel-dev/MaxKB#1649]
### 联系方式

976094510@qq.com

### MaxKB 版本

1.7.1

### 问题描述

之前版本可以正常显示知识来源的分段，但是1.7开始变成了“执行详情”

### 重现步骤

![1d09fe42a89fba00bc37644072650df](https://github.com/user-attachments/assets/98bd5ea2-2a1c-42c4-bd5c-fca45213ceaf)
![cbb3405da6d51779903e0b987cee99f](https://github.com/user-attachments/assets/c821143e-3b49-455a-a4b7-0a0ee96b0f20)

**Comment by jstbw** [comment]
简单编排可以正常显示知识来源，引用的分段，但是这个高级编排却只能显示执行详情，实际运用中，给最终用户显示编排流程是不合理的

**Comment by baixin513** [comment]
感谢反馈，高级编排应用中会有多个知识库检索节点，有些用户还会在函数中查询引用外部数据，有些用户还会使用多路召回重排模型， 所以高级编排应用无法像简单编排应用那样，仅显示知识来源。
