### ISSUE TITLE
提出问题之后，一直显示“回答中。。。”，很久之后出现connect error

### ISSUE THREAD

**Issue by skillful2002** [1Panel-dev/MaxKB#165]
### 联系方式

458058285@qq.com

### MaxKB 版本

Center OS 7.6 (虚拟机，8核CPU16G内存）

### 问题描述

使用ollama模型中的llama2或qwen:0.5b，在提出问题之后，一直显示“回答中。。。”，很久之后出现connect error
<img width="1195" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/10183545/a3c9e376-a980-4ca1-ba99-00f3b1d79ffd">
![image](https://github.com/1Panel-dev/MaxKB/assets/10183545/1ec45493-1e94-4b31-a1ef-bb9037d18d42)

### 重现步骤

使用ollama模型中的llama2或qwen:0.5b，在提出问题之后，一直显示“回答中。。。”，很久之后出现connect error

### 期待的正确结果

使用ollama模型中的llama2或qwen:0.5b，在提出问题之后，一直显示“回答中。。。”，很久之后出现connect error

**Comment by skillful2002** [comment]
提示词已经最简化了，就只有一个question了


期待明天
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Panel-dev/MaxKB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Panel-dev/MaxKB] 提出问题之后，一直显示“回答中。。。”，很久之后出现connect error (Issue #165)





 
提示词简化一下内容，减少引用分段数，CPU配置的回答较慢，少携带一些内容。

**Comment by skillful2002** [comment]
提示词已经最少了吧
<img width="616" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/10183545/c9d51e6a-53b4-4042-8ac5-7e9137410906">
知识库就一个问题
<img width="512" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/10183545/218fc99b-93c1-44b9-97dd-40393ed62bc8">

**Comment by baixin513** [comment]
这个错误是模型返回的，可以到模型管理中去保存一下 qwen:0.5b 这个模型，看看能否正常保存。

**Comment by liufan4622656** [comment]
我刚开始也出现在这个，然后我把小骆驼那个后台打开就正常了

**Comment by baixin513** [comment]
如果没有问题，该 issue，先关闭了

**Comment by insoliang** [comment]
> 我刚开始也出现在这个，然后我把小骆驼那个后台打开就正常了
请问小骆驼后台是什么呀

**Comment by baixin513** [comment]
> > 我刚开始也出现在这个，然后我把小骆驼那个后台打开就正常了
> > 请问小骆驼后台是什么呀

那是跑大模型的 Ollama 平台，Ollama 关了提问肯定报错
