### ISSUE TITLE
[BUG]动态注入第三方script资源时，存在重复添加maxkb标签问题

### ISSUE THREAD

**Issue by lambert959** [1Panel-dev/MaxKB#1659]
### MaxKB 版本

v1.3.1

### 问题描述

动态注入第三方maxkb时，出现多次添加maxkb节点

### 重现步骤

![image](https://github.com/user-attachments/assets/da60c480-eabd-4269-9934-4df0ae226e01)

![image](https://github.com/user-attachments/assets/63d8dc44-33e9-412b-bfdb-04fc9e4249f6)
页面加载后再动态注入时，只执行了一次script.onload事件，正常显示一个maxkb节点
如果页面刷新会导致先执行了script.onload，后执行window.onload,在页面添加了两次maxkb节点

### 期待的正确结果

embed.js 增加节点已存在的判断，不在重复添加

![image](https://github.com/user-attachments/assets/0afd7117-6d6f-4efb-82fa-c222b01cece6)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化
