### ISSUE TITLE
关于api接口和分词疑问和建议

### ISSUE THREAD

**Issue by 496672097** [1Panel-dev/MaxKB#166]
### MaxKB 版本

4.18最新版本

### 请描述您的需求或者改进建议

第一个是关于API的疑问。
我在系统中创建了应用， 应用模块中提供了api访问的功能， 并且提供申请accesstoken的地方。文档地址为http://192.168.106.106:8080/doc/ 。但此文档是整个系统的api。
我想将其接入其他系统中。是否有针对我新建的应用的"测试应用"的开发文档，比如我第一步应该xxx. 第二部应该XX的说明。
第二个是关于分词功能的，
当用户知识库数量较大的时候，发送的请求并没有进行分词处理。而是将整个TXT文档传输出去了，导致一个请求消耗token的数量巨大。是否有办法降低token的消耗。

**Comment by baixin513** [comment]
第一个关于使用应用的 APIkey 对话的说明文档已经更新到 wiki，地址如下：
https://github.com/1Panel-dev/MaxKB/wiki/3.1-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%BA%94%E7%94%A8%E7%9A%84APIKey%E8%BF%9B%E8%A1%8C%E5%AF%B9%E8%AF%9D%E8%B0%83%E7%94%A8

该 issue 先关闭了
