### ISSUE TITLE
[FEATURE]知识库-点击文档后，希望段落，可以排序；(目前似乎是根据创建时间排序的，最早创建的排在最前面)

### ISSUE THREAD

**Issue by shaohuayangfit2** [1Panel-dev/MaxKB#1663]
### MaxKB 版本

1.7.2

### 请描述您的需求或者改进建议

知识库-点击文档后，希望段落，可以排序；
1，目前似乎是根据创建时间排序的，最早创建的排在最前面
2，希望可以增加个倒序或者顺序排序的排序按钮；
3，让最新更新的，可以展示在最前面或者最后面

**Comment by baixin513** [comment]
根据更新时间显示，位置会变来变去，体验并不好。
后期会考虑根据文档顺序，但近期先安排不上。
