### ISSUE TITLE
[BUG]权限设置只勾选管理知识库权限，结果用户看不到，只勾选查看，能看到而且能编辑

### ISSUE THREAD

**Issue by weishuo6** [1Panel-dev/MaxKB#1664]
### 联系方式

1373916729@qq.com

### MaxKB 版本

V1.7.0

### 问题描述

权限设置只勾选管理，结果用户看不到；只勾选查看，能看到而且能编辑；两个都勾选效果同只勾选查看

### 重现步骤

1、团队成员-选择成员-配置权限，选择知识库，勾选管理权限，取消查看权限
![image](https://github.com/user-attachments/assets/a4cf381c-ee80-4533-a5c2-9d8131cdfee7)

### 期待的正确结果

勾选管理可以查看可以编辑，勾选查看只能查看不能编辑

**Comment by zyyfit** [comment]
感谢反馈，后面我们会优化管理和查看联动选中，不过只有查看权限的时候可以编辑这个问题我没有复现，请问您是怎么操作的呢
![图片](https://github.com/user-attachments/assets/ff0b87ad-b5bd-43f3-9804-482965f9adbd)

**Comment by weishuo6** [comment]
我明白你意思了，目前是点保存的时候才会提示没有权限访问，我建议最好是按钮搞成灰色，无法点击。例如文件上传那里，其实还是能点上传，而且能传，只是无法保存，直接搞成灰色无法点击的最好

**Comment by baixin513** [comment]
v1.8.0 已发布！
