### ISSUE TITLE
[BUG]生成问题时勾选其他文档继续生成问题，提示正在生成，请重新下发

### ISSUE THREAD

**Issue by yaoyi111** [1Panel-dev/MaxKB#1668]
### 联系方式

God47@qq.com

### MaxKB 版本

1.7.1

### 问题描述

在知识库中选择前两个分页的内容，点击生成关联问题后。再进入第三个分页，勾选分页上的内容，点击生成关联问题，会出现如下提示。
![7a83fa4ab0424a50cb320771d793964](https://github.com/user-attachments/assets/368a1f83-cdc4-4f6a-8d45-93cf6e572b67)

### 重现步骤

在知识库中选择前两个分页的内容，点击生成关联问题后。再进入第三个分页，勾选分页上的内容，点击生成关联问题，会出现如下提示。

### 期待的正确结果

状态不是  执行中  的分段内容，可以正常执行生成关联问题的操作。

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by baixin513** [comment]
v1.8.0 已发布！
