### ISSUE TITLE
[FEATURE]知识库页面希望能增加 全部选择功能，方便进行批量删除和生成问题

### ISSUE THREAD

**Issue by yaoyi111** [1Panel-dev/MaxKB#1669]
### MaxKB 版本

1.7.1

### 请描述您的需求或者改进建议

知识库页面希望能增加 全部选择功能，方便批量删除和生成问题，现在只能全选当前分页的内容。如果客户上传的内容很多，有几十个分页，想要批量删除或者批量生成关联问题时，需要每个分页都进行一次操作。

### 请描述你建议的实现方案

知识库页面增加全部选择功能

**Comment by baixin513** [comment]
1、文档全部删除，可以直接删除知识库；
2、文档全部重新向量化，可以直接在知识库面板中操作知识库的重新向量化。 
3、文档全部生成问题，后续会在知识库面板中操作，不会在文档列表中操作。
