### ISSUE TITLE
[BUG]相同应用下可以看到其他人的对话日志

### ISSUE THREAD

**Issue by bboysoulcn** [1Panel-dev/MaxKB#167]
### MaxKB 版本

v1.0.3

### 问题描述

相同应用下可以看到其他人的对话日志

### 重现步骤

相同应用下可以看到其他人的对话日志

**Comment by baixin513** [comment]
感谢反馈，但是没明白您说的问题是什么？ 方便的话详细描述一下问题并提供相应截图。

**Comment by bboysoulcn** [comment]
> 感谢反馈，但是没明白您说的问题是什么？ 方便的话详细描述一下问题并提供相应截图。

就是我是管理员然后创建了一个应用，然后创建了一个账号叫小明，并且把小明加入了我的团队，而且给了小明使用这个应用的权限，小明使用这个应用的对话日志我是可以看到的，同时我使用这个应用的对话日志小明也是可以看到的

**Comment by baixin513** [comment]
了解了，我们的使用场景如下描述：
对话日志是显示当前应用所有的对话。是维护人员查看所有用户真实的对话记录，方便来根据提问调整知识库内容的。
团队成员是协同管理知识库和应用的，有权限就能全部看到，主要是协作维护知识库内容。

**Comment by bboysoulcn** [comment]
> 了解了，我们的使用场景如下描述： 对话日志是显示当前应用所有的对话。是维护人员查看所有用户真实的对话记录，方便来根据提问调整知识库内容的。 团队成员是协同管理知识库和应用的，有权限就能全部看到，主要是协作维护知识库内容。
> 
> 当前还无法满足您的场景。

ok
