### ISSUE TITLE
[FEATURE]结合LangSmith

### ISSUE THREAD

**Issue by armored-glitch** [1Panel-dev/MaxKB#1675]
### MaxKB 版本

 v1.7.1 

### 请描述您的需求或者改进建议

尊敬的MaxKB团队：
       后续考虑结合LangSmith 方便用户调试、协作、测试和监控LLM 应用程序。

### 请描述你建议的实现方案

提供接入LangSmith Token 的入口，用户填入申请Token
只需在 LangChain 代码中设置三个环境变量即可，所有跟踪步骤都将自动记录

**Comment by liqiang-fit2cloud** [comment]
目前没有计划。
