### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Shy280** [1Panel-dev/MaxKB#1677]
### 联系方式

280960087@qq.com

### MaxKB 版本

 v1.6.1 (build at 2024-09-29T19:14, commit: 81ffe59c)

### 问题描述

在嵌入其他网站的过程中 出现跨域问题：

```
The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
```

部署maxkb的方式：
docker
部署站点协议：
http
嵌入的系统协议：
http
已在应用设置中设置允许跨域
![0fa2862427a1d6d78f911873d384b61](https://github.com/user-attachments/assets/16b344bc-ec1d-4ba3-8f38-5f8b3c09c12d)
![5a14a4e6dd951b4f6ebe4e1675a8f97](https://github.com/user-attachments/assets/c5f77856-e7d1-48b1-a226-00ea6012a40f)

但是仍然提示其报错
响应标头仍然是：
Cross-Origin-Opener-Policy: same-origin

### 重现步骤

如何设置都会出现该问题

**Comment by shaohuzhang1** [comment]
这个是使用apikey的跨域设置，只适用于在其他应用使用apikey调用maxkb系统的接口。可以描述一下具体操作吗

**Comment by zyyfit** [comment]
您好，跨域不是在白名单里设置的，需要在appkey中设置
![图片](https://github.com/user-attachments/assets/63a1b9a8-bbbb-474d-aba0-b5956379b9f2)

![图片](https://github.com/user-attachments/assets/b7a8dc44-3b83-4777-a3b8-b1f38ce2e194)

**Comment by Shy280** [comment]
> 您好，跨域不是在白名单里设置的，需要在appkey中设置 ![图片](https://private-user-images.githubusercontent.com/73461316/389348436-63a1b9a8-bbbb-474d-aba0-b5956379b9f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDMyMDgsIm5iZiI6MTczMjUwMjkwOCwicGF0aCI6Ii83MzQ2MTMxNi8zODkzNDg0MzYtNjNhMWI5YTgtYmJiYi00NzRkLWFiYTAtYjU5NTYzNzliOWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyNDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MThjYmI2YjFlMjYwYWM5ZDc4OGNhNjFjYTA4ZWVhNGQ4Mjg5NWNkZDFmMjEyZTEyYTk3MDEzZTEwYTRlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W6Fi8N-QHXZ_CHX7OsoMpEdBk6JT5-lhOl9K9TSVeHc)
> 
> ![图片](https://private-user-images.githubusercontent.com/73461316/389348245-b7a8dc44-3b83-4777-a3b8-b1f38ce2e194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDMyMDgsIm5iZiI6MTczMjUwMjkwOCwicGF0aCI6Ii83MzQ2MTMxNi8zODkzNDgyNDUtYjdhOGRjNDQtM2I4My00Nzc3LWEzYjgtYjFmMzhjZTJlMTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyNDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiY2NhMDE3NWRmMmM2MjZmZTBhOWQ0NWY2OGE5MDFiYWU0YjJkOWRlNjQ0OGQyNzA1YzAwMWY3YjYzNmE2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._EdknpossKUH9_26OrSIRho5z9hdpW-hMKl8BcOlioI)

你好 这里的设置也有：
![image](https://github.com/user-attachments/assets/88fdd3a3-a12a-4da6-ac6a-abea37f679a1)
