### ISSUE TITLE
[BUG]【应用】调试页面，在下面明明有引用分段，但是还是提示“没有在知识库中查找到相关信息”

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1679]
### MaxKB 版本

v1.7.0

### 问题描述

【应用】调试页面，在下面明明有引用分段，但是还是提示“没有在知识库中查找到相关信息”

### 重现步骤

【应用】调试页面，在下面明明有引用分段，但是还是提示“没有在知识库中查找到相关信息”
![image](https://github.com/user-attachments/assets/38303494-2344-4f0b-b3b7-6a4e82a0c55b)

**Comment by zyyfit** [comment]
提示词的问题
