### ISSUE TITLE
当前不能像OpenAI那样对话的。

### ISSUE THREAD

**Issue by samcaicn** [1Panel-dev/MaxKB#168]
当前不能像OpenAI那样对话的。
需要先获取一个对话id 才可以进行对话，具体要看我们API文档。

_Originally posted by @baixin513 in https://github.com/1Panel-dev/MaxKB/issues/33#issuecomment-2056631455_
            
牛逼

**Comment by baixin513** [comment]
感谢反馈，我们的架构无法支持接入一个模型来分发 API key的功能。
