### ISSUE TITLE
[FEATURE]简繁字体混用的环境命中率低

### ISSUE THREAD

**Issue by WongHohin** [1Panel-dev/MaxKB#169]
### MaxKB 版本

1.0.2

### 请描述您的需求或者改进建议

在简繁字体混用的环境中使用，命中率较低。
例如知识库的文档的繁体的，如果用简体提问会存在向量数据库搜不出的情况。

### 请描述你建议的实现方案

希望可以在提问的时候统一把问题转换成简体或者繁体来解决。

**Comment by baixin513** [comment]
感谢反馈，系统会把原始问题进行向量召回的。您可以输入问题时切换成繁体字输入问题。
