### ISSUE TITLE
[BUG]【系统管理-团队成员】给成员勾选应用的查看权限，但是该成员对应应用下的应用接入-企业微信对接的内容能修改且能正常保存。

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1690]
### MaxKB 版本

v1.7.2

### 问题描述

【系统管理-团队成员】给成员勾选应用的查看权限，但是该成员对应应用下的应用接入-企业微信对接的内容能修改且能正常保存。

### 重现步骤

【系统管理-团队成员】给成员勾选应用的查看权限，但是该成员对应应用下的应用接入-企业微信对接的内容能修改且能正常保存。
![image](https://github.com/user-attachments/assets/ab6446f1-8d8e-4649-ba99-2300698e64f3)

![image](https://github.com/user-attachments/assets/9c4e3afa-9722-461b-9c95-a2745f276d16)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by baixin513** [comment]
v1.8.0 已发布！
