### ISSUE TITLE
应用中对话日志功能增强需求

### ISSUE THREAD

**Issue by 496672097** [1Panel-dev/MaxKB#170]
### MaxKB 版本

1.1

### 请描述您的需求或者改进建议

1、增加对话日志增加知识库命中情况，原因：对话日志有 根据用户回答调整回答准确性的作用。但是没有知识库命中情况调整起来没有指导方向。
2、增加对话token消耗记录。 管理人员可以根据问答情况调整知识库结构，达到降本增效的目的。
3、咨询是否开放源代码，希望能进行二次开发。

**Comment by baixin513** [comment]
感谢反馈，回答如下：
1、是要在知识库分段中增加命中率么？ 查看分段的命中清空？
2、每次对话在对话详情中都有记录 tokens 消费，在应用的监控统计中也有 tokens 的数量统计。
3、当前项目是开源开放的，支持二次开发。

**Comment by 496672097** [comment]
感谢回复。那就放心开发了。
