### ISSUE TITLE
[FEATURE]md编辑器兼容css，原样输出html

### ISSUE THREAD

**Issue by RuanLia** [1Panel-dev/MaxKB#1708]
### MaxKB 版本

1.7.0

### 请描述您的需求或者改进建议

md编辑器兼容css，原样输出html，样式输出很普通，比如表格样式不够精致，无法实现表格的固定列宽及背景色等。直接写html，部分不兼容，不显示css。有其他md编辑器比maxkb自带的编辑器兼容性强。如：https://markdown.lovejade.cn/
![1732784160678](https://github.com/user-attachments/assets/6e7856c4-6dcd-4f6f-8ff5-3a1c777c90ef)
![1732784160702](https://github.com/user-attachments/assets/efb087ca-ca7c-4656-a032-285df8c948ca)
![1732784160690](https://github.com/user-attachments/assets/05f2d201-0274-4338-a268-09ae1561e210)
![image](https://github.com/user-attachments/assets/02168849-3e30-4906-83ab-faddd2c5dd26)

### 请描述你建议的实现方案

优化maxkb自带的md编辑器

**Comment by liqiang-fit2cloud** [comment]
感谢建议，你发的md编辑器基于vue2，没有vue3的开发库，不与MaxKB兼容。
而且目前并不是主流编辑器，所有暂时不考虑。

**Comment by RuanLia** [comment]
> 感谢建议，你发的md编辑器基于vue2，没有vue3的开发库，不与MaxKB兼容。 而且目前并不是主流编辑器，所有暂时不考虑。

我知道不与MaxKB兼容，只是想问是否可以做到兼容更多的html标签以及直接输出css样式，使可玩性更高，客户想要什么样式都可以输出出来，定制化程度更高，回答格式也更加美观。
