### ISSUE TITLE
建议在回答问题的时候，能响应式的输出？

### ISSUE THREAD

**Issue by zhqfdn** [1Panel-dev/MaxKB#172]
### MaxKB 版本

最新版本

### 请描述您的需求或者改进建议

建议在回答问题的时候，能响应式的输出，这样体验感会好很多，因为一直看到回答中..不知道什么时间结束

**Comment by baixin513** [comment]
感谢反馈，当前就是响应式的输出，回答中是模型返回数据较慢还没有拿到第一股流。

**Comment by zhqfdn** [comment]
> 感谢反馈，当前就是响应式的输出，回答中是模型返回数据较慢还没有拿到第一股流。

我测试了一下 open webui 他是ollama 边生成边显示的，咱们这个是基本上等ollama 生成完了才一下子显示出来。

**Comment by baixin513** [comment]
> 等ollama 生成完了才一下子显示出来

这里答案输出的逻辑优化了一下，下个版本更新一下试试看。
