### ISSUE TITLE
[BUG]前端无法启动

### ISSUE THREAD

**Issue by huangzhaorong** [1Panel-dev/MaxKB#1721]
### MaxKB 版本

main

### 问题描述

前段启动后敲地址一片空白。

### 重现步骤

Uncaught Error: A route named "application" has been added as a child of a route with the same name. Route names must be unique and a nested route cannot use the same name as an ancestor.
![1733041591584](https://github.com/user-attachments/assets/2e109a95-b4b4-4c43-a0ed-ef7ec72c9a63)

**Comment by liqiang-fit2cloud** [comment]
本地开发遇到的问题自己看看吧，每个人的环境和水平都不同，没有精力给大家一一检查。实在搞不定的就用官方版本。

**Comment by chengyi3192** [comment]
路由配置的问题：子路路由和父路由不能重名
修改两个地方：MaxKb/UI/src/router/modules/application.ts、MaxKb/UI/src/router/modules/dataset.ts
![image](https://github.com/user-attachments/assets/10de79e3-e3d2-486c-937a-dda0af0f7675)
![image](https://github.com/user-attachments/assets/8cadf9f0-c761-4442-adc6-58e7740dd6f9)
