### ISSUE TITLE
什么时候支持上传excel文件或者excel文件要怎么格式化处理？

### ISSUE THREAD

**Issue by xfeel2023** [1Panel-dev/MaxKB#173]
### MaxKB 版本

1.0.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/MaxKB/assets/142104448/6bb57050-5ea7-4735-b304-c3a21dd59712)
如图，我是小白，建立了知识库，但效果很差，该怎么设置这样数据的格式呢？现在的知识库是这个样子的
![image](https://github.com/1Panel-dev/MaxKB/assets/142104448/d3bc4eb8-9a72-4cf2-8546-d07d490a73f6)

**Comment by xfeel2023** [comment]
要整理成
物料编码：xxx
物料规格：xxxxx
这样的格式才能提高命中率吗？
比如我现在要找8MHz的物料有哪些，现在回答找不到

**Comment by baixin513** [comment]
感谢反馈，暂时还不支持 Excel 文件，就算支持也需要按照格式整理文档，建议可以直接在知识库中整理分段。
您可以试着改几个分段，把 物料编码作为分段标题、物理规格作为分段内容、然后将想要找的问题如：8MHz 作为关联问题，整理几个分段，在命中测试中测试一下看看。

**Comment by xfeel2023** [comment]
好吧，我再研究研究...

**Comment by baixin513** [comment]
好的，该 issue 先关闭了。
