### ISSUE TITLE
[BUG] 工作流里面调试提问，答案显示不完整，直接卡住

### ISSUE THREAD

**Issue by jackjiang517** [1Panel-dev/MaxKB#1730]
### MaxKB 版本

最新版本

### 问题描述

工作流里面调试提问，答案显示不完整，直接卡住

### 重现步骤

工作量流里面点击调试，输入问题
![微信图片_20241202113623](https://github.com/user-attachments/assets/95cf1837-86f6-42cd-b1d0-c82620e2f60b)

### 期待的正确结果

能完整显示回复答案

**Comment by baixin513** [comment]
我们未复现该问题，如果你之前是拉取的main分支代码的问题，可以重新拉取最新版本的release分支。
该issue先关闭了
