### ISSUE TITLE
[BUG]不配置知识库，只配置应用，无法进行有效对话

### ISSUE THREAD

**Issue by 1eez** [1Panel-dev/MaxKB#174]
### MaxKB 版本

1.0.3

### 问题描述

如下图所示，我在MaxKB 1.0.3版本中，只配置了模型，然后创建应用。并未创建知识库。
但在对话过程中，虽然百度云后台已经看到了调用量（也扣费了）
但前端的对话感觉并没有回答用户提出的问题。
<img width="1311" alt="企业微信20240419-122318@2x" src="https://github.com/1Panel-dev/MaxKB/assets/17718224/107ad4bc-450a-4046-b080-b013df708c86">
<img width="1317" alt="企业微信20240419-122409@2x" src="https://github.com/1Panel-dev/MaxKB/assets/17718224/a58e0886-d82f-4f21-ac77-990836190a7c">
<img width="1048" alt="企业微信20240419-122446@2x" src="https://github.com/1Panel-dev/MaxKB/assets/17718224/4e3af5c9-baf4-44a6-83a8-05234abbeacd">
<img width="1332" alt="企业微信20240419-122553@2x" src="https://github.com/1Panel-dev/MaxKB/assets/17718224/3dca1178-4b38-4b98-8fb6-dcd5c75a1371">

### 重现步骤

步骤：
1、系统设置 - 模型设置 - 添加模型（千帆大模型）
2、应用 - 创建应用
3、点击刚刚创建应用的公开访问链接
4、输入问题后，答非所问。

**Comment by baixin513** [comment]
感谢反馈，提示词您需要设置上 {question}, 该变量是用户提的问题，如果不加 {question} 用户问题是不会发给模型的。

提示词如下：
你是一个很有用的帮手，解决用户提出的问题。
问题是{question}

**Comment by 1eez** [comment]
原来如此，是我的问题，感谢解惑。
