### ISSUE TITLE
[FEATURE]支持同时设置多个模型【应用编排】

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#176]
### MaxKB 版本

1.0.0

### 请描述您的需求或者改进建议

支持同时对接多个模型，设想的一个使用场景参考：

1. 当命中率 1.0时，返回本地知识库文档；
2. 当命中率在0.7-0.99 时，走低版本模型；
3. 当命中率在 0.5-0.7 时，走高版本模型，给用户更好的对话体验；
4. 当命中率小于 0.5 时，不走模型，直接返回预设的回答，比如：当前未能学习到相关知识

**Comment by macaty** [comment]
这个很好的建议

**Comment by baixin513** [comment]
感谢反馈，该需求需要设定步骤节点的多种处理逻辑，需要编排功能来实现。
后期开发编排时会考虑。

**Comment by baixin513** [comment]
当前工作流中可以加个函数节点，获取一下检索结果列表中分段的相似度，然后在判断器中设置上述条件，后面跟随AI节点选择期望的模型即可实现。
