### ISSUE TITLE
[FEATURE] Amazon Bedrock模型支持配置代理地址

### ISSUE THREAD

**Issue by limin-fit2** [1Panel-dev/MaxKB#1762]
### MaxKB 版本

V1.7.2

### 请描述您的需求或者改进建议

对接Bedrock模型时不能配置代理地址，调用默认地址，导致账号直接被禁用，无法申诉，须重新注册新的账号，希望可以增加一个api域名地址栏配置代理地址
![image](https://github.com/user-attachments/assets/88175562-13e2-4135-a11f-30f7734c68f1)

**Comment by baixin513** [comment]
感谢反馈，无法支持。
