### ISSUE TITLE
[FEATURE]【知识库】问题增加来源标注

### ISSUE THREAD

**Issue by AndroidBaby1** [1Panel-dev/MaxKB#1763]
### MaxKB 版本

v1.7.2

### 请描述您的需求或者改进建议

目前 MaxKB 支持生成关联问题，但是有时候 AI 生成的问题不一定是实际想要的，能不能给问题加上来源标识（AI or 人工）。运营阶段可以要审核 AI 生成的是否要删除。

### 请描述你建议的实现方案

![image](https://github.com/user-attachments/assets/952cd6b4-bb41-495e-ac20-ae25f9e09297)
![image](https://github.com/user-attachments/assets/e2d67179-cf2d-46c4-a673-ad4a67539685)

_No response_

**Comment by liqiang-fit2cloud** [comment]
没有计划支持。
是否删除请根据问题内容决定，不建议根据由谁生成决定，如果不需要AI生成的问题可以不生成。
