### ISSUE TITLE
[FEATURE]支持markdown/docx类型文档以标题为问题的方式 批量录入问答对

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#177]
### MaxKB 版本

1.0.0

### 请描述您的需求或者改进建议

参考 qanything，可以支持通过表格批量录入问题及答案；目前只能批量录入问题还需要手动去关联
<img width="2007" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/40552640/4abf34b6-2fd5-4705-b8e1-5f844971fcce">

### 请描述你建议的实现方案

当然具体实现可以再仔细想想

**Comment by baixin513** [comment]
感谢反馈，文档录入时可以考虑增加个设置：自动添加分段标题为关联问题。 上传的文档格式可以把 问题作为标题，下面是答案。
