### ISSUE TITLE
[BUG] pdf 文档只识别到第一页

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [1Panel-dev/MaxKB#1774]
### 联系方式

zaopeng.guo@fit2cloud.com

### MaxKB 版本

1.8

### 问题描述

知识库导入文档只能识别到第一页

### 重现步骤

知识库导入 pdf 文档，只能识别到第一页。附件是测试的文件，图片是后台的报错。
[监护手册待完善(1).pdf](https://github.com/user-attachments/files/18022978/1.pdf)

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/c1276154-84fc-42a0-bc94-f8a574b7e9ff">

<img width="896" alt="image" src="https://github.com/user-attachments/assets/335dadfc-629a-402c-b389-6ba29056d169">

**Comment by baixin513** [comment]
感谢反馈，后续版本中修复

**Comment by baixin513** [comment]
v1.8.1 已发布
