### ISSUE TITLE
[FEATURE] 历史记录能否实现侧边隐藏

### ISSUE THREAD

**Issue by xuwei999-NT** [1Panel-dev/MaxKB#1775]
### MaxKB 版本

v1.7.1

### 请描述您的需求或者改进建议

点击红色矩形框，实现侧边隐藏。
![图片](https://github.com/user-attachments/assets/ff8c457b-ea7f-4112-a7a1-bdeaf00b351c)

**Comment by liqiang-fit2cloud** [comment]
没有计划。
