### ISSUE TITLE
[FEATURE] 新版本启动后登录页面空白

### ISSUE THREAD

**Issue by Darren-w** [1Panel-dev/MaxKB#1778]
### MaxKB 版本

v18.0

### 请描述您的需求或者改进建议

启动服务后，登录界面显示空白。通过开发者模型可以看到有一个报错：
![image](https://github.com/user-attachments/assets/6c00a149-2247-4bee-92d8-04195138c869)

### 请描述你建议的实现方案

正常使用

**Comment by liqiang-fit2cloud** [comment]
本地开发遇到的问题请自行解决，每个人的环境和水平都不同，没有精力给大家一一检查。实在搞不定的就用官方版本。

**Comment by Darren-w** [comment]
没有进行二次开发，直接克隆项目启动运行1.8版本。

**Comment by liqiang-fit2cloud** [comment]
自己检查环境和编译过程，实在搞不定的就用官方容器版本。

**Comment by Darren-w** [comment]
好的，因为最开始是这样启动，所以可以快速的更新咋们版本。

能否帮忙确认下这个地方的报错部分逻辑是否能复现。是环境的问题再去使用咋们的容器版本

![image](https://github.com/user-attachments/assets/e8facb66-9cc5-471d-8885-838a7a91709e)
