### ISSUE TITLE
[FEATURE]后续是否考虑使用无头浏览器爬取动态网页内容

### ISSUE THREAD

**Issue by linfengjjj** [1Panel-dev/MaxKB#1779]
### MaxKB 版本

v1.8

### 请描述您的需求或者改进建议

有不少网站页面内容是通过js动态加载的，如果不通过浏览器渲染，就无法爬取到内容。
所以希望可以支持使用无头浏览器爬取动态网页内容。

**Comment by liqiang-fit2cloud** [comment]
没有计划。

**Comment by liqiang-fit2cloud** [comment]
不会把精力花在文档抓取和预处理上。
