### ISSUE TITLE
[BUG]企业微信扫码登录中Agent ID变成APP Key

### ISSUE THREAD

**Issue by B14Lettingo** [1Panel-dev/MaxKB#1781]
### 联系方式

1812951966@qq.com

### MaxKB 版本

 v1.8.0 (build at 2024-12-05T12:09, commit: 77c334a7)

### 问题描述

登录认证中企业微信中的APP key此输入框无法输入Agent ID。若将Agent ID输入此文本框中后续的对接测试虽然可以通过，但是实际请求调用时会出现Agent ID undefined。

### 重现步骤

1.在企微扫码登录的对接界面中将Agent ID 输入至APP Key。
2.保存对接信息并退出MK。
3.点击扫码登录。

### 附加信息

<img width="932" alt="微信图片_20241206100530 - 副本" src="https://github.com/user-attachments/assets/15554e7b-cf6c-4157-9e4b-3431fc89b12b">
<img width="958" alt="微信图片_20241206100454" src="https://github.com/user-attachments/assets/0e9be554-a1a4-4761-98bd-c271fd7f4a6f">
<img width="1232" alt="微信图片_20241206100455" src="https://github.com/user-attachments/assets/79cf751c-194a-4eeb-b266-9717f2089760">
<img width="932" alt="微信图片_20241206100530 - 副本" src="https://github.com/user-attachments/assets/5982f378-705b-4cec-82a0-f04970fd8247">

**Comment by baixin513** [comment]
感谢反馈，后续版本中修复

**Comment by baixin513** [comment]
v1.8.1 已发布
