### ISSUE TITLE
[FEATURE]支持文档导出

### ISSUE THREAD

**Issue by macaty** [1Panel-dev/MaxKB#179]
### MaxKB 版本

1.0.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/MaxKB/assets/16797633/dcb5c459-26b6-4458-8253-ecd74841b263)
建议支持文档导出，方便其他合作者修改，并第一时间重新导入。

**Comment by baixin513** [comment]
感谢反馈，您可以先添加用户，然后在团队管理中添加成员并分配知识库的权限给该成员进行维护，我们支持团队多人协作维护。

<img width="1376" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/db160869-983b-4b7f-b74a-19b4e5cc3068">
