### ISSUE TITLE
[FEATURE]期望可以添加支持 openrouter 模型供应商。 

### ISSUE THREAD

**Issue by xwlops** [1Panel-dev/MaxKB#1790]
### MaxKB 版本

v1.8.0 (build at 2024-12-05T12:08, commit: a3e7fcb5)

### 请描述您的需求或者改进建议

在模型供应商中有一家 [openrouter.ai](https://openrouter.ai/models?max_price=0)的供应商，这里有很多免费的模型可以使用，而且国内也不受限制，期望可以添加支持该模型供应商。

**Comment by liqiang-fit2cloud** [comment]
兼容openai格式的接口可以直接添加。

**Comment by xwlops** [comment]
<img width="672" alt="image" src="https://github.com/user-attachments/assets/aa139276-9d98-4897-963a-190266954bfc">

在openai中添加[qwen-2-7b-instruct](https://openrouter.ai/qwen/qwen-2-7b-instruct:free/api)失败
<img width="615" alt="image" src="https://github.com/user-attachments/assets/9f6aeb3d-9542-4da2-bef3-280ae631c897">

在ollama中添加[qwen-2-7b-instruct](https://openrouter.ai/qwen/qwen-2-7b-instruct:free/api)失败

**Comment by liqiang-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/3bb1c5de-5dd1-43f4-875e-4bfe308fe0d5)
就是用openai，不过你这个模型填的对么？
