### ISSUE TITLE
[FEATURE] 文件識別文字，隱藏文字全文識別輸出時候，提示詞無法保留於歷史對話中。

### ISSUE THREAD

**Issue by alansiva** [1Panel-dev/MaxKB#1792]
### MaxKB 版本

V1.8

### 请描述您的需求或者改进建议

當文件識別或是圖片識別的結果(歷史對話)，無法正確的傳遞給下一次對話使用。除非將文件識別的內容進行指定回覆一次性輸出給使用者，才會成為歷史對話。

![螢幕擷取畫面 2024-12-09 143840](https://github.com/user-attachments/assets/1a9c75d8-34f8-4f67-bc95-f0c0fe9f9d19)

### 请描述你建议的实现方案

文件識別內容應該要可以保存在全域變數中，或是隱藏在歷史對話紀錄中，識別結果不應該要強制輸出才可以進行後續追問。

**Comment by baixin513** [comment]
感谢反馈，后续会在AI对话节点的历史聊天记录 增加设置。
选择工作流的历史记录，对话时携带 用户的问题和AI回复内容；（所有节点的返回内容）
选择节点的历史记录，对话时携带节点的提示词和当前节点的回复内容。

**Comment by baixin513** [comment]
v1.8.1 已发布
