### ISSUE TITLE
自定义endpoint

### ISSUE THREAD

**Issue by agneitnyreh** [1Panel-dev/MaxKB#1798]
### MaxKB 版本

最新

### 请描述您的需求或者改进建议

自定义endpoint，同义千问类似接口

### 请描述你建议的实现方案

自定义endpoint域名

**Comment by liqiang-fit2cloud** [comment]
没有计划。

**Comment by Cupcc** [comment]
> 没有计划。
弃坑

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> No plan.
Abandoned pit

**Comment by Cupcc** [comment]
> 没有计划。

弃坑

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> No plan.

Abandoned pit

**Comment by Cupcc** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > No plan.
> 
> Abandoned pit

I find [cherry-studio](https://github.com/CherryHQ/cherry-studio) supports custom endpoints. Have a try.
