### ISSUE TITLE
一直显示回答中，后台在对话日志中能监控到回答的内容

### ISSUE THREAD

**Issue by mysenr** [1Panel-dev/MaxKB#1801]
### MaxKB 版本

1.8.0

### 问题描述

360极速浏览器13.5.2044.0版本，一直显示回答中，后台在对话日志中能监控到回答的内容
![image](https://github.com/user-attachments/assets/4b895d5e-5bb9-4499-af2a-d8fb15b31a3f)
edge浏览器正常显示回答内容。

### 重现步骤

打开360浏览器，输入内容，无法回答（显示回答中...）

**Comment by mysenr** [comment]
360极速浏览器，刷新后，通过查看历史记录，是可以看到之前提问回答的内容。

**Comment by liqiang-fit2cloud** [comment]
换Chrome试试呢？

**Comment by mysenr** [comment]
> 换Chrome试试呢？

其他浏览器都没问题，edge、火狐、谷歌都可以。

**Comment by mysenr** [comment]
![image](https://github.com/user-attachments/assets/87ca52e6-0933-4408-b407-c0589eb1f04c)
这个版本不行，360极速浏览器X也能正常，这是属于浏览器问题？

**Comment by liqiang-fit2cloud** [comment]
不知道，不行你换个浏览器吧。其实这种情况下MaxKB也没啥可改的。。
