### ISSUE TITLE
[BUG]【知识库】web知识库，批量导入网页地址时，抓到的接口有请求体，但是swagger上没有填写请求体的地方。

### ISSUE THREAD

**Issue by 2lipan** [1Panel-dev/MaxKB#1809]
### MaxKB 版本

v1.8

### 问题描述

【知识库】web知识库，批量导入网页地址时，抓到的接口有请求体，但是swagger里没有填写请求体的地方，导致不能在swagger上调试。

### 重现步骤

【知识库】web知识库，批量导入网页地址时，抓到的接口有请求体，但是swagger里没有填写请求体的地方，导致不能在swagger上调试。
![8c0681488398e0ae1595caf134a1a2f](https://github.com/user-attachments/assets/54cc592e-24b4-481b-8b3c-da28e2e1b7c8)
![663d50476e324c5efafdc041e03ba5a](https://github.com/user-attachments/assets/247c0d3c-cec8-444e-91e2-7079d93d191b)
![bf19f9259907e4c233265f304448414](https://github.com/user-attachments/assets/005b0e6e-74ca-4ac6-a7d4-11234d4a7801)
![1733827556119](https://github.com/user-attachments/assets/c31bb270-8364-4e03-b355-5b289dbf133c)

**Comment by baixin513** [comment]
v1.8.1 已发布
