### ISSUE TITLE
[FEATURE]建议函数库传参支持decimal类型，现在函数库输入参数，传参要传array，array里包含了decimal就会报错。

### ISSUE THREAD

**Issue by Ankers-liu** [1Panel-dev/MaxKB#1818]
### MaxKB 版本

1.8.0

### 请描述您的需求或者改进建议

议函数库传参是支持decimal类型，现在函数库输入参数，传参要传array，array里包含了decimal就会报错。

### 请描述你建议的实现方案

议函数库传参是支持decimal类型，现在函数库输入参数，传参要传array，array里包含了decimal就会报错。

**Comment by shaohuzhang1** [comment]
不能序列化的都传递不了,你可以传入数据后在函数库里面进行转换
