### ISSUE TITLE
[FEATURE]本地启动服务，并实现调试功能

### ISSUE THREAD

**Issue by xiachuan7890** [1Panel-dev/MaxKB#1819]
### MaxKB 版本

1.8

### 请描述您的需求或者改进建议

本地启动服务，并实现调试功能，能否在文档里说么

**Comment by liqiang-fit2cloud** [comment]
本地开发遇到的问题请自行解决，每个人的环境和水平都不同，没有精力给大家一一检查。实在搞不定的就用官方版本。
