### ISSUE TITLE
[BUG]知识库中文件状态筛选失效

### ISSUE THREAD

**Issue by Henry-Shaw** [1Panel-dev/MaxKB#1820]
### MaxKB 版本

1.8.0

### 问题描述

从1.6.1使用离线包升级至1.8.0版本后，在知识库按照文件状态进行筛选时，筛选失败状态时是文件状态为成功的文档，筛选其他状态返回空

### 重现步骤

1. 创建知识库
2. 批量上次文档
3. 使用文件状态进行筛选

### 期待的正确结果

正确的文件状态筛选

### 附加信息

观察pgsql数据库中document表的status字段，从varchar(1)更新成了varchar(20)，以前文档状态时是2、3，在1.8.0版本状态变成了nn0、nn1、nn2

**Comment by baixin513** [comment]
感谢反馈，该问题在1.8.1已解决，今天会发布。

**Comment by baixin513** [comment]
v1.8.1 已发布
