### ISSUE TITLE
[FEATURE]通过API KEY进行知识库命中测试

### ISSUE THREAD

**Issue by xy3xy3** [1Panel-dev/MaxKB#1826]
### MaxKB 版本

v1.8.1

### 请描述您的需求或者改进建议

https://doc.tryfastgpt.ai/docs/development/openapi/dataset/#%E6%90%9C%E7%B4%A2%E6%B5%8B%E8%AF%95

https://docs.dify.ai/zh-hans/guides/knowledge-base/maintain-dataset-via-api#jian-suo-zhi-shi-ku

可以参考这个,添加维护知识库,测试知识库的api

### 请描述你建议的实现方案

设置一个key,允许该key调用知识库api

**Comment by liqiang-fit2cloud** [comment]
已有，专业版支持。

**Comment by samcaicn** [comment]
> 专业版支持api。

你妈

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Professional version supports API.

your mother

**Comment by samcaicn** [comment]
> 专业版支持api。

这个傻逼产品，都提需求几个月了，装不理解就算了，还你妈做成收费的：
https://github.com/1Panel-dev/MaxKB/issues/353

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Professional version supports API.

I’ve been requesting this stupid product for months, just pretend I don’t understand it, and let your mother make it for a fee:
https://github.com/1Panel-dev/MaxKB/issues/353
