### ISSUE TITLE
[BUG]当首页URL地址不是主站点地址时，web 站点无法同步子页面

### ISSUE THREAD

**Issue by shenkaibo** [1Panel-dev/MaxKB#1828]
### 联系方式

shenkaibo

### MaxKB 版本

1.8.1

### 问题描述

web 站点同步当首页URL地址不是主站点地址时，子页面无法同步
如:
首页地址： https://www.promptfoo.dev/docs/intro/ 
子页面地址：https://www.promptfoo.dev/docs/installation/ 、https://www.promptfoo.dev/docs/xxx

当同步子页面时，截取子页面后缀  docs/installation/ 拼接 到https://www.promptfoo.dev/docs/intro/  ，
最终为 https://www.promptfoo.dev/docs/intro/docs/installation/ ,这样导致子页面无法同步。

### 重现步骤

web 站点同步 https://www.promptfoo.dev/docs/intro/ 

### 期待的正确结果

建议 在 web 站点同步处 增加 「主站地址」选项，子页面后缀直接拼接到 「主站地址」上
![image](https://github.com/user-attachments/assets/64a1368b-fb93-4ec8-a388-05e9a11b7972)

**Comment by baixin513** [comment]
感谢反馈，单页面应用无法支持，子地址不包含根地址的无法支持。
