### ISSUE TITLE
[FEATURE] 版本升级

### ISSUE THREAD

**Issue by rainbowers** [1Panel-dev/MaxKB#1829]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

因为maxkb每个月都会有新版本或者补丁、那么对于老版本升级到新版的操作方面存在疑问，比如：1.2升级到1.8，表结构发生很大变化，如何平滑升级，且数据不受影响

### 请描述你建议的实现方案

1.2升级到1.8，表结构发生很大变化，如何平滑升级，且数据不受影响

**Comment by maninhill** [comment]
MaxKB 支持平滑升级，直接按文档操作即可。当然，我们建议每次升级前做下备份，哪怕有意外也可以恢复。
