### ISSUE TITLE
[BUG]权限管理问题

### ISSUE THREAD

**Issue by zhqfdn** [1Panel-dev/MaxKB#183]
### 联系方式

88325467@qq.com

### MaxKB 版本

最新版本

### 问题描述

给用户授权   管理（没有授权）   应用（授权）

### 重现步骤

用户权限管理

### 期待的正确结果

当只给用户授权了  （应用）权限，用户登陆后，不应该出现 【+】 新应用的权限。

**Comment by shaohuzhang1** [comment]
感谢反馈，每个用户都有权限添加应用和知识库 授权是授权自己的应用和知识库给其他用户管理.
