### ISSUE TITLE
[FEATURE]AI对话角色设定文本支持引用变量

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1831]
### MaxKB 版本

1.9.0

### 请描述您的需求或者改进建议

AI对话节点的提示词部分支持通过{{}}方式引用变量，希望角色设定部分也支持这种方式引用变量。目是是使得同一个应用在不同的环境下可以有不同角色表现，而不需要用分支判断节点加一堆分支

**Comment by baixin513** [comment]
重复 issue #1583
