### ISSUE TITLE
[BUG]重新回答，会重复添加记录

### ISSUE THREAD

**Issue by oneperfect01** [1Panel-dev/MaxKB#1832]
### MaxKB 版本

 v1.8.1

### 问题描述

在客户端点击重新回答时，会将所有的回答都重复添加到历史记录中

### 重现步骤

直接点击重新回答，可以在历史记录中，重新回答的记录和原来的记录都会被添加到历史记录，

### 期待的正确结果

如果操作来自重新回答，应该只记录最后一次的回答，要不然会影响历史记录的准确性。
或者，可以选择删除此条/不加入历史记录

**Comment by baixin513** [comment]
感谢反馈，当前所有的用户问题和回复都会记录，AI回复后如果觉得当前答案不太满意，maxkb提供的是【换个答案】操作，该操作会换一批引用分段，生成提示词发送给模型，让模型重新回答。

系统不会随意删除历史对话记录。
