### ISSUE TITLE
有额外处理预设向量模型shibing624_text2vec-base-chinese的token限制吗?

### ISSUE THREAD

**Issue by 02hao09** [1Panel-dev/MaxKB#1835]
### MaxKB 版本

v1.7.0

### 请描述您的需求或者改进建议

查到shibing624_text2vec-base-chinese的token限制为128, 请问若chunk size > 128 会被截断吗? 还是有做额外处理, 保证chunk都有向量化?

**Comment by baixin513** [comment]
感谢反馈，目前分块向量化最多256个字符，不会有你说的问题。
