### ISSUE TITLE
问答界面报错

### ISSUE THREAD

**Issue by phantom0718** [1Panel-dev/MaxKB#1840]
### MaxKB 版本

1.7.2

### 问题描述

问答界面报错

### 重现步骤

问答界面报错
【access token】此字段不能为null.
 Must be a valid uulD.

**Comment by baixin513** [comment]
感谢反馈，你提供的信息无法判断问题，请先升级到最新版本，然后再试一下。
如果有问题，请填写相应的复现步骤或操作视频。
