### ISSUE TITLE
[BUG]前端加载字体文件太大，建议优化

### ISSUE THREAD

**Issue by shenkaibo** [1Panel-dev/MaxKB#1846]
### 联系方式

shenkaibo

### MaxKB 版本

1.8.1

### 问题描述

![image](https://github.com/user-attachments/assets/b12f77ab-5d2c-40d6-ac73-0d8b0c05c7f8)

### 重现步骤

前端加载字体文件太大，建议优化

**Comment by liuruibin** [comment]
加大带宽吧该说不说

**Comment by liqiang-fit2cloud** [comment]
阿里的字体，就这么大。
