### ISSUE TITLE
[BUG]【模型管理】- 优化添加模型的表单，增加提示词

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/MaxKB#185]
### MaxKB 版本

1.0.3

### 问题描述

<img width="600" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/85377380/8bf4230f-fefe-4e2a-83b5-bb4b75428020">

我本地有 ollama 下载好的 通义千问模型，我想用这个，请问可以实现吗？还是只能用 llama

### 重现步骤

模型里面只能下拉
<img width="605" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/85377380/adb164df-2e72-48a8-87cf-e7c00605bd44">

### 期待的正确结果

安装我所需要的任意模型，比如

<img width="475" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/85377380/e587c9fb-aefe-442b-881a-3c55591351df">

**Comment by baixin513** [comment]
感谢反馈，基础模型可以自定义输入qwen:0.5b 然后回车，即可对接。

**Comment by xaswq** [comment]
可以了，需要手动输入再打个回车，建议优化下这个逻辑。可以有个选项是其他，然后用户手动输入
<img width="747" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/85377380/8710fee4-754e-407a-a908-db18f3d8e651">

**Comment by baixin513** [comment]
感谢反馈，后期版本我们优化一下支持自定义输入的提示语

**Comment by DirtyKnightForVi** [comment]
> 感谢反馈，后期版本我们优化一下支持自定义输入的提示语

这边也有一个问题：
内网环境中，我已经起了一个ollama服务，也已经启动了一个模型（不是ollama pull 的，而是通过ollama create 的）。他会读取这个服务上的模型吗？还是说一定要手动填写我已经启动的模型名？

**Comment by DirtyKnightForVi** [comment]
以及你们怎么更改不同用户登陆使用是，导致的ollama模型切换重新加载到问题？

**Comment by baixin513** [comment]
> > 感谢反馈，后期版本我们优化一下支持自定义输入的提示语
> 
> 这边也有一个问题： 内网环境中，我已经起了一个ollama服务，也已经启动了一个模型（不是ollama pull 的，而是通过ollama create 的）。他会读取这个服务上的模型吗？还是说一定要手动填写我已经启动的模型名？

需要手动在 MaxKB 的 Ollama 模型表单中的基础模型输入你在 Ollama 上创建的模型名称就可以对接。

**Comment by baixin513** [comment]
> 以及你们怎么更改不同用户登陆使用是，导致的ollama模型切换重新加载到问题？

后端应用切换模型，新的会话ID会使用新的模型配置。 已经打开的会话窗口还是之前的配置，关闭重开或者刷新链接后会适用新的应用配置。
