### ISSUE TITLE
[FEATURE]大需求：建议知识文档处理过程可以自行流程编排处理

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#1851]
### MaxKB 版本

1.9.0

### 请描述您的需求或者改进建议

当前maxkb的知识解析、检索能力还较弱，例如不支持图像、不支持数据库、不支持知识图谱等等，建议将知识的解析、检索过程同样开放流程编排的方式给用户处理

**Comment by baixin513** [comment]
这真是一个大需求，近期满足不了，明年会重点考虑。

**Comment by liqiang-fit2cloud** [comment]
近期没计划的先关掉。
