### ISSUE TITLE
[BUG]Xorbits Inference 部署了模型 ChatTTS 接入的时候提示：校验失败,请检查参数是否正确: Request timed out. 

### ISSUE THREAD

**Issue by taochach** [1Panel-dev/MaxKB#1858]
### MaxKB 版本

v1.8.0 (build at 2024-12-05T12:08, commit: a3e7fcb5)

### 问题描述

![image](https://github.com/user-attachments/assets/8d9171b8-c506-44fb-a5b0-7a8f4d363141)

### 重现步骤

对接模型提示错误

**Comment by baixin513** [comment]
请求超时，请检查网络及环境问题。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thank you, xinference started by docker can access the host computer normally from the outside, but the host computer cannot be accessed from the maxkb container started by another docker.
