### ISSUE TITLE
[BUG] 无法设置每个应用的模型参数！

### ISSUE THREAD

**Issue by piwawa** [1Panel-dev/MaxKB#1859]
### MaxKB 版本

v1.8.0

### 问题描述

这堆参数，直接调用 maxkb 的 API 传入这些参数没效果：

```
    "temperature": 9,
    "top_p": 60,
    "n": 8,
    "stream": true,
    "stop": "magna laboris ut est Lorem",
    "max_tokens": 11,
    "presence_penalty": 17,
    "frequency_penalty": 96,
```

这里是空的

![image](https://github.com/user-attachments/assets/1270c698-b730-481a-964d-961b353bfe57)

### 重现步骤

如上

### 期待的正确结果

上图应该允许设置传参，或者在调用 maxkb 的应用 API 时能够正常传参

**Comment by baixin513** [comment]
感谢反馈，请在模型管理中设置模型参数，根据模型官网API，配置相对应的参数
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/6499d306-ade4-4401-bd4e-d32682bd1ad2" />

**Comment by piwawa** [comment]
![image](https://github.com/user-attachments/assets/4717a1e8-3242-49d3-9d5c-6f49e7241319)

假如要设置为 2000，应该怎么选啊？
