### ISSUE TITLE
[FEATURE]问答页面，希望支持对问答字体调整大小

### ISSUE THREAD

**Issue by binbin0406** [1Panel-dev/MaxKB#1861]
### MaxKB 版本

1.8.1

### 请描述您的需求或者改进建议

MK问答演示页面中，希望支持对问答字体自定义调整大小

### 请描述你建议的实现方案

MK问答演示页面中，希望支持对问答字体自定义调整大小，设置后在小助手问答页面中同步更新。

### 附加信息

<img width="918" alt="1734431185163" src="https://github.com/user-attachments/assets/871b11e2-5519-4565-a2eb-9b61a769372e" />

**Comment by baixin513** [comment]
感谢反馈，暂无计划
