### ISSUE TITLE
[BUG]使用内部的OpenAI图片理解模型，上传图片后，图片理解正确，但是还有其他报错信息

### ISSUE THREAD

**Issue by spritelyl** [1Panel-dev/MaxKB#1867]
### 联系方式

14707070227

### MaxKB 版本

v1.8.1

### 问题描述

使用内部的OpenAI图片理解模型，对接成功后，上传图片后，图片理解正确，但是还有其他报错信息
![image](https://github.com/user-attachments/assets/130fdd06-0ab7-45d4-85b3-bcd12d10e389)

### 重现步骤

1. 使用内部的图片理解模型，对接成功后，上传图片后，图片理解正确，但是还有其他报错信息
![image](https://github.com/user-attachments/assets/e31df227-687d-46c5-b908-3b9b9badeb61)

具体报错信息是：
HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/o200k_base.tiktoken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f565c126e50>: Failed to resolve 'openaipublic.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)"))

2. 内部使用一样的api接口,后台模型返回值是正常的
![image](https://github.com/user-attachments/assets/0cec7f13-0353-4086-96ad-575caba7dedb)

### 期待的正确结果

使用内部的OpenAI图片理解模型，对接成功后，上传图片后，图片理解正确，没有其他报错信息

**Comment by liqiang-fit2cloud** [comment]
什么叫内部的OpenAI图片理解模型？

**Comment by spritelyl** [comment]
> 什么叫内部的OpenAI图片理解模型？

就是部署在内部服务器的openai格式的模型

**Comment by liqiang-fit2cloud** [comment]
用什么部署的，ollama还是xinference？

**Comment by spritelyl** [comment]
> 用什么部署的，ollama还是xinference？

通过LitServe 运行书生-万象internVL2.5，然后提供支持openai 接口格式的服务api 与 MaxKB 对接的

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> What is deployed using, ollama or xinference?

Run Shusheng-Wanxiang internVL2.5 through LitServe, and then provide a service api that supports the openai interface format to interface with MaxKB

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I guess your visual LLM configuration is wrong. Take a screenshot to see how it is configured.

**Comment by spritelyl** [comment]
> 估计你视觉LLM配置错了，截图看看咋配置的

可以了，咨询了开发，通过修改代码已解决，感谢支持，

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> I guess your visual LLM configuration is wrong. Take a screenshot to see how it is configured.

It’s ok. I consulted the development team and it was solved by modifying the code. Thank you for your support.
