### ISSUE TITLE
[FEATURE] 使用openai的embedding api

### ISSUE THREAD

**Issue by zhiqing0205** [1Panel-dev/MaxKB#187]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

感觉召回率有点低，特别是英文文档中文提问，感觉是embedding的问题

**Comment by baixin513** [comment]
感谢反馈，可以先到我们论坛中参考一下更改embedding模型的配置操作的帖子。

**Comment by baixin513** [comment]
当前使用的Embedding模型为 text2vec-base-chinese ，针对英文文档，中文问题召回的相似度确实较低。您可以找一下符合您需求的向量化模型，更改一下配置，
更改embedding模型的配置 可参考以下帖子，该 issue就先关闭了。
https://bbs.fit2cloud.com/t/topic/3876/17

**Comment by carbonz0** [comment]
> > 当前使用的Embedding模型为 text2vec-base-chinese ，针对英文文档，中文问题召回的相似度确实较低。您可以找一下符合您需求的向量化模型，更改一下配置， 更改embedding模型的配置 可参考以下帖子，该 issue就先关闭了。 https://bbs.fit2cloud.com/t/topic/3876/17
> 
> docker更新挂载点之后，然后进入到yaml里面更改model_name就行了吗？怎么确认实际使用的是指定的这个模型呢？有哪里的日志或者标识可以确认吗？

改EMBEDDING_MODEL_PATH和EMBEDDING_MODEL_NAME，然后重启docker。
