### ISSUE TITLE
[Feature] The user hopes that when selecting to display "Knowledge Source", the user can download the corresponding word/pdf document.

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1873]
### MaxKB Version

1.8.0

### Please describe your needs or suggestions for improvements

<img width="761" alt="1734593994179" src="https://github.com/user-attachments/assets/825c0d08-f132-41bf-b97f-85e88e28ddef" />

### Please describe the solution you suggest

用户希望，可以下载知识来源下方的 文档。
从使用场景来看，对该客户来说是合理需求。
这是一家全球猎头公司，他们有各种规范文档，涉及到人事政策。在得到答案后，想查看对应的文档。

**Comment by baixin513** [comment]
感谢反馈，当前上传文档时未存储原始文件，离线文件无法下载，但web站点的文档可以跳转到对应的链接。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback. The original file is not stored when uploading documents. Offline files cannot be downloaded, but documents on the web site can jump to the corresponding link.
