### ISSUE TITLE
Conversation export

### ISSUE THREAD

**Issue by Readyou123** [1Panel-dev/MaxKB#1880]
### MaxKB Version

1.8.0

### Please describe your needs or suggestions for improvements

导出历史对话能否导出为word格式

**Comment by liqiang-fit2cloud** [comment]
你可以自己把导出的excel转换word。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
You can convert the exported excel to word yourself.
