### ISSUE TITLE
Questions about caching

### ISSUE THREAD

**Issue by phantom0718** [1Panel-dev/MaxKB#1881]
### MaxKB Version

1.7.2

### Please describe your needs or suggestions for improvements

是否可用将项目使用的本地内存缓存和文件缓存，切换成分布式缓存，统一集中管理？

**Comment by liqiang-fit2cloud** [comment]
有计划，但近期不会做。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I have plans, but I won’t do it in the near future.
