### ISSUE TITLE
[Feature] Some users mentioned that the ChatTTS and FunASR speech models deployed on the local model Ollama/vLLM/Xinference can be added to the local speech model configuration.

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#1884]
### MaxKB Version

1.8.0

### Please describe your needs or suggestions for improvements

有用户提本地模型Ollama/vLLM/Xinference上部署的ChatTTS和FunASR语音模型可以添加到本地语音模型配置里。

### Please describe the solution you suggest

ChatTTS和FunASR语音模型，查了一下，口碑还可以。

### Additional Information

目前本地模型，只支持 大语言 ，向量模型。

**Comment by 35plus** [comment]
刚刚查了一下xinference已经可以对接语音模型，该需求可以暂时忽略

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I just checked that xinference can already connect to the speech model. This requirement can be ignored for the time being.
