### ISSUE TITLE
[FEATURE]知识库支持导出吗？如何导出。

### ISSUE THREAD

**Issue by liubin595338764** [1Panel-dev/MaxKB#189]
### MaxKB 版本

v1.0.4 (build at 2024-04-19T16:59, commit: 7c001221)

### 请描述您的需求或者改进建议

如何导出知识库？
比如我们项目有多个模块，每个模块可以是一个知识库，由不同的人在本地撰写、训练，完成之后统一倒入到真实环境的知识库里面。

分段详情里面可以关联问题，可能会设置很多关联问题。

如果不支持导入导出知识库，那么我们在本地设置的关联问题，在真实环境需要重新设置，就非常麻烦。

### 请描述你建议的实现方案

支持导出/导入知识库

**Comment by baixin513** [comment]
感谢反馈，当前还不支持知识库导入导出。后期版本可以迭代。
但当前是支持团队协作的。方案如下：
1.由一个负责人的账号统一创建所有知识库和应用；
2.添加成员，分配授权成员各自对应模块的知识库权限；
3.成员登陆后可以看到授权的知识库，可以正常添加知识库内容。

**Comment by ChishFoxcat** [comment]
同样，我也需要此需求。比如，我从Web站点创建的知识库，但是此站点的格式不够严谨，导入后段落混乱命中率低，修改后怕数据丢失
我的想法是，导出其知识库，导入依然是Web站点，并且外围文档编辑器也能正常查看

**Comment by baixin513** [comment]
近期版本会 支持知识库导出。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
