### ISSUE TITLE
[Feature] Users create a front-end question page, similar to kimi's homepage. They hope that after asking questions in the search box and clicking the question button, they can jump to the Maxkb application and put the information in the search box Take it 

### ISSUE THREAD

**Issue by yaoyi111** [1Panel-dev/MaxKB#1893]
### MaxKB Version

1.8.1

### Please describe your needs or suggestions for improvements

用户自己制作一个前端提问页面，类似kimi的首页，希望在搜索框中提问后点提问按钮，能跳转到Maxkb的应用里，并把搜索框中的信息带过去，目前无法把问题信息带过去。

### Please describe the solution you suggest

![image](https://github.com/user-attachments/assets/4b8a5fa3-a7c6-489c-9e4d-5b63ddae6bf3)
例如kimi首页，在搜索框中提交问题，点击提问按钮可以把问题信息带入到回答列表中。
![image](https://github.com/user-attachments/assets/ccb12881-8199-4b42-b0a0-5c7d4d954fa1)
希望能提供这方面的能力

**Comment by baixin513** [comment]
感谢反馈，自己开发的前端问答页面，可以通过应用API Key的方式进行对话， 我们支持标准的OpenAI调用格式。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback, the front-end Q&A page developed by ourselves can be used for dialogue by applying API Key. We support the standard OpenAI calling format.
