### ISSUE TITLE
[Feature] Only users who want to pass CAS authentication and are in the system user list can log in to the backend.

### ISSUE THREAD

**Issue by yaoyi111** [1Panel-dev/MaxKB#1894]
### MaxKB Version

1.8.1

### Please describe your needs or suggestions for improvements

希望CAS认证通过的且在系统用户列表中的用户，或admin，才可登录后台。
比如我的用户名是test在用户列表中，就可以允许进系统后台，其他的用户即使CAS认证通过了，但不在用户列表中，就不允许登录后台

**Comment by baixin513** [comment]
感谢反馈，暂无该计划，其他不需要的用户可以在用户管理中禁用或删除。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback. There is no plan for this yet. Other unnecessary users can be disabled or deleted in user management.
