### ISSUE TITLE
[Feature] Visual chart

### ISSUE THREAD

**Issue by Readyou123** [1Panel-dev/MaxKB#1897]
### MaxKB Version

1.8.0

### Please describe your needs or suggestions for improvements

能否实现输入数据，利用python的一些画图的库输出可视化的图表，现在只能生成代码，无法转化为图表

**Comment by liqiang-fit2cloud** [comment]
能吧，但你要自己研究。
参考https://www.zhihu.com/zvideo/1834282854537891840

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Yes, but you have to do your own research.
Reference https://www.zhihu.com/zvideo/1834282854537891840
