### ISSUE TITLE
[BUG] 测试配置kimi的模型API，失败

### ISSUE THREAD

**Issue by Liaoqinchao** [1Panel-dev/MaxKB#190]
### MaxKB 版本

版本号：v1.0.4 (build at 2024-04-19T16:59, commit: 7c001221)

### 问题描述

配置好kimi助手，配置好API APIkey 提示失败。没找到

### 重现步骤

直接配置kimi的API

### 相关日志输出

```shell
校验失败,请检查参数是否正确: Error code: 404 - {'code': 5, 'error': 'url.not_found', 'message': '没找到对象', 'method': 'POST', 'scode': '0x5', 'status': False, 'ua': 'OpenAI/Python 1.23.1', 'url': '/chat/completions'}
```

**Comment by shaohuzhang1** [comment]
kimi的api域名为https://api.moonshot.cn/v1,是否是api域名未配置正确

**Comment by Liaoqinchao** [comment]
已解决。确实是这个问题，刚测试到。看KIMI官网具体接口文档才排查出来
