### ISSUE TITLE
[Bug] qwen2.5-7b-instruct model does not exist in Ollama

### ISSUE THREAD

**Issue by liudonghua123** [1Panel-dev/MaxKB#1902]
### Contact Information

thiscloud123

### MaxKB Version

v1.8.1 (build at 2024-12-12T09:57, commit: 16ecccbd)

### Problem Description

I want to add qwen2.5 modes, but it failed with `qwen2.5-7b-instruct 模型在Ollama不存在`

### Steps to Reproduce

1. add qwen2.5 modes like phi3 or llama3:8b.

### The expected correct result

The modes add successfully .

### Related log output

`docker compose logs -f` doesn't show any logs related to this operation. 

Here is the ollama modes list:

```
[root@ha-master-1 maxkb]# ollama list
NAME                              ID              SIZE      MODIFIED           
qwen2.5:7b                        845dbda0ea48    4.7 GB    5 seconds ago         
qwen2.5:7b-instruct               845dbda0ea48    4.7 GB    13 seconds ago        
llama3.2:latest                   a80c4f17acd5    2.0 GB    About a minute ago    
llama3:8b                         365c0bd3c000    4.7 GB    About a minute ago    
phi3:latest                       4f2222927938    2.2 GB    4 minutes ago         
mixtral:latest                    d39eb76ed9c5    26 GB     2 weeks ago           
llama3.2-vision:latest            38107a0cd119    7.9 GB    2 weeks ago           
nomic-embed-text:latest           0a109f422b47    274 MB    2 weeks ago           
mistral:latest                    f974a74358d6    4.1 GB    2 weeks ago           
llava:latest                      8dd30f6b0cb1    4.7 GB    2 weeks ago           
shaw/dmeta-embedding-zh:latest    55960d8a3a42    408 MB    2 months ago          
qwen2.5:1.5b                      65ec06548149    986 MB    2 months ago          
qwen2.5:0.5b                      a8b0c5157701    397 MB    2 months ago          
codegemma:latest                  0c96700aaada    5.0 GB    2 months ago          
phi3.5:latest                     61819fb370a3    2.2 GB    2 months ago          
qwen2.5:latest                    845dbda0ea48    4.7 GB    2 months ago          
gemma2:latest                     ff02c3702f32    5.4 GB    2 months ago          
[root@ha-master-1 maxkb]#
```

### Additional Information

Maybe the name is incorrect, change `qwen2.5-7b-instruct` to `qwen2.5:7b-instruct` or `qwen2.5:7b`?

![image](https://github.com/user-attachments/assets/0d7bd131-fb6e-488c-9543-151112de0af4)

**Comment by baixin513** [comment]
感谢反馈，模型名称需要与ollama list 列出的模型名称保持一致才可以添加成功，如：qwen2.5:7b-instruct

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback. The model name needs to be consistent with the model name listed in ollama list before it can be added successfully, such as: qwen2.5:7b-instruct

**Comment by liudonghua123** [comment]
The mode name is hardcoded as select items, I also update the custom mode name as `qwen2.5:7b-instruct` in the first text field, but it didn't help, maybe need to update the following code.

https://github.com/1Panel-dev/MaxKB/blob/ae7c446e811d0085c0fca757e64c28f786e321ef/apps/setting/models_provider/impl/ollama_model_provider/ollama_model_provider.py#L104-L131

![image](https://github.com/user-attachments/assets/15e035e9-48a5-425e-8ceb-8c182dce5d15)

**Comment by liudonghua123** [comment]
I tried update the above code (vim %s/qwen2.5-/qwen2.5:/g) and restart the container, the name of select items updated and it's ok now.

![image](https://github.com/user-attachments/assets/16b20fa5-b788-4b6e-9f24-6467e02e4a20)

![image](https://github.com/user-attachments/assets/94dd88e2-b93b-4845-96d4-24745a0302b8)

**Comment by baixin513** [comment]
如果基础下拉列表中的模型名称与你的ollama list 列出的名称不一致，你可以在基础模型中自定义输入ollama list 列出的模型名称，然后回车即可以 添加成功。
无需修改代码。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
If the model name in the basic drop-down list is inconsistent with the name listed in your ollama list, you can customize the model name listed in the ollama list in the basic model and press Enter to add it successfully.
No need to modify the code.
