### ISSUE TITLE
[Feature] Is it possible to consider not limiting the type of knowledge base, enable web and file knowledge bases to complement each other?

### ISSUE THREAD

**Issue by linfengjjj** [1Panel-dev/MaxKB#1903]
### MaxKB Version

v1.8.1

### Please describe your needs or suggestions for improvements

客户需要web站点的内容，但是web站点的内容又不太够，需要在该知识库中通过文件继续补充内容，后续是否考虑规划呢。

**Comment by baixin513** [comment]
感谢反馈，不同类型的知识库处理机制不同，web站点的知识库内容不足，你可以在通用知识库上传离线文档。 如果想在一个知识库管理，把文档迁移过去就可以了。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback. Different types of knowledge bases have different processing mechanisms. The knowledge base content of the web site is insufficient. You can upload offline documents in the general knowledge base. If you want to manage it in a knowledge base, just migrate the documents there.

**Comment by linfengjjj** [comment]
Thanks, i got it.
