### ISSUE TITLE
[FEATURE] 【应用】提示词支持获取时间的变量

### ISSUE THREAD

**Issue by rty813** [1Panel-dev/MaxKB#191]
### MaxKB 版本

v1.0.4 (build at 2024-04-19T16:59, commit: 7c001221)

### 请描述您的需求或者改进建议

希望web知识库支持定时同步功能。例如每天上午九点更新。

### 请描述你建议的实现方案

无

**Comment by baixin513** [comment]
感谢反馈，同步会先删除文档再重新获取，若分段维护了关联问题同步时会取消关联关系，操作需要谨慎，不建议开定时任务同步。

**Comment by rty813** [comment]
> 感谢反馈，同步会先删除文档再重新获取，若分段维护了关联问题同步时会取消关联关系，操作需要谨慎，不建议开定时任务同步。

我有个需求是需要让应用知道当前时间，所以就用知识库添加了一个获取时间API。但如果不能自动同步，这个就没有作用了。或者可以仿照dify的“添加工具”功能：
![image](https://github.com/1Panel-dev/MaxKB/assets/22488813/a1572e56-1df0-45bf-a1d7-19c3afcb8330)

**Comment by baixin513** [comment]
如果是需要让应用知道当前时间，那这个需求应该是在提示词中加个获取时间的变量就能解决吧。

**Comment by rty813** [comment]
> 如果是需要让应用知道当前时间，那这个需求应该是在提示词中加个获取时间的变量就能解决吧。

是的，这样也可以。
