### ISSUE TITLE
[Bug] After re-entering the conversation, the table is no longer displayed.

### ISSUE THREAD

**Issue by 2722183335** [1Panel-dev/MaxKB#1916]

**Comment by 2722183335** [comment]
解决了

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
solved
