### ISSUE TITLE
[Feature] Google gemini API address customization

### ISSUE THREAD

**Issue by sky121666** [1Panel-dev/MaxKB#1936]
### MaxKB Version

 v1.8.1

### Please describe your needs or suggestions for improvements

gemini无法国内无法直接访问，需要自定义API地址

**Comment by baixin513** [comment]
感谢反馈，您可以通过添加OpenAI供应商来对接自定义API地址的Gemini模型

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback, you can connect the Gemini model with a custom API address by adding an OpenAI provider.
