### ISSUE TITLE
需要在线更新功能

### ISSUE THREAD

**Issue by 496672097** [1Panel-dev/MaxKB#194]
### MaxKB 版本

1.1

### 请描述您的需求或者改进建议

docker快速开始的， 但是整个系统更新很快。对于整个项目是优点。但是对于docker用户就比较麻烦了。 希望增加在线更新功能。

**Comment by rty813** [comment]
用watchtower

**Comment by baixin513** [comment]
感谢反馈，你可以执行命令更新：docker pull 1panel/maxkb
然后执行一下快速启动命令：docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb
