### ISSUE TITLE
调用对话接口时候报错“application-11b1f030bb3ef891b896edf9d8a51124” is not a valid UUID.'[BUG]

### ISSUE THREAD

**Issue by osgochina** [1Panel-dev/MaxKB#198]
### MaxKB 版本

v1.0.3

### 问题描述

通过`api/api/application/8dbc4680-fd2e-11ee-bd77-0242ac110002/chat/open`根据应用id获取会话id,得到会话id,
再调用`/api/application/chat_message/73fe5630-005c-11ef-8f99-0242ac110002`会话接口,报错
```
{
  "code": 500,
  "message": "['“application-11b1f030bb3ef891b896edf9d8a51124” is not a valid UUID.']",
  "data": null
}
```

### 重现步骤

通过`api/api/application/8dbc4680-fd2e-11ee-bd77-0242ac110002/chat/open`根据应用id获取会话id,得到会话id,
再调用`/api/application/chat_message/73fe5630-005c-11ef-8f99-0242ac110002`会话接口,报错
```
{
  "code": 500,
  "message": "['“application-11b1f030bb3ef891b896edf9d8a51124” is not a valid UUID.']",
  "data": null
}
```

**Comment by baixin513** [comment]
感谢反馈，这个确认是 bug，与#192 重复，后期版本会修复，改 issue 先关闭了，可以在#192 中跟进进度。
