### ISSUE TITLE
[FEATURE] 可以支持 cloudflare ai 吗？ 或者开放模型自定义配置?

### ISSUE THREAD

**Issue by 34892002** [1Panel-dev/MaxKB#199]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

cloudflare推出了ai gateway 和 Workers AI 支持很多开源模型。希望可以支持接入或者开放模型自定义配置
https://developers.cloudflare.com/ai-gateway/
https://developers.cloudflare.com/workers-ai/

**Comment by baixin513** [comment]
感谢反馈，近期暂无计划支持。

**Comment by jhyvictory** [comment]
希望尽快支持
