### ISSUE TITLE
[BUG]添加智谱AI报错

### ISSUE THREAD

**Issue by gxf5784828** [1Panel-dev/MaxKB#202]
### 联系方式

916388061@qq.com

### MaxKB 版本

v1.0.4

### 问题描述

<img width="976" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/38247991/82b18b9c-42d3-4097-9018-0e648c2d1f40">
添加智谱AI报错

### 重现步骤

添加智谱AI报错

**Comment by baixin513** [comment]
感谢反馈，该错误是认证错误，检查一下 Key 是否有前后空格，在智谱控制台中是否还存在？
<img width="1420" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/d265565c-b7d2-48d4-b26f-99b8cb311ded">

**Comment by gxf5784828** [comment]
都无空格，且在智谱控制台中存在，直接复制过来的，用代码直接调用是正常的~

**Comment by baixin513** [comment]
我们测试了多个智谱 AI 的账号均能正常添加模型和对话。

建议重建创建个 API Key。若还是不行，请截个使用智谱 API Key的页面。

**Comment by gxf5784828** [comment]
fa7e2df857132c685465abaec766659b.S8GJCdsEjkhRu923
给你们测试下，
<img width="1888" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/38247991/bf960b24-2156-4dfb-b85c-fc16d665723a">
代码是正常的

**Comment by gxf5784828** [comment]
<img width="1883" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/38247991/2d151ece-cb08-40c0-9c9a-75d8cc4de1f8">

**Comment by baixin513** [comment]
> fa7e2df857132c685465abaec766659b.S8GJCdsEjkhRu923

这个 key 可以添加模型成功哦，亲，你这边是不是二开了？
<img width="1302" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/f22dab4e-0dd9-45a0-91a5-e7a831578d91">

**Comment by baixin513** [comment]
亲，为了安全性，你先把这个 key 在智谱 AI 控制台删除一下吧。
然后确认一下部署的服务器是否为 ARM 架构的 ？

**Comment by gxf5784828** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/38247991/9fb4a3cb-1cf3-4521-9664-15fd09a97c93)
好的已删除。

**Comment by baixin513** [comment]
如果可以重新部署一下或者换个机器部署一下，应该是你那边环境或网络问题。Key是没问题。

**Comment by baixin513** [comment]
该 issue 先关闭了。

**Comment by gxf5784828** [comment]
好的，这块我查到问题了，是因为服务器时间比正常的慢5分钟
