### ISSUE TITLE
[FEATURE]【对话窗口】增加历史对话记录

### ISSUE THREAD

**Issue by Readyou123** [1Panel-dev/MaxKB#206]
### MaxKB 版本

v1.0.4

### 请描述您的需求或者改进建议

是否可以支持显示历史对话记录

### 请描述你建议的实现方案

在演示界面增加一个列表，用于显示历史对话记录

**Comment by baixin513** [comment]
感谢反馈，该需求在后面版本排期开发。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
