### ISSUE TITLE
[FEATURE]第一次调用的时候总感觉有些慢

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/MaxKB#208]
### MaxKB 版本

1.0.3

### 请描述您的需求或者改进建议

第一次ollama对话总是感觉有些慢，请问如何优化，让模型常驻后台？ 

### 请描述你建议的实现方案

增加一个模型的预加载，方便用户对话

**Comment by baixin513** [comment]
第一次是哪里慢？ 一般 Ollama 的模型快慢与机器配置有关系，CPU 的会慢一些，GPU 的会快。

**Comment by xaswq** [comment]
是GPU机器，第一次似乎都有个启动时间
