### ISSUE TITLE
[BUG]回答里带链接，包含#时#会被删除

### ISSUE THREAD

**Issue by zxr3680166** [1Panel-dev/MaxKB#209]
### MaxKB 版本

 1.0.3

### 问题描述

https://hrsspub.sz.gov.cn/rcyth/website//detail/sgpx0001?mode=1

链接里的#被删除

### 重现步骤

<img width="563" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/4338858/e400e2b5-fa78-4539-8759-b835da55aa22">

**Comment by baixin513** [comment]
感谢反馈，回答的内容都是大模型返回的。经常会不返回链接或者返回错误的链接，这个MaxKB控制不住。

**Comment by KunBuFenZi** [comment]
不，链接是知识库文档提供的，尝试了所有大模型，和文档里大部分链接发现，不含#都正常，含#的，#会消失，但是直接用官方api，不走maxkb时，不会出现此问题

**Comment by KunBuFenZi** [comment]
> 感谢反馈，回答的内容都是大模型返回的。经常会不返回链接或者返回错误的链接，这个MaxKB控制不住。

不，链接是知识库文档提供的，尝试了所有大模型，和文档里大部分链接发现，不含#都正常，含#的，#会消失，但是直接用官方api，不走maxkb时，不会出现此问题
