### ISSUE TITLE
[FEATURE]可以自定义小助手图标

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#212]
### MaxKB 版本

 1.0.0

### 请描述您的需求或者改进建议

可以自定义如图所示小助手图标头像
<img width="606" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/40552640/15d12128-248d-4ace-bdf8-4d65a3fdc039">

**Comment by baixin513** [comment]
感谢反馈，暂时没有该计划。
