### ISSUE TITLE
[FEATURE]能否新增接入讯飞星火及智谱API

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/MaxKB#213]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

目前支持Kimi和通义千问，很方便，希望支持更多国产大模型的API

### 请描述你建议的实现方案

新增接入

### 附加信息

求交流群

**Comment by baixin513** [comment]
感谢反馈，智谱 AI 和讯飞星火在 v 1.0.4 版本支持, 请更新至最新版本。

**Comment by xaswq** [comment]
给力，感谢！
