### ISSUE TITLE
[FEATURE]【应用编排】增加多模型分流

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/MaxKB#214]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

后续能否设置为配置多个模型API，设置优先级，当前面的API挂了，额度不够的时候切换到后续的API，并且最好能保持最近的几次会话

**Comment by baixin513** [comment]
感谢反馈，该需求需要在后期开发应用编排时会考虑兼容一下。

**Comment by baixin513** [comment]
可以升级到最新版本v1.8.0，添加多个版本试用一下
