### ISSUE TITLE
[FEATURE]请问星火API如何接入？

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/MaxKB#215]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/MaxKB/assets/85377380/0a5e51c2-f831-4e11-b18d-e06ca4303e54)

API域名这里写什么呢？
wss://spark-api.xf-yun.com/v3.5/chat
试了不行

**Comment by baixin513** [comment]
感谢反馈，可以参考一下文档，不同的模型 API 域名不同，主要还需要保证应用有使用的 tokens，否则会添加失败。
https://github.com/1Panel-dev/MaxKB/wiki/2.3-%E6%A8%A1%E5%9E%8B%E7%AE%A1%E7%90%86#235-%E6%B7%BB%E5%8A%A0%E8%AE%AF%E9%A3%9E%E6%98%9F%E7%81%AB%E5%A4%A7%E6%A8%A1%E5%9E%8B

**Comment by xaswq** [comment]
谢谢！解决了，是顺序问题，建议和星火控制台的几个参数顺序保持一致 @baixin513 

![image](https://github.com/1Panel-dev/MaxKB/assets/85377380/fd907687-c53d-4997-ba54-e36a9a7c12dd)


![image](https://github.com/1Panel-dev/MaxKB/assets/85377380/9fb67189-d151-49b6-8d0f-c8133958877b)
