### ISSUE TITLE
[BUG]内存占用太大，占到50%以上

### ISSUE THREAD

**Issue by cnliucheng** [1Panel-dev/MaxKB#216]
### MaxKB 版本

1.0.4

### 问题描述

4G内存的vps运行maxkb以后，内存占用超过了50%

### 重现步骤

无

### 期待的正确结果

降低内存占用率

### 附加信息

![screenshot-192 3 148 197_1030-2024 04 23-11_22_56](https://github.com/1Panel-dev/MaxKB/assets/32115849/e91c30af-6fc2-4de6-8857-fd12b19979d3)

**Comment by baixin513** [comment]
感谢反馈，运行 MaxKB 需要的配置要求是 2c4GB 。

**Comment by AlanWang2333** [comment]
> ### 联系方式
> _No response_
> 
> ### MaxKB 版本
> 1.0.4
> 
> ### 问题描述
> 4G内存的vps运行maxkb以后，内存占用超过了50%
> 
> ### 重现步骤
> 无
> 
> ### 期待的正确结果
> 降低内存占用率
> 
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> ![screenshot-192 3 148 197_1030-2024 04 23-11_22_56](https://private-user-images.githubusercontent.com/32115849/324676338-e91c30af-6fc2-4de6-8857-fd12b19979d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzExODIsIm5iZiI6MTcxNTQzMDg4MiwicGF0aCI6Ii8zMjExNTg0OS8zMjQ2NzYzMzgtZTkxYzMwYWYtNmZjMi00ZGU2LTg4NTctZmQxMmIxOTk3OWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEyMzQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZDk5N2NlM2QwN2JhNzQ3OWMxZGVhMmE3MzFkNWM1NjJlNDQ3OTdkODI1ZDdkYmRkNzM2MDZlNTJiMzIzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Knusrn2PbK9PasTl2Fawd0-NPeFHs_9EBFc3gi5w1yY)

大佬，请问你的fastgpt是怎么装上去的，我想把他的整个compose里面的几个容器拆开，用1panel的软件代替，这样比较好看
