### ISSUE TITLE
[BUG] 启动后的白屏问题

### ISSUE THREAD

**Issue by hao-joey-zhang** [1Panel-dev/MaxKB#219]
### MaxKB 版本

1.0.4

### 问题描述

自己在本地用docker build, 服务启动并且登陆后, 会遇到白屏, 页面无法正常加载, 在URL点击刷新后正常. 跳转到其他页面也发生同样的问题. 必须刷新否则会白屏.

一键启动版本没有问题, 只有本地docker build 出问题.

![image](https://github.com/1Panel-dev/MaxKB/assets/9167244/9214eaeb-0191-492c-a69e-0e483f6b17d9)

### 重现步骤

1. 下载最新代码, 或者前一个版本, 或者 1.0.4 release
2. 打开代码, 将 install 中的 dockerfile 放在 root.
3. docker build . -t xxx
4. docker run -d --name=maxkb -p 8080:8080 -e OLLAMA_PROXY_URL=http://host.docker.internal:11434/v1 -v ~/.maxkb:/var/lib/postgresql/data xxx

**Comment by baixin513** [comment]
感谢反馈，请切换到v 1.0.4 tag , main分支 是当前开发分支，开发过程中会存在一些问题。

**Comment by baixin513** [comment]
F12 检查一下前端排查一下，前端应该报错了。
