### ISSUE TITLE
类opanai api[FEATURE]

### ISSUE THREAD

**Issue by samcaicn** [1Panel-dev/MaxKB#220]
### MaxKB 版本

1.0

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/MaxKB/assets/3318094/743a80cc-7114-4c82-8199-20b61d63534a)
类opanai api

**Comment by samcaicn** [comment]
https://github.com/infiniflow/ragflow/blob/main/docs/conversation_api.md
学习下这个

**Comment by shaohuzhang1** [comment]
目前我们的apikey使用方式也是这样的,
先获取一个chat_id,然后使用chat_id进行对话和先获取conversation_id在用conversation_id进行对话如出一辙

**Comment by pearl6217** [comment]
api怎么用的啊？也没找到文档

**Comment by shaohuzhang1** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/80892890/361ce024-63cc-4cf4-90f7-0fb4878e9723)
接口文档地址

**Comment by pearl6217** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/54811246/7482ada9-905b-4659-a395-6b3e91a73cd3)打不开主要是

**Comment by shaohuzhang1** [comment]
如果是本地开发的话,需要访问8080/doc

**Comment by pearl6217** [comment]
可以了，感谢感谢！！！
