### ISSUE TITLE
[FEATURE]如何和mivlus，chroma等向量数据库集成

### ISSUE THREAD

**Issue by lonerranger** [1Panel-dev/MaxKB#221]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

如何和mivlus，chroma等向量数据库集成

### 请描述你建议的实现方案

如何和mivlus，chroma等向量数据库集成

**Comment by shaohuzhang1** [comment]
需要二开才可以

**Comment by maninhill** [comment]
我们目前使用 [PostgreSQL / pgvector](https://www.postgresql.org/)，暂无计划支持其他向量数据库。
