### ISSUE TITLE
无法建立新用户

### ISSUE THREAD

**Issue by binxushy** [1Panel-dev/MaxKB#222]
### MaxKB 版本

1.0.4

### 问题描述

无论我输入什么用户名，都提示用户不符合规则.提示信息截屏时候消失。
提示信息： 密码长度6-20个字符，必须字母、数字、特殊字符组合
![image](https://github.com/1Panel-dev/MaxKB/assets/92415464/8bfaddfa-0a83-41c3-b3d0-f56db2f65afd)

### 重现步骤

可以重现

### 期待的正确结果

能正常建立用户

**Comment by binxushy** [comment]
my connect email: bxu006@sina.com

**Comment by shaohuzhang1** [comment]
密码必须要组合比如 zhangshaohu@1 zhangshaohu..1 需要特殊字符,大写字母,小写字母,数字 任意三种组合

**Comment by binxushy** [comment]
还是不行，譬如我用的下面的密码还是出错
Njust#608

**Comment by binxushy** [comment]
你好：
        谢谢及时回复，但：还是不行，譬如我用的下面的密码还是出错,总是提示用户名不对，用户名我用llm_user01, llmuser密码用Njust#608都不对
RegardsXuBin----- 原始邮件 -----发件人：shaohuzhang1 ***@***.***>
收件人：1Panel-dev/MaxKB ***@***.***>
抄送人：binxushy ***@***.***>,  Author ***@***.***>
主题：Re:_[1Panel-dev/MaxKB]_无法建立新用户_(Issue_#222)
日期：2024年04月23日 17点37分


密码必须要组合比如 ***@***.*** zhangshaohu..1 需要特殊字符,大写字母,小写字母,数字 任意三种组合

**Comment by binxushy** [comment]
用户名和密码有不同的要求。用户名只能是字符，密码要三种结合。已经解决
