### ISSUE TITLE
[FEATURE] 添加llama模型报错“api域名无效”

### ISSUE THREAD

**Issue by evilvlso** [1Panel-dev/MaxKB#227]
### MaxKB 版本

latest

### 请描述您的需求或者改进建议

添加llama模型报错“api域名无效”（如图1）
环境：
macos intel
maxkb docker启动
llama 本地启动
已检查：
1. llama服务正常，如图2，3
2. maxkb容器能ping主机ip是通的，如图4
3. 测试api地址+v1 ，问题依旧

麻烦指点下是啥问题
-------
<img width="717" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/25767862/89e2b9e9-efa9-4092-bad6-e8305809fd42">
<img width="411" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/25767862/00991cdf-f6ba-4214-af85-a8fd8537a378">
<img width="843" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/25767862/aa414f63-f4bc-4926-90d6-b9113d0e25b5">
<img width="564" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/25767862/9a8e84a7-d9df-436f-a18e-a7a9cb968a98">

**Comment by baixin513** [comment]
感谢反馈，要进入 maxkb容器中，执行 curl http://192.168.0.101:11434

**Comment by evilvlso** [comment]
感谢回复！
1. 检查了maxkb容器网络，由于设置了http_proxy导致无法curl，已解决网络问题
2. 但maxkb容器内curl正常后依旧报错“API域名无效”，如图1,2,3
<img width="453" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/25767862/a0f147c7-74c6-4955-9ec4-04cd24f8b581">
<img width="716" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/25767862/6d85139d-67b9-4227-b27d-87a3154fd4de">
<img width="1099" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/25767862/07d618fd-37d1-487c-afa4-8a0e70fe7b24">

感谢指点！

**Comment by baixin513** [comment]
确认一下安装的MaxKB的版本，在右上角 用户-关于中可以看到版本号。

0.9.0 版本的 API 域名后面需要加上 /v1
后面版本不需要。

**Comment by evilvlso** [comment]
感谢再次回复！
虽然添加/v1 问题依旧，但是通过重新docker pull最新镜像现在可以了
多谢！可以关闭了

**Comment by zmalibaba** [comment]
如果你想调用本地的ollama 中的大模型，域名aip试试：http://host.docker.internal:11434
我的是这样成功的。

**Comment by Kybin-x** [comment]
> 如果你想调用本地的ollama 中的大模型，域名aip试试：http://host.docker.internal:11434 我的是这样成功的。

感谢！

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> If you want to call the large model in local ollama, try the domain name aip: http://host.docker.internal:11434 This is how I succeeded.

grateful!
