### ISSUE TITLE
[FEATURE]增加命中缓存数据库

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#228]
### MaxKB 版本

1.0.0

### 请描述您的需求或者改进建议

 可以增加命中缓存数据库，每次请求完大模型后返回的数据存到一个缓存数据库中，当拼接后的数据向量值等于或者近似等于之前请求过的数据时，不请求大模型，直接返回结果；
可以限制容量，经常命中的排序最高，容量满了之后新的请求替换排序最低的结果；
可以为企业极大程度的节约成本。

**Comment by baixin513** [comment]
感谢反馈，后期会支持文档设置不走模型优化，一些比较精准的可以设置成直接返回。
该需求与issue #56 重复，预计下个功能版本支持。
