### ISSUE TITLE
[FEATURE]对话内容可以批量存储到问题库及知识库

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#229]
### MaxKB 版本

 1.0.0

### 请描述您的需求或者改进建议

可以批量存储对话内容，方便录入信息

### 请描述你建议的实现方案

具体实现上可能需要好好想想

**Comment by baixin513** [comment]
感谢反馈，我们考虑一下

**Comment by tieren168** [comment]
例如将微信聊天记录导入进去,就可以实现分析用户关系,喜好等功能

**Comment by baixin513** [comment]
v1.8.0 已发布！
