### ISSUE TITLE
[FEATURE]能否建个交流群

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/MaxKB#230]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

作为1panel首批赞助用户，很需要一个及时交流群

**Comment by baixin513** [comment]
感谢反馈，后面考虑一下。

**Comment by baixin513** [comment]
主打听劝，已建群。
![image](https://github.com/1Panel-dev/MaxKB/assets/52996290/8b3c5fe2-8294-42da-84ba-235046596f72)

**Comment by xaswq** [comment]
已进群，给力！
