### ISSUE TITLE
https://github.com/infiniflow/ragflow/blob/main/docs/conversation_api.md

### ISSUE THREAD

**Issue by samcaicn** [1Panel-dev/MaxKB#232]
https://demo.ragflow.io/v1这个可以直接做为baseurl访问，但是基于maxkb的 https://site.maxkb.com/v1
加上key无法正常请求

             https://github.com/infiniflow/ragflow/blob/main/docs/conversation_api.md
学习下这个

_Originally posted by @samcaicn in https://github.com/1Panel-dev/MaxKB/issues/220#issuecomment-2071558446_

**Comment by baixin513** [comment]
你好，该问题在 #220 中回答。
