### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by samcaicn** [1Panel-dev/MaxKB#233]
### MaxKB 版本

1.0

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/MaxKB/assets/3318094/513004de-0031-438f-8e11-ca8622fc112d)
![image](https://github.com/1Panel-dev/MaxKB/assets/3318094/9818ebc7-ac02-4789-9aa7-f22edebc7275)
具体怎么拼接蕾丝openai的请求地址呢？这样嘛？https://mp.nbee.cn/api/v1/8d6f0b36ce0a8ae7

### 请描述你建议的实现方案

https://mp.nbee.cn/api/v1/8d6f0b36ce0a8ae7
key：application-8e3a2b4b5a64fa

**Comment by samcaicn** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/3318094/f492c44b-e40b-45ee-8276-67075a75feff)
怎么添加为oneapi的一个类似openai请求渠道呢？

**Comment by baixin513** [comment]
感谢反馈，您这不是我们的产品，建议咨询 oneapi  产品。
