### ISSUE TITLE
[FEATURE]怎么拼接类似openai的请求地址呢？兼容openai

### ISSUE THREAD

**Issue by samcaicn** [1Panel-dev/MaxKB#235]
### MaxKB 版本

1.0

### 请描述您的需求或者改进建议

MaxKB 版本
1.0

请描述您的需求或者改进建议
image
image
具体怎么拼接蕾丝openai的请求地址呢？这样嘛？https://mp.nbee.cn/api/v1/8d6f0b36ce0a8ae7

请描述你建议的实现方案
https://mp.nbee.cn/api/v1/8d6f0b36ce0a8ae7
key：application-8e3a2b4b5a64fa

**Comment by baixin513** [comment]
当前机制暂不支持。
