### ISSUE TITLE
[FEATURE]希望开场白能增加会话选项。譬如[1]售后咨询,[2]投诉,[3]产品建议

### ISSUE THREAD

**Issue by learnin9** [1Panel-dev/MaxKB#236]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

1：目前用户进来后，不知道该问什么，所以希望能增加一个会话选项
2：可以根据用户选择项，再根据精准问题进行精准的知识库回答

**Comment by baixin513** [comment]
感谢反馈，需求挺好的，我们后面考虑一下实现方案。

**Comment by baixin513** [comment]
哦哦，你是说的快捷问题呢？
我想成了按照类别指定召回的知识库

**Comment by baixin513** [comment]
如果可以满足了，该需求就先关闭了？
