### ISSUE TITLE
[BUG] maxkb创建好了，但是访问失败，postgresql启动不了

### ISSUE THREAD

**Issue by asd2333** [1Panel-dev/MaxKB#240]
### 联系方式

1637603030@qq.com

### MaxKB 版本

1.0.4

### 问题描述

maxkb创建好了，但是访问失败

环境是deepin 
docker安装相关的软件
![image](https://github.com/1Panel-dev/MaxKB/assets/20329012/4dd4fdb0-7179-46f3-9daa-4244fec95c56)
配置
![截图_选择区域_20240424151410](https://github.com/1Panel-dev/MaxKB/assets/20329012/ae90d6b1-48df-4152-940c-e799b79edcf4)
访问页
![截图_选择区域_20240424151359](https://github.com/1Panel-dev/MaxKB/assets/20329012/ffd809df-a2a9-4c31-aa1a-a45d9c69d3fe)

### 重现步骤

创建完成就没有

**Comment by baixin513** [comment]
感谢反馈，地址不对，需要在 1panel 中设置以下服务器 IP 地址， 然后在访问 maxkb。

**Comment by asd2333** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/20329012/fd3cb847-428b-46db-aef4-37af81d0987b)
已经添加了

**Comment by asd2333** [comment]
> Contributor

![image](https://github.com/1Panel-dev/MaxKB/assets/20329012/b87202ce-e35d-41df-8c4a-6a27015fc503)
已经添加

**Comment by asd2333** [comment]
> 感谢反馈，地址不对，需要在 1panel 中设置以下服务器 IP 地址， 然后在访问 maxkb。

![截图_选择区域_20240424152807](https://github.com/1Panel-dev/MaxKB/assets/20329012/12b34734-b548-4f5e-af49-286a2d7c6f41)
已经添加

**Comment by baixin513** [comment]
您在命令行输入: ip addr ，查到服务器的 IP 地址后，把 上图1panel 中服务器地址改成  您通过 ip addr 查询到的 IP。

**Comment by asd2333** [comment]
> 查到服务器的 IP 地
是图片中的红色指向吗
![image](https://github.com/1Panel-dev/MaxKB/assets/20329012/80355db9-4847-401d-8bb7-1911a4fdf4fb)
这个是指向之后的页面请求
![image](https://github.com/1Panel-dev/MaxKB/assets/20329012/e4acfbcc-27f7-4ac5-a822-fbf19b8540db)

**Comment by asd2333** [comment]
已经添加过postsql 
![截图_选择区域_20240424162134](https://github.com/1Panel-dev/MaxKB/assets/20329012/59a226db-dafd-4ac4-842b-af6741675c4e)
为什么在maxkb 上还是存在这个5432 请求不到
![截图_选择区域_20240424162146](https://github.com/1Panel-dev/MaxKB/assets/20329012/9f2ad9dd-46f9-4748-b3e1-b16ab407eb02)

**Comment by baixin513** [comment]
看一下 issue  #46 的解决方案

**Comment by baixin513** [comment]
如果没有问题，该 issue 先关闭了。

**Comment by yuebanfeiyu** [comment]
这个我也复现了

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I've reappeared this too
