### ISSUE TITLE
[BUG]多轮对话中没办法上下文理解

### ISSUE THREAD

**Issue by li-silin** [1Panel-dev/MaxKB#242]
### MaxKB 版本

v1.0.4

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/100558350/014d0128-b4bf-4808-a0c2-025f4d454e3f)

### 重现步骤

后台设置了1问题的答案，但AI 并不能根据选择的数字关联的问题进行回复。

**Comment by li-silin** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/100558350/694d43dc-c725-4360-950b-b2ae11759355)

**Comment by baixin513** [comment]
感谢反馈，问题要和内容有关系，AI才好回答，不是随便写个1，问题a, 模型也推理不出答案。
你可以拿真实的问答场景进行测试。
