### ISSUE TITLE
postgresql启动不了

### ISSUE THREAD

**Issue by zmm1996** [1Panel-dev/MaxKB#243]
### MaxKB 版本

最新

### 问题描述

wsl2 for windows11

![image](https://github.com/1Panel-dev/MaxKB/assets/40532959/a0a8524a-0337-42ec-88ed-94bcb1e45e39)

![image](https://github.com/1Panel-dev/MaxKB/assets/40532959/8bdd5d84-25a1-4b8e-bf2c-3c3f21df78bc)

### 重现步骤

docker run  -d --name=maxkb -p 8080:8080 -v ./psdata:/var/lib/postgresql/data --privileged=true  1panel/maxkb

### 相关日志输出
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ... 127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response

_No response_

**Comment by baixin513** [comment]
感谢反馈，PgSQL启动不了，请参考一下 issue #46 的解决方案

**Comment by zmm1996** [comment]
> 感谢反馈，PgSQL启动不了，请参考一下 issue #46 的解决方案

不适用当前报错，

改成了docker-compose

`version: '3.1'

services:
  maxkb:
    image: 1panel/maxkb
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - maxkb_data:/var/lib/postgresql/data


volumes:
  maxkb_data:
`

![image](https://github.com/1Panel-dev/MaxKB/assets/40532959/1df1c960-e4af-4fac-8319-588d413a3af4)

**Comment by baixin513** [comment]
compose文件在 image: 1panel/maxkb 下面加privileged: true

**Comment by limxc** [comment]
win11 wsl2下无效

**Comment by baixin513** [comment]
如果没有问题，该 issue 先关闭了

**Comment by ChaoII** [comment]
wsl2 下解决了吗？

**Comment by xinkeng0** [comment]
> wsl2 下解决了吗？

WSL2运行没问题，volume不要挂载windows主机的目录，挂载wsl里的。

**Comment by ldm457872020** [comment]
> win11 wsl2下无效

升级docker desktop

**Comment by EasongChung** [comment]
群辉安装遇到同样的问题，有解决办法么？

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I encountered the same problem during Qunhui installation. Is there any solution?

**Comment by liyujiang-gzu** [comment]
> privileged: true

加了没用

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> privileged: true

It's useless to add it

**Comment by liyujiang-gzu** [comment]
> > privileged: true
> 
> 加了没用

不挂载 /var/lib/postgresql/data 或者挂载到数据卷才能启动，挂载到目录不能启动：
#  - ./data:/var/lib/postgresql/data
  - postgres_data:/var/lib/postgresql/data

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > privileged: true
>
> It's useless to add it

Only by not mounting /var/lib/postgresql/data can it be started:
# - ./data:/var/lib/postgresql/data
