### ISSUE TITLE
请问如何在群晖上部署？[BUG]

### ISSUE THREAD

**Issue by jasonyun** [1Panel-dev/MaxKB#244]
### 联系方式

zhichaoyun@gmail.com

### MaxKB 版本

MaxKB最新版

### 问题描述

请问如何在群晖上部署？

### 重现步骤

请问如何在群晖上部署？

**Comment by baixin513** [comment]
有 docker 环境就能安装，如果没有 docker 环境，要先去装个 docker 环境。

**Comment by jasonyun** [comment]
有docker，但是通过地址:8080进不去！
