### ISSUE TITLE
[BUG]更新新版代码后消耗 tokens: 每次都是0了，旧版本没有这个问题

### ISSUE THREAD

**Issue by li-silin** [1Panel-dev/MaxKB#247]
### MaxKB 版本

最新版

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/100558350/cc633865-074d-4061-b43b-a93562130e21)

### 重现步骤

每次聊天，消耗 tokens: 都是0

**Comment by baixin513** [comment]
最新版本没发布呢， 最新版本支持不走模型，你的问题走模型了 ？ 没走模型tokens 就是 0
