### ISSUE TITLE
docker部署后，访问404

### ISSUE THREAD

**Issue by CurtainRight** [1Panel-dev/MaxKB#249]
### MaxKB 版本

v1.0.4 (build at 2024-04-19T16:59, commit: 7c001221)

### 问题描述

通过容器化部署，通过挂载config配置外部pg，同时只启动应用main.py。但是启动后访问404，后台无报错。

### 重现步骤

![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/a8a0a9b3-e7cf-41a6-9760-5e7dcbf960ce)
![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/6348f0a9-79c2-4d0c-9101-bdd3fd62e9b9)

### 期待的正确结果

如何正确访问

### 相关日志输出

```shell
![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/3369bf5f-4f8f-49a6-b119-6969ee9db3dd)
```

### 附加信息

![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/2e86a015-27b6-4629-8a4a-bdb2593213b2)

**Comment by CurtainRight** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/80de0174-77cf-4118-a3dc-b573d9709bc2)

**Comment by shaohuzhang1** [comment]
需要先执行 npm run build

**Comment by CurtainRight** [comment]
1. 不对啊，我看dockerfile中只启动了pg，main.py啊
![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/c758349a-439e-47b4-8631-128c9f937abf)
2. 而且我拉的镜像闷，还要啥npm，里面都有呢
![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/0ea3d72d-502f-43f8-a266-1c01e9edde74)

**Comment by shaohuzhang1** [comment]
dockerfile中web-build有执行吗

**Comment by CurtainRight** [comment]
官网的docker镜像呢。
![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/adec891d-7e6f-4c9e-b6c9-86b8b9e56c32)
启动镜像区别，就是用的自己外面的数据库，然后启动的main
![image](https://github.com/1Panel-dev/MaxKB/assets/32890541/9a67f38b-3ea5-47c0-b669-0bde94c04d4e)

**Comment by shaohuzhang1** [comment]
config 的配置 添加一个DEBUG: false

**Comment by CurtainRight** [comment]
就是这个配置。能够问下为什么吗，我看dockerfile CMD的时候，也没有指定啊

**Comment by shaohuzhang1** [comment]
项目的install/config.yaml 有指定
