### ISSUE TITLE
docker 容器嵌入机器人报 502

### ISSUE THREAD

**Issue by boqh** [1Panel-dev/MaxKB#253]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

本地启动了另一个docker容器，嵌入了机器人，但访问机器人报 502 ，2个容器在同一个网络下，访问地址是 容器名:8080

**Comment by shaohuzhang1** [comment]
容器名改为宿主机ip

**Comment by baixin513** [comment]
如果没有问题，该 issue 先关闭了
