### ISSUE TITLE
[FEATURE]知识库导入web数据,能否增加关键字过滤/替换/截取的选项/字数大小能否自定义缩小些

### ISSUE THREAD

**Issue by tieren168** [1Panel-dev/MaxKB#257]
### MaxKB 版本

v1.0.4

### 请描述您的需求或者改进建议

知识库导入web数据,能否增加关键字过滤/替换/截取的选项/
字数大小能否自定义缩小些

**Comment by baixin513** [comment]
高级分段试试，支持自定义分段长度

**Comment by tieren168** [comment]
增加一个模版数据导入,,可以用json或者csv等格式, 大家按模版的样式处理好数据导入进去.  
能导入最好也能导出,方便数据迁移或者快速修改数据.

**Comment by tieren168** [comment]
> web知识库需要设置选择器来过滤自己想要的内容。
> 过滤器支持设置多个。

你的意思是说,现在的版本可以通过选择器过滤吗? 能否详细说说如何过滤多个内容.谢谢

**Comment by baixin513** [comment]
支持设置选择器，如下图：
<img width="1070" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/ebeeb586-50a4-47fb-83a0-6f7fdd5ba266">
<img width="1068" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/e81da593-53dc-4b06-95ee-d66b26f91fef">


具体选择器的使用方式可以参考[菜鸟教程 css 选择器](https://www.runoob.com/cssref/css-selectors.html)。
