### ISSUE TITLE
[FEATURE]支持 Llama3

### ISSUE THREAD

**Issue by Avey777** [1Panel-dev/MaxKB#259]
### MaxKB 版本

1.0.1

### 请描述您的需求或者改进建议

希望支持Llama3

**Comment by baixin513** [comment]
感谢反馈，一直支持的。
<img width="605" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/edb34c2a-35b1-49f4-9425-ca5b88928d99">
