### ISSUE TITLE
[FEATURE] 由于网络的问题, 能否制作一键清理的功能, 以及从其他地方拷贝到文件夹中

### ISSUE THREAD

**Issue by caisxg** [1Panel-dev/MaxKB#260]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

由于网络的问题, 能否制作一键清理的功能, 以及从其他地方拷贝到文件夹中.

仔细看了一下,model 文件全部是 sha256 文件, 如果下载中断, 可能会导致模型重新下载, 因此建议可以清除 ollema 无效的模型.

还有就是, 能否从其他文件夹拷贝到 data 文件夹下?

### 请描述你建议的实现方案

大致想法,就是新建一个小型数据库, 收集公开的 sha256,以及自己导入的 model, 然后根据内置数据库,进行清理无效 model

**Comment by baixin513** [comment]
感谢反馈，没看明白问题 ，Ollama 模型下载中断，导致模型对接失败 ？
另外， 在 MaxKB 删除模型只是删除 MaxKB 中的模型配置信息，我们不会去删除 Ollama 的模型文件。我们也不能一键清理 Ollama的文件。
