### ISSUE TITLE
[FEATURE] 应用描述、提示词的长度太短

### ISSUE THREAD

**Issue by DirtyKnightForVi** [1Panel-dev/MaxKB#262]
### MaxKB 版本

应该是最新的，直接用docker保存的

### 请描述您的需求或者改进建议

1、应用描述是否对应的对话中的System？这部分的长度太短了
2、直接在内网环境中部署的话，版本号和文本段的编辑按钮都显示不出来
3、更换Embendding模型的方法，在日志中看不到当前的模型是什么，没法确认是否替换成功。

**Comment by baixin513** [comment]
感谢反馈，
1.应用描述是MaxKB中对应用的描述。
2.3请提供下图片

**Comment by baixin513** [comment]
如果没有问题，该 issue 先关闭了
