### ISSUE TITLE
群晖container manager问题

### ISSUE THREAD

**Issue by CNYANGANG** [1Panel-dev/MaxKB#266]
### MaxKB 版本

1.0.4

### 问题描述

群晖container manager布署后打不开。

2024-04-26 17:25:16.272 CST [29] LOG:  checkpoint complete: wrote 6 buffers (0.0%
); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.255 s, total
=0.892 s; sync files=5, longest=0.095 s, average=0.051 s; distance=2 kB, estimate
=2 kB                                                                            
2024-04-26 17:25:16.415 CST [7] LOG:  database system is ready to accept connecti
ons                                                                              
127.0.0.1:5432 - accepting connections                                     
Operations to perform:                                                           
Apply all migrations: application, contenttypes, dataset, django_apscheduler, e
mbedding, setting, users                                                         
Running migrations:                                                              
No migrations to apply.                                                        
Your models in app(s): 'application' have changes that are not yet reflected in
a migration, and so won't be applied.                                           
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.
py migrate' to apply them.                                                       
Operations to perform:                                                           
Apply all migrations: application, contenttypes, dataset, django_apscheduler, e
mbedding, setting, users                                                         
Running migrations:                                                              
No migrations to apply.                                                        
Your models in app(s): 'application' have changes that are not yet reflected in
a migration, and so won't be applied.                                           
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.
py migrate' to apply them.                                                       
April 26, 2024 - 17:25:26                                                        
Django version 4.1.13, using settings 'smartdoc.settings'                        
Starting development server at http://0.0.0.0:8080/                              
Quit the server with CONTROL-C.

### 重现步骤

2024-04-26 17:25:16.272 CST [29] LOG:  checkpoint complete: wrote 6 buffers (0.0%
); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.255 s, total
=0.892 s; sync files=5, longest=0.095 s, average=0.051 s; distance=2 kB, estimate
=2 kB                                                                            
2024-04-26 17:25:16.415 CST [7] LOG:  database system is ready to accept connecti
ons                                                                              
127.0.0.1:5432 - accepting connections                                     
Operations to perform:                                                           
Apply all migrations: application, contenttypes, dataset, django_apscheduler, e
mbedding, setting, users                                                         
Running migrations:                                                              
No migrations to apply.                                                        
Your models in app(s): 'application' have changes that are not yet reflected in
a migration, and so won't be applied.                                           
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.
py migrate' to apply them.                                                       
Operations to perform:                                                           
Apply all migrations: application, contenttypes, dataset, django_apscheduler, e
mbedding, setting, users                                                         
Running migrations:                                                              
No migrations to apply.                                                        
Your models in app(s): 'application' have changes that are not yet reflected in
a migration, and so won't be applied.                                           
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.
py migrate' to apply them.                                                       
April 26, 2024 - 17:25:26                                                        
Django version 4.1.13, using settings 'smartdoc.settings'                        
Starting development server at http://0.0.0.0:8080/                              
Quit the server with CONTROL-C.

**Comment by shaohuzhang1** [comment]
项目已经成功启动并且暴露8080端口,请确认能访问群晖的8080端口

**Comment by CNYANGANG** [comment]
> 项目已经成功启动并且暴露8080端口,请确认能访问群晖的8080端口

拒绝了我们的连接请求。

**Comment by baixin513** [comment]
网络问题，您可以排查一下网络环境。
