### ISSUE TITLE
[BUG]离线部署的时候，每次回答完都会报错

### ISSUE THREAD

**Issue by linjia1993912** [1Panel-dev/MaxKB#270]
### MaxKB 版本

1.0.4

### 问题描述

在小助手应用回答完成以后会报错
<img width="1087" alt="截屏2024-04-26 19 56 19" src="https://github.com/1Panel-dev/MaxKB/assets/57213312/618f96ba-841b-496b-88db-996475ca6058">
<img width="1190" alt="截屏2024-04-26 19 22 44" src="https://github.com/1Panel-dev/MaxKB/assets/57213312/e4bdb5c5-0e85-4015-929b-51dcd2bfd0da">
![161714125699_ pic](https://github.com/1Panel-dev/MaxKB/assets/57213312/b5e14e24-2aa1-4cf4-8e3a-5661f4fe8c2d)

### 重现步骤

ollama离线部署llama3中文微调版本，在别的webui对模型进行对话时没有该问题，可排除模型问题，只有在maxkb中对话才报错

### 期待的正确结果

不报错

**Comment by Zhanghao-19970918** [comment]
老兄  你的基座模型是哪个？

**Comment by linjia1993912** [comment]
> 老兄你的底座模型是哪个？

llama3 清华微调的那个
