### ISSUE TITLE
[FEATURE]用户权限设置需更细分

### ISSUE THREAD

**Issue by Shitao5** [1Panel-dev/MaxKB#271]
### MaxKB 版本

v1.0.4 (build at 2024-04-19T16:59, commit: 7c001221)

### 请描述您的需求或者改进建议

当前权限设置仅包含「管理」和「使用」两项。对于应用，仅拥有「使用」权限的用户，依然可以看到应用的概览、设置、命中测试以及对话日志。在账号为客户使用的情况下，希望仅能使用问答功能，以及看到账号的对话日志；不希望看到概览、设置、命中测试以及所有的对话日志。

### 请描述你建议的实现方案

1. 细分权限：管理、使用（可查看不能修改）、仅问答（具体可取名）。
2. 调整权限范围：管理是均可使用，使用只包含问答功能。

**Comment by baixin513** [comment]
感谢反馈，按照你的需求你可以只需要把公开访问链接给他，他可以进行问答即可 。
用户管理和成员权限设置是协作维护知识库和应用的。
