### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wmvm0** [1Panel-dev/MaxKB#272]
### MaxKB 版本

最新版

### 问题描述

智能分段切换到高级分段后，右侧的分段会调整为智能分段的结果。但是再从高级分段切回只能分段右侧的段落不会变化
<img width="376" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/45738680/8d6c41b8-7007-4b4c-a928-90b68324c993">

### 重现步骤

从只能分段切换到高级分段在切换回来

### 期待的正确结果

每次切换右侧的分段会和左侧的选项一起联动

**Comment by baixin513** [comment]
感谢反馈，规则变更后，点击【生成预览】即可按最新规则生成分段。

不支持实时预览。
