### ISSUE TITLE
[BUG]没有权限访问

### ISSUE THREAD

**Issue by jg0014** [1Panel-dev/MaxKB#274]
### MaxKB 版本

1.0.4

### 问题描述

获取会话id，返回403 没有权限访问

### 重现步骤

![image](https://github.com/1Panel-dev/MaxKB/assets/63099132/f98bc3aa-015b-49fc-bbf0-9349cb55e0fd)

### 相关日志输出

```shell
{
    "code": 403,
    "message": "没有权限访问",
    "data": null
}
```

**Comment by baixin513** [comment]
感谢反馈，参考下文档，按照文档操作执行即可。
https://github.com/1Panel-dev/MaxKB/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%BA%94%E7%94%A8%E7%9A%84APIKey%E8%BF%9B%E8%A1%8C%E5%AF%B9%E8%AF%9D%E8%B0%83%E7%94%A8

**Comment by jg0014** [comment]
看文档马虎了，麻烦了！感谢！
