### ISSUE TITLE
希望可以添加跨域支持！

### ISSUE THREAD

**Issue by Evanora-y** [1Panel-dev/MaxKB#276]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

希望可以添加跨域支持！

### 请描述你建议的实现方案

添加请求头即可

**Comment by tongque0** [comment]
我也需要这个

**Comment by shaohuzhang1** [comment]
不允许跨域是为了安全, 最好是在页面加一个开关 设置可跨域的地址。已经在安排了

**Comment by Evanora-y** [comment]
太棒了

**Comment by ljp888** [comment]
修改  apps/common/middleware/static_headers_middleware.py 这个文件 添加跨域的头就能跨域了
`class StaticHeadersMiddleware(MiddlewareMixin):
    def process_request(self, request):
        if request.method == 'OPTIONS':
            return HttpResponse(status=200,
                                headers={"Access-Control-Allow-Origin": "*",
                                         "Access-Control-Allow-Methods": "GET, POST, DELETE,PUT",
                                         "Access-Control-Allow-Headers": "Origin,X-Requested-With,Content-Type,Accept,Authorization,token"})
    def process_response(self, request, response):
        if request.path.startswith('/ui/chat/'):
            access_token = request.path.replace('/ui/chat/', '')
            application_access_token = QuerySet(ApplicationAccessToken).filter(access_token=access_token).first()
            if application_access_token is not None:
                if application_access_token.white_active:
                    # 添加自定义的响应头
                    response[
                        'Content-Security-Policy'] = f'frame-ancestors {" ".join(application_access_token.white_list)}'
                response.content = (response.content.decode('utf-8').replace(
                    '<link rel="icon" href="/ui/favicon.ico" />',
                    f'<link rel="icon" href="{application_access_token.application.icon}" />')
                .replace('<title>MaxKB</title>', f'<title>{application_access_token.application.name}</title>').encode(
                    "utf-8"))
        response['Access-Control-Allow-Origin']='*'
        response['Access-Control-Allow-Methods']='GET, POST, DELETE,PUT'
        response['Access-Control-Allow-Headers']='Origin,X-Requested-With,Content-Type,Accept,Authorization,token'
        return response`
