### ISSUE TITLE
[BUG] 1Panel 部署 MaxKB 关于里面版本号为空

### ISSUE THREAD

**Issue by chixq** [1Panel-dev/MaxKB#277]
### MaxKB 版本

空

### 问题描述

1Panel 部署 MaxKB 关于里面版本号为空

### 重现步骤

<img width="681" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/1032739/3c0149fc-9e10-4960-a305-5749687556b5">

能看到版本号是 1.0.4，但是 MaxKB web 页面控制台却为空。

<img width="630" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/1032739/cf4a3ced-644a-4214-95ef-518009578fdc">

**Comment by baixin513** [comment]
感谢反馈， 我们这边正常打包的版本应该是可以获取到版本号的。
你这边是二开的还是通过 1panel部署的 MaxKB ？

**Comment by liqiang-fit2cloud** [comment]
@wanghe-fit2cloud  你能重现么？

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 你能重现么？

1Panel 应用商店使用的是 MaxKB 官方镜像，未能复现上述问题。

**Comment by chixq** [comment]
我用的是 1Panel 部署的。没关系，可能是个体原因（网络/浏览器）。

<img width="2157" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/1032739/01efef1f-3ad1-409e-a921-caa5b580bd92">
