### ISSUE TITLE
[BUG]  API Key 字符长度过长时，添加模型报错

### ISSUE THREAD

**Issue by chixq** [1Panel-dev/MaxKB#278]
### MaxKB 版本

1.0.4

### 问题描述

类似这个 Issue 的需求 https://github.com/1Panel-dev/MaxKB/issues/142

实际测试过程中，通过 1Panel 本地部署 kimi-free-api 项目（ https://github.com/LLM-Red-Team/kimi-free-api ），
模型接入选择 OpenAI，kimi-free-api 地址为 http://192.168.1.37:8000 报错如下：

<img width="696" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/1032739/7a0e25f7-faaf-40a4-9938-958889f6b773">

API 添加版本信息仍然报错如下：

<img width="668" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/1032739/ba45d35b-69f7-4efc-bb1b-71813764f2c4">

可以确认的是，kimi-free-api 工作正常，通过 1Panel 部署 chatgpt-next-web 服务，接入 API 没问题。

<img width="1120" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/1032739/80d8b229-be3a-4cd9-881e-5b8124e007ae">

### 重现步骤

如上。

**Comment by baixin513** [comment]
感谢反馈，确认一下基础模型名称与部署的LLM名称要一致，基础模型输入：kimi-free-api  ，回车 试一下呢。

**Comment by chixq** [comment]
_确认一下基础模型名称与部署的LLM名称要一致，基础模型输入：kimi-free-api  ，回车 试一下呢。_

这个应该跟名称没关系，同时我也试了，结果一样。看报错是不是解析 API Endpoint 的时候需要 /v1 类似这样的字段，但实际情况 OpenAI Compatible API 不一定需要。

字段过长的原因是因为这个不是标准的 API，所以 sk 会比一般 OpenAI 长，这个应该放开长度限制。

**Comment by baixin513** [comment]
我们测试了这边最大的字符长度大概在 190 个左右的字符，加密后的最大长度为：5120 个字符。还请确认一下你的sk会有多少个字符数。

**Comment by chixq** [comment]
<img width="454" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/1032739/80b1a2ec-8734-4a01-93c0-dfa9092c7374">

398 个。

同时，API Endpoint 对于自定义 OpenAI 兼容的 API，是不是也需要放开格式，不一定非要 /v1

**Comment by baixin513** [comment]
API Key 长度我们加长一些，下个版本更新。
