### ISSUE TITLE
[FEATURE] Open Interpreter 现在在github上面有开源的，可以做数据分分析能不能和llama3结合，加入MAXkb中呢？或者与pandas结合，实习对本地文档数据的分析，绘图

### ISSUE THREAD

**Issue by doriszhang2020** [1Panel-dev/MaxKB#279]
### MaxKB 版本

-

### 请描述您的需求或者改进建议

既然能够加入本地知识库，除了做问答以外，也可以更加进阶，对大量 PDF进行汇总总结论文（从zotero中导入数据），对本地的excel的文档数据进行科研绘图，可视化等

### 请描述你建议的实现方案

-Open Interpreter 现在在github上面有开源的，可以做数据，写代码

**Comment by baixin513** [comment]
感谢反馈，当前只有问答对话，其他多模态的需求，后期开发应用编排时考虑。 您这需求近期还无法达到，有了编排功能后您按需求拆解步骤提出相应的问题。

**Comment by baixin513** [comment]
由于该需求比较笼统，短期内无法实现，等编排功能发布后您按需求拆解步骤提出相应的问题。该 issue暂时先关闭了。
