### ISSUE TITLE
[FEATURE]基于RAG的知识库检索质量不高，实现基于Cross Encoder(BERT)的本地Reranker

### ISSUE THREAD

**Issue by doriszhang2020** [1Panel-dev/MaxKB#281]
### MaxKB 版本

-

### 请描述您的需求或者改进建议

Reranker能够将本地向量排序打分，使得文档结果更加准确，目前有闭园的RERANK，为了数据的隐私性，请问能够支持Cross Encoder(BERT)的本地Reranker

### 请描述你建议的实现方案

-

**Comment by baixin513** [comment]
感谢反馈，目前我们的机制还不适合增加 rerank模型，增加 rerank后安装包变得大很多，且对部署机器配置也会增加。但增加rerank后检索效率会慢很多，效果可能也没有那么理想。综合考虑我们暂时不计划增加 rerank模型。

但在 v1.1.0 版本中我们加了 全文检索和混合检索（向量检索+全文检索） 会提高检索质量。可以先试用一下。

再次感谢建议！

**Comment by doriszhang2020** [comment]
请问您的这个有使用介绍么，或者演示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月28日(周日) 上午10:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1Panel-dev/MaxKB] [FEATURE]基于RAG的知识库检索质量不高，实现基于Cross Encoder(BERT)的本地Reranker (Issue #281)




 
感谢反馈，目前我们的机制还不适合增加 rerank模型，增加 rerank后安装包变得大很多，且对部署机器配置也会增加。但增加rerank后检索效率会慢很多，效果可能也没有那么理想。综合考虑我们暂时不计划增加 rerank模型。
 
但在 v1.1.0 版本中我们加了 全文检索和混合检索（向量检索+全文检索） 会提高检索质量。可以先试用一下。
 
再次感谢建议！
