### ISSUE TITLE
[FEATURE]允许知识库的更新，知识都是不断改变的，如何对于已经存在的知识进行更新，并重新写入数据库（保留历史记录）

### ISSUE THREAD

**Issue by doriszhang2020** [1Panel-dev/MaxKB#282]
### MaxKB 版本

-

### 请描述您的需求或者改进建议

知识都是不断改变的，如何对于已经存在的知识进行更新，并重新写入数据库，进行chat时，可以通过聊天发现知识的旧，通过聊天，要求更新该知识（保留旧知识），以后回答优先引用更新知识点，但是在做综述时，对于该主题知识点，可以按照历史顺序进行综述。类似文献综述。

### 请描述你建议的实现方案

-

**Comment by baixin513** [comment]
感谢反馈，知识库更新，您需要更新维护知识库中内容，我们无法判断哪些数据是旧知识，哪些是新知识。您可以自行维护分段标题、内容或管理问题从而达到您想要命中的内容。
