### ISSUE TITLE
[FEATURE]需求:除了本地上传知识库，是否可以做个类似的excel表格界面，要求ai把我复制粘贴的数据（内容）按照excel表格设定好队列，自动识别并输入到excel表格对应位置，来进行数据或者内容管理呢

### ISSUE THREAD

**Issue by doriszhang2020** [1Panel-dev/MaxKB#283]
### MaxKB 版本

-

### 请描述您的需求或者改进建议

就是比如进行人员的信息、知识构建，一键填入设定好的数据库，方便知识的搜集和处理，尤其是科研数据等高度重复的，大大减少人力来输入

### 请描述你建议的实现方案

-

**Comment by baixin513** [comment]
感谢反馈，暂无改计划。
