### ISSUE TITLE
[FEATURE]关于模型设置 - 模型设置

### ISSUE THREAD

**Issue by shuyunnn** [1Panel-dev/MaxKB#285]
### MaxKB 版本

v1.0.4

### 请描述您的需求或者改进建议

模型设置中，如果选择ollama的话，怎么不让自由选择ollama list 中的其他模型？还是我哪里操作错误。

### 附加信息
![image](https://github.com/1Panel-dev/MaxKB/assets/154390043/802a3648-0656-42dd-9b27-c6b7f185b279)

_No response_

**Comment by baixin513** [comment]
感谢反馈， 模型库中的模型太多了，我们列不过来，有些还是名称还是用户自定义的。
但是这里我们是支持自定义输入模型名称的， 如想要对接 qwen:0.5b 就直接输入 qwen:0.5b 然后回车既可以添加成功。
如果 Ollama 上没有部署 qwen：0.5b。 我们还会自动下载该模型。
