### ISSUE TITLE
[FEATURE]增加浏览器插件或者能够支持将本地模型的api导出给pc端其他应用使用，以实现本地模型进行类openai 的免费api

### ISSUE THREAD

**Issue by doriszhang2020** [1Panel-dev/MaxKB#286]
### MaxKB 版本

-

### 请描述您的需求或者改进建议

本地其他应用如文献管理软件，也可以使用makkb的本地聊天模型，调用api进行翻译或者文献解读而不需要把文献导入到知识库。

### 请描述你建议的实现方案

-

**Comment by baixin513** [comment]
感谢反馈，无法满足该需求，暂无改计划。
