### ISSUE TITLE
[FEATURE]关于系统设置 - 模型设置

### ISSUE THREAD

**Issue by shuyunnn** [1Panel-dev/MaxKB#290]
### MaxKB 版本

v1.0.4

### 请描述您的需求或者改进建议

添加模型的时候，如果选择ollama，基础模型是否能自由选择 llama中已经运行的模型？
![Uploading 513B2FA3-B3E8-4812-A85A-EA96B0CD2609.png…]()

**Comment by baixin513** [comment]
感谢反馈，没有运行的模型添加后会自动下载。
