### ISSUE TITLE
[FEATURE] 在应用里通过日志绑定问题的时候，问题可以修改

### ISSUE THREAD

**Issue by qingad** [1Panel-dev/MaxKB#292]
### MaxKB 版本

v1.04

### 请描述您的需求或者改进建议

在应用里通过日志绑定问题的时候，问题可以修改。目前只能指定内容和标题，绑定问题是不能修改的。

**Comment by baixin513** [comment]
感谢反馈，对话日志是日志，用户提的问题就是无法修改。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
