### ISSUE TITLE
[FEATURE]问题可以忽略标点符合

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#294]
### MaxKB 版本

 1.0.4

### 请描述您的需求或者改进建议

 对于关联的问题中的标点符号在进行向量匹配时可以忽略，标点符合不应该对内容的权重带来一点儿影响

**Comment by baixin513** [comment]
感谢反馈，后期考虑优化一下。

**Comment by baixin513** [comment]
问题是先分词在向量化，正常来说是没有标点符号的。
