### ISSUE TITLE
[FEATURE]关于问答界面支持上传图片或文档

### ISSUE THREAD

**Issue by shuyunnn** [1Panel-dev/MaxKB#295]
### MaxKB 版本

v1.0.4

### 请描述您的需求或者改进建议

如果后台大模型支持图片识别，是否可以在问答界面的问题输入框里，增加上传文件的功能？

**Comment by baixin513** [comment]
用户端提问时 上传图片么？

**Comment by shuyunnn** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/154390043/57d99516-4bb7-4362-9312-449df6e6f2d7)
是的，类似上面这个。

**Comment by RipperTs** [comment]
+1

**Comment by qjx378** [comment]
+1

**Comment by baixin513** [comment]
v1.8.0 已发布！
