### ISSUE TITLE
[FEATURE]如何修改 docker 端口

### ISSUE THREAD

**Issue by GitHdu** [1Panel-dev/MaxKB#296]
### MaxKB 版本

1.0.3

### 请描述您的需求或者改进建议

如何修改8080端口为其他端口

### 请描述你建议的实现方案

docker 小白，请问代码里替换所有 8080 端口就可以了吗

**Comment by tongque0** [comment]
如果你想将容器的 8080 端口映射到宿主机的 9090 端口，你可以修改 -p 参数如下：
docker run -d --name=maxkb -p 9090:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb

**Comment by GitHdu** [comment]
> 如果你想将容器的 8080 端口映射到宿主机的 9090 端口，你可以修改 -p 参数如下： docker run -d --name=maxkb -p 9090:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb

不用修改内部代码吗

**Comment by tongque0** [comment]
在Docker中，`-p`参数用于将容器内的端口映射到宿主机的端口上，从而允许外部访问容器中运行的服务。这是网络配置的重要部分，尤其是在部署对外提供服务的应用时。

## 基本语法

```bash
docker run -p [宿主机端口]:[容器端口] [镜像名]

```
示例: 

将容器的80端口映射到宿主机的8080端口，适用于例如Web服务器：

docker run -p 8080:80 nginx

**Comment by tongque0** [comment]
> > 如果你想将容器的 8080 端口映射到宿主机的 9090 端口，你可以修改 -p 参数如下： docker run -d --name=maxkb -p 9090:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb
> 
> 如果要改容器的端口呢


在Docker中，`-p`参数用于将容器内的端口映射到宿主机的端口上，从而允许外部访问容器中运行的服务。这是网络配置的重要部分，尤其是在部署对外提供服务的应用时。

## 基本语法

```bash
docker run -p [宿主机端口]:[容器端口] [镜像名]

```
示例: 

将容器的80端口映射到宿主机的8080端口，适用于例如Web服务器：

docker run -p 8080:80 nginx
