### ISSUE TITLE
[BUG]使用NGINX进行二级域点跳转会出现js路径不正常

### ISSUE THREAD

**Issue by Arrding** [1Panel-dev/MaxKB#304]
### MaxKB 版本

版本号：v1.0.4

### 问题描述

需求：在nginx上设置二级域名LLM，跳转到内网IP，经测试发现，嵌入第三方的url在这种场景下，不会加上LLM，导致js路径报错。

### 重现步骤

![1](https://github.com/1Panel-dev/MaxKB/assets/149556585/e82596a2-e693-49ad-8bfe-7710ff979c2e)
![2](https://github.com/1Panel-dev/MaxKB/assets/149556585/bf359199-5d1a-4611-97f7-84a42820e9f9)
![3](https://github.com/1Panel-dev/MaxKB/assets/149556585/9200324a-a674-4400-b5e7-8bedb47d5652)
![4](https://github.com/1Panel-dev/MaxKB/assets/149556585/e0db14c9-0233-45d8-bac7-9ef5cfb61bab)
![5](https://github.com/1Panel-dev/MaxKB/assets/149556585/cf66d09e-cffb-4d81-b66c-e80b66bce582)
![6](https://github.com/1Panel-dev/MaxKB/assets/149556585/76a1edaa-c2a3-4d05-a29a-e431d5c4f2c8)
![7](https://github.com/1Panel-dev/MaxKB/assets/149556585/7439dc5a-f3eb-447c-b417-f75bd742d0bb)
![8](https://github.com/1Panel-dev/MaxKB/assets/149556585/58a9f313-a4bc-4bcc-aa7c-057476fde793)

### 期待的正确结果

能正确识别这种转发并加上目录

**Comment by shaohuzhang1** [comment]
目前maxkb无法解决这一个问题,因为maxkb 的ui再打包的时候指定了BASE_PATH=/ui/ 如果需要使用nginx的二级路径负载均衡 则需要修改ui/env/.env 修改BASE_PATH
![image](https://github.com/1Panel-dev/MaxKB/assets/80892890/a4e489be-dfd2-4db8-ac56-77e999239d95)
然后使用npm run build 使用nginx代理前后端

**Comment by shaohuzhang1** [comment]
因为除了index.html的src 其他js里面的src也是通过base_path决定的 经过尝试只修改index.html无法达到预期效果。
只能重新打包才可以做到,所以maxkb不能支持你这个需求

**Comment by swtseaman** [comment]
请问这个没有好的解决方法吗
