### ISSUE TITLE
[BUG] 异常value too long for type character varying(256)

### ISSUE THREAD

**Issue by ljp888** [1Panel-dev/MaxKB#305]
### 联系方式

234166810@qq.com

### MaxKB 版本

1.0.4

### 问题描述

异常value too long for type character varying(256) 
![37154e8e57907a14d67209cfa5bd66f](https://github.com/1Panel-dev/MaxKB/assets/14199299/4145eacf-828a-4977-a063-bd34f5ac3cda)

### 重现步骤

一篇文章做总结的时候

**Comment by baixin513** [comment]
感谢反馈，确认为 bug，下个版本修复，请关注版本更新。
