### ISSUE TITLE
[BUG]上传2个 20M的文档超时

### ISSUE THREAD

**Issue by ljp888** [1Panel-dev/MaxKB#306]
### 联系方式

234166810@qq.com

### MaxKB 版本

1.0.4

### 问题描述

![47c55fd9a7e569f3dd18942cab1252f](https://github.com/1Panel-dev/MaxKB/assets/14199299/4cca5043-f52b-456f-899c-10bde72a746a)
![abfc94d15b281a4946e4f94bfd480c8](https://github.com/1Panel-dev/MaxKB/assets/14199299/f308da74-1916-4b73-ae3e-63e3f357b1cf)
上传过后就超时了然后预览啥也看不到

### 重现步骤

上传2个20m以上文档 或者 1个大于40m的文档后 预览分段那60秒后超时

**Comment by baixin513** [comment]
感谢反馈，我们后面版本优化一下超时时间。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Why did everything get better all of a sudden, and now 20M is still being processed? ? ? What is the cause? The same computer has the wsl virtual machine of window 10. Now I have been working on the docker and wsl virtual machine of 11 for several hours with no results.
