### ISSUE TITLE
[BUG] 新版本token使用量下降了，但AI也变得不这么智能了

### ISSUE THREAD

**Issue by DavinciEvans** [1Panel-dev/MaxKB#309]
### 联系方式

znsydavinci@gmail.com

### MaxKB 版本

开发版

### 问题描述

模型应用配置、prompt均一致。相同的一个问题，也关联到了正确的知识库。在1.0.3版本中，虽然消耗的token比较大，但模型返回的结果更好。新版本似乎做了对于token的优化，但明显回答质量也下降了。能否通过修改源码将相关的代码进行注释或者新增一个配置呢？

### 重现步骤

最新commit的开发版本中的回答：

![QQ截图20240429114759](https://github.com/1Panel-dev/MaxKB/assets/45795384/cb4da3a0-ed10-4682-9bb9-0f5c66c1e7f3)

1.0.3版本中的回答：

![QQ截图20240429114819](https://github.com/1Panel-dev/MaxKB/assets/45795384/488b1369-51aa-4dd6-a1e3-9cf20232b0cf)

从图中可以看到，新版本只消耗了1k不到的token，但回答质量明显不如老版本的结果

**Comment by baixin513** [comment]
感谢反馈，昨天修复了一个 BUG ，你在更新到最新的 commit 试试。
