### ISSUE TITLE
支持改造成https吗?

### ISSUE THREAD

**Issue by run-gump-run** [1Panel-dev/MaxKB#318]
### MaxKB 版本

v1.0.4 

### 请描述您的需求或者改进建议

假设嵌入的第三方网站是https网站，会被浏览器拦截，只能嵌入http网站中。针对要嵌入https网页的场景该如何解决呢？

### 请描述你建议的实现方案

MaxKB支持配置https访问。

**Comment by shaohuzhang1** [comment]
部署nginx,https域名代理访问就可以了
