### ISSUE TITLE
希望可以加入 Claude 模型

### ISSUE THREAD

**Issue by BluerAngala** [1Panel-dev/MaxKB#321]
### MaxKB 版本

v1.1.0

### 请描述您的需求或者改进建议

目前大模型未支持 Claude ，请求支持，并开放自定义添加其他大模型。

**Comment by baixin513** [comment]
AWS 的模型么，后期需要先调研一下对接方式

**Comment by liliuwei** [comment]
Claude用着还行，期待支持
