### ISSUE TITLE
讯飞星火添加失败[BUG]

### ISSUE THREAD

**Issue by yc-2503** [1Panel-dev/MaxKB#322]
### MaxKB 版本

空版本号

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/11872314/8022d2a6-dd6f-4d95-b087-7c5accf739dc)

### 重现步骤

按照文档添加星火

**Comment by baixin513** [comment]
感谢反馈，讯飞星火需要应用有剩余token，新购买的token有延时，需要过个三五分钟后再添加模型对接。
