### ISSUE TITLE
[BUG]创建应用，不选择模型，开启问题优化和多轮对话就会出现错误

### ISSUE THREAD

**Issue by kbc1118** [1Panel-dev/MaxKB#326]
### 联系方式

1群里的：你个老六

### MaxKB 版本

1.10

### 问题描述

#看图
![微信图片_20240430000659](https://github.com/1Panel-dev/MaxKB/assets/150053657/784bec0c-3a89-4b31-b72c-6ba4786ef92f)

### 重现步骤

创建应用，不选择模型，开启问题优化和多轮对话就会出现错误

**Comment by baixin513** [comment]
感谢反馈，我们排查一下。
