### ISSUE TITLE
[BUG]设置了无引用知识库分段时，回复异常

### ISSUE THREAD

**Issue by macaty** [1Panel-dev/MaxKB#328]
### MaxKB 版本

1.1.0

### 问题描述

从1.0.4 升级1.1.0来，设置了无引用知识库分段时，回复制定信息
![image](https://github.com/1Panel-dev/MaxKB/assets/16797633/ed0c9201-3a89-40d1-8daf-71ccc37960c5)
测试的时候，有引用信息，但是回复 无引用知识库
![image](https://github.com/1Panel-dev/MaxKB/assets/16797633/abfc4bb6-514a-497d-82dc-451880ec427e)

### 重现步骤

同上

**Comment by macaty** [comment]
回退至1.0.4版本后就正常

**Comment by baixin513** [comment]
这个问题昨晚已经解决，需要重新升级一下，在关于中确认一 1.1.0 的 commit，要与下图一致。
<img width="587" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/657c5526-770a-41a7-949d-6087d296a7ff">
