### ISSUE TITLE
[FEATURE]希望可以设计成标签式对话栏

### ISSUE THREAD

**Issue by gundamwing01** [1Panel-dev/MaxKB#329]
### MaxKB 版本

1.10

### 请描述您的需求或者改进建议

当前对话形式在每次启动应用后就新开页面，无法看到之前的对话记录，对于前文的内容要追溯或者继续对话会很不方便。

### 请描述你建议的实现方案

希望能够参考GPT、GEMINI这样，在左边能有对话主题标签。然后点开应用后，能够看到每个主题里的所有对话记录。一方面方便归类对话的主题，另一方面能够基于原有的对话内容，进行上下文关联。

**Comment by baixin513** [comment]
感谢反馈，显示历史对话记录，与 #206 issue 重复
