### ISSUE TITLE
支持openapi兼容调用[FEATURE]

### ISSUE THREAD

**Issue by samcaicn** [1Panel-dev/MaxKB#33]
### MaxKB 版本

1.0

### 请描述您的需求或者改进建议

fastapi 即可

**Comment by baixin513** [comment]
感谢反馈，下个版本支持，等下周发版更新。

**Comment by jingzl** [comment]
建议支持 openai 接口的本地化调用，比如chatglm3-6b，baichuan2，qwen等。

**Comment by baixin513** [comment]
可以通过 Ollama 调用本地模型的。

> 建议支持 openai 接口的本地化调用，比如chatglm3-6b，baichuan2，qwen等。

**Comment by samcaicn** [comment]
good

**Comment by samcaicn** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/3318094/32263d7d-08c5-44b0-88c8-46695c503f51)

**Comment by baixin513** [comment]
当前不能像OpenAI那样对话的。
需要先获取一个对话id 才可以进行对话，具体要看我们API文档。
