### ISSUE TITLE
可不可以新增除了ollama之外的自定义模型接口[FEATURE]

### ISSUE THREAD

**Issue by zemanzhang809** [1Panel-dev/MaxKB#333]
### MaxKB 版本

v1.0.4 

### 请描述您的需求或者改进建议

因为ollama的模型库不是很全，所以更期待能有一些其他的模型对接方式，例如chatglm系列的相关模型，ollama上并没有直接的安装方式。只能自部署chatglm等的模型，自部署的模型更方便调用一些自己微调的自部署模型。。。

**Comment by baixin513** [comment]
感谢反馈，我们后续讨论一下。

**Comment by baixin513** [comment]
同 issue #423
