### ISSUE TITLE
[FEATURE]未命中回答支持 markdown 格式

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#339]
### MaxKB 版本

 1.1.0

### 请描述您的需求或者改进建议

 未命中的内容支持设置 markdown 格式的内容

**Comment by baixin513** [comment]
感谢反馈，我们支持 markdown 样式输出。需要您维护内容的时候按照markdown 的样式输入。

**Comment by fitchibing** [comment]
好的，测试了确实支持
