### ISSUE TITLE
模型添加，提示API域名无效 

### ISSUE THREAD

**Issue by jingzl** [1Panel-dev/MaxKB#34]
### 联系方式

jingzl@hotmail.com

### MaxKB 版本

0.9.1

### 问题描述

部署完毕后，进入 系统设置 --- 模型设置 --- ollama ---- 添加模型：
![image](https://github.com/1Panel-dev/MaxKB/assets/2803602/c818547a-ceaf-4c01-84be-2a0b3d000437)
点击 添加，提示 API域名无效

### 重现步骤

直接可以重复出现

**Comment by jingzl** [comment]
本地的 ollama run qweb:7b 已经运行，并且可测试

**Comment by jingzl** [comment]
参考其他已关闭的 issue，调整为：
http://127.0.0.1:11434/v1 
仍然提示同样的错误

**Comment by jingzl** [comment]
curl http://127.0.0.1:11434/api/generate -d '{
  "model": "qwen:7b",
  "prompt": "天空为啥是蓝色"
}'
能正常返回数据

**Comment by baixin513** [comment]
v0.9.1版本的API域名不需要加v1了，系统会自动加上的
您换成宿主机的IP地址试试，不要用127.0.0.1。

**Comment by jingzl** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/2803602/dbe75888-da06-4a63-9f7d-fcf70909f279)
报同样的错误

**Comment by baixin513** [comment]
使用 ip addr 确认一下 IP 地址是否正确，检查下网络配置，端口号有没有禁用。

**Comment by baixin513** [comment]
如果没有问题 issue 先关闭了。

**Comment by jingzl** [comment]
还是同样的问题，都在一个服务器上，本地处理，IP和端口，均验证了。 @baixin513

**Comment by kigner** [comment]
docker调用宿主机器里运行的ollama应该这样写：
http://host.docker.internal:11434

**Comment by baixin513** [comment]
把 API 域名 复制到浏览器中访问，是否显示 Ollama is running

**Comment by StrGlee** [comment]
因为MaxKB部署在docker中，所以访问不到虚机中的 http://127.0.0.1:11434 
需要在启动ollama serve之前设置一下环境变量 export OLLAMA_HOST='0.0.0.0:11434'
在docker里面 curl http://主机ip:11434看看能不能通

**Comment by YooogiYun** [comment]
> export OLLAMA_HOST='0.0.0.0:11434'

很棒! 我试了好多方法, 最后还是你的这办法好使.
我是通过 Windows 里的 WSL2 的 1Panel 部署的 Ollama 和 MaxKB.
由于两个 apps 都在 docker 里. 所以访问不了对方. (但是还有疑问, 希望懂的人解答一下, 后续提出)
1. 我是先把 Ollama 和 MaxKB 都 Stop 了
2. 在 WSL2 里输入 export OLLAMA_HOST='0.0.0.0:11434'.
3. 再启动 Ollama 和 MaxKB.
4. Wsl2 里输入 ip addr, 找到 wsl2 的 ip 地址, 
5. 然后 curl http://<wsl2-ipv4>:11434/ 来验证 ollama 访问成功
6. 回到 MaxKb 的 web 界面, 新建加入 Ollama 模型. API 地址同上: http://<wsl2-ipv4>:11434/. 这次就行 :happy:

另外, 还有一个问题就是: 
明明都是通过 1panel 安装的 apps, 1panel 自己起了一个 bridge 的 docker 网络, 叫做 1panel-network
![1panel-network](https://github.com/1Panel-dev/MaxKB/assets/127641096/e86abd29-4586-48c5-91b8-df81f7553cc4)

并且 1panel 安装的 docker apps, 一般都是加入了这个 network 的.
![apps](https://github.com/1Panel-dev/MaxKB/assets/127641096/b13b0684-c36c-42da-a69f-1ff39ecb4a9d)

为什么不能直接通过 docker app name 来实现同一网络下的 http 访问呢?
例如:
在 MaxKb 里 curl http://1Panel-ollama-VWhN:11434/ ???
为什么不行呢? 或者说, 我对同一网络下的理解有误差?
希望懂的人解答一下. 感谢:thanks:

**Comment by hobbyqhd** [comment]
http://host.docker.internal:11434/
