### ISSUE TITLE
[FEATURE] 是否可以自行安裝下載的gguf大模型?

### ISSUE THREAD

**Issue by wing0210** [1Panel-dev/MaxKB#343]
### MaxKB 版本

v1.1.0

### 请描述您的需求或者改进建议

否可以自行安裝下載的gguf大模型?
例如我有下載 "Llama3-8B-Chinese-Chat-GGUF-8bit" 對中文的支持很好
但卻無法安裝到 MaxKB 裡面 有點可惜
畢竟 Llama3 使用上雖然還可以 但經常回覆英文
幾使我強調使用中文也是一樣

**Comment by baixin513** [comment]
感谢反馈，我们需要讨论一下，调研一下私有模型的通用对接方式。

**Comment by tbdavid2019** [comment]
@wing0210 
可以ollama run wangshenzhi/llama3-8b-chinese-chat-ollama-q8
再透過 maxKB 調用

**Comment by learnin9** [comment]
ollama pull wangshenzhi/llama3-8b-chinese-chat-ollama-q8就可以了

**Comment by shaohuzhang1** [comment]
maxkb 添加ollama供应商模型 基础模型使用wangshenzhi/llama3-8b-chinese-chat-ollama-q8 系统就会自动取下载哦
