### ISSUE TITLE
[BUG] ui文件打包报错

### ISSUE THREAD

**Issue by ljp888** [1Panel-dev/MaxKB#348]
### 联系方式

234166810@qq.com

### MaxKB 版本

1.1.1

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/14199299/85e4fd72-19f9-4828-bafd-77969ebe35d2)
打包ui文件的时候报错 无法打包

### 重现步骤

回复正常

**Comment by baixin513** [comment]
感谢反馈，我们先排查确认一下。
