### ISSUE TITLE
个人聊天功能

### ISSUE THREAD

**Issue by belugaming** [1Panel-dev/MaxKB#349]
### MaxKB 版本

最新

### 请描述您的需求或者改进建议

这个项目非常的棒，支持自定义支持库，可是我查阅了很多资料，好像这个项目只是适合一些企业做问答类型的AI回复，比如说嵌入到网页里面，不过我想这个项目能够作为一个我自己的一个知识库，比如说我生活中遇到了一些问题和工作上遇到的问题，我把一些文件发给它，然后让它来更准确的帮助我，不过我发现演示里面不会保存聊天记录，希望开发者可以考虑一下，非常感谢

**Comment by baixin513** [comment]
感谢反馈，保留历史聊天记录有用户提过issue，我们后续会考虑的。

**Comment by belugaming** [comment]
非常感谢！

baixin ***@***.***>于2024年5月3日 周五22:29写道：

**Comment by belugaming** [comment]
哦对了 最好可以在聊天的时候继续发文档给语言模型

ming beluga ***@***.***>于2024年5月3日 周五22:30写道：

**Comment by baixin513** [comment]
与 issue #295 和 issue #206 重复。
