### ISSUE TITLE
[FEATURE]How to chat with obsidian and ollama（local language model）？

### ISSUE THREAD

**Issue by doriszhang2020** [1Panel-dev/MaxKB#350]
### MaxKB 版本

latest

### 请描述您的需求或者改进建议

ollama is a good way to run local languase model(like llama3 8b),and the AI can easily input the so much inorder data quickerly as we want,eg,we copy a lot of information of one person,we just paste in the ai ,and ask it to write in we already set table,it can quickerly write in correct location in the table insted of we one by one.And also ,chat with ai can easily darw picture of data .And the obsidian is a markdown soft,which can easily write so many things ,if we write in ob and upload the data to Nocodb,and then chat with the information auto .

### 请描述你建议的实现方案

Nocodb support REST API，also support Python api.Obsidian can connet by plusign.

**Comment by baixin513** [comment]
Thank you for your feedback. 
Firstly, this requirement requires a multi-step workflow to be implemented, and we need to support the workflow first; Then add some third-party extension components, such as Nocodb as you mentioned.
So this requires several iterations in the later versions, and it cannot meet this requirement in the short term. You can take a look at the missing components after we have implemented the workflow function and submit specific requirements for use.
