### ISSUE TITLE
[FEATURE] 当前ppt知识文档非常的多，知识库文件上传类型是否可以支持ppt和pptx文档类型，

### ISSUE THREAD

**Issue by wivw0306** [1Panel-dev/MaxKB#351]
### MaxKB 版本

master

### 请描述您的需求或者改进建议

建议知识库上传文件类型支持ppt和pptx的支持。

**Comment by baixin513** [comment]
感谢反馈，当前已支持PDF，PPT可以输出为PDF格式的哦。暂时不支持PPT
