### ISSUE TITLE
[BUG] 管理员权限相关问题3个

### ISSUE THREAD

**Issue by wivw0306** [1Panel-dev/MaxKB#352]
### MaxKB 版本

master

### 问题描述

1、管理员admin账号默认无法查看其他用户创建的应用、知识库和模型。
2、模型多用户无法共享。
3、一个用户给另一个用户开发了知识库的权限后，另一个用户创建应用时无法关联这个知识库。

### 重现步骤

1、管理员admin账号默认无法查看其他用户创建的应用、知识库和模型。
2、模型多用户无法共享。
3、一个用户给另一个用户开放了知识库的权限后，另一个用户创建应用时无法关联这个知识库

### 期待的正确结果

问题1：期待默认admin用户具有所有权限，可以查看所有用户创建的应用、知识库、模型。
问题2：期待模型可以共享关联。
问题3：期待一个用户给另一个用户开放了知识库权限后，另一个用户创建的应用可以关联这个知识库。

**Comment by baixin513** [comment]
感谢反馈，当前的机制就是用户隔离的哦，用户的资源归自己所有，但是可以授权成员协同维护。

**Comment by wivw0306** [comment]
当前的机制就是用户隔离: 这点可以理解，但是 作为系统管理员，分配给普通员工创建用户，但不到员工的所有操作，觉得很奇怪，建议从近期看管理员角色用户可以看到所有，从长远规划看能有更明细的权限管理更好，保障创建的对象资源可以复用，比如知识库复用是很迫切的，因为我看不到别人的知识库，我得重新上传一次。
