### ISSUE TITLE
希望 通过应用的API Key 进行对话时， 能使用通用的OpenAI 格式

### ISSUE THREAD

**Issue by wang-zhibo** [1Panel-dev/MaxKB#353]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

希望增加会话api  能支持oneapi   格式

**Comment by baixin513** [comment]
感谢反馈， OneAPI 应该和 OpenAI 的格式是通用的，您可以在 MaxKB 添加 模型时选择 OpenAI供应商，然后 API 域名输入 OneAPI 的服务地址，基础模型输入你想要对接的OneAPI 中的模型名称。

**Comment by wang-zhibo** [comment]
是我没有描述清楚, 是这样的  是想把 maxkb 知识库的 会话 接入 oneapi, 方便管理,和接入别的项目   类似于 maxkb 里的 /api/application/chat_message/{chat_id}  接口, 把他标准化 openai api 格式

**Comment by jwdstef** [comment]
意思就是API接口对其openai的API接口，这样maxkb的对外API就可以当openai的方式来使用了，这个提议非常好，建议加上

**Comment by fitchibing** [comment]
支持，

**Comment by soonxf** [comment]
希望希望能将知识库接口输出格式转为跟 openAi 一样的格式,这样就能将 MaxKB 集成到 one-ai 进行管理了

**Comment by samcaicn** [comment]
我三个月前都提了，这产品经理愣是理解不了，差点都想群里直接找他们的人聊了。我微信xukai80229

**Comment by samcaicn** [comment]
为了解决这个问题拉群一起交流吧，这几个月我也找了几个解决方案！

![image](https://github.com/user-attachments/assets/bdd428d2-cd64-47f6-8854-e10c991ad23d)

添加验证消息“exo”
拉群。
