### ISSUE TITLE
[BUG]每次在Docker中重启MaxKB容器后，已配置的知识库和模型会被清空

### ISSUE THREAD

**Issue by zmalibaba** [1Panel-dev/MaxKB#354]
### MaxKB 版本

版本信息为空，初步判定为v.1.1.1

### 问题描述

使用 docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb  安装后，在docker中对容器maxkb重启后，通过localhost:80880访问，之前添加的知识库、模型设置等数据会全部清空。

### 重现步骤

1、docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb  安装后
2、通过http://localhost:80880访问，进行修改密码、添加知识库、模型设置，已经完全跑通。
3、在docker中对容器maxkb重启。
4、再次http://localhost:80880访问，需要重新设置密码、知识库，在第2部设置好的数据全部会失效，回到刚部署的状态。

### 期待的正确结果

重新docker 容器时，已配置的数据应持续保留，而不是每次重启都清空掉。这样就没法关机了。

**Comment by zmalibaba** [comment]
已解决，我的是Windows 系统，需要把docker 容器挂载到硬盘的某个位置就可以了。步骤： 删除现有容器，重新执行docker run -d --name=maxkb -p 8080:8080 -v F:/MaxKB:/var/lib/postgresql/data 1panel/maxkb   就可以了

**Comment by hexixiang** [comment]
我在windows的wsl系统里面安装也会出现和你一样的报错，并且管理员密码一直报错，只能重置密码，重置之后所有数据都会消失。
并且没有解决

**Comment by zmalibaba** [comment]
> 我在windows的wsl系统里面安装也会出现和你一样的报错，并且管理员密码一直报错，只能重置密码，重置之后所有数据都会消失。 并且没有解决

我没试过过你说的wsl，我一直用docker desktop，按我上面的方法把容器挂载到windows的某个文件夹就可以了，实现数据持久化
