### ISSUE TITLE
[FEATURE] 自动生成推荐问题

### ISSUE THREAD

**Issue by litongjava** [1Panel-dev/MaxKB#355]
### MaxKB 版本

版本号：v1.1.1 (build at 2024-04-30T17:22, commit: 2d7562f2)

### 请描述您的需求或者改进建议

更加分段后的数据 在导入数据时自动生成 推荐问题
![img_v3_02ai_83c2d96a-72f1-49dc-b3f8-e2f0800caa3h](https://github.com/1Panel-dev/MaxKB/assets/31761981/6c55b768-9864-47f6-9768-08f1abc7b9de)
zengj

### 请描述你建议的实现方案

我测试过程
1.问 what is crn ,机器人正确回复
2.在后端管理中手动添加关联问题
3.问 what is crn 机器人错误回复
4.但是需要添加的关联问题太多,手动添加费时费力,希望可以在导入文档是自动完成这一过程

**Comment by baixin513** [comment]
感谢反馈，关联问题需要人工维护是为了提高命中率，增加答案的准确度。
自动生成关联问题无法判断问题的准确性，还会扰乱命中结果，效果可能还不如不关联问题。
关联问题维护目前还是不能偷懒的。
