### ISSUE TITLE
[FEATURE] 历史消息 向量入库 相似度 检索

### ISSUE THREAD

**Issue by litongjava** [1Panel-dev/MaxKB#356]
### MaxKB 版本

版本号：v1.1.1 (build at 2024-04-30T17:22, commit: 2d7562f2)

### 请描述您的需求或者改进建议

![img_v3_02ai_dd9ddb03-a1f0-47f2-9726-0a518f858dbh](https://github.com/1Panel-dev/MaxKB/assets/31761981/e15fbc58-88d1-4e41-87b0-f5c407f2eeb8)
![Lyf5WyK2gd](https://github.com/1Panel-dev/MaxKB/assets/31761981/b98bb777-c777-468d-ad8a-a041e473862e)
1. 问 who is instructor ,机器人回复了两门课程的instructor,who is instructor这个问题是我在后台指定的
2.但是当我询问 ics141的课程后,再次询问 who is instructor 应当只回复 ics141的instructor
3.我测试时已经开启了多轮会话

### 请描述你建议的实现方案

1.用户的会话记录也进行向量化,入库
2.用户询问问题时 不仅对 文档分片进行相似度计算 也对 历史问答记录 记录进行相似度计算
3.llmt推理

**Comment by baixin513** [comment]
感谢反馈
针对第 1 点 与issue #229 重复，后期会考虑。
针对第 2 点 暂不考虑，若把第一点的会话记录存入知识库后，也没有必要做第二点。
第3 个没明白

**Comment by litongjava** [comment]
1.用户的会话记录也进行向量化,入库
2.用户询问问题时 不仅对 文档分片进行相似度计算 也对 历史问答记录 记录进行相似度计算
3.llm推理

问答记录可能会被继承造成幻觉。因为同一个问题不同，实际的回答并不相同。建议分开存储。并在问答时提供一个选项开关。

第3点打错字了。是llm推理

顺便问一个小问题
能否更换到专用的向量数据库，以提高性能

**Comment by baixin513** [comment]
当前不可以更换数据库，只能是 PgSQL，目前性能是没有问题的。

会话记录存储的请在issue #229 中跟进一下状态。
