### ISSUE TITLE
[BUG]创建新用户时用户名含有 0 时校验不通过

### ISSUE THREAD

**Issue by gundamwing01** [1Panel-dev/MaxKB#358]
### MaxKB 版本

1.1.1

### 问题描述

MaxKB里要创建新用户，但是设置条件太苛刻，太繁琐。并且根据系统要求设定了用户名又通不过
![image](https://github.com/1Panel-dev/MaxKB/assets/22724517/13380c3d-b505-4a25-a96a-4e14c37f74d5)

### 重现步骤

![image](https://github.com/1Panel-dev/MaxKB/assets/22724517/06aafa76-bc68-49de-a46b-089a91f097dc)

### 期待的正确结果

希望尽快修复BUG，将用户名和密码的设定规则交给客户，不要弄这么多繁琐的要求。

### 附加信息

![image](https://github.com/1Panel-dev/MaxKB/assets/22724517/ae5b0c55-aa4b-4379-a98d-7f8e1125ebab)

**Comment by baixin513** [comment]
感谢反馈，确认为 bug，用户名中含有0 校验不通过，下个版本修复。
