### ISSUE TITLE
更多关于个人用户使用上的功能

### ISSUE THREAD

**Issue by belugaming** [1Panel-dev/MaxKB#359]
### MaxKB 版本

最新

### 请描述您的需求或者改进建议

尊敬的开发者您好，请问可以在之后的版本中添加聊天记录以及兼容多模态语言模型的功能吗，比如用OpenAI的API可以给它在聊天的时候发一些PDF文件或者图片

**Comment by baixin513** [comment]
与 issue #295 重复
