### ISSUE TITLE
[FEATURE] 希望能够支持从Git文档仓库同步导入Markdown

### ISSUE THREAD

**Issue by shugen002** [1Panel-dev/MaxKB#36]
### MaxKB 版本

v0.9.1

### 请描述您的需求或者改进建议

很多文档是采用Markdown编写的，通过直接读取对应的Git仓库，可以直接跳过文档渲染器带来的影响，获取干净的信息。

（最好能够支持Gitea就好了）

### 请描述你建议的实现方案

注册成gitea/github应用，然后借助webhook触发自动同步更新信息

**Comment by baixin513** [comment]
感谢反馈，我们先讨论一下。

**Comment by baixin513** [comment]
经讨论：Github仓库中的文档项目为单页面应用，目前没有比较好的实现方案。近期暂不考虑。
Github 上的 wiki是多页面的，我们下个版本支持 Github上wiki 文档的自动抓取。

**Comment by shugen002** [comment]
所以是对于类似 https://github.com/jumpserver/docs/ 这类的git仓库的自动抓取是暂时不做支持吗？
但对于 https://github.com/1Panel-dev/MaxKB/wiki 这种做支持吗？

但我认为，要是做了第一个那种仓库的支持，那么对于下面这种也是同样可以被覆盖到的，都是可以通过`git clone https://github.com/1Panel-dev/MaxKB.wiki.git`来拉取内容

**Comment by baixin513** [comment]
1、自动获取wiki数据 的当前已经支持，只是存在bug下个版本就正常了。
2、仓库的这种目前实现方案如你所说：先克隆到本地，然后对目录下文档进行遍历，上传支持的文档格式。中间不确定性因素较多，近期暂时没规划。
3、当前你可以自行克隆到本地，然后上传离线文档到知识库。我们到是可以优化一下上传文档时支持选择文件夹，自动上传文件夹下面所有符合格式的文件。

> 所以是对于类似 https://github.com/jumpserver/docs/ 这类的git仓库的自动抓取是暂时不做支持吗？ 但对于 https://github.com/1Panel-dev/MaxKB/wiki 这种做支持吗？
> 
> 但我认为，要是做了第一个那种仓库的支持，那么对于下面这种也是同样可以被覆盖到的，都是可以通过`git clone https://github.com/1Panel-dev/MaxKB.wiki.git`来拉取内容
