### ISSUE TITLE
增加联网功能

### ISSUE THREAD

**Issue by 496672097** [1Panel-dev/MaxKB#360]
### MaxKB 版本

最新

### 请描述您的需求或者改进建议

希望增加一个如同百度智能体一样的联网功能，最好能有限定网站搜索的设置，可以开启和关闭。
![image](https://github.com/1Panel-dev/MaxKB/assets/20740855/08080649-30e6-4eff-80f8-5f912154e68d)

**Comment by baixin513** [comment]
感谢反馈，近期暂无该计划。
