### ISSUE TITLE
本地源码方式启动报错

### ISSUE THREAD

**Issue by shuyixiao0917** [1Panel-dev/MaxKB#362]
### 联系方式

chinasjh2022@126.com

### MaxKB 版本

v1.1.1发行版

### 问题描述

源码方式启动之后报错启动不成功
![image](https://github.com/1Panel-dev/MaxKB/assets/111023943/e4455aa5-5114-4eb6-af47-34f6fc3638f9)
![image](https://github.com/1Panel-dev/MaxKB/assets/111023943/d24529e8-5c99-41db-8016-08bccf91890d)

### 重现步骤

下载v1.1.1源码方式启动就出现了

**Comment by shaohuzhang1** [comment]
你的pgsql数据库是否是utf-8编码

**Comment by shuyixiao0917** [comment]
> 你的pgsql数据库是否是utf-8编码

是的，为此我还特意昕创建了一个utf-8的数据库

**Comment by shaohuzhang1** [comment]
排查一下你的本地开发环境,或者使用main的最新代码试一下
