### ISSUE TITLE
[FEATURE] 支持上传html格式的文档

### ISSUE THREAD

**Issue by zexho994** [1Panel-dev/MaxKB#364]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

希望可以支持html , md格式中table的友好切割方式，来提高table数据的命中率

**Comment by baixin513** [comment]
感谢反馈，关于html的后续可以考虑支持一下。
md格式中table的友好切割方式是怎么个友好切割法？ 没太明白。

**Comment by zexho994** [comment]
比如markdown的格式
| Month    | Savings |
| -------- | ------- |
| January  | $250    |
| February | $80     |
| March    | $420    |

现在无论哪种切割方式，切割了table后，每一行的数据关联不到列，这样就失去了数据的语义了。
假如可以 Month=january , Savings=250 , Monty=February, Savings=80这样，就可以让table的每一行数据保证原有的语义。
现在MaxKB提供了很多的分段规则，希望这个点也可以变为一种可选切割规则，因为在实际使用时表格的回答效果不太好。

**Comment by baixin513** [comment]
使用 markdown 样式的表格导入后，会按 markdown 样式切割表格。如下图
<img width="1241" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/a9a6a165-30e6-4537-9038-db7a80b09be1">

提问后只要命中分段，测试了一下回答也是正确的，你使用的什么模型呢？
<img width="756" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/7b799f78-68bd-43e1-a918-2934045bf8e3">

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
