### ISSUE TITLE
[FEATURE]是否考虑可配置文档向量化模型

### ISSUE THREAD

**Issue by XHP007** [1Panel-dev/MaxKB#366]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

目前MaxKB知识库创建时，文档向量化应该使用的是text2vec。能否考虑可以配置向量化模型，方便用户问答调优，以及提高MaxKB项目的灵活性。

**Comment by baixin513** [comment]
感谢反馈，该需求与 issue #60 重复
