### ISSUE TITLE
[FEATURE]【应用编排】增加 HTTP API 访问数据

### ISSUE THREAD

**Issue by ljp888** [1Panel-dev/MaxKB#369]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

知识库增加通过API接口访问数据,直接调用给到大模型 ,这样就不用把原有的数据导入知识库了, 知识库数据同步比较费劲不能实时更新知识库

**Comment by baixin513** [comment]
感谢反馈，需要在支持编排工作流之后 再考虑一下。
