### ISSUE TITLE
[BUG]建立WEB站点知识库时URL错误，无法解析网址

### ISSUE THREAD

**Issue by Robert-ZLF** [1Panel-dev/MaxKB#374]
### MaxKB 版本

v1.1.1

### 问题描述

在建立WEB站点知识库时，遇到URL错误，无法解析网址的情况。
想解析的地址为https://www.tbquant.net/helper
1. 当这个地址作为根目录时报错，本地电脑可以正常访问
<img width="736" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/42110848/c341b963-5941-4490-b6e2-5247c5d033f5">
2. 当在添加文档时加入这个地址是却显示导入成功
<img width="987" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/42110848/03ec6475-3605-4fc0-a99f-547d4a74dbe1">
但是在文档列表里找不到
3. 在添加文档加入这个地址的字地址后https://www.tbquant.net/faq?position=toc22 不能获取数据
<img width="2231" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/42110848/2106abb1-2962-480e-b22b-29647f147b88">

### 重现步骤

同问题描述

### 期待的正确结果

正常爬取https://www.tbquant.net/helper页面及其子页面上的文字内容

**Comment by baixin513** [comment]
感谢反馈，https://www.tbquant.net/helper  是单页面应用，当前是无法解析的，maxkb 不支持单页面应用的网页爬取。

<img width="1145" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/4f47f7e9-9afb-4682-adf0-094c835827de">
