### ISSUE TITLE
是否可以适配其他方式部署的大模型接口，例如Fastchat、TensorRT-LLM[FEATURE]

### ISSUE THREAD

**Issue by Camelia9704** [1Panel-dev/MaxKB#377]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

关于调用大模型推理的部分，是否可以将其他部署方式的接口封装成现有的形式接入

### 请描述你建议的实现方案

如果可行的话，可以在model provider下增加示例代码？

**Comment by baixin513** [comment]
感谢反馈，暂时还没有计划。
