### ISSUE TITLE
[BUG] 添加模型时 表单未清空

### ISSUE THREAD

**Issue by wivw0306** [1Panel-dev/MaxKB#378]
### MaxKB 版本

v1.1.1

### 问题描述

1、先随意选中一个厂商，比如选中openai，然后点击添加模型，选中模型，然后点击基础模型下拉，看到的是当前厂商的模型累表。此时无任何问题。
2、当改变选中厂商后，比如这次选中的是ollama，然后点击添加模型，然后点击基础模型下拉，此时将出现问题，看到的是openai的下拉列表。

### 重现步骤

<img width="989" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/95760640/3440f6a5-e716-475a-8b1b-fb07b574353d">

### 期待的正确结果

改进建议：
1、建议点击基础下拉时，下拉列表必须根据当前所选的厂商 和 必选 模型类型后才能进行下拉显示。

**Comment by baixin513** [comment]
感谢反馈，添加模型的时候未清空表单，后续版本可以优化一下。
