### ISSUE TITLE
建立了应用，但是问问题的时候，一直显示回答中，一直不给结果

### ISSUE THREAD

**Issue by quzefeng** [1Panel-dev/MaxKB#379]
### 联系方式

16819749@qq.com

### MaxKB 版本

v1.1.1

### 问题描述

建立了应用，但是问问题的时候，一直显示回答中，一直不给结果,CPU占用率也不高；知识库也建立了，模型我换成通义千问就可以回答；但是用llama2，就不反馈没有任何应答；
![QQ截图20240507162526](https://github.com/1Panel-dev/MaxKB/assets/17823304/56456c58-c813-4bcb-91dd-e2d391eb4d0b)
![QQ截图20240507162555](https://github.com/1Panel-dev/MaxKB/assets/17823304/4a62340c-bfb9-41ea-97f4-b662c5fb1a47)
![QQ截图20240507162623](https://github.com/1Panel-dev/MaxKB/assets/17823304/b6a455c6-d463-45b2-ad2b-a5d699474259)
![4](https://github.com/1Panel-dev/MaxKB/assets/17823304/433b7282-e09b-4003-b8ed-33cb63da9243)
![5](https://github.com/1Panel-dev/MaxKB/assets/17823304/babeff5f-5348-46dd-bac4-e56ff93b5663)

### 重现步骤

建立知识库，建立应用。

**Comment by baixin513** [comment]
参考一下这个帖子的调整建议：https://bbs.fit2cloud.com/t/topic/4855
