### ISSUE TITLE
[FEATURE]对话日志可以关联到已存在文档

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#383]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

目前对话日志只能选择新建文档，但实际情况是很多时候可以关联到已经录入的内容。

### 请描述你建议的实现方案

对话日志可以关联到已经存在的文档

**Comment by baixin513** [comment]
感谢反馈，对话日志可以关联到已存在的文档。
