### ISSUE TITLE
[BUG] 找不到模块

### ISSUE THREAD

**Issue by renziyou** [1Panel-dev/MaxKB#385]
### MaxKB 版本

1.1.1

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/8150303/86107771-99d3-4858-807e-f1f23eba05e8)

node:v20.13.0
Python: 3.12.3

### 重现步骤

打开代码报找不到模块

**Comment by baixin513** [comment]
1.进入前端项目
cd ui
2.安装依赖
npm i 
3.启动
npm run dev
4.打包
npm run build

**Comment by renziyou** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/8150303/f3b83000-f3d8-40a3-846e-e8a23ebe814d)

**Comment by renziyou** [comment]
> 1.进入前端项目 cd ui 2.安装依赖 npm i 3.启动 npm run dev 4.打包 npm run build

![image](https://github.com/1Panel-dev/MaxKB/assets/8150303/3cb356ec-87e4-4cbb-8eec-3bdf8cac3124)
