### ISSUE TITLE
无法提供本地知识库的具体引用文档及引用位置

### ISSUE THREAD

**Issue by forverd** [1Panel-dev/MaxKB#386]
### MaxKB 版本

 v1.1.1

### 请描述您的需求或者改进建议

回到问题后可否补充答案中引用了具体哪个文档的具体位置
具体格式可参照论文引用文档的格式

**Comment by baixin513** [comment]
感谢反馈，在应用-概览- 访问限制中打开显示知识来源，即可在问答时查看引用的内容。
<img width="816" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/de3efe92-a8e9-4b39-b21f-9fd4f875740e">
