### ISSUE TITLE
[FEATURE]对话日志可以关联到已存在文档

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#389]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

 很多时候对话日志中的问题是已经存在的问题，但是没有关联到正确的分段，希望可以在对话日志这里能快捷的关联到已存在分段，否则的话需要另外开一个tab 去寻找已存在分段

**Comment by baixin513** [comment]
对话列表关联也是要查询知识库-文档-分段，一样的操作。暂不考虑
