### ISSUE TITLE
[BUG]执行命令之后，container建好了，但是没有打印访问网址

### ISSUE THREAD

**Issue by loong1118** [1Panel-dev/MaxKB#39]
### MaxKB 版本

登陆不上

### 问题描述

![3](https://github.com/1Panel-dev/MaxKB/assets/160469332/0ddd1103-eaa2-4f14-b5fd-34f9371860a2)

### 重现步骤

执行你们的docker run

**Comment by wanghe-fit2cloud** [comment]
你的服务器已存在名为 `maxkb` 的容器，请手动执行以下命令强制删除该容器，然后再使用 `docker run` 命令安装 `MaxKB`。

```shell
docker rm -f maxkb
`

**Comment by loong1118** [comment]
> 你的服务器已存在名为 `maxkb` 的容器，请手动执行以下命令强制删除该容器，然后再使用 `docker run` 命令安装 `MaxKB`。
> 
> ```shell
> docker rm -f maxkb
> ```

![1](https://github.com/1Panel-dev/MaxKB/assets/160469332/78daffbe-ac3c-472c-a31f-20ed79e5cb2d)
并没有用

**Comment by wanghe-fit2cloud** [comment]
仔细看返回结果，那不是已经提示成功删除容器并创建成功了吗？

**Comment by loong1118** [comment]
> 仔细看返回结果，那不是已经提示成功删除容器并创建成功了吗？

对呀，但是我如何进到前端页面去使用服务呢？MD里不是讲的会在控制台里打印访问网址么

**Comment by loong1118** [comment]
> 仔细看返回结果，那不是已经提示成功删除容器并创建成功了吗？

![1](https://github.com/1Panel-dev/MaxKB/assets/160469332/02493317-e38e-4c9a-9c8f-523e5c822537)
还是这个地方直接填我本地IP就可以了

**Comment by wanghe-fit2cloud** [comment]
> 还是这个地方直接填我本地IP就可以了

是的，替换成服务器 IPv4 地址和对外暴露的容器端口。

**Comment by loong1118** [comment]
> > 还是这个地方直接填我本地IP就可以了
> 
> 是的，替换成服务器 IPv4 地址和对外暴露的容器端口。

成功使用服务了 感谢
