### ISSUE TITLE
[FEATURE]支持多种embedding模型

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#390]
### MaxKB 版本

 1.1.1

### 请描述您的需求或者改进建议

 一个新的知识库/应用在初次创建时支持选择另外的embedding模型，默认的模型不太好用

### 请描述你建议的实现方案

可以在合适的地方选择embedding模型

**Comment by baixin513** [comment]
感谢反馈，该需求与 issue #60 重复。
