### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ccynet** [1Panel-dev/MaxKB#393]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

【知识库】希望增加通过API接口方式增加知识库的方式，实现动态添加知识库

**Comment by shaohuzhang1** [comment]
可以访问 访问接口文档 调用接口实现
接口文档地址:
![image](https://github.com/1Panel-dev/MaxKB/assets/80892890/f6a63742-fa0c-4df9-bca9-3cdea9cafdf5)
