### ISSUE TITLE
[FEATURE]是否通过引入neo4j，增强知识检索的准确性

### ISSUE THREAD

**Issue by doriszhang2020** [1Panel-dev/MaxKB#396]
### MaxKB 版本

最新

### 请描述您的需求或者改进建议

目前检索准确性不高，且需要手动关联，非常不好。

### 请描述你建议的实现方案

参考huggingfists
【知识图谱之从大模型到Neo4j-哔哩哔哩】 https://b23.tv/bgJnFUP

### 附加信息

～

**Comment by baixin513** [comment]
感谢反馈，技术栈不同，无法采纳。
