### ISSUE TITLE
[FEATURE]怎么指定默认登录信息

### ISSUE THREAD

**Issue by yuanjie-ai** [1Panel-dev/MaxKB#399]
### MaxKB 版本

lastest

### 请描述您的需求或者改进建议

默认登录信息
用户名：admin
默认密码：MaxKB@123..

### 请描述你建议的实现方案

默认登录信息
用户名：admin
默认密码：MaxKB@123..

### 附加信息

默认登录信息
用户名：admin
默认密码：MaxKB@123..

**Comment by baixin513** [comment]
没看明白，默认登录信息就是你部署后 登录系统的用户名和密码。

你是想调 API 接口么？

**Comment by OnesZhang** [comment]
默认账号密码是在代码里写死的，如果想指定的话，自己编译。
[apps/users/migrations/0001_initial.py](https://github.com/1Panel-dev/MaxKB/blob/7f30d03abda16fce2b91b50f0f2ca91b4180b6e9/apps/users/migrations/0001_initial.py#L10)

**Comment by baixin513** [comment]
MaxKB 部署完登录 admin后会提示你修改密码可以修改默认的密码。

但如果你想部署完成使用你指定的默认登录信息，你需要自行二开修改。
