### ISSUE TITLE
[FEATURE]导入分段的时候能批量导入关联问题么

### ISSUE THREAD

**Issue by ljp888** [1Panel-dev/MaxKB#400]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

再大量导入分段数据的时候,测试命中低,需要添加关联问题,有时候数据量太大每个分段添加关联问题根本不实际, 最后带导入分段的时候有特定格式能把关键词导入分段中的关联问题
比如 [关键词1,关键词2] 等等  设置一个固定的格式

**Comment by baixin513** [comment]
下个版本v1.1.2可以在导入文档时 把标题 设置为关联问题，明天发布。
文档维护时，可以把问题 前加个 # 或者设置为标题格式。 

与 issue #177 重复
