### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wjcaozhi** [1Panel-dev/MaxKB#402]
### MaxKB 版本

v1.1.1 (build at 2024-04-30T17:22, commit: 2d7562f2)

### 问题描述

docker 方式启动 无法创建数据库
错误提示如下:
2024/5/9 16:30:49popen failure: Cannot allocate memory
2024/5/9 16:30:49initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/15/bin/initdb"
2024/5/9 16:30:59127.0.0.1:5432 - no response
2024/5/9 16:31:00waiting for postgres
2024/5/9 16:31:00127.0.0.1:5432 - no response
2024/5/9 16:31:01waiting for postgres
2024/5/9 16:31:01127.0.0.1:5432 - no response
2024/5/9 16:31:02waiting for postgres
2024/5/9 16:31:02127.0.0.1:5432 - no response

### 重现步骤

安装进行并启动：
docker run -d --name=maxkb -p 8080:8080 -v /home/maxkb/data:/var/lib/postgresql/data 1panel/maxkb
容器启动后内部日志报错:
2024/5/9 16:30:49popen failure: Cannot allocate memory
2024/5/9 16:30:49initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/15/bin/initdb"
2024/5/9 16:30:59127.0.0.1:5432 - no response
2024/5/9 16:31:00waiting for postgres
2024/5/9 16:31:00127.0.0.1:5432 - no response
2024/5/9 16:31:01waiting for postgres
2024/5/9 16:31:01127.0.0.1:5432 - no response
2024/5/9 16:31:02waiting for postgres
2024/5/9 16:31:02127.0.0.1:5432 - no response

**Comment by baixin513** [comment]
参考 issue #46
