### ISSUE TITLE
[FEATURE]嵌入第三方浮窗模式建议

### ISSUE THREAD

**Issue by OnesZhang** [1Panel-dev/MaxKB#403]
### MaxKB 版本

v1.1.1

## 按钮置于页面最上层
embeb.js中`#maxkb .maxkb-chat-button`
建议增加`z-index: 1000;`使按钮悬浮于最上方
（因为我遇到了不能点击的问题，我的网站自身设置有z-index将.maxkb-chat-button覆盖了）
| 无z-index | 有z-index |
|--------|--------|
| ![image](https://github.com/1Panel-dev/MaxKB/assets/49380376/1f68b1a1-94ae-4e2e-9f0b-d7f32c08d81a) | ![image](https://github.com/1Panel-dev/MaxKB/assets/49380376/23ec33e1-654e-4415-9bca-395695345d29) |

## 建议后台可以配置`第一次进来的引导提示`
1. 是否开启首次引导
2. 首次引导的文字内容

**Comment by baixin513** [comment]
感谢反馈，暂时还没有计划加设置， 这里你可以使用 iframe 方式嵌入。
