### ISSUE TITLE
[FEATURE] 功能建议

### ISSUE THREAD

**Issue by myshzzx** [1Panel-dev/MaxKB#413]
### MaxKB 版本

-

### 请描述您的需求或者改进建议

- 建议支持自动爬取知识库, 通常企业都有自己的知识库, 让用户导入文档不是个好办法
- 建议支持本地 LLM 训练自己的知识库, 真正做到 LLM与企业知识库结合

**Comment by ljp888** [comment]
不太现实,每个公司的数据库格式都不一样, 还不如调用公司的数据接口 固定好格式,然后把返回的结果当分段给大模型这样会不会好点

**Comment by myshzzx** [comment]
html格式不一样?

**Comment by myshzzx** [comment]
> 不太现实,每个公司的数据库格式都不一样, 还不如调用公司的数据接口 固定好格式,然后把返回的结果当分段给大模型这样会不会好点

html格式不一样?

**Comment by baixin513** [comment]
感谢反馈，由于每家公司的知识库类型不一样，当前只支持多页面的web站点爬取， 近期暂无计划支持，后期支持对接也会选择主流的知识库平台。
