### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by wuyeguo** [1Panel-dev/MaxKB#417]
### MaxKB 版本

版本号：v1.1.1 (build at 2024-04-30T17:22, commit: 2d7562f2)

### 请描述您的需求或者改进建议

1. 演示界面不提示知识库数据，但是调试界面是有的
![调试预览](https://github.com/1Panel-dev/MaxKB/assets/421034/48e096c7-2caa-4bae-a467-74ec567145bc)
![演示](https://github.com/1Panel-dev/MaxKB/assets/421034/3345238d-16fc-4980-8e2d-86e26b7cd4d1)

2.  是否可以在日志中给出提交给下游模型的提示语，便于调试？

**Comment by baixin513** [comment]
<img width="1018" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/f84e015b-bd6a-4048-a7fa-ddd970c6f907">

如上图打开显示知识来源 ，客户端提问就会显示了

**Comment by wuyeguo** [comment]
> <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/52996290/329536069-f84e015b-bd6a-4048-a7fa-ddd970c6f907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTM0OTMsIm5iZiI6MTcxNTM5MzE5MywicGF0aCI6Ii81Mjk5NjI5MC8zMjk1MzYwNjktZjg0ZTAxNWItYmQ2YS00MDQ4LWE3ZmEtZGRkOTcwYzZmOTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAyMDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZjM5NTRkY2YwOTZmZjU2ZTQ4MDZkZjI3YmI4Y2E5NWFmNWFmZWFkYzkxMmU3YTRlOWIxOWJkMjYyNWM4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lkahgu1xWrBHZUxTNP1J28reO3kvHA0_hJUBpou5WO8">
> 如上图打开显示知识来源 ，客户端提问就会显示了

谢谢，没注意，第二个问题有办法么？
后端用的ollma，用lamma3的时候，总是返回英文，不过我自己和lamma3聊天并不会，不知道不知道到底是什么什么导致的，所以想看看提示词是啥

**Comment by baixin513** [comment]
> > <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/52996290/329536069-f84e015b-bd6a-4048-a7fa-ddd970c6f907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTM0OTMsIm5iZiI6MTcxNTM5MzE5MywicGF0aCI6Ii81Mjk5NjI5MC8zMjk1MzYwNjktZjg0ZTAxNWItYmQ2YS00MDQ4LWE3ZmEtZGRkOTcwYzZmOTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAyMDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZjM5NTRkY2YwOTZmZjU2ZTQ4MDZkZjI3YmI4Y2E5NWFmNWFmZWFkYzkxMmU3YTRlOWIxOWJkMjYyNWM4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lkahgu1xWrBHZUxTNP1J28reO3kvHA0_hJUBpou5WO8">
> > 如上图打开显示知识来源 ，客户端提问就会显示了
> 
> 谢谢，没注意，第二个问题有办法么？
> 后端用的ollma，用lamma3的时候，总是返回英文，不过我自己和lamma3聊天并不会，不知道不知道到底是什么什么导致的，所以想看看提示词是啥

提示词中加上：请使用中文回答问题。
