### ISSUE TITLE
[FEATURE] 在聊天界面支持新建对话，以及对话切换

### ISSUE THREAD

**Issue by Virtual1257** [1Panel-dev/MaxKB#418]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

目前的应用聊天页面不能新建对话，也不支持直接切换对话，希望可以在同一个应用下，新建多个对话，类似于下图
![image](https://github.com/1Panel-dev/MaxKB/assets/26375052/29a48882-cb29-487a-bbe9-db37fda19aed)

**Comment by baixin513** [comment]
感谢反馈，已存在相同issue，下个版本支持。

**Comment by Virtual1257** [comment]
非常感谢您对开源的贡献，我想问一下目前版本更新的频率是一周一个版本吗？下个版本预计什么时候发布？

**Comment by baixin513** [comment]
正常功能版本迭代是每月一个，当有bug时会尽快修复发出小版本，若有已完成的新功能也会随小版本发出。
用户反馈比较多的功能会优先安排开发，让用户早点用上。
