### ISSUE TITLE
[BUG]内存和CPU占用实在太高了

### ISSUE THREAD

**Issue by neatstudio** [1Panel-dev/MaxKB#419]
### MaxKB 版本

最新版

### 问题描述

1、一共换了三个模型 ：llama2:13b / chinese /和默认的。
2、除了默认是占用4G左右内存外，其他都占用在8G左右的内存
![image](https://github.com/1Panel-dev/MaxKB/assets/229186/b7bdb84a-ad63-4c6a-b882-9355490ce8cf)

### 重现步骤

直接安装最新版，ollama模型也是最新（昨天：2024-05-09），刚刚测试
1、设置为WEB知识库时，直接将我的网站拉崩了
2、当可用知识库较少时，内存和CPU的占用并没有减少

### 期待的正确结果

期望：
1、即使是有限的知识库，也能够相对正常输出
2、CPU占用减少
3、抓取WEB内容时，能够减小并发，我可以接受抓1天甚至2天，但不能接受把目标网站抓崩

**Comment by shaohuzhang1** [comment]
cpu占用高是因为要做向量化处理
抓取web内容的时候,是没有并发拉取的.

**Comment by shaohuzhang1** [comment]
ollama调用模型是需要很大的算力的,建议用gpu

**Comment by neatstudio** [comment]
> 1.cpu占用高是因为要做向量化处理。 2.抓取web内容的时候,是没有并发拉取的。 3.ollama调用模型是需要很大的算力的,建议用gpu。

主要是看你们的介绍视频里写2核4G也能跑。但没想到影响这么大。只能先缓一缓再使用了，或者什么时候有了GPU再说了

**Comment by shaohuzhang1** [comment]
maxkb只需要2核4g就可以了,ollama跑模型需要很多的算力资源
你可以使用在线模型比如讯飞星火,新用户免费200wtokens

**Comment by neatstudio** [comment]
我大概知道 网站为什么被 爬崩了。。好象是触发 了1panel的 waf。我等会再试一下。
