### ISSUE TITLE
[BUG] 导入的文档删除部分的分段后，字符数不会重新计算

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/MaxKB#421]
### 联系方式

i@chish.cn

### MaxKB 版本

v1.1.2

### 问题描述

导入文档，删除部分分段后，文档预览的字符数量不会重新计算，但分段数正常

排查操作：
- 刷新页面，强制（清除缓存）刷新页面
- 清除所有 cookie ，缓存
- 使用无痕模式浏览

使用以上操作均无效

> 获取版本时，发现左上角关于页面的版本号消失了
> ![image](https://github.com/1Panel-dev/MaxKB/assets/76027184/502ca619-a57a-4f30-b103-8a3f452df91b)

### 重现步骤

导入任意文档，删除部分分段或全部删除

### 期待的正确结果

字符数能够重新计算

**Comment by shaohuzhang1** [comment]
感谢反馈，已确定bug，下个版本修复。

**Comment by ChishFoxcat** [comment]
@shaohuzhang1 你好，不知道为什么，更新版本后依然有此类 bug ，请问是什么原因

![image](https://github.com/1Panel-dev/MaxKB/assets/76027184/bad83dbe-dc4e-46d0-b035-906d77e13ca6)

![image](https://github.com/1Panel-dev/MaxKB/assets/76027184/4ffdf4ef-30d7-4e81-856e-0b3beab52206)

**Comment by shaohuzhang1** [comment]
你添加一个分段就好了 历史数据没更新

**Comment by ChishFoxcat** [comment]
> 你添加一个分段就好了 历史数据没更新

删除掉最后一个分段会提示错误
![image](https://github.com/1Panel-dev/MaxKB/assets/76027184/d19d4e6b-5dc8-4691-a441-79b2e228b7b3)

但最终还是会被删掉
![image](https://github.com/1Panel-dev/MaxKB/assets/76027184/bc8b4e73-e72c-47ba-b424-2382d2bd4cad)

![image](https://github.com/1Panel-dev/MaxKB/assets/76027184/55d06872-6908-43cf-bb60-42e62fdb2480)
