### ISSUE TITLE
[FEATURE]本地化其他模型: vLLM和Xinference

### ISSUE THREAD

**Issue by Readyou123** [1Panel-dev/MaxKB#423]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

希望能够本地加载ollama之外的大模型，例如chatglm

**Comment by baixin513** [comment]
感谢反馈，需要研究一下对接方式，方便的话会进行对接。

**Comment by baixin513** [comment]
本地化模型供应商 在 1.5.0 版本还会支持 vLLM和Xinference 。
