### ISSUE TITLE
建议增加保存对话功能的同时增加删除对话功能

### ISSUE THREAD

**Issue by kbc1118** [1Panel-dev/MaxKB#426]
### MaxKB 版本

1.1.2

### 请描述您的需求或者改进建议

建议增加保存对话功能的同时增加删除对话功能，比如一个月删除一次或三个月删除，还有删除所有对话。
毕竟对话太多的时候硬盘容量也会占用的。

### 请描述你建议的实现方案

建议增加保存对话功能的同时增加删除对话功能，比如一个月删除一次或三个月删除，还有删除所有对话。
毕竟对话太多的时候硬盘容量也会占用的。

**Comment by baixin513** [comment]
感谢反馈，目前对话日志是保留近半年，不计划增加删除日志的功能，原因如下：
1.应用概览中的监控统计是根据记录的日志详情进行统计的，如果放开让用户删除对话日志，会导致统计数据不准，
2.用户删除对话记录，管理维护人员也无法跟踪查证用户真实的对话记录。
