### ISSUE TITLE
建议在前端显示引用知识库内容时，能直接预览

### ISSUE THREAD

**Issue by gzcls** [1Panel-dev/MaxKB#427]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/MaxKB/assets/136059643/daca2d24-e0a9-4bd8-bebc-2b722b9140af)

**Comment by baixin513** [comment]
感谢反馈，在应用— 概览—访问限制中有个显示知识来源的开关，打开后用户端提问就会显示知识来源

**Comment by gzcls** [comment]
引用知识来源设置我知道，我意思是点开这个知识来源，显示的内容希望能用markdwon格式显示出来。

baixin ***@***.***> 于2024年5月12日周日 08:14写道：
