### ISSUE TITLE
用户提问时增加认证验证功能

### ISSUE THREAD

**Issue by gzcls** [1Panel-dev/MaxKB#428]
### MaxKB 版本

1.1.1

### 请描述您的需求或者改进建议

实际场景：在企业内部可能存在多个知识库问答系统，并面对不同的用户群，希望能增加用户管理功能（可在后台中针对当关应用设置是否需启用用户管理，当启用时，用户打开应用时需进行用户登陆），实现保密型知识库只面向特定用户。

**Comment by baixin513** [comment]
感谢反馈， 可以考虑一下，在访问限制增加提问认证 ，当用户打开提问页面时先输入配置认证 key，验证通过则可以提问。

**Comment by zyyfit** [comment]
1.7.0版本已发布，请更新到最新版使用
