### ISSUE TITLE
[FEATURE] 建议增加用户注册和模型共享功能

### ISSUE THREAD

**Issue by mantoufan** [1Panel-dev/MaxKB#429]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

非常好的系统，只需两步成为一个多用户的知识库，每个用户可以使用管理员已经添加的模型，创建自己的知识库：
1. 管理员可以设置哪些模型允许共享（其它用户可以直接使用）
2. 开放用户注册入口

### 请描述你建议的实现方案

1. 在模型设置 → 增加模型时 → 添加是否允许共享的复选框
2. 在登录界面（首页）→ 用户注册按钮

**Comment by baixin513** [comment]
感谢反馈
1.MaxKB定位是企业知识库，用户需要有admin来统一进行可控管理，不计划增加注册功能。

2.MaxKB用户是一个个体，用户下的资源都属于自己，可以添加成员协作维护资源，但一般需要维护的是知识库和应用，模型无须协作维护。如果给成员分配了应用管理权限，成员是可以修改应用模型为创建者所有可用模型的。

再就知识库，应用和模型之间关联的前提是创建者必须属于同一个用户。不同用户的资源相互关联使用会乱。

暂时不计划模型共享使用。
