### ISSUE TITLE
[FEATURE]增加前端、后端、数据库分离部署的方式

### ISSUE THREAD

**Issue by gyj0825** [1Panel-dev/MaxKB#43]
### MaxKB 版本

v1.0.0

### 请描述您的需求或者改进建议

建议增加分离部署，不是必须使用all-in-one的模式，增加更多灵活性。尤其是vactorDB。

**Comment by liqiang-fit2cloud** [comment]
目前没有计划支持前后端分离部署。
数据库分离部署请参考https://github.com/1Panel-dev/MaxKB/issues/31 。
