### ISSUE TITLE
[FEATURE]不支持Excel？不难吧，去年的Chatchat都有了

### ISSUE THREAD

**Issue by wwweber** [1Panel-dev/MaxKB#430]
### MaxKB 版本

1.1.0

### 请描述您的需求或者改进建议

建议增加结构化表格excel及csv，这样方便结构化数据导入

**Comment by baixin513** [comment]
感谢反馈， 你指的是Excel 表格整理的问答对内容么？

**Comment by wwweber** [comment]
大多数是 QA 形式的
也有一部分是结构化知识库，比如医学类的名称，功效，用法，用量，意义，案例，等等

**Comment by baixin513** [comment]
了解，我们后续考虑一下吧。

**Comment by baixin513** [comment]
我们近期会支持 Excel 问答对的文档类型。需要按照模板格式整理内容。

**Comment by liqiang-fit2cloud** [comment]
我觉得excel和csv这种可以直接按行分段？

**Comment by baixin513** [comment]
当前先支持Excel /csv 问答对的格式，录入系统时可以自动关联相关问题，减少操作。
需要按照下方格式整理
<img width="1228" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/0ed739ce-c249-441d-8ed7-214de309d1ae">

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
