### ISSUE TITLE
[BUG]批量导入选中将标题添加关联问题,标题为空时报错

### ISSUE THREAD

**Issue by ljp888** [1Panel-dev/MaxKB#432]
### 联系方式

234166810@qq.com

### MaxKB 版本

1.1.2

### 问题描述

![cc248eb14f7b74f93cf9022e667dd10](https://github.com/1Panel-dev/MaxKB/assets/14199299/d80f0d49-1cd7-4722-9a27-e9db2441fc83)
批量导入选中将标题添加关联问题,标题为空时报错

### 重现步骤

批量导入选中将标题添加关联问题,标题为空时报错

### 期待的正确结果

如果标题为空时不加关联问题

**Comment by baixin513** [comment]
感谢反馈，我们复现一下。

**Comment by baixin513** [comment]
我们测试了标题为空、标题为空格等情况都能正常，为了方便快速排查问题，如果方便的话可以把上传报错的文档发到我邮箱：xin.bai@fit2cloud.com  感谢反馈与配合。


<img width="1410" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/f23bb8d9-7e17-4db2-8d56-228ac9f8bc0e">

<img width="1420" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/6960c5d9-bf02-4c67-8726-b93ef819c643">

**Comment by ljp888** [comment]
已发邮箱

**Comment by baixin513** [comment]
好的，已经复现，下个版本修复。
