### ISSUE TITLE
[FEATURE]应用支持工作流编排

### ISSUE THREAD

**Issue by baixin513** [1Panel-dev/MaxKB#433]
### MaxKB 版本

1.1.2

### 请描述您的需求或者改进建议

应用支持工作流编排

**Comment by Readyou123** [comment]
工作流编排是可以自定义整个流程吗，可以任意调用各种api或者插件

**Comment by zclcz** [comment]
能做到类似agentstudio 可以制作agent吗 自定义配置工作流程实现agent
