### ISSUE TITLE
[BUG]MaxKB+ollama部署本地知识库，模型配置提示域名无效

### ISSUE THREAD

**Issue by SongTao7708** [1Panel-dev/MaxKB#441]
### 联系方式

longmiaost@126.com

### MaxKB 版本

1.1.0

### 问题描述

配置ollama模型时,提示api域名无效

### 重现步骤

本地ollama已正常启动
![12689](https://github.com/1Panel-dev/MaxKB/assets/126642458/0ca20d0c-fe1a-41d7-9e87-f0c4ba0e1718)
配置参数如下图
![4085](https://github.com/1Panel-dev/MaxKB/assets/126642458/0ccc6956-f405-4393-9b37-f05a84c7d9f4)
![17111](https://github.com/1Panel-dev/MaxKB/assets/126642458/8399c0f2-f17b-403d-b4a2-c07ce1e5a61c)

### 期待的正确结果

请问：如何解决？谢谢

**Comment by baixin513** [comment]
请参考论坛的解决方案：https://bbs.fit2cloud.com/t/topic/4165/4
