### ISSUE TITLE
[FEATURE]调用“嵌入第三方”时能传入问题，让弹窗一打开就开始回答问题

### ISSUE THREAD

**Issue by Arrding** [1Panel-dev/MaxKB#442]
### MaxKB 版本

V1.1.2

### 请描述您的需求或者改进建议

<img width="818" alt="微信图片_20240514095038" src="https://github.com/1Panel-dev/MaxKB/assets/149556585/f5586e6c-f8cc-48b3-bc4f-658075c016fd">

### 请描述你建议的实现方案

我希望能实现调用“嵌入第三方”时能传入参数（问题描述），让弹窗一打开就开始回答问题

**Comment by Arrding** [comment]
补充：传入问题这个，不是强制，用户可传可不传；为空时就按当前方式显示。

**Comment by baixin513** [comment]
感谢反馈，暂无计划支持。
