### ISSUE TITLE
[BUG] 提示词模版不生效

### ISSUE THREAD

**Issue by Jaylenwa** [1Panel-dev/MaxKB#443]
### MaxKB 版本

v1.1.2

### 问题描述

![Snipaste_2024-05-14_14-52-22](https://github.com/1Panel-dev/MaxKB/assets/65205528/ec3082d4-56b3-41bb-bf81-a4a79b97de00)

这只是一个例子，提示词模板设置成其他的也是不生效

### 重现步骤

提示词模板内容：
已知信息：
{data}
回答要求：。
- 把回答翻译成英文回复。
问题：
{question}

实际回答的效果：
回答还是用中文回答

### 期待的正确结果

回答根据提示词模板的要求输出

**Comment by baixin513** [comment]
感谢反馈，
上图应用表单中的提示词是 有命中知识库分段的提示词。 
如果没有引用知识库分段 继续问模型的话，需要在关联知识库的参数设置中 再设置一下提示词内容。
你的应该是没有引用知识库内容，可以在下面的提示词中进行设置。
<img width="1041" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/5df989a3-db14-43ad-a184-1ef496824ec6">
