### ISSUE TITLE
[BUG]没有响应

### ISSUE THREAD

**Issue by cnwillz** [1Panel-dev/MaxKB#445]
### MaxKB 版本

v1.1.2

### 问题描述

出现某一次问题回答时间很长的情况，如果另外开一个标签页访问或者刷新会导致当前浏览器会话无法访问

### 重现步骤

偶发出现，无法稳定复现
回答的请求过程中或者回答跳出文字的过程中刷新

### 附加信息

#444

**Comment by shaohuzhang1** [comment]
可能是你浏览器响应流断开了,可以检查你的网络是否开了翻墙代理之类的。
