### ISSUE TITLE
[FEATURE]开放postgresql 5432 端口外部访问

### ISSUE THREAD

**Issue by wangjiansong** [1Panel-dev/MaxKB#446]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

postgresql只能在容器内部访问，建议开放外部访问

**Comment by ljp888** [comment]
这个可以自己在服务器上设置吧

**Comment by shaohuzhang1** [comment]
你可以docker run 的时候 再加一个-p 5432:5432 就好啦
