### ISSUE TITLE
[FEATURE] endpoint不一致问题

### ISSUE THREAD

**Issue by w3nl1ng** [1Panel-dev/MaxKB#455]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

我使用ollama运行大模型时发现，ollama默认的endpoint是/api/chat，而MaxKB使用的endpoint是/v1/chat/completions
![llama-endpoint](https://github.com/1Panel-dev/MaxKB/assets/130684618/9adc87b1-184d-48fe-a2c2-acfe48f089ab)
我不知道这两个endpoint是否有区别，我实际使用上感觉/api/chat这个endpoint效果更好

**Comment by shaohuzhang1** [comment]
/api/chat和/v1/chat/completions 没有区别

**Comment by w3nl1ng** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/130684618/ae1d76d6-8f81-400e-b0ef-98e4c76ca6fa)
我看了源码，确实是这样的，谢谢解答
