### ISSUE TITLE
[FEATURE]用户问答页面显示知识来源使用markdown页面显示

### ISSUE THREAD

**Issue by lianxintao** [1Panel-dev/MaxKB#457]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

![屏幕截图_15-5-2024_13822_localhost](https://github.com/1Panel-dev/MaxKB/assets/32242545/d2a5b56b-a470-4fe0-8306-e0d8b8699b92)
现有的引用知识来源 显示不带格式，不能显示图片，表格 等数据。  建议用户问答页面显示知识来源使用markdown页面显示。因为AI模型生成的答案有时并不是很好，所以需要显示引用知识来源，建议用户问答页面显示知识来源使用markdown页面显示，使用户获得更好的阅读体验。

**Comment by baixin513** [comment]
感谢反馈，后续版本优化。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
