### ISSUE TITLE
[BUG]Docker无法正常启动

### ISSUE THREAD

**Issue by LeiyuanBlog** [1Panel-dev/MaxKB#46]
### 联系方式

15326047083@163.com

### MaxKB 版本

lastest

### 问题描述

waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres

### 重现步骤

docker run

### 期待的正确结果

start up 

### 相关日志输出

```shell
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
```

### 附加信息

waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres
127.0.0.1:5432 - no response
waiting for postgres

**Comment by baixin513** [comment]
数据库没启动，执行 docker restart maxkb 试一下。

**Comment by LeiyuanBlog** [comment]
![image](https://github.com/1Panel-dev/MaxKB/assets/44362360/3931fce1-b2c2-4e45-a35b-7823c1f64b1c)

**Comment by LeiyuanBlog** [comment]
restart不管用

**Comment by LeiyuanBlog** [comment]
解决了，centos的selinux问题，启动参数需增加 --privileged=true

**Comment by xuchunhua-com** [comment]
> 解决了，centos的selinux问题，启动参数需增加 --privileged=true

在maxkb目录下的docker-compose.yml、docker-compose-pgsql.yml中增加privileged=true

**Comment by yangfeiyi2011** [comment]
我这样添加了docker-compose.yml文件还是没用，是我添加的地方不对吗？
`networks:
    1panel-network:
        external: true
services:
    maxkb:
        container_name: ${CONTAINER_NAME}
        privileged: true
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: 1panel/maxkb:v1.8.0
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:8080
        restart: unless-stopped
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./python-packages:/opt/maxkb/app/sandbox/python-packages`

**Comment by yangfeiyi2011** [comment]
networks:
    1panel-network:
        external: true
services:
    maxkb:
        container_name: ${CONTAINER_NAME}
        privileged: true
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: 1panel/maxkb:v1.8.0
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:8080
        restart: unless-stopped
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./python-packages:/opt/maxkb/app/sandbox/python-packages

**Comment by yangfeiyi2011** [comment]
<img width="569" alt="image" src="https://github.com/user-attachments/assets/dce1118b-30ff-4241-aa2e-72e54c3a91c0" />
