### ISSUE TITLE
建议增加定期清理对话记录的功能

### ISSUE THREAD

**Issue by shanghairendaimin** [1Panel-dev/MaxKB#469]
### MaxKB 版本

1.13

### 请描述您的需求或者改进建议

在知识库中询问的问题，一般询问过几天后就不太会再使用了，这样的死数据没有长期保留的需求。建议增加自动清理的开关，可以做定期的自动清理。

**Comment by baixin513** [comment]
感谢反馈，后续可以考虑增加定时清理对话日志功能。

**Comment by zyyfit** [comment]
1.7.0版本已发布，请更新到最新版使用
