### ISSUE TITLE
[BUG]嵌入第三方网站之后聊天记录无法保存，刷新一下就没了，能导出聊天记录或者

### ISSUE THREAD

**Issue by liuzj288** [1Panel-dev/MaxKB#470]
### MaxKB 版本

v1.1.3

### 问题描述

嵌入第三方网站之后聊天记录无法保存，刷新一下就没了，

### 重现步骤

嵌入第三方网站之后聊天记录无法保存，刷新一下就没了，

**Comment by baixin513** [comment]
感谢反馈，维护者可以在 应用的对话日志中看到 聊天记录详情。 
用户端如果想看历史聊天记录需要等 1.2.0 版本，已存在该 issue。

<img width="1428" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/0ca7290c-3d9b-4873-8142-da5588da5652">

**Comment by swtseaman** [comment]
已经升级到 :v1.1.3 (build at 2024-05-15T17:49, commit: e74ba87f)，  用户端并没有历史聊天记录功能；未登录的状态下

**Comment by swtseaman** [comment]
> 已经升级到 :v1.1.3 (build at 2024-05-15T17:49, commit: [e74ba87](https://github.com/1Panel-dev/MaxKB/commit/e74ba87fc65965673426bdc99122d6389a6c2ca4))， 用户端并没有历史聊天记录功能

看错了，请问1.2.0什么时候更新

**Comment by baixin513** [comment]
v1.2.0 5月30 日发布
