### ISSUE TITLE
建议能够增加对接钉钉和企业微信的小程序接口

### ISSUE THREAD

**Issue by shanghairendaimin** [1Panel-dev/MaxKB#473]
### MaxKB 版本

1.1.3

### 请描述您的需求或者改进建议

能够在钉钉或者企业微信的工作台中添加自建的maxkb的小程序，通过这个小程序在手机端上使用maxkb

**Comment by baixin513** [comment]
感谢反馈，企业微信不支持外部调用，借助第三方系统也会有封号风险，目前还没有好的解决方案。
