### ISSUE TITLE
[FEATURE]知识库文档添加重新embeding操作

### ISSUE THREAD

**Issue by Virtual1257** [1Panel-dev/MaxKB#475]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

# 需求 
目前替换embeding模型后，原有向量数据库里保存的数据不可用了，只能删除文档，然后重新上传文档后，分段再重新embeding。这个流程比较麻烦。能否在知识库文档页面的操作里添加“重新embeding”的操作，点击后会删除对应向量数据库里的数据，然后重新embeding，并保存到向量数据库。这样以后在系统运行过程中替换embeding模型后，便于数据的再处理。
# 改进建议
![1715926682006](https://github.com/1Panel-dev/MaxKB/assets/26375052/3555e4f7-0917-4148-a468-89c5c92aaa8d)

### 请描述你建议的实现方案

在知识库文档页面的操作里添加“重新embeding”的操作，点击后会删除对应向量数据库里的数据，然后重新embeding，并保存到向量数据库。

**Comment by baixin513** [comment]
感谢反馈，建议很棒，后续版本增加。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
