### ISSUE TITLE
[BUG] 使用自己封装的openai 接口，演示时没有知识库匹配信息

### ISSUE THREAD

**Issue by huangguifeng** [1Panel-dev/MaxKB#476]
### MaxKB 版本

-

### 问题描述

  
![image](https://github.com/1Panel-dev/MaxKB/assets/31758761/0c677857-d0bc-4bb8-8d65-ec22e5b6ab89)

不知道是我的模型问题呢，还是那里有问题。

### 重现步骤

![image](https://github.com/1Panel-dev/MaxKB/assets/31758761/fd701d01-8703-447d-aa1f-71eaaf9c68b5)
大模型，采用自己部署的，openai 格式的api 

### 期待的正确结果

![image](https://github.com/1Panel-dev/MaxKB/assets/31758761/87b2edb4-0a1b-4e1c-840b-4e6aac9d098a)

**Comment by baixin513** [comment]
感谢反馈，显示知识来源的话，需要在应用-访问限制功能开启后对话时才会显示引用知识库的内容。
