### ISSUE TITLE
添加分段的分段内容字数限制，建议参数化，并在前端页面可调，而不是写死-4096

### ISSUE THREAD

**Issue by jingruhou** [1Panel-dev/MaxKB#477]
### MaxKB 版本

版本号:v1.1.2 (build at 2024-05-10T11:16, commit: d724a543)

### 请描述您的需求或者改进建议

添加分段的分段内容字数有限制.
建议参数化，并在前端页面可调，而不是写死-4096

### 附加信息

![微信图片_20240517183654](https://github.com/1Panel-dev/MaxKB/assets/6825570/8d4f8f51-6bf6-426b-b353-68c6eecc5c1d)

**Comment by baixin513** [comment]
感谢反馈，目前数据库字段最大长度是4096，我们后续再考虑一下。

**Comment by jingruhou** [comment]
Dify中的分段数据貌似就没有4096的限制

![image](https://github.com/1Panel-dev/MaxKB/assets/6825570/fcbf6643-8cac-4350-80bd-7aa603c150ec)

**Comment by baixin513** [comment]
分段内容长度扩展为10万个字符， 由使用用户自行把握分段长度，但如果分段过长，超过模型接收的字符数，模型会返回错误。

**Comment by 13535048320** [comment]
v1.10.7 版本智能分段依旧限制在 4.1k 长度

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The smart segmentation of the v1.10.7 version is still limited to 4.1k length
