### ISSUE TITLE
[FEATURE]加入閱讀圖片及網絡搜尋

### ISSUE THREAD

**Issue by bloomin1** [1Panel-dev/MaxKB#478]
### MaxKB 版本

1.1.3

### 请描述您的需求或者改进建议

想請求加入閱讀圖片及網絡搜尋

### 请描述你建议的实现方案

加入閱讀圖片及網絡搜尋

**Comment by baixin513** [comment]
感谢反馈， 在支持工作流编排之后可以考虑一下。

**Comment by baixin513** [comment]
当前已经支持图片理解和模型联网查询，可以升级到v1.8试用一下
