### ISSUE TITLE
希望能通过API管理知识库[FEATURE]

### ISSUE THREAD

**Issue by prodcd** [1Panel-dev/MaxKB#481]
### MaxKB 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

用户有很多数据会实时更新，比如当前一些传感器参数、传感器报警状态、人员所在区域、车辆所在区域等。现有知识库无法通过API实时更新。

### 请描述你建议的实现方案

希望在用户接入问答页面的时候，或者定时，能够由本地系统生成实时数据，再通过API方式，更新用户的这些数据到知识库中，以便用户询问。而不是人工更新。
比如用户可能会问：“xx位置里面现在有几个人？”、“今天进入了多少辆车”、“张三现在在哪”、“xx罐体的温度是多少”等实时性的问题。

**Comment by baixin513** [comment]
感谢反馈，通用知识库近期还没有计划。如果是 web站点的知识库可以通过手动同步更新。
