### ISSUE TITLE
[FEATURE] 在 Swagger API 文档中添加 HTTPS 支持

### ISSUE THREAD

**Issue by HarleyQiu** [1Panel-dev/MaxKB#483]
### MaxKB 版本

1.1.3

### 请描述您的需求或者改进建议

注意到`https://IP/doc`的API 接口文档未明确支持 HTTPS。目前的 Swagger API 文档中在 Schemes 部分只提供了 HTTP 选项，没有提供 HTTPS。能否提供一个HTTPS的选项呢？

**Comment by liqiang-fit2cloud** [comment]
MaxKB本身只提供HTTP接口，HTTPS请自行通过nginx之类的反向代理进行配置，HTTPS证书也配置在反向代理上。

**Comment by HarleyQiu** [comment]
感谢您的回复。目前我已经通过使用nginx作为反向代理并配置了SSL证书来实现HTTPS支持。但是在实际使用Swagger API文档进行接口测试时，由于Schemes选项中仅列出了HTTP，而未包括HTTPS，这限制了我直接在Swagger界面中测试接口。我理解MaxKB本身只提供HTTP接口，但添加HTTPS选项至Swagger文档的Schemes中可以提供更全面的测试支持并增强用户体验。希望您能考虑此项改进，以便使Swagger文档能更准确地反映通过反向代理配置的实际使用环境。
