### ISSUE TITLE
[FEATURE] 请问是否可以在如下环境做私有化部署，arm架构，非docker模式，纯cpu，Embedding模型使用bge-large-zh-v1.5，Chat模型使用chatglm3-6b

### ISSUE THREAD

**Issue by ticang** [1Panel-dev/MaxKB#489]
### MaxKB 版本

main

### 请描述您的需求或者改进建议

[FEATURE] 请问是否可以在如下环境做私有化部署，arm架构，非docker模式，纯cpu，Embedding模型使用bge-large-zh-v1.5，Chat模型使用chatglm3-6b

**Comment by shaohuzhang1** [comment]
非docker 部署请参考:
https://github.com/1Panel-dev/MaxKB/wiki/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA
