### ISSUE TITLE
[BUG] 关于创建完大模型进度条一直不更新的问题

### ISSUE THREAD

**Issue by Virtuoso461** [1Panel-dev/MaxKB#49]
### 联系方式

13666051426

### MaxKB 版本

v1.0.0

### 问题描述

关于创建完大模型进度条一直不更新的问题

### 重现步骤

在云端服务器上创建一个应用 网速较低,大概1M的情况下,模型进度条一直卡在0.1％ ,观看1panel仪表盘磁盘io,下载完成后进度还是在0.1％

### 期待的正确结果

有无更新进度条的方法,或者我在ollama镜像中下载好模型,这边不进行自动模型下载,直接读取我下载好的模型,省去这一步骤

### 附加信息

![image](https://github.com/1Panel-dev/MaxKB/assets/69096688/5eda197f-0b68-4b89-b71e-f4304ba48495)

**Comment by baixin513** [comment]
Ollama 上未下载的模型，MaxKB才会下载，若在Ollama 上下载完成，MaxKB直接添加不会再下载。

**Comment by Virtuoso461** [comment]
嗯 有试过 本地有了 他还是继续下载 不明白原因 本地已经下过llama2-chinese

&nbsp;


邱家鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月13日(星期六) 中午12:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1Panel-dev/MaxKB] [BUG] (Issue #49)














 
Ollama 上未下载的模型，MaxKB才会下载，若在Ollama 上下载完成，MaxKB直接添加不会再下载。

**Comment by baixin513** [comment]
你可以先在Ollama上确认好模型能正常运行，然后到MaxKB 中直接对接一下。对接时基础模型是在Ollama 上执行ollama run 基础模型的名字，要保证一致。

**Comment by baixin513** [comment]
不要两边执行下载操作，先把MaxKB 中的模型删除，等Ollama中模型下载完成正常返回后，再在MaxKB中添加模型对接就不会下载了。
