### ISSUE TITLE
[BUG]演示页面新增的历史记录在手机端无法隐藏，右侧对话框已经看不到了

### ISSUE THREAD

**Issue by lbemi** [1Panel-dev/MaxKB#492]
### MaxKB 版本

-

### 问题描述

演示页面新增的历史记录在手机端无法隐藏，右侧对话框已经看不到了，希望适配一下

### 重现步骤

演示页面新增的历史记录在手机端无法隐藏，右侧对话框已经看不到了，希望适配一下

**Comment by baixin513** [comment]
感谢反馈，该功能还在开发测试中，代码拉取话用  v1.1.0的分支或用v1.1.3 tag
