### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by mike2001** [1Panel-dev/MaxKB#495]
### MaxKB 版本

1.1.3

### 请描述您的需求或者改进建议

docker run -d --name=maxkb -p 8110:8110 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb

不可以自定义端口吗？容器里面还是8080端口，会和其他容器端口冲突

### 请描述你建议的实现方案

docker run -d --name=maxkb -p 8110:8110 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb

### 附加信息

docker run -d --name=maxkb -p 8110:8110 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb

**Comment by shaohuzhang1** [comment]
docker run -d --name=maxkb -p 8110:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb
自定义端口这样

**Comment by mike2001** [comment]
> docker run -d --name=maxkb -p 8110:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb 自定义端口这样

我是要改8080，这个端口改不了，我有其他的容器用的是8080

**Comment by shaohuzhang1** [comment]
不明白你的意思,容器内部端口是隔离的。映射到宿主机端口修改就好了

**Comment by mike2001** [comment]
我有一个容器已经占用8080端口了， 运行maxkb的docker就会报端口占用错误。我不知道是不是因为两个容器不能用同一个端口？
