### ISSUE TITLE
[BUG]开场白不支持Markdown表格语法，无法显示一个表格。

### ISSUE THREAD

**Issue by gzcls** [1Panel-dev/MaxKB#496]
### MaxKB 版本

v1.1.3 

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/136059643/14af72d2-c4ac-4589-b53c-1a98c6e87fc1)

### 重现步骤

在开场白录入以下Markdown信息，未显示为表格：
| 姓名   | 年龄 | 城市    |
| ------ | ---- | ------- |
| 小明   | 25   | 北京    |
| 小红   | 30   | 上海    |
| 小华   | 28   | 广州    |

**Comment by baixin513** [comment]
感谢反馈，后续版本支持。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
