### ISSUE TITLE
[FEATURE]开场白字数限制为1024，建议放宽到2048或更大。

### ISSUE THREAD

**Issue by gzcls** [1Panel-dev/MaxKB#497]
### MaxKB 版本

v1.1.3 

### 请描述您的需求或者改进建议

![93e9c0152e2474866d98746ca7e91ec](https://github.com/1Panel-dev/MaxKB/assets/136059643/947b1122-4bc2-4555-bf84-62ca0fea09a2)
当开场白纳入较多网络链接时，1024个字数不够用，建议放宽。

**Comment by baixin513** [comment]
感谢反馈，后续版本优化。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
