### ISSUE TITLE
关于页面优化

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [1Panel-dev/MaxKB#5]
### MaxKB 版本

v0.9.0

### 问题描述

1、出现了重复的 `版本` 和 `版本号`
2、目前使用的 docker 镜像版本是 v0.9.0，但页面显示的版本号是 v1.0.0
3、建议先隐藏 `授权数量` 和 `过期时间`
4、建议增加 `论坛求助`、`使用手册`、`项目地址` 等链接

![image](https://github.com/1Panel-dev/MaxKB/assets/46734380/ac233e51-d4f6-47e2-a3fc-20e8caac7b46)

### 重现步骤

进入 Web 控制台，点击右上角 `个人中心`，进入 `关于` 页面。

**Comment by baixin513** [comment]
已优化，等待正式发布。
