### ISSUE TITLE
[BUG]docker镜像部署后，无法正常启动

### ISSUE THREAD

**Issue by lichtud** [1Panel-dev/MaxKB#50]
### 联系方式

498585298@qq.com

### MaxKB 版本

1.0

### 问题描述

docker镜像部署后，无法正常启动，ping了端口发现服务没有启动，也找不到日志在哪看
![1713081375393](https://github.com/1Panel-dev/MaxKB/assets/99418115/557c7e11-1d8f-4814-a372-57381abee4f9)
。

### 重现步骤

docker run -d --name=maxkb -p 58091:8080 -v /app/conda/maxkb:/var/lib/postgresql/data 1panel/maxkb

**Comment by shaohuzhang1** [comment]
docker logs maxkb 看一下容器日志

**Comment by lichtud** [comment]
日志是:
waiting for postgres
127.0.0.1:5432 - no response

postgres 数据库需要单独安装吗？我没注意额

> docker logs maxkb 看一下容器日志

**Comment by liqiang-fit2cloud** [comment]
see this https://github.com/1Panel-dev/MaxKB/issues/46

**Comment by lichtud** [comment]
> see this #46

解决了，抱歉我没注意有类似的issue，给您们添麻烦了。
