### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Richard-kkk** [1Panel-dev/MaxKB#501]
### MaxKB 版本

v1.1.3

### 请描述您的需求或者改进建议

支持SQLite数据库文件导入,轻量级文件型数据库

### 请描述你建议的实现方案

应该和DataEase对接各个数据库的技术实现原理差不多。

**Comment by liqiang-fit2cloud** [comment]
目前没有支持数据库导入的计划，只支持文本文档。
