### ISSUE TITLE
[FEATURE]引用分段数最大值增大到 100 个

### ISSUE THREAD

**Issue by baixin513** [1Panel-dev/MaxKB#503]
### MaxKB 版本

1.1.2

### 请描述您的需求或者改进建议

引用分段数最大值增大到 100 个， 分段太散，当前最多引用 10 个不够用。

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
