### ISSUE TITLE
[FEATURE]允许上传附件

### ISSUE THREAD

**Issue by i138** [1Panel-dev/MaxKB#504]
### MaxKB 版本

v1.1.3

### 请描述您的需求或者改进建议

一些模型支持上传附件，比如LLAVA、openGPT4等支持对上传的图片、excel、doc等附件进行分析，但是目前对话窗口不支持上传附件。

### 请描述你建议的实现方案

学习openwebUI，支持对话中可以上传附件。

**Comment by baixin513** [comment]
感谢反馈，重复 issue，同 #295
