### ISSUE TITLE
想问一下是否支持将知识库导出成.pkl的格式[FEATURE]

### ISSUE THREAD

**Issue by roselite-iris** [1Panel-dev/MaxKB#505]
### MaxKB 版本

unknown

### 请描述您的需求或者改进建议

我觉得如果可以导出知识库，可以让个性化开发可操作性更强一点，比如我可以在我自己写的一个应用里面嵌入知识库。不知道您这边是否鼓励这种想法。

**Comment by baixin513** [comment]
感谢反馈，后续版本计划支持知识库导出excel。
