### ISSUE TITLE
[优化]建议增加访问来源IP白名单控制系统访问权限

### ISSUE THREAD

**Issue by gzcls** [1Panel-dev/MaxKB#509]
### MaxKB 版本

v1.1.3 

### 请描述您的需求或者改进建议

知识库更多针对企业内部使用，建议增加IP白名单进行控制。
![ffbb818287fd6a4a2276cc081eaa380](https://github.com/1Panel-dev/MaxKB/assets/136059643/a1122ae5-61a0-4612-a477-31834ecc5b01)

**Comment by liqiang-fit2cloud** [comment]
黑白名单这种建议通过WAF控制或者网络安全策略控制。
