### ISSUE TITLE
[BUG]【知识库】Web站点知识库，完整同步报错

### ISSUE THREAD

**Issue by luoxluo611** [1Panel-dev/MaxKB#51]
### 联系方式

6128685@qq.com

### MaxKB 版本

1,0

### 问题描述

文档全量更新无法使用，报错

### 重现步骤

进入文档，点击批量删除

### 期待的正确结果

可以批量删除

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by shaohuzhang1** [comment]
确认整体同步报错,下一个版本修复。
