### ISSUE TITLE
[BUG]【用户问题】此字段不能为空字符串。

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/MaxKB#512]
### 联系方式

cat@acat.email

### MaxKB 版本

看不到，但是是1panel应用商店安装的最新版

### 问题描述

版本号如下看不到
![image](https://github.com/1Panel-dev/MaxKB/assets/58991169/1e23fe4f-50f3-4622-87e1-7e761cc5871c)

### 问题：每次首次打开演示的时候都有概率会出现这个问题，首句话会提示你【用户问题】此字段不能为空字符串，第二话会开始恢复正常，不能稳定复现，但是经常会出现来恶心你一下。从两个版本之前就有这个问题，这回更新还是有这个问题
![Screenshot - 2024-05-22 18 52 48](https://github.com/1Panel-dev/MaxKB/assets/58991169/85823de9-f1c7-40d7-89f7-9d530a67f6bb)
![Screenshot - 2024-05-22 18 52 39](https://github.com/1Panel-dev/MaxKB/assets/58991169/1b88ece9-b3ed-4d9f-b7a8-cd78f37f6f03)
### 我的应用配置都是
**提示词：**
![image](https://github.com/1Panel-dev/MaxKB/assets/58991169/f4148862-1c52-4387-8a7c-62690e9a911c)
**多轮对话**和**问题优化**打开，不使用知识库

### 重现步骤

在配置页的调试中不会遇到这种问题，另外这个GIF就属于是运气好，只有第一次使用的时候复现了一次

![recording](https://github.com/1Panel-dev/MaxKB/assets/58991169/fdec104a-0c58-449f-97bb-3db066c67e13)

### 相关日志输出

```shell
日志里都是正常的API请求，唯一可疑的就是这种日志

/opt/py3/lib/python3.11/site-packages/django/db/models/base.py:364: RuntimeWarning: Model 'dataset.dynamics' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
```

**Comment by baixin513** [comment]
感谢反馈， 开启问题后会先让模型根据上下文优化一次问，模型可能并没有返回优化后的问题，导致再后续第二次让模型回答时 丢失了用户的问题，这个问题已经解决了，可以升级为最新的 v1.1.3版本。

**Comment by baixin513** [comment]
可以关闭问题优化。

**Comment by baixin513** [comment]
可以重新登录一下，版本号是在登录时获取的。

**Comment by miaowmint** [comment]
> 感谢反馈， 开启问题后会先让模型根据上下文优化一次问题，模型可能并没有返回优化后的问题，导致后续第二次让模型回答时 ，丢失了用户的问题，这个问题已经解决了，可以升级为最新的 v1.1.3版本。

![image](https://github.com/1Panel-dev/MaxKB/assets/58991169/7560e5c3-cbae-4dca-9d88-e05df57867c7)
现在的版本就是1.1.3 我先试试关闭问题优化看看吧

**Comment by miaowmint** [comment]
emmm 我试了 关闭了问题优化也还是有这个问题 
![image](https://github.com/1Panel-dev/MaxKB/assets/58991169/979cbd73-f5ac-49f0-a302-3d4fa95064e1)
![image](https://github.com/1Panel-dev/MaxKB/assets/58991169/5482eb9e-fd37-41f6-9997-76280f764001)
![image](https://github.com/1Panel-dev/MaxKB/assets/58991169/2bfcf8e1-b24d-4d14-b24a-5735ae39e431)

**Comment by baixin513** [comment]
点击快捷问题后我们做了防抖限制，只能发送一次问题，但从你的现象看应该是 一下发了 2 个提问，第二个问题为空。 
我们这边测试环境无法复现。如果你那边环境可以联网的话，可以进入我们技术交流群，进行排查一下。
![MaxKB小助手](https://github.com/1Panel-dev/MaxKB/assets/52996290/ca52713c-4df3-4497-ab4e-eb88e9a6c5da)

**Comment by baixin513** [comment]
已复现，同一个浏览器打开两个应用的对话页面，认证共享导致的 bug。

**Comment by miaowmint** [comment]
> 已复现，同一个浏览器打开两个应用的对话页面，认证共享导致的 bug。

对对对 是这样的 坐等大佬们修复

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
