### ISSUE TITLE
[FEATURE]iOS调用时，在点击输入栏时，页面会变大走样，希望能优化成输入时页面不要变大

### ISSUE THREAD

**Issue by Arrding** [1Panel-dev/MaxKB#514]
### MaxKB 版本

V1.1.2

### 请描述您的需求或者改进建议

iOS调用时，用了WKWebview，用苹果手机自带的浏览器加载嵌入第三方的URL 
    https://www.test.com:12345/ui/chat/123456abcddd343。
用户在点击输入栏时，页面会变大走样（第4图），希望能优化成输入时页面不要变大
![code1](https://github.com/1Panel-dev/MaxKB/assets/149556585/6eb423b8-0d88-413f-b4e2-51006309737c)
![code2](https://github.com/1Panel-dev/MaxKB/assets/149556585/a676aa07-ada1-4f48-9813-9808f29ba88d)
![微信图片_20240522220334](https://github.com/1Panel-dev/MaxKB/assets/149556585/596fb7b0-ecc8-445c-8c91-72991bab219b)
![微信图片_20240522220343](https://github.com/1Panel-dev/MaxKB/assets/149556585/43fda807-7331-4f2e-ae01-a3d3776627a6)

### 请描述你建议的实现方案

输入问题时，H5页面不要变大

**Comment by baixin513** [comment]
感谢反馈，需要在嵌入的项目的 meta标签加 2 个参数：minimum-scale=1, maximum-scale=1

<meta
      name="viewport"
      content="width=device-width, initial-scale=1.0,charset=gbk,minimum-scale=1, maximum-scale=1"
    />

**Comment by Arrding** [comment]
iOS调用时，用了WKWebview，直接调用这个URL    https://www.test.com:12345/ui/chat/123456abcddd343，没有地方写上你说的meta呀

**Comment by baixin513** [comment]
我们这边可以正常适配的，你可能需要研究一下在 ios 程序中的设置。
