### ISSUE TITLE
[FEATURE]建议接入xinference

### ISSUE THREAD

**Issue by zealze** [1Panel-dev/MaxKB#515]
### MaxKB 版本

main

### 请描述您的需求或者改进建议

是否有接入xinference的计划，除了ollama，Xinference可用的模型也有很多呢。[Xorbits Inference](https://github.com/xorbitsai/inference/blob/main/README_zh_CN.md)

**Comment by baixin513** [comment]
感谢反馈，后续考虑一下。

**Comment by shaohuzhang1** [comment]
可以尝试通过添加openai供应商去对接[xinference]
