### ISSUE TITLE
[BUG]PDF 文件导入后字符数是 0

### ISSUE THREAD

**Issue by colicoyzo** [1Panel-dev/MaxKB#517]
### 联系方式

colico@163.com

### MaxKB 版本

v1.1.3

### 问题描述

导入部分pdf文件后，显示导入成功，但是导入字符数为0  
![17d05f5187f019a727f4fe04ea5ddad](https://github.com/1Panel-dev/MaxKB/assets/26223279/ff0d4c87-ba5c-472d-a266-56f8f9713401)

### 重现步骤

部分的pdf没有复制权限的，导入后字符数为0，还有docx文件也有存在类似的问题

### 期待的正确结果

能正常导入，并客户进行分段

**Comment by prodcd** [comment]
我也遇到过类似的事。分段是0，你点进去看看分段，是不是导入的pdf是乱码。pdf格式很多文件并不适合直接导入。

**Comment by baixin513** [comment]
PDF 目前只能识别文本，PDF 中的图片无法识别。需要排查一下内容为 0 的 PDF 文件是不是都是图片？

**Comment by colicoyzo** [comment]
不是图片，是有文字的，有部分是纯文字的内容

**Comment by baixin513** [comment]
方便的话提供一下导入为 0 的 PDF 文件，发送到 xin.bai@fit2cloud.com。

**Comment by baixin513** [comment]
如果 PDF 文本字迹不清晰也是识别不到的，目前 PDF 这块还没有好的解决方案。
未收到您的文档，建议您先优化一下文档。
