### ISSUE TITLE
嵌入其他网站首次访问的引导页面开关

### ISSUE THREAD

**Issue by gaohongli** [1Panel-dev/MaxKB#519]
### MaxKB 版本

v1.1.1 

### 请描述您的需求或者改进建议

嵌入其他网站后，首次访问会展示聊天窗口的引导页面，会给原网站用户产生不好体验。

### 请描述你建议的实现方案

1.去掉引导页面，实际上完全没必要，用户能看到右下角的客服图标，没必要引导。2.后台增加配置开关，可关闭。

**Comment by baixin513** [comment]
感谢反馈，后续版本考虑一下

**Comment by baixin513** [comment]
该功能在专业版中支持
