### ISSUE TITLE
[FEATURE]【知识库】文档支持迁移功能

### ISSUE THREAD

**Issue by luoxluo611** [1Panel-dev/MaxKB#52]
### MaxKB 版本

1.0

### 请描述您的需求或者改进建议

希望文档可以支持从一个项目迁移到另外一个项目，方便批量整理数据

### 请描述你建议的实现方案

增加批量迁移按钮，迁移的时候支持选择有权限的项目

**Comment by shaohuzhang1** [comment]
感谢反馈,该需求规划在近期内,请关注后续版本
