### ISSUE TITLE
[BUG]添加讯飞星火源报错 PathDomainError

### ISSUE THREAD

**Issue by nygula** [1Panel-dev/MaxKB#525]
### MaxKB 版本

1.1.3

### 问题描述

code: 500
data: null
message: "校验失败,请检查参数是否正确: Code: 10404, Error: PathDomainError:(08:46:23.642) no category route found"

### 重现步骤

填入讯飞星火 appid appkey appsecret   api: wss://spark-api.xf-yun.com/v1.1/chat   点击添加按钮报错

**Comment by baixin513** [comment]
1、确认基础模型填写的什么？ 是否为 general ？
<img width="908" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/af1b67fd-8ae0-4a61-95d5-a9779712888b">

**Comment by nygula** [comment]
很抱歉,是我的问题,没有发现基础模型是可以手动输入的 ,目前可供下拉选择的是 generalv2 generalv3 generalv3.5 .
