### ISSUE TITLE
[FEATURE]可否添加问题推荐功能？

### ISSUE THREAD

**Issue by jarlin8** [1Panel-dev/MaxKB#535]
### MaxKB 版本

1.13

### 请描述您的需求或者改进建议

我自己用prompt实现了，但是没法直接点击发送，需要复制到对话框 比较麻烦。
![image](https://github.com/1Panel-dev/MaxKB/assets/81870669/ed2d0dc6-0665-45a2-ae9b-32011d1713ef)

**Comment by baixin513** [comment]
与 #516 重复
