### ISSUE TITLE
[FEATURE] 能否提供离线安装包

### ISSUE THREAD

**Issue by maninhill** [1Panel-dev/MaxKB#538]
### MaxKB 版本

1.1.0

### 请描述您的需求或者改进建议

1. 官方提供离线包安装方式
2. 使用 Docker compose 方式，而不是 all in one，适合生产环境部署

**Comment by liqiang-fit2cloud** [comment]
ok.

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
