### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by a937983423** [1Panel-dev/MaxKB#541]
### 联系方式

937983423@qq.com

### MaxKB 版本

最新版，才安装的

### 问题描述

I am using Arch Linux, where ollama is installed directly on the host and it functions normally, with API access working as expected. However, when it comes to MaxKB, I've set it up using Docker, and I'm encountering an issue where I can't add models. When attempting to add an ollama model, I receive a notification stating that the API endpoint is invalid. This odd issue persists whether I try to access it using the IP plus port (e.g., ip:port) or the format http://host.docker.internal:11434.

### 重现步骤

安装很多次都是那样

**Comment by shaohuzhang1** [comment]
Please try changing /etc/systemd/system/ollama.service.d/override.conf,If this directory is not available, create it

vim /etc/systemd/system/ollama.service.d/override.conf
```
[Service]
Environment="OLLAMA_HOST=0.0.0.0"
```
systemctl daemon-reload
systemctl restart ollama
