### ISSUE TITLE
使用源码方式启动报错

### ISSUE THREAD

**Issue by shuyixiao0917** [1Panel-dev/MaxKB#543]
### 联系方式

chinasjh2022@126.com

### MaxKB 版本

v1.1.1发行版

### 问题描述

使用源码的方式启动总是报错
![image](https://github.com/1Panel-dev/MaxKB/assets/111023943/688d6a84-4a76-49ce-ac9e-2cd8fe0e3a16)

数据库已经使用镜像的方式部署启动，执行部署文档中的代码没有问题
![image](https://github.com/1Panel-dev/MaxKB/assets/111023943/be0dc801-bb0e-4239-a712-83980f656331)
但是总是启动不了 求解答

### 重现步骤

源码的方式按照官方给的步骤走，启动后端服务就会出现这个问题

**Comment by youngzm339** [comment]
需要先确保已经安装了[pgvector](https://github.com/pgvector/pgvector)插件，这里看报错PostgreSQL找不到插件

**Comment by shuyixiao0917** [comment]
> 需要先确保已经安装了[pgvector](https://github.com/pgvector/pgvector)插件，这里看报错PostgreSQL找不到插件

好的我这边排查到问题原因了谢谢啦~
