### ISSUE TITLE
[FEATURE]腾讯混元大模型接口支持

### ISSUE THREAD

**Issue by laolin** [1Panel-dev/MaxKB#546]
### MaxKB 版本

lasted

### 请描述您的需求或者改进建议

增加支持腾讯混元大模型的接口

**Comment by baixin513** [comment]
感谢反馈，后续调研一下。

**Comment by gdhucoder** [comment]
我也有这方面的需求，请评估，并希望在MaxKB中支持混元大语言模型

**Comment by youngzm339** [comment]
调研了半天，发现langchain.community中的Tencent Hunyuan似乎是有问题的（langchain方面也有相关issue）。我这些天看看混元大模型官方最新文档把上游fix下再处理接入，翻了下之前和现在的接入指南发现腾讯云混元好像在版本更新时对接口有大的改动。
