### ISSUE TITLE
[FEATURE] docker 容器安装能否支持下外部DB

### ISSUE THREAD

**Issue by zy84338719** [1Panel-dev/MaxKB#547]
### MaxKB 版本

1.1.3

### 请描述您的需求或者改进建议

docker 容器安装能否支持下外部DB
通过环境变量的方式注入进去
外部创建的完整sql

### 请描述你建议的实现方案

docker 容器安装能否支持下外部DB
通过环境变量的方式注入进去
外部创建的完整sql

**Comment by shaohuzhang1** [comment]
可以修改/opt/maxkb/conf/config.yaml 连接外部pgsql
在启动的时候使用-v 可以将配置挂载到宿主机目录
docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data -v ~/.maxkbconf:/opt/maxkb/conf 1panel/maxkb

**Comment by geosmart** [comment]
config.yaml修改了DB配置无效，挂载进去还是使用127.0.0.1:5432。
改环境变量也不行，有使用远程postgresql的例子吗？
