### ISSUE TITLE
[FEATURE]添加聊天记录删除按钮及功能

### ISSUE THREAD

**Issue by Virtual1257** [1Panel-dev/MaxKB#548]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

在聊天页面添加历史记录删除功能和其他属性修改的功能，类似chatgpt那样
![image](https://github.com/1Panel-dev/MaxKB/assets/26375052/a867f061-c111-4049-b232-44fad483830e)
另外，建议解除只显示20条的限制

**Comment by baixin513** [comment]
感谢反馈，后续版本在考虑，另外您使用了是未经测试的分钟，不能保证没有 bug。建议使用 release 版本的分支。
