### ISSUE TITLE
[FEATURE]在 Swagger API 文档的Schemes选项中添加 HTTPS 选项

### ISSUE THREAD

**Issue by HarleyQiu** [1Panel-dev/MaxKB#549]
### MaxKB 版本

1.1.3

### 请描述您的需求或者改进建议

目前已经通过使用nginx作为反向代理并配置了SSL证书来实现HTTPS支持。但是在实际使用Swagger API文档进行接口测试时，由于Schemes选项中仅列出了HTTP，而未包括HTTPS，这限制了我直接在Swagger界面中测试接口。我理解MaxKB本身只提供HTTP接口，但添加HTTPS选项至Swagger文档的Schemes中可以提供更全面的测试支持并增强用户体验。希望您能考虑此项改进，以便使Swagger文档能更准确地反映通过反向代理配置的实际使用环境。

**Comment by baixin513** [comment]
感谢反馈，暂无计划，同issue #483
