### ISSUE TITLE
[FEATURE]【知识库】希望用户提问时命中人工维护过的分段内容可不走AI模型直接返回。

### ISSUE THREAD

**Issue by ulleo** [1Panel-dev/MaxKB#56]
### MaxKB 版本

V1.0.0

### 请描述您的需求或者改进建议

希望用户提问时命中人工维护过的分段内容可不走AI模型直接返回。

**Comment by shaohuzhang1** [comment]
感谢反馈,改需求规划在近期内,请关注后续版本
