### ISSUE TITLE
[FEATURE]支持内部的wiki导入

### ISSUE THREAD

**Issue by njnuwjq** [1Panel-dev/MaxKB#564]
### MaxKB 版本

v1.1.1

### 请描述您的需求或者改进建议

内部的wiki该如何导入？
有二次验证的过程
目前直接填地址导入的是空数据
直接get url， 当然也是空的
浏览器打开啊， 会自动导入到验证过程

**Comment by njnuwjq** [comment]
为了模拟浏览器的行为，包括处理二次验证，你可以使用Python中的Selenium库。Selenium可以自动化浏览器操作，模拟用户在浏览器中的一系列操作，包括处理验证过程。

**Comment by baixin513** [comment]
感谢反馈，近期暂时没有支持计划。
