### ISSUE TITLE
[FEATURE] 国外有很多到模型，官方是否可以公开接入方法和接口，大家共同完善社区。 

### ISSUE THREAD

**Issue by smallyaohailu** [1Panel-dev/MaxKB#567]
### MaxKB 版本

v1.1.3

### 请描述您的需求或者改进建议

[FEATURE] 国外有很多到模型，官方是否可以公开接入方法和接口，大家共同完善社区。 

### 请描述你建议的实现方案

[FEATURE] 国外有很多到模型，官方是否可以公开接入方法和接口，大家共同完善社区。

**Comment by liqiang-fit2cloud** [comment]
代码都是开源的，欢迎一起完善，有很多小伙伴已经提交代码支持不少模型了。
