### ISSUE TITLE
[BUG]本地搜索对英文大小写敏感，期望RAG过程应该是对大小写不敏感的

### ISSUE THREAD

**Issue by dark2star** [1Panel-dev/MaxKB#57]
### MaxKB 版本

v1.0.0 (build at 2024-04-10T19:09, commit: cbaf704f)

### 问题描述

本地搜索对英文大小写敏感，期望RAG过程应该是对大小写不敏感的

### 重现步骤

录入英文文档，对话中输入英文关键字即可100%复现

**Comment by baixin513** [comment]
感谢反馈，确认一下您反馈的问题：

需求1.  在搜索框中检索文档名称、分段标题、内容等查询功能时大小写不敏感（当前大小写敏感）。
该功能可以实现。

需求2.  当用户提问时，向量召回分段内容时大小写不敏感（当前大小写敏感）。
当前向量化模型不太支持，分段内容含有英文向量化处理时就是敏感的，召回时肯定也敏感。
 
您可以自行换个支持大小写不敏感的向量化模型试试。

**Comment by baixin513** [comment]
需求1已完成，请更新至v1.0.1
