### ISSUE TITLE
[FEATURE]支持角色设定

### ISSUE THREAD

**Issue by li-silin** [1Panel-dev/MaxKB#574]
### MaxKB 版本

v1.0.4

### 结构化的 prompt 支持，市面上很多使用结构化prompt 

![31fe09bade05e8d279516f795364989](https://github.com/1Panel-dev/MaxKB/assets/100558350/ae55b961-990c-488d-b259-1083f717dede)

**Comment by baixin513** [comment]
感谢反馈，后续版本排期支持。

**Comment by baixin513** [comment]
V1.3.0 版本中已支持角色设定
