### ISSUE TITLE
[BUG]上传 md格式文档，一个分段内容超过 4096 个字符时，上传报错

### ISSUE THREAD

**Issue by baixin513** [1Panel-dev/MaxKB#576]
### MaxKB 版本

 v1.1.3

### 问题描述

上传md格式文档，一个分段内容超过 4096 个字符时，上传报错。

### 重现步骤

![image](https://github.com/1Panel-dev/MaxKB/assets/52996290/c23e5e68-695d-470e-bb1b-c888a876702c)

**Comment by maninhill** [comment]
v1.2.0 已发布：https://github.com/1Panel-dev/MaxKB/releases/tag/v1.2.0
