### ISSUE TITLE
支持对接豆包大语言模型

### ISSUE THREAD

**Issue by shanghairendaimin** [1Panel-dev/MaxKB#578]
### MaxKB 版本

1.1.3

### 请描述您的需求或者改进建议

如腾讯的混元、字节跳动的豆包可以考虑增加API接口，这样可以让用户选择性更多

**Comment by baixin513** [comment]
感谢反馈，豆包模型可以通过添加 OpenAI 供应商对接上。
腾讯混元模型对接与 issue #546 重复。

**Comment by shaohuzhang1** [comment]
豆包可以通过openai供应商去添加。
