### ISSUE TITLE
[FEATURE]问题是否可以批量关联分段，或者一键关联全部分段

### ISSUE THREAD

**Issue by bolide** [1Panel-dev/MaxKB#581]
### MaxKB 版本

版本号:v1.1.3 (build at 2024-05-15T17:49, commit: e74ba87f)

### 请描述您的需求或者改进建议

是否能设置一个问题，批量关联所有分段
回答问题随机选择一个提示回答
![1](https://github.com/1Panel-dev/MaxKB/assets/2173185/6ed08287-2e2e-429e-a8d6-3b206b265dff)

### 请描述你建议的实现方案

1、问题增加一个批量关联段落
2、随机选择段落回答

**Comment by baixin513** [comment]
感谢反馈，问题中可以批量关联分段，问题l列表-操作-关联分段，可以选择多个分段关联
<img width="1425" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/3c860d72-8cca-48a5-a868-4b4e66f49f4f">
