### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by lianxintao** [1Panel-dev/MaxKB#583]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

markdown 中的本地图片不能自动上传，pdf文件中的图片上传后丢失。

**Comment by baixin513** [comment]
感谢反馈：
1、markdown 格式的文档本身就不存储图片，你可以在maxkb的分段中支持上传本地图片。
2、pdf本身就是图片，里面的图片是无法解析的。
