### ISSUE TITLE
[FEATURE] 集成到自研平台后，因maxkb大量引用外部js、css资源导致审核不通过，被迫下线

### ISSUE THREAD

**Issue by wivw0306** [1Panel-dev/MaxKB#585]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

问题如题，引用外部资源问题见截图？
<img width="903" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/95760640/831e7d3d-f39c-411a-b866-065de2d7bde5">

**Comment by baixin513** [comment]
升级到 v1.2.0 试一下，该版本会先请求本地的 js资源

**Comment by wivw0306** [comment]
v1.2.0版本问题依然存在。

根本原因是前端依赖的md-editor-v3库中依赖第三方资源。如图：
<img width="1158" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/95760640/c77829a5-54a2-4d72-94c3-38aa46bb7815">

**Comment by bobolau** [comment]
建议优化一下cdnBase的配置，全局查找将需要cdn的资源放到本地单独的cdn目录，允许部署时选择本地cdn或者在线cdn

**Comment by baixin513** [comment]
好的，后续版本优化一下。
