### ISSUE TITLE
[BUG]通过 API 进行对话的 API 文档接口错误

### ISSUE THREAD

**Issue by baixin513** [1Panel-dev/MaxKB#587]
### MaxKB 版本

v1.2.0

### 问题描述

[BUG]通过 API 进行对话的 API 文档接口不对

### 重现步骤

[BUG]通过 API 进行对话的 API 文档接口不对,需要在接口前面加上 /api
![image](https://github.com/1Panel-dev/MaxKB/assets/52996290/504399a8-3000-40a0-b334-a55db86747a6)

**Comment by xy2yp** [comment]
请问是不是还没有推送最新的docker？我用latest标签下载，还是有这个问题

**Comment by shaohuzhang1** [comment]
是的,还没发布最新版本

**Comment by xy2yp** [comment]
请问是不是还没有推送最新的docker？我用latest标签下载，还是有这个问题

**Comment by xy2yp** [comment]
> 是的,还没发布最新版本

好的，感谢
