### ISSUE TITLE
[BUG]api地址填入chatgpt web后无法响应

### ISSUE THREAD

**Issue by samcaicn** [1Panel-dev/MaxKB#59]
### MaxKB 版本

1.0

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/3318094/fceab06a-7d60-4e89-83e4-a89894d9659a)
api地址填入chatgpt web后无法响应

### 重现步骤

api地址和key填入chatgptweb
无法响应

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by baixin513** [comment]
您好，您的截图并非 MaxKB 产品的问答页面。
如果有 MaxKB 问题，请描述一下问题操作，并把提供一下截图。
我们好快速帮您解决。
