### ISSUE TITLE
导入pdf内容丢失、表格内容识别完全错乱

### ISSUE THREAD

**Issue by newsyh** [1Panel-dev/MaxKB#591]
### MaxKB 版本

最新版本

### 请描述您的需求或者改进建议

导入pdf文档后，有的内容直接找不到了。
另外pdf文件中如果有表格，适配直接全部乱了

请问这是系统本身的缺陷还是操作问题呢

**Comment by baixin513** [comment]
感谢反馈， PDF 目前只能解析到文本文字，解析不了表格，如果 PDF 上文字不清晰也是解析不到的。
