### ISSUE TITLE
[FEATURE]MaxKB知识库上传,修改删除,接口文档

### ISSUE THREAD

**Issue by peiqi00001** [1Panel-dev/MaxKB#599]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

MaxKB知识库上传,修改删除,接口文档

**Comment by baixin513** [comment]
感谢反馈，应用-概览-API 访问凭证有使用应用 API Key调用对话的 API 文档，知识库的暂时没有。
