### ISSUE TITLE
[FEATURE] 【知识库】支持指定 Embedding 模型

### ISSUE THREAD

**Issue by dydwgmcnl4241** [1Panel-dev/MaxKB#60]
### MaxKB 版本

1.0.0

### 请描述您的需求或者改进建议

建议支持指定本地embedding模型

**Comment by baixin513** [comment]
感谢反馈，我们后面讨论一下该需求。

**Comment by lyy0755** [comment]
可以支持一下BGE M3-Embedding

**Comment by Tony1236** [comment]
希望在构建知识库这里可以选择指定的embedding模型

**Comment by zexho994** [comment]
催一下 ddd

**Comment by forverd** [comment]
考虑下M3E ddd

**Comment by tomener** [comment]
确实需要，顶一下

**Comment by cyhasuka** [comment]
@baixin513 同催更，注意到添加模型页中存在“模型类型”选项卡，建议此处可直接调用ollama或其他外部api的嵌入模型完成该功能。
![image](https://github.com/1Panel-dev/MaxKB/assets/34462246/583fc067-e771-456a-8fc9-495ec22d5f86)

**Comment by ensean** [comment]
日常催更，顺便问下目前的向量化模型是？

**Comment by cyhasuka** [comment]
> 日常催更，顺便问下目前的向量化模型是？

@ensean  shibing624/text2vec-base-chinese。另外可以手动更改，下载hf格式模型到embedding/model目录后，更改容器环境变量EMBEDDING_MODEL_NAME为所需模型即可。
