### ISSUE TITLE
[BUG]添加gemini模型接口出错

### ISSUE THREAD

**Issue by marine19811006** [1Panel-dev/MaxKB#600]
### MaxKB 版本

最新版

### 问题描述

添加gemini出现
![maxkb](https://github.com/1Panel-dev/MaxKB/assets/155867490/f5cbd957-fd75-470e-bdf8-ba2614edf960)

### 重现步骤

添加不上去

**Comment by baixin513** [comment]
感谢反馈，使用 Gemini API 需要确保所在服务器位于 Gemini API所支持的地区：https://ai.google.dev/gemini-api/docs/available-regions?hl=zh-cn，否则无法调用API，并且无法进入Google AI Studio。

**Comment by marine19811006** [comment]
clash设置了tun模式，开了全局还是不行？

**Comment by liqiang-fit2cloud** [comment]
> clash设置了tun模式，开了全局还是不行？

没试过，你再检查一下clash配置，或者确保所在服务器位于 Gemini API所支持的地区。
