### ISSUE TITLE
[BUG]dockerhub上镜像启动失败

### ISSUE THREAD

**Issue by MartinH04** [1Panel-dev/MaxKB#602]
### MaxKB 版本

v1.1.3 & v1.2.0

### 问题描述

docker容器运行后抛出错误

### 重现步骤

运行：docker run -d --name=maxkb -p 8080:8080 1panel/maxkb:v1.1.3
日志：docker logs -f maxkb

### 期待的正确结果

初始化正常

### 相关日志输出

```shell
显示：
popen failure: Cannot allocate memory
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/15/bin/initdb"
```

**Comment by liqiang-fit2cloud** [comment]
没遇到过，不过参考[这个](https://github.com/labring/FastGPT/issues/1061)，可以试试用更高版本内核的操作系统，或者启动命令加上privileged=true。

**Comment by shaohuzhang1** [comment]
这个是因为内存不够 默认pgsql需要占用宿主机内存的1/4 保证有足够的内存 或者修改pgsql的参数

**Comment by liqiang-fit2cloud** [comment]
MaxKB-v1.6.0 会解决这个问题。
