### ISSUE TITLE
[FEATURE]支持10000以上最多引用字符数

### ISSUE THREAD

**Issue by cgdg3** [1Panel-dev/MaxKB#603]
### MaxKB 版本

1.2.0

### 请描述您的需求或者改进建议

当前知识库搜索匹配后，允许提交的最多引用字符数是10000。如qwen plus api可以支持30k输入。希望将最多引用字符数设置为自定义输入模式。

### 请描述你建议的实现方案

最多引用字符数设置为自定义输入模式，可以填一个默认值（如5000），如果用户自己编辑，可以写一个自定义的正整数，如30000（30k）,128000（128k）甚至更高。并给出提示，上下文长度支持能力由大模型限制，最大值不超过大模型允许的上下文长度。

### 附加信息

![5d1484a0cd8cc5f8c1b7ead14ad1cd7](https://github.com/1Panel-dev/MaxKB/assets/59676490/cb4bea56-fd41-47fa-9407-9b46648642fb)

**Comment by baixin513** [comment]
感谢反馈，后续版本优化。

**Comment by baixin513** [comment]
已在 v1.2.1版本调整为 10 万
