### ISSUE TITLE
pdf导入优化建议

### ISSUE THREAD

**Issue by newsyh** [1Panel-dev/MaxKB#604]
### MaxKB 版本

1.2

### 请描述您的需求或者改进建议

1.pdf文件导入内容丢失严重，没有按照文档顺利进行切分
2.表格内容识别不出
3.建议参考fastgpt

**Comment by baixin513** [comment]
PDF 目前只能解析到文本，图片表格都无发解析，参考产品的 pdf文档也是无法识别表格及图片，目前还没有好的解决方案。
