### ISSUE TITLE
应用的api访问能否兼容OpenAI格式，想以OpenAI的格式去请求应用。

### ISSUE THREAD

**Issue by hcppxgit** [1Panel-dev/MaxKB#605]
### MaxKB 版本

版本号:v1.2.0 (build at 2024-05-30T11:33, commit: ac25c392)

### 请描述您的需求或者改进建议

目前根据应用里面API访问凭据生成的密钥和接口我调用不成功，希望能改进成能以OpenAI格式调用进行对话

**Comment by baymax55** [comment]
请问关于API访问凭据有文档吗
