### ISSUE TITLE
[FEATURE]支持千帆appbuilder

### ISSUE THREAD

**Issue by hogking** [1Panel-dev/MaxKB#606]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

你好，目前看QianfanChatModel代码内通过langchain.community实现了千帆模型的对接。但Appbuilder模型无法通过qianfan sdk直接调用，而是要通过appbuilder sdk调用。也是百度近期开放的免费模型之一，内置agent定义等。不知道是否支持上呢？

（文档详见：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Nlks5zkzu，关键词为appbuilder）

**Comment by baixin513** [comment]
感谢反馈，该产品与MaxKB 类似产品，暂时没有计划支持。
