### ISSUE TITLE
API接口地址是什么

### ISSUE THREAD

**Issue by xiaohaiqing** [1Panel-dev/MaxKB#609]
### MaxKB 版本

main

### 问题描述

请问本地源码部署后，如何访问swagger接口地址

### 重现步骤

swagger接口地址是什么呢

**Comment by baixin513** [comment]
感谢反馈，在应用-概栏 -API 访问凭证中有 应用对话的 API
<img width="1393" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/f88bc29c-087c-442e-b450-42b019b1e316">

**Comment by xiaohaiqing** [comment]
> 感谢反馈，在应用-概栏 -API 访问凭证中有 应用对话的 API <img alt="image" width="1334" src="https://private-user-images.githubusercontent.com/52996290/337072835-6a5d6db0-751c-47b1-a990-0d28b6608b1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjYxMzcsIm5iZiI6MTcxODA2NTgzNywicGF0aCI6Ii81Mjk5NjI5MC8zMzcwNzI4MzUtNmE1ZDZkYjAtNzUxYy00N2IxLWE5OTAtMGQyOGI2NjA4YjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwMzAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGY5YjRiMTY5MDE5MWI4MzBkMDI5OGJhY2EzYTBhOTVmMGIwYzIyNDI0OWRmMmJlODIyYTg3MmQ3YjhlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TPX6i28CzgRhAs5AYKyDL-NuW2vWzLmnXwnq3e2eBm4">

你好，我直接访问这个地址的时候浏览器报如下错误，请问这是什么问题呢：The server is configured with a public base URL of /ui/ - did you mean to visit [/ui/doc/chat](http://127.0.0.1:3000/ui/doc/chat) instead?

**Comment by xiaohaiqing** [comment]
> 感谢反馈，在应用-概栏 -API 访问凭证中有 应用对话的 API <img alt="image" width="1334" src="https://private-user-images.githubusercontent.com/52996290/337072835-6a5d6db0-751c-47b1-a990-0d28b6608b1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzIxOTUsIm5iZiI6MTcxODA3MTg5NSwicGF0aCI6Ii81Mjk5NjI5MC8zMzcwNzI4MzUtNmE1ZDZkYjAtNzUxYy00N2IxLWE5OTAtMGQyOGI2NjA4YjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyMTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YTg0MWI4ZmY1YmIwZDViNzJiYjZiYTM5OGRlMzUzZGNlMTA0ZGU5NGMzZDkxNWVlOTNlNGZiMjY1Y2Q2ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CGLH46l-V0qTl8z0cbBmSpICTE3kbDkBrWUdF5AVd2w">

我又试了下，源码部署的不行

**Comment by xiaohaiqing** [comment]
> 感谢反馈，在应用-概栏 -API 访问凭证中有 应用对话的 API <img alt="image" width="1334" src="https://private-user-images.githubusercontent.com/52996290/337072835-6a5d6db0-751c-47b1-a990-0d28b6608b1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTY4MTIsIm5iZiI6MTcxODA5NjUxMiwicGF0aCI6Ii81Mjk5NjI5MC8zMzcwNzI4MzUtNmE1ZDZkYjAtNzUxYy00N2IxLWE5OTAtMGQyOGI2NjA4YjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA5MDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MGY2OWRhNmY4YzU3ODM5N2UxYmNiZjBhM2M4OGMzY2RiMzdkYTZmOGM5NzFiY2UyYTM5MTJiYThhZjkzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DlJnveAxu85rfM-ESwmuuEnIHOX23qGj4P3iM2IFNhw">

ok，感谢
