### ISSUE TITLE
[BUG] 【知识库】- 分段管理中新创建的段落页面关联问题无法绑定

### ISSUE THREAD

**Issue by qingad** [1Panel-dev/MaxKB#61]
### MaxKB 版本

v1.0.0

### 问题描述

各位maxkb的工程师，你们好，有个段落绑定的问题。在新创建的段落页面立刻关联问题的话，填写的问题会无法绑定。

### 重现步骤

在新创建的段落页面立刻关联问题的话，填写的问题会无法绑定。

### 期待的正确结果

创建段落和问题绑定可以同时进行

**Comment by baixin513** [comment]
感谢反馈，该问题与 #53 重复。下个版本修复。
