### ISSUE TITLE
[BUG] 更新到最新版本v1.2.0后，swagger只有一部分api列表了

### ISSUE THREAD

**Issue by finovy** [1Panel-dev/MaxKB#610]
### MaxKB 版本

v1.2.0

### 问题描述

![图片](https://github.com/1Panel-dev/MaxKB/assets/139359420/2053c515-d54e-49db-b174-e9173655921e)

### 重现步骤

在API访问凭据下发的地址点击进入api文档的

**Comment by baixin513** [comment]
感谢反馈，应用的 API 访问凭证就是只有应用对话的 API 接口。其他的是系统级别，不会在应用中展示，后续放到系统级别。
当前版本还不支持查看全局接口文档

**Comment by tomener** [comment]
后面还会有这些去掉的接口吗？
