### ISSUE TITLE
【求助】无法打开swagger，无法查看api接口列表

### ISSUE THREAD

**Issue by nmbtwzt** [1Panel-dev/MaxKB#611]
### MaxKB 版本

1.20

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/50111234/b6123921-4734-4f9d-ab36-fab27c8bd904)
无论是输入网址，还是从应用概览中，都无法查看api接口列表，
按是按开发环境部署的，请问是否有类似开关是管理swagger？

### 重现步骤

访问
![image](https://github.com/1Panel-dev/MaxKB/assets/50111234/1479f72a-db89-4f6e-a09b-17604dd7bad2)
出现
![image](https://github.com/1Panel-dev/MaxKB/assets/50111234/de7e084a-ae45-42c6-b651-8f40cfce90a0)

### 附加信息

是否是网址访问错误？相关的doc等都尝试，全都无法打开swagger

**Comment by baixin513** [comment]
访问地址端口不对，要访问后端服务，端口是 8080

**Comment by nmbtwzt** [comment]
> 访问地址端口不对，要访问后端服务，端口是 8080

![image](https://github.com/1Panel-dev/MaxKB/assets/50111234/344e37d5-ee16-4315-8236-29c4648f273d)
我修改了项目端口号，从8080改成3000了，或者映射到端口3001
其他服务访问都是正常
![image](https://github.com/1Panel-dev/MaxKB/assets/50111234/5a2ae399-4075-4841-a18d-597cad8998ea)

就是无法打开swagger
![image](https://github.com/1Panel-dev/MaxKB/assets/50111234/03caab0f-0367-473c-8e2d-99644118bd4c)

**Comment by 02hao09** [comment]
@nmbtwzt 我在網址最後方加上"/"可以正常連線 ex : http://xx.xx.xxxx:8080/doc/chat/
