### ISSUE TITLE
[FEATURE]分段标题不参与检索

### ISSUE THREAD

**Issue by WongHohin** [1Panel-dev/MaxKB#613]
### MaxKB 版本

1.2.0

### 请描述您的需求或者改进建议

分段标题现在的作用好像只是辅助管理，并不参与检索。如果分段内容中没有分段标题的字眼，提问的问题并不能准确匹配到这个分段。

**Comment by baixin513** [comment]
感谢反馈，分段标题与分段内容放在一起同时参与检索，且分段标题权重会比内容高一些。
