### ISSUE TITLE
[BUG] swagger中的 /application/profile 接口问题

### ISSUE THREAD

**Issue by chk4991** [1Panel-dev/MaxKB#614]
### MaxKB 版本

1.2.0

### 问题描述

在swagger中调用 /application/profile 接口，返回结果是一堆html代码，并没有会话id，与使用手册中的。“如何使用应用的API Key进行对话调用” 不一致。
![image](https://github.com/1Panel-dev/MaxKB/assets/49022065/b5b8a6a8-385d-481f-98f4-946b229597a3)

### 重现步骤

按使用手册可复现。

**Comment by baixin513** [comment]
感谢反馈，解决方案见 issue #587

**Comment by bluedkl** [comment]
> 感谢反馈，重复 [issue #587](https://github.com/1Panel-dev/MaxKB/issues/587) ，接口前加上 /api

刚刚接触不太明白，怎么在接口前加上/api啊
