### ISSUE TITLE
[BUG]导入带有表格样式的md文件分段后表格格式丢失

### ISSUE THREAD

**Issue by zhangdong12306** [1Panel-dev/MaxKB#615]
### 联系方式

971571238@qq.com

### MaxKB 版本

1.2.0

### 问题描述

导入带有表格样式的md文件，智能分段和高级分段无法完成原有格式的导入，导入后表格格式丢失，如下图所示：
![01](https://github.com/1Panel-dev/MaxKB/assets/167972933/585b33ba-d36c-4087-a5b0-17d5ae11d86f)
原有md文件显示如下：
![02](https://github.com/1Panel-dev/MaxKB/assets/167972933/9e0bff77-fd89-449b-8b6e-1e2e83b7837e)

### 重现步骤

[example.md](https://github.com/user-attachments/files/15613320/example.md)
利用该文件添加知识库即可复现

### 期待的正确结果

分段预览后同原始md文件表格格式相同如下图所示
![03](https://github.com/1Panel-dev/MaxKB/assets/167972933/6ec63f2c-5889-47bd-8110-c0d2b005b12c)

**Comment by baixin513** [comment]
感谢反馈， 单独添加分段能正常显示表格，导入的时候表格多了空行导致没有显示表格样式，需要排查一下。

**Comment by baixin513** [comment]
已在 v1.2.1版本解决。
