### ISSUE TITLE
[FEATURE]希望演示界面文本输入框能根据输入文本内容自适应调整

### ISSUE THREAD

**Issue by KyoMio** [1Panel-dev/MaxKB#616]
### MaxKB 版本

1.2.0

### 请描述您的需求或者改进建议

希望演示界面文本输入框能做成那种根据文本行数支持扩大的，类似于chat-next-web项目的那种输入框，对大量文本输入更友好一点。
![image](https://github.com/1Panel-dev/MaxKB/assets/38713408/c33e1be4-06a2-4f1e-8363-01327004744d)

**Comment by baixin513** [comment]
感谢反馈，后续版本优化。
