### ISSUE TITLE
[BUG]源代码部署启动镜像失败

### ISSUE THREAD

**Issue by yanxiaochen** [1Panel-dev/MaxKB#619]
### 联系方式

1615703120@qq.com

### MaxKB 版本

1.2.0

### 问题描述

在Dockerfile 文件中  
ENTRYPOINT ["bash", "-c"]
CMD [ "/usr/bin/run-maxkb.sh" ]

到构建镜像的时候到run-maxkb.sh文件中时以下步骤时
#!/bin/bash   出现无法运行该命令的错误。

### 重现步骤

直接构建源码镜像

### 期待的正确结果

应该在 到构建镜像的时候到run-maxkb.sh文件中的
#!/usr/bin/bash   

修改为： #!/usr/bin/bash

### 相关日志输出

```shell
bash: line 1: /usr/bin/run-maxkb.sh: cannot execute: required file not found
```

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，源码部署遇到的问题自己解决即可。

**Comment by ouzexi** [comment]
> ### 联系方式
> [1615703120@qq.com](mailto:1615703120@qq.com)
> 
> ### MaxKB 版本
> 1.2.0
> 
> ### 问题描述
> 在Dockerfile 文件中 ENTRYPOINT ["bash", "-c"] CMD [ "/usr/bin/run-maxkb.sh" ]
> 
> 到构建镜像的时候到run-maxkb.sh文件中时以下步骤时 #!/bin/bash 出现无法运行该命令的错误。
> 
> ### 重现步骤
> 直接构建源码镜像
> 
> ### 期待的正确结果
> 应该在 到构建镜像的时候到run-maxkb.sh文件中的 #!/usr/bin/bash
> 
> 修改为： #!/usr/bin/bash
> 
> ### 相关日志输出
> ```shell
> bash: line 1: /usr/bin/run-maxkb.sh: cannot execute: required file not found
> ```
> 
> ### 附加信息
> _No response_

楼主，这个问题我也遇到了，按理来说bin链接到/usr/bin，他们的内容是一样的，不明白为什么找不到文件呢？

**Comment by yanxiaochen** [comment]
因为在Dockerfile 文件中 是指定到"/usr/bin/run-maxkb.sh "   /usr 下面的
而且在源码里面的   run-maxkb.sh  文件中 是  #!/bin/bash   只需要改为 #!/usr/bin/bash  即可解决找不到路径的问题

**Comment by yanxiaochen** [comment]
我上面最开始提的打错了
