### ISSUE TITLE
[BUG] 提示语不正确

### ISSUE THREAD

**Issue by Jaylenwa** [1Panel-dev/MaxKB#620]
### MaxKB 版本

v1.2.0

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/65205528/cdf843e7-33ea-4578-b593-f81350475e0e)

### 重现步骤

![image](https://github.com/1Panel-dev/MaxKB/assets/65205528/686521d5-dd7e-4dca-bff9-673f8411db16)

**Comment by baixin513** [comment]
适用格式如下：
标题：问题
正文：答案

![image](https://github.com/1Panel-dev/MaxKB/assets/52996290/46ef1513-c271-4722-b379-8b76c587ba72)
