### ISSUE TITLE
[BUG] 添加千问模型报错

### ISSUE THREAD

**Issue by winslis2** [1Panel-dev/MaxKB#622]
### 联系方式

1362330842@qq.com

### MaxKB 版本

v1.1.3

### 问题描述

运行环境：Mac intel docker部署

成功部署项目后，调整qianwen模型出现问题：
    配置千问max模型调用正常，在阿里云百炼后台新增了一个应用并配置了知识库，想测试下MaxKB能否直接调用百炼应用，但千问模型中配置中没有找到Api地址的配置，所以选择了openai配置千问max,emmm~~，配置应用地址：https://dashscope.aliyuncs.com/api/v1/apps/xxxxxappid/completion
后面发现不行就改为正常千问配置，出现报错：
![image](https://github.com/1Panel-dev/MaxKB/assets/38451303/e200fc6c-31c2-47a6-b792-cc969d1c70cb)
已尝试重新添加模型，源码中并没有请求dashscope.aliyuncs.com代码，不确定是否用到缓存，在V1.2.0没有发现修复此问题

### 重现步骤

无复现

**Comment by winslis2** [comment]
在线升级V1.2.0模型添加正常

**Comment by baixin513** [comment]
感谢反馈，错误提示阿里云接口返回的。
