### ISSUE TITLE
[BUG] 离线安装maxkb，导入docker镜像失败

### ISSUE THREAD

**Issue by jhyvictory** [1Panel-dev/MaxKB#624]
### MaxKB 版本

1.2.0

### 问题描述

这两天docker抽风了，所以尝试离线安装
sudo docker load -i maxkb-v1.2.0-offline.tar.gz
结果返回
open /var/lib/docker/tmp/docker-import-1371897389/maxkb-v1.2.0-offline/json: no such file or directory
是什么原因，求助

### 重现步骤

sudo docker load -i maxkb-v1.2.0-offline.tar.gz
或者
sudo docker load < maxkb-v1.2.0-offline.tar

**Comment by baixin513** [comment]
感谢反馈，当前离线安装支持的是x86，arm 架构的不支持。

**Comment by shaohuzhang1** [comment]
tar -zxvf maxkb-v1.2.0-offline.tar.gz
解压后执行 bash install.sh
