### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by shatang123** [1Panel-dev/MaxKB#626]
### MaxKB 版本

1.20.0

### 请描述您的需求或者改进建议

我希望在开放API的聊天接口中新增用户信息字段，提供给第三方应用调用时填写(非必填)，同时查询聊天记录时返回这些字段。
这样后续的用户分析会更加方便，不然三方系统需要手动记录聊天记录和用户的关联关系

**Comment by baixin513** [comment]
感谢反馈，暂不支持，无法管理提问用户。
