### ISSUE TITLE
[BUG] 模型 qwen-plus 不支持 流式输出 ,智谱 ai glm-4 也不行,一大段一大段输出

### ISSUE THREAD

**Issue by soonxf** [1Panel-dev/MaxKB#627]
### 联系方式

soonxf@dingtalk.com

### MaxKB 版本

v1.2.0 

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/43446813/d1df105d-c727-4218-b21c-f622a064f700)
![Uploading image.png…]()

模型 qwen-plus 不支持 流式输出 ,智谱 ai glm-4 也不行,一大段一大段输出

### 重现步骤

随意提问,都不支持 流式输出

**Comment by liqiang-fit2cloud** [comment]
用户客户端和MaxKB之间有个nginx之类的反向代理么？

**Comment by soonxf** [comment]
已解决 

nginx server 节点增加如下配置

```
    # 流式输出
    proxy_cache off;
    proxy_buffering off; 
    chunked_transfer_encoding on;
    tcp_nopush on; 
    tcp_nodelay on;
    keepalive_timeout 600;
```
