### ISSUE TITLE
[FEATURE]建议在创建助手时，可以设置模型的TopK，TopN Temperature等相关参数

### ISSUE THREAD

**Issue by Rain19981998** [1Panel-dev/MaxKB#641]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

建议在创建助手时，可以设置模型的TopK，TopN Temperature等相关参数

### 请描述你建议的实现方案

建议在创建助手时，可以设置模型的TopK，TopN Temperature等相关参数

**Comment by baixin513** [comment]
感谢反馈，重复 issue #58
