### ISSUE TITLE
[BUG]内存占用高达1.63GiB，可否优化下？

### ISSUE THREAD

**Issue by RainyNightGitHub** [1Panel-dev/MaxKB#646]
### MaxKB 版本

v1.2.0 (build at 2024-05-30T11:33, commit: ac25c392)

### 问题描述

我是腾讯云部署的1panel，在1panel应用里部署的MaxKB，目前什么都没操作，内容占用就高达1.6G，太高了，可否优化下占用？

### 重现步骤

无

**Comment by shaohuzhang1** [comment]
无法优化,模型加载需要1G

**Comment by RainyNightGitHub** [comment]
> 无法优化,模型加载需要1G

收到，已改回Ollama Webui。
