### ISSUE TITLE
你好，可以实现api调用，在程序里面得到相应的答案吗

### ISSUE THREAD

**Issue by GaoHZ1** [1Panel-dev/MaxKB#647]
### MaxKB 版本

版本号:v1.2.0 (build at 2024-05-30T11:33, commit: ac25c392)

### 请描述您的需求或者改进建议

api怎么使用呀请问？
![image](https://github.com/1Panel-dev/MaxKB/assets/138955900/e4ee91dd-7724-4b7c-b322-65d67e21d506)

**Comment by baixin513** [comment]
感谢反馈，参考 wiki 上的文档：
https://github.com/1Panel-dev/MaxKB/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%BA%94%E7%94%A8%E7%9A%84API-Key%E8%BF%9B%E8%A1%8C%E5%AF%B9%E8%AF%9D%E8%B0%83%E7%94%A8
