### ISSUE TITLE
[FEATURE] Session保存

### ISSUE THREAD

**Issue by rainbowers** [1Panel-dev/MaxKB#649]
### MaxKB 版本

1.20

### 请描述您的需求或者改进建议

目前版本session是保存在服务器本地对的，是否考虑将session保存在redis或者memcached这类的nosql中，以提升性能

### 请描述你建议的实现方案

目前版本session是保存在服务器本地对的，是否考虑将session保存在redis或者memcached这类的nosql中，以提升性能

**Comment by baixin513** [comment]
感谢反馈，暂不考虑。
