### ISSUE TITLE
[BUG] php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by simonkuang** [1Panel-dev/MaxKB#650]
### MaxKB 版本

1.2.1

### 问题描述

1. offline 形式安装
2. **OS**：RaspberryPi OS 64bit 最新版。已通过 `apt update; apt upgrade` 升级到最新
3. 访问 `http://<ip>:8080` 后，使用默认账号密码登录
4. 登录失败，回到登录界面。报错 `php_network_getaddresses: getaddrinfo failed: Name or service not known` 

### 重现步骤

1. 完全按照手册中的步骤，使用 offline 方式安装。显示安装成功。
2. 访问 `http://<ip>:7890`，使用默认用户名、密码登录。

### 期待的正确结果

进入系统

### 相关日志输出

```shell
......

NAME      IMAGE     COMMAND   SERVICE   CREATED   STATUS    PORTS

WARNING: No memory limit support
WARNING: No swap limit support
Docker 目录及文件大小 :
8.4G    /var/lib/docker

Docker 目录所在磁盘使用情况 :
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  124G   31G   87G  26% /

日志文件大小 :
du: cannot access '/opt/maxkb/logs/': No such file or directory

MaxKB 运行目录及文件大小 :
10M     /opt

MaxKB 运行目录使用情况 :
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  124G   31G   87G  26% /
[MaxKB Log]: 服务启动成功!
======================= 安装完成 =======================

请通过以下方式访问:
 URL: http://$LOCAL_IP:8080
```
```


### 附加信息

_No response_

**Comment by shaohuzhang1** [comment]
应该是内存不够,或者是没有权限分配内存导致的
可以修改/opt/maxkb/docker-compose.yml ,/opt/maxkb/docker-compose-pgsql.yml添加privileged: true 尝试解决此问题
![image](https://github.com/1Panel-dev/MaxKB/assets/80892890/9de84578-e458-423e-80e9-0376380a5bd5)
![image](https://github.com/1Panel-dev/MaxKB/assets/80892890/ad219fdb-103f-4273-a619-066dbb1d2c4a)
修改完后执行 
kbctl reload
