### ISSUE TITLE
[FEATURE]怎麽利用maxkb的對話來觸發指定的一些API功能？

### ISSUE THREAD

**Issue by vball** [1Panel-dev/MaxKB#654]
### MaxKB 版本

1.2.0

### 请描述您的需求或者改进建议

比如説今天英偉達的股票報價是多少，然後可以觸發調用我們其它系統的API來查詢股票的當前報價

### 请描述你建议的实现方案

是不是利用語義的相似度來判斷，比如先定義會觸發動作的語句，比如查詢股票【XXX】，然後拿到用戶輸入的語句判斷相似度后觸發？maxkb内置有這種類似邏輯嗎？

**Comment by baixin513** [comment]
感谢反馈，当前版本没有这种逻辑，您可以等工作流功能出来后再看一下。

**Comment by vball** [comment]
工作流預計什麽時候可以出來？

**Comment by baixin513** [comment]
等1.3发布。
