### ISSUE TITLE
[FEATURE]建议增加embedding模型配置支持更多的API或离线embedding模型，引入rerank模型对检索结果精排提高问答检索知识的准确率

### ISSUE THREAD

**Issue by zhangdong12306** [1Panel-dev/MaxKB#655]
### MaxKB 版本

1.2.0

### 请描述您的需求或者改进建议

现有应用默认内置了embedding模型shibing624_text2vec-base-chinese用作文档向量化处理，对应不同的任务类型，其他的embedding模型文档向量化后的检索效果更好，希望能引入模块化的embedding模型加载方式；在使用过程中会出现相关引用相关知识根本匹配不上的情况，希望通过rerank和embedding的增强剔除掉不相关的引用增加可靠性

### 请描述你建议的实现方案

建议通过类似应用现支持的LLM模型设置方式增加embedding模型设置，让用户自定义进行文档向量化的模型；rerank模型类似

**Comment by baixin513** [comment]
感谢反馈，重复 issue #60
