### ISSUE TITLE
[BUG]大模型返回json时，解析出错

### ISSUE THREAD

**Issue by ziye142857** [1Panel-dev/MaxKB#656]
### MaxKB 版本

1.2.0

### 问题描述

大模型返回json，解析有问题，只展示到了title。
数据如下：
{
  "title": "张三收",
  "body": "我要邀请他参加活动",
  "email": "xxx@qq.com"
}
报错截图
![image](https://github.com/1Panel-dev/MaxKB/assets/82377240/6f71b69b-9481-4e10-9746-19f46ee9db8d)
![image](https://github.com/1Panel-dev/MaxKB/assets/82377240/739b1a05-2baa-4ca3-b279-e99ad0e4ae8c)

### 重现步骤

使用的是qwen-turbo
1.设置提示词：
回答要求：
邮件的信息整理成{"title":"标题",“body”:"正文","email":"邮箱信息"}的Json格式
问题：
{question}
2.设置无引用知识库分段时
回答要求：
邮件的信息整理成"{"title":"内容摘要",“body”:"正文","email":"邮箱信息"}"这样的Json格式。
问题：
{question}
3.提问
我要发一份邮件给张三，邀请他周末一起去公园玩，他的邮箱是xxxx@qq.com

### 期待的正确结果

正确解析数据

**Comment by baixin513** [comment]
感谢反馈，应该是个 bug，后续版本修复。
