### ISSUE TITLE
[BUG] 模型问答开启问答优化，会有负优化的现象

### ISSUE THREAD

**Issue by Jaylenwa** [1Panel-dev/MaxKB#657]
### 联系方式

1318248167@qq.com

### MaxKB 版本

2024/06/14  main分支源码

### 问题描述

当前这种问题优化方式，有概率是负优化。甚至完全曲解了原先的问答内容。

![bug](https://github.com/1Panel-dev/MaxKB/assets/65205528/52abbb29-0ca8-428c-a3f1-135e72a95552)

### 重现步骤

源码编译，打断点

### 期待的正确结果

有个疑问，这种优化问答的方式，效果应该是完全取决于大模型本身能力的强弱。 
优化这一步是不是应该在自然语言理解【NLU】阶段。而不是直接使用大模型进行优化，不确定性太高。

**自然语言理解 (NLU)**阶段
1. **文本预处理**：如去除无关字符、标点符号、大小写转换等。
2. **拼写检查与纠正**：利用拼写检查算法或模型识别出可能的错别字。
3. **语义理解**：即便在纠正错别字之后，还需通过自然语言理解技术进一步分析问题的意图、关键词和实体。

**eg:  上述只是个人见解**。

**Comment by baixin513** [comment]
感谢反馈，当前问题优化的提示词是代码中设定的会影响优化效果，后续会放出问题优化的模型选择和自定义提示词功能 issue #404 。
关于上面几点的预处理也可以在工作流编排功能出来后，会支持函数库，可以自行写一些代码来处理你说的情况。
