### ISSUE TITLE
[FEATURE] 科大讯飞希望可以支持1.1版本

### ISSUE THREAD

**Issue by nianyi-778** [1Panel-dev/MaxKB#658]
### MaxKB 版本

v1.2.1

### 请描述您的需求或者改进建议

科大讯飞希望可以支持1.1版本

### 附加信息

<img width="735" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/23355645/7249c363-7553-4854-b9d5-d6f949d8d921">

**Comment by nianyi-778** [comment]
<img width="1586" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/23355645/4a7d394c-b2f5-4114-9e50-e92d0462968f">

**Comment by baixin513** [comment]
感谢反馈！
基础模型填写错误，对应讯飞的domain： general
详见：https://bbs.fit2cloud.com/t/topic/6159/2

官方文档：https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
