### ISSUE TITLE
[FEATURE]关于api文档的恢复或开放

### ISSUE THREAD

**Issue by cdzk** [1Panel-dev/MaxKB#659]
### MaxKB 版本

v1.2.1

### 请描述您的需求或者改进建议

希望能够恢复或开放与v1.1.x版本一样的[http://maxkb服务地址/doc](http://xn--maxkb-p86hj6yxdq69m/doc)全部api文档

**Comment by baixin513** [comment]
感谢反馈，全量后续放系统级别，当前版本只提供通过 API Key 进行对话调用的接口文档
