### ISSUE TITLE
[BUG] maxkb 文档点击同步，会同步额外内容出来

### ISSUE THREAD

**Issue by xhy12** [1Panel-dev/MaxKB#661]
### MaxKB 版本

版本号:v1.2.0 (build at 2024-05-30T11:33, commit: ac25c392)

### 问题描述

maxkb 文档点击同步，会同步额外内容出来

![Snipaste_2024-06-21_11-08-12](https://github.com/1Panel-dev/MaxKB/assets/43202800/5ce65203-f658-42e5-a0e3-6d59a21a349f)

![image](https://github.com/1Panel-dev/MaxKB/assets/43202800/0459099e-2742-4f0c-b3db-4a2a2f78955f)

### 重现步骤

采用的 ms官网文档同步，然后文档更新后，根绝文档切片点击同步，
问题： maxkb 文档点击同步，会同步额外js de内容出来

**Comment by baixin513** [comment]
感谢反馈， web站点同步，可以添加选择器过滤你想同步的网页上的内容。如果没有添加选择器默认会同步 body。
同步文档或知识库都会先删除文档在同步新增，所以如果给分段添加过关联问题或修改过分段内容的，不建议直接同步，如果需要同步整个 web站点，建议把人工修改过的文档迁移到其他的知识库中。

详细操作请参考 用户手册说明：https://github.com/1Panel-dev/MaxKB/wiki
