### ISSUE TITLE
[BUG]应用API对话接口返回Unicode编码

### ISSUE THREAD

**Issue by DexterQY** [1Panel-dev/MaxKB#662]
### MaxKB 版本

v1.2.1

### 问题描述

调用应用API对话接口返回的中文部分显示为Unicode编码

### 重现步骤

curl -X 'POST' \
  'http://[ip]:[port]/api/application/chat_message/3a91b464-2f7d-11ef-a09f-0242ac120003' \
  -H 'accept: application/json' \
  -H 'AUTHORIZATION: application-437effc39d40d18f63453bcdd1823f18' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": "hello world",
  "re_chat": false,
  "stream": true
}'

### 期待的正确结果

正常显示中文

### 附加信息

![image](https://github.com/1Panel-dev/MaxKB/assets/32505750/4f6b7ab0-c507-47f0-bfd9-17554ca39bb2)

**Comment by shaohuzhang1** [comment]
响应数据可以这样utf-8解码
result.content.decode('utf-8')
