### ISSUE TITLE
[FEATURE] 应用在问答时支持选择知识库

### ISSUE THREAD

**Issue by Jaylenwa** [1Panel-dev/MaxKB#664]
### MaxKB 版本

最新版本

### 请描述您的需求或者改进建议

现状：
新建知识库、新建应用。 应用使用时需要先关联知识库。

需求：
能不能支持应用在使用时动态选择知识库？这样我只需要创建一个通用应用，在问答时选择不同的知识库就可以实现无数个应用。用起来也更方便。
举个例子：假如我有20个知识库（知识库的内容是完全独立的），那我就需要建20个应用。如果可以在使用应用时选择知识库，那我只需要建一个应用。

### 请描述你建议的实现方案

能不能支持应用在使用时动态选择知识库？这样我只需要创建一个通用应用，在问答时选择不同的知识库就可以实现无数个应用。用起来也更方便。

### 附加信息

举一个百川知识库问答的例子：

![image](https://github.com/1Panel-dev/MaxKB/assets/65205528/a4054820-84fd-465c-8c97-d6826f0afc9a)

**示例**

![image](https://github.com/1Panel-dev/MaxKB/assets/65205528/257649c4-63d7-4596-918d-fc01ee50d713)

**Comment by baixin513** [comment]
感谢反馈， 当前机制知识库是在管理端维护，提问用户可能并不知道答案在哪个知识库中，暂时还没有这个计划
