### ISSUE TITLE
[FEATURE]是否可以支持接入智谱AI更多的模型，以及在问问题可以上传文档或者图片进行提问

### ISSUE THREAD

**Issue by zhangleijun111** [1Panel-dev/MaxKB#666]
### MaxKB 版本

latest

### 请描述您的需求或者改进建议

]是否可以支持接入智谱AI更多的模型，以及在问问题可以上传文档或者图片进行提问

### 请描述你建议的实现方案

]是否可以支持接入智谱AI更多的模型，以及在问问题可以上传文档或者图片进行提问

### 附加信息

]是否可以支持接入智谱AI更多的模型，以及在问问题可以上传文档或者图片进行提问

**Comment by baixin513** [comment]
感谢反馈，当前已经支持智谱AI模型。还不支持用户提问时上传文档。
