### ISSUE TITLE
[BUG]使用应用的API Key接口调用未登录

### ISSUE THREAD

**Issue by Thinking80s** [1Panel-dev/MaxKB#669]
### MaxKB 版本

v1.1.3 (build at 2024-05-15T17:49, commit: e74ba87f)

### 问题描述

使用应用的API Key接口调用未登录
<img width="971" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/338079/b6003127-41b2-45f0-8292-aadb81d092a0">

### 重现步骤

使用应用的API Key接口调用未登录

**Comment by baixin513** [comment]
感谢反馈，请根据文档进行操作：https://github.com/1Panel-dev/MaxKB/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%BA%94%E7%94%A8%E7%9A%84API-Key%E8%BF%9B%E8%A1%8C%E5%AF%B9%E8%AF%9D%E8%B0%83%E7%94%A8
