### ISSUE TITLE
[BUG]图片url错误导致图片不显示

### ISSUE THREAD

**Issue by WongHohin** [1Panel-dev/MaxKB#673]
### MaxKB 版本

1.2.0

### 问题描述

在知识库中能显示出来的图片，到回答的时候就有概率会显示不出来，F12查看图片的url，发现url不对。
在引用里是这样的：
![image](https://github.com/1Panel-dev/MaxKB/assets/44478940/fc76999d-df5f-414f-903a-b6839de2d6e4)

第一种情况：
![image](https://github.com/1Panel-dev/MaxKB/assets/44478940/7b65f956-a49f-4592-b21b-c7dcd2e3f011)

第二种情况：
![image](https://github.com/1Panel-dev/MaxKB/assets/44478940/13b6ba88-eccb-41ce-b587-2e16b73a9f27)

有时候还会出现这种情况：
![image](https://github.com/1Panel-dev/MaxKB/assets/44478940/81e2427b-44f4-468e-9173-5eb206306eaf)

### 重现步骤

按wiki操作，把带图片的docx上传，再提问，引用分段都有带出来，在引用里能看到图片

**Comment by baixin513** [comment]
感谢反馈，分段中能看到图片说明MaxKB没有问题，AI回答不显示图片这是模型返回的URL，MaxKB无法控制。
如果图片比较重要需要回答时显示的，建议把文档的命中处理方式改成直接回答，这样就不走大模型了。
