### ISSUE TITLE
[Bug]批量导入在线文档,中间文档抓取失败会影响后面的文档不在继续抓取

### ISSUE THREAD

**Issue by bingshan2024** [1Panel-dev/MaxKB#677]
### MaxKB 版本

1.21

### 请描述您的需求或者改进建议

1.应用嵌入第三方页面后，页面右下侧弹出的提示内容，应该允许管理员在后台有权限修改：
比如我们的需求是：
🌟 遇见问题，不再有障碍！      改为显示： 公司logo图片    公司名称你的智能小助手。    改为显示：您好，我是您的专属XXXX智能助手，您可以向我咨询关于XXX事项的问题~
点我，迅速开启高效对话模式，让问题变成过去式。 
我知道了。         改为显示：   
![white-help](https://github.com/1Panel-dev/MaxKB/assets/174347401/7aaec6ab-036a-4527-9b27-06437672ca5f)
问答规范                     我知道了。
![1](https://github.com/1Panel-dev/MaxKB/assets/174347401/27b64322-a703-4102-a6a6-7f2b8e394b5a)
总之，这个弹出显示管理员后台可以关闭显示，可以修改显示内容，内容可以分段排版；为了与嵌入页面的颜色相匹配，希望拥有可以自定义文字颜色的权利，或者在手册里提供如何在嵌入代码里自定义也行。
2.应用嵌入第三方页面后，页面右下侧的MaxKB头像位置是否可以自自定义在页面的位置？在一个单位如果领导指定在某个位置显示是必须得到执行的，相当一部分用户并不掌握二开的技术能力，所以能后台授权给管理员的就不要打包到镜像里不让修改。
3、
![333](https://github.com/1Panel-dev/MaxKB/assets/174347401/ce353b6c-5f05-4e55-b7bb-f3b0e5c77a6c)
历史记录图标左侧可以增加一个“问答规范”或者“问答技巧”或“帮助”或“使用指南”的小图标，用户点击后可以弹出多张左右切换的图片格式问答技巧或者管理员后台自定义发布的文字格式问话模板样式参考。
4.应用对话中的问、答头像，允许管理员后台自定义修改替换，比如使用：
![wen](https://github.com/1Panel-dev/MaxKB/assets/174347401/8b809813-1121-4021-b157-94f4a6c6ddef)
![da](https://github.com/1Panel-dev/MaxKB/assets/174347401/c7feb426-f474-4ffe-b495-617125aa8463)
5.虽然现在应用对话框随着输入文字的增多会自适应变高，但是建议应用对话框的默认高度再调高一点，比如
![555](https://github.com/1Panel-dev/MaxKB/assets/174347401/36acbcb9-7f3f-42a5-8656-e2a3ff3d0041)
理由是问答助手不是普通搜索引擎框，智能对话输入的文字相对较多，如果默认输入四行文字以后再自适应，用户心理上将更加舒服，现在默认是一行，用户心理感觉不得劲，当然具体默认几行，需要你们斟酌。
![4444](https://github.com/1Panel-dev/MaxKB/assets/174347401/b26353f3-46bd-48c9-997d-92891d27faaa)
对话框无文字输入时的边框颜色（灰色）与框内的白色背景对比度太小，使用时眼睛定位费劲，建议对话框边框颜色灰度再加深一点。如果有可能，输入框默认高度加高的话，可以在最后一行增加一个“还可以输入多少字”的提示，数字使用红色显示。
“请输入”改为“请输入您想了解的问题，Ctrl+Shift键换行，输入完毕Enter键发送”
6.关键的一个需求：允许管理员对用户使用进行管理。比如将应用嵌入我们的网站主页后，员工点击MaxKB图标提示“”登录”，这样就过滤掉未被授权用户使用导致泄密事件的发生。假设我们单位授权100名员工使用，可采取用户名+密码的方式授权使用，考虑到我们的员工电脑都局域网固定IP且已经实名认证绑定，所以采取管理员直接后台新增授权员工电脑IP或者某个IP段，使用这些电脑的员工可以直接点开MaxKB图标使用的用户体验是最佳的，顺便解决了员工忘记或修改密码频繁给管理员增加工作量的问题，当该员工被取消授权时，管理员直接后台暂停或者停止、删除该IP的使用权限即可。当然其他一些用户用不到这个功能，可以允许管理员在后台设置全员无限制访问和授权访问，但是我们目前是急需要授权访问，这是我们单位的硬性要求。
7、
![66](https://github.com/1Panel-dev/MaxKB/assets/174347401/9583a3bd-f0b0-45c7-b054-12a80b1f4198)
后台：应用    知识库     系统设置
建议将三个模块改换到左侧上下显示（默认弹开状态就行，不要让用户再二次点开）
应用：
      我的应用
      创建应用
知识库：
      我的知识库
      创建知识库
系统设置：
       用户管理
       团队成员
       模型设置
       邮箱设置
8、
![888](https://github.com/1Panel-dev/MaxKB/assets/174347401/0a1e2393-1927-43e1-8103-584877b2f687)
知识库，导入文档，输入文档地址：假设我需要添加1万个网址，我一次性粘贴进来100个，当系统抓取到第三个或者第十个。。。网址时，这个网站恰好升级维护或者网址从http更换为https，则抓取就卡在这里停止了，需要人工核对已经导入的文档列表，找到剔除抓取失败的那个网址后，再次粘贴后面未抓取的网址，可能又会继续前面的卡主的情况。是否可以这样解决：当碰到暂时无法访问的网址时，该网址（文件名称）仍然正常在列表里显示，但是字符数 | 分段 | 文件状态 分别显示为“0” “0” “失败”，假设我一次性读取了5000个网站后，我就可以翻页查看哪些是失败的，可以人工处理修正网址或删除。当然如果能一键把这些失败显示为0 的能排序集中显示就更好了，就不用翻页了。
我还有一个问题没有搞懂，比如我添加了网站：https://www.gov.cn/  ，当天进行了抓取分段。很显然这个网站是每天更新网页信息的，我需要每天更新抓取新发布的网页信息，那么点击“同步知识库”-“替换同步”就可以达到我的要求了吗？我试了几次发现之前添加的网址字符数、分段都是不变化的，保持了首次抓取时的状态。

**Comment by baixin513** [comment]
感谢您的反馈，关于您反馈的问题回复如下：
1234条会在我们的企业版功能中。
5 ：配色可以优化一下
6：与issue #428 重复
7：当前架构不计划修改
8: 批量导入在线文档的，正常是不会中断，抓取失败的文档状态为失败，不会影响后面的文档抓取，如果中断就是BUG。
