### ISSUE TITLE
[BUG]導入知識庫的頁面在小屏幕的電腦適配時無法顯示翻頁功能

### ISSUE THREAD

**Issue by vball** [1Panel-dev/MaxKB#682]
### MaxKB 版本

1.2.1

### 问题描述

<img width="1429" alt="截屏2024-07-02 10 52 50" src="https://github.com/1Panel-dev/MaxKB/assets/1772818/3f46e011-bf1c-46db-bb67-bd36559f9530">

### 重现步骤

<img width="1429" alt="截屏2024-07-02 10 52 50" src="https://github.com/1Panel-dev/MaxKB/assets/1772818/95823c6d-6454-4969-ad11-79af3cf31cd1">

**Comment by baixin513** [comment]
感谢反馈，二开过的请自行排查一下问题。正常版本没有这个问题。
