### ISSUE TITLE
[BUG] 上传页面，点击开始导入没有权限访问

### ISSUE THREAD

**Issue by Ausli** [1Panel-dev/MaxKB#683]
### 联系方式

a532089051@outlook.com

### MaxKB 版本

1.2.1 & 1.3.0

### 问题描述

上传文档开始导入，没有权限访问

### 重现步骤

https://github.com/1Panel-dev/MaxKB/assets/70201547/37abff79-7e28-4e38-bcc9-23c200a9bf8c

**Comment by shaohuzhang1** [comment]
确定这个知识库是admin用户的  如果是其他用户的知识库需要授权给admin用户

**Comment by Ausli** [comment]
admin，系统管理员

**Comment by shaohuzhang1** [comment]
在系统设置里面的团队管理里面查看一下有没有这个知识库

**Comment by Ausli** [comment]
https://github.com/1Panel-dev/MaxKB/assets/70201547/53fb2dc2-69eb-4d0c-b432-378e9561a9c2

有的，之前还是上传一个，现在一个都上传不了

**Comment by shaohuzhang1** [comment]
是使用的官方镜像安装的吗？

**Comment by Ausli** [comment]
> 是使用的官方镜像安装的吗？

是的，使用1panel面板应用商城安装的

**Comment by Ausli** [comment]
删除知识库应用重装后仍然是同样的问题

**Comment by baixin513** [comment]
使用官方标准包无法复现您的问题，建议您铲除环境，重新下载官方最新的安装包重新安装一下。

**Comment by Ausli** [comment]
https://github.com/user-attachments/assets/5696ce0c-e9b8-48d0-983d-0e3f5c99e9a8

**Comment by Ausli** [comment]
![image](https://github.com/user-attachments/assets/abe32766-b938-4984-b893-82c1e8c70daf)
原因已找到，1panel拦截了

**Comment by houlangs** [comment]
遇到相同问题，关闭1p waf解决。建议两边开发同步下
