### ISSUE TITLE
[BUG] admin修改密码界面，无法输入邮箱

### ISSUE THREAD

**Issue by Ausli** [1Panel-dev/MaxKB#685]
### MaxKB 版本

1.2.1

### 问题描述

admin修改密码界面，无法输入邮箱，鼠标是禁止的标志，无法输入

### 重现步骤

https://github.com/1Panel-dev/MaxKB/assets/70201547/65a4fdc2-abc9-44b5-88e1-9cd6b1c8be3f

### 附加信息

在用户管理添加邮箱后仍然不显示邮箱

**Comment by shaohuzhang1** [comment]
admin修改密码在这里修改
![image](https://github.com/1Panel-dev/MaxKB/assets/80892890/ff0081e8-6063-4cf8-bb96-18251d01232b)
用户需要配置邮箱才可以进行修改

**Comment by Ausli** [comment]
配置邮箱后无效

**Comment by Ausli** [comment]
这个问题没有解决，请打开这个issues

**Comment by Ausli** [comment]
KeePassXC-Browser插件冲突导致的，问题已经解决了
