### ISSUE TITLE
[FEATURE] /docs之前的接口文档放在哪了

### ISSUE THREAD

**Issue by yuanjie-ai** [1Panel-dev/MaxKB#693]
### MaxKB 版本

lastest

### 请描述您的需求或者改进建议

[FEATURE] /docs之前的接口文档放在哪了

### 请描述你建议的实现方案

[FEATURE] /docs之前的接口文档放在哪了

### 附加信息

[FEATURE] /docs之前的接口文档放在哪了

**Comment by baixin513** [comment]
感谢反馈，之前链接放错了，应用那应该只有通过API进行对话的文档，系统的接口文档会在后续版本中放出。
