### ISSUE TITLE
[FEATURE]对话框是否可以支持上传图片pdf word excel等

### ISSUE THREAD

**Issue by zhangleijun111** [1Panel-dev/MaxKB#694]
### MaxKB 版本

latest

### 请描述您的需求或者改进建议

对话框是否可以支持上传图片pdf word excel等

### 请描述你建议的实现方案

对话框是否可以支持上传图片pdf word excel等

### 附加信息

对话框是否可以支持上传图片pdf word excel等

**Comment by liqiang-fit2cloud** [comment]
没有计划支持。目前知识库只允许管理员在后台维护，对话框中只能提问指定范围内的问题，不支持上传文件。
