### ISSUE TITLE
回答下方列表显示知识库所有符合相似度的回答，以便用户查看

### ISSUE THREAD

**Issue by sc1999vip** [1Panel-dev/MaxKB#699]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

![知识库引用](https://github.com/1Panel-dev/MaxKB/assets/54068617/58782308-f80c-47c5-ade0-7d2ccd75c212)

是否可以在回答下方显示相关知识库引用，并列表形式展示所有符合应用中设置相似度的相关回答。如图所示

**Comment by baixin513** [comment]
感谢反馈，需要在概览中设置一下 显示知识来源
https://maxkb.cn/docs/user_manual/app/app-view/#3
