### ISSUE TITLE
添加猜你想问功能

### ISSUE THREAD

**Issue by sc1999vip** [1Panel-dev/MaxKB#700]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

![猜你想问](https://github.com/1Panel-dev/MaxKB/assets/54068617/a9d76a3c-4e03-4506-82b9-3ba204befebc)
根据用户提问，添加猜你想问的功能，如果所示。以便引导用户下一步提问

**Comment by baixin513** [comment]
感谢反馈，需求同 #516
