### ISSUE TITLE
maxkb并发

### ISSUE THREAD

**Issue by jiangxia207** [1Panel-dev/MaxKB#705]
### MaxKB 版本

v1.2.1

### 请描述您的需求或者改进建议

llama3支持并发，但是maxkb /api/application/chat_message接口还是单线程

**Comment by baixin513** [comment]
感谢反馈，MaxKB不做并发限制且支持多人同时提问。您再研究一下Ollama的配置，或者改成在线模型的。

**Comment by jiangxia207** [comment]
我本地ollama 没用docker,直接服务器上运行的， ollama现在为5并发， ps信息为/tmp/ollama94539040/runners/cuda_v11/ollama_llama_server --model /usr/share/ollama/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 10240 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --parallel 5 --port 38389。  使用jmeter测试3并发要27秒， 
![image](https://github.com/1Panel-dev/MaxKB/assets/2645658/1c8c0217-083b-4429-a965-a2656fd77080)
麻烦再看下呢。

**Comment by jiangxia207** [comment]
另外ollama 并发调整后， 单读测试接口也慢了很多， 从5秒到18秒。

**Comment by 6925404** [comment]
我也遇到并发的问题 ollama 和 vllm 都是最大6个并发，ollama设置并发数 还是6个，很奇怪。
