### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by zhangshuai0220** [1Panel-dev/MaxKB#713]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

1、增加访问控制权限校验
2、增加后台接口增加知识库文档

### 请描述你建议的实现方案

1、当前链接公开后没有对用户进行限制，建议后台增加匿名开关，当不允许匿名时 第三方系统调用接口传用户名获取token，然后需要带上token才可以进行会话
2、希望增加知识库文档上传接口，方便第三方系统同步知识库

**Comment by baixin513** [comment]
感谢反馈，回复如下：
问题1: 同需求 #428 
问题2: 会在企业版中提供整个系统的API，预计下个月发布。
