### ISSUE TITLE
不支持本地git模式安装

### ISSUE THREAD

**Issue by smileyboy2019** [1Panel-dev/MaxKB#718]
### MaxKB 版本

最新版本

### 问题描述

git 下载后You can run `cp config_example.yml /opt/maxkb/conf/config.yml`, and edit it.
第一个错误
第二错误
![image](https://github.com/1Panel-dev/MaxKB/assets/59221294/142694a0-3577-47d2-a410-ba4dbfaa2448)

### 重现步骤

从新安装也是报错

**Comment by shaohuzhang1** [comment]
参考这个:https://github.com/1Panel-dev/MaxKB/wiki/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA
