### ISSUE TITLE
[FEATURE]支持函数库

### ISSUE THREAD

**Issue by Ljohn001** [1Panel-dev/MaxKB#725]
### MaxKB 版本

v1.3.0

### 请描述您的需求或者改进建议

请问现在编排中能否加入langchain 智能体Agents，可以动态调用外部接口，实现数据及时捕获功能
使用场景：
比如我想要知道今天值班同事是谁，可以调用相关的接口返回值班人数据，最后通过llm给返回。

**Comment by baixin513** [comment]
感谢反馈，等后面版本支持函数库，预计 1.5

**Comment by jlokys** [comment]
+1 建议这块可以提速，增加工具库管理，在应用中可以选择，利用agent代理，增强丰富rag，工具能返回特定结构化数据，同时在对话界面可以针对回答内容，定制回答显示块的界面。

**Comment by charles820** [comment]
+1

**Comment by wucanhong** [comment]
+1
