### ISSUE TITLE
[BUG]AI编排中，指定回复的内容，不能在任务流程中传递，会返回空

### ISSUE THREAD

**Issue by mingdiantianxia** [1Panel-dev/MaxKB#726]
### 联系方式

1982104592@qq.com

### MaxKB 版本

v1.3.0 (build at 2024-07-03T18:30, commit: 28fb1db7)

### 问题描述

![image](https://github.com/1Panel-dev/MaxKB/assets/18722959/6a37d36c-d22b-4611-8281-f197145a9ce3)
![image](https://github.com/1Panel-dev/MaxKB/assets/18722959/e7022e85-6dc8-464a-a808-97c054f17b72)
AI编排中，指定回复的内容，不能在任务流程中传递，会返回空

### 重现步骤

在AI编排的任务中间插入一个“指定回复”组件

### 期待的正确结果

“指定回复”的内容应该支持向下传递，这样可以对上层答案进行补充和修正。

**Comment by baixin513** [comment]
感谢反馈，后续版本修复。
