### ISSUE TITLE
模型和知识库可以在不同用户中共享（分只读和修改权限），其它用户在建立应用的时候可以选择这些模型和知识库

### ISSUE THREAD

**Issue by binxushy** [1Panel-dev/MaxKB#731]
### MaxKB 版本

1.0.4

### 请描述您的需求或者改进建议

希望某个用户统一管理所有模型的建立，其它用户不需重复再建立模型了，但其它用户（通过授权该用户或所有用户）可以使用这些模型。不同的用户可以建立自己的知识库，同时共享给指定用户或所有用户。
其它用户在建立应用的时候可以选择这些模型和知识库

### 请描述你建议的实现方案

无

### 附加信息

谢谢！

**Comment by baixin513** [comment]
感谢反馈，当前的机制是用户资源相互隔离的，因为有关联关系的不能随意删除，但可以协作维护一个资源，暂时先不计划放开相互使用。
