### ISSUE TITLE
[FEATURE] 希望增加在引用分段中能夠查看引用的完整文件

### ISSUE THREAD

**Issue by 02hao09** [1Panel-dev/MaxKB#734]
### MaxKB 版本

v1.3.0

### 请描述您的需求或者改进建议

希望能夠再點選引用分段中的檔案名稱時查看引用的完整文件,
如下圖所示, 點選紅框後, 能夠顯示此文件的完整內容.
![image](https://github.com/1Panel-dev/MaxKB/assets/63303985/c33e68aa-f0e3-4fc9-84f1-ef7c125b6648)

**Comment by baixin513** [comment]
感谢反馈，当前是不存原始文档的，后续再考虑一下。

**Comment by baixin513** [comment]
在1.8版本中，如果是web站点知识库的文档，点击文档名称后可以跳转查看原文档地址。您可以升级到v1.8.0版本试用一下
