### ISSUE TITLE
希望通过API方式提交知识库

### ISSUE THREAD

**Issue by smileyboy2019** [1Panel-dev/MaxKB#737]
### MaxKB 版本

1。3

### 请描述您的需求或者改进建议

文档里面没有详细描述，知识库可以如何添加，比如知识库在传统数据库中，怎么导入到目前数据库中，有没有接口，文章分段，(Prompt Engineering 过程希望有API 可以操作

**Comment by geosmart** [comment]
+1

**Comment by baixin513** [comment]
感谢反馈，后续企业版中会提供用户级别的系统API。
