### ISSUE TITLE
问题在知识库中没有找到，自动会去大模型中找寻。需求：如在知识库中找不到，直接回答没有，不要去大模型中找了，不然答非所问

### ISSUE THREAD

**Issue by wjhmiss** [1Panel-dev/MaxKB#740]
### MaxKB 版本

v1.3.0

### 问题描述

问题在知识库中没有找到，自动会去大模型中找寻。需求：如在知识库中找不到，直接回答没有，不要去大模型中找了，不然答非所问

### 重现步骤

问题在知识库中没有找到，自动会去大模型中找寻。需求：如在知识库中找不到，直接回答没有，不要去大模型中找了，不然答非所问

### 期待的正确结果

问题在知识库中没有找到，自动会去大模型中找寻。需求：如在知识库中找不到，直接回答没有，不要去大模型中找了，不然答非所问

**Comment by lixiangwuxian** [comment]
可以使用高级编排
![图片](https://github.com/1Panel-dev/MaxKB/assets/16081973/f2147de9-6682-42e0-9e66-9d2652697eb9)

**Comment by baixin513** [comment]
简易应用配置如下：
<img width="1130" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/52996290/9a0a125c-7c0c-464c-a65c-ea5af5096a15">
