### ISSUE TITLE
[FEATURE] 部署及性能相关问题

### ISSUE THREAD

**Issue by wivw0306** [1Panel-dev/MaxKB#742]
### MaxKB 版本

master

### 请描述您的需求或者改进建议

官方提供的部署方式底层是采用python manage.py runserver方式启用，据我所知这种一般是用于开发模式，请问这种方式是否可以用于生产环境？
如图：
<img width="949" alt="image" src="https://github.com/1Panel-dev/MaxKB/assets/95760640/059e7749-a790-4846-b764-02464ccf94ea">

### 请描述你建议的实现方案

建议采用uwsgi 或者gunicorn、或者uvicon、等异步高性能方案进行部署。

**Comment by shaohuzhang1** [comment]
收到反馈,尝试使用其他方案进行部署

**Comment by baixin513** [comment]
感谢反馈，生产环境建议使用离线部署方式，参考官方文档：https://maxkb.cn/docs/installation/offline_installtion/
