### ISSUE TITLE
[FEATURE]高级编排时执行详情只显示知识库引用

### ISSUE THREAD

**Issue by WongHohin** [1Panel-dev/MaxKB#744]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

现在应用使用高级编排模式后，打开了显示知识来源，执行详情会把整个过程都显示出来，然而用户一般只需要看到知识库引用了哪些分段，其它的看不懂也不需要看。

### 请描述你建议的实现方案

可以设置执行详情里只显示知识库检索的结果，或者可以自定义显示内容

**Comment by baixin513** [comment]
感谢反馈，应用概览中可以设置不显示知识来源。

高级编排的执行详情是整个流程的执行过程，可以详细看到执行的哪个节点。
知识库检索节点可以有N个，每个节点引用的内容都不同，无法像简易配置的应用显示一个知识来源。

另外，如果用不到复杂的编排流程，建议您使用简易配置的应用。
