### ISSUE TITLE
返回的分段结果排序不对，不是按照命中高低顺序排序[BUG]

### ISSUE THREAD

**Issue by dlluckboy** [1Panel-dev/MaxKB#746]
### MaxKB 版本

01.3.0

### 问题描述

返回的分段结果排序不对，不是按照命中高低顺序排序
<img width="83" alt="微信图片_20240712105816" src="https://github.com/user-attachments/assets/d8a68a83-2cf3-40b4-a8c3-799a092b11b9">

### 重现步骤

。。

**Comment by baixin513** [comment]
感谢反馈，后续版本修复。
