### ISSUE TITLE
[BUG]打开doc/chat显示404

### ISSUE THREAD

**Issue by franklin87** [1Panel-dev/MaxKB#747]
### 联系方式

490495556@qq.com

### MaxKB 版本

版本号:v1.3.0 (build at 2024-07-03T18:30, commit: 28fb1db7)

### 问题描述

![image](https://github.com/user-attachments/assets/2eb1d5e5-b364-42dc-aba1-26c11b9df10a)

### 重现步骤

输入http://192.168.0.20:8080/doc/chat
会自动价格ui变成  http://192.168.0.20:8080/ui/doc/chat
不过有和没有都是404

**Comment by baixin513** [comment]
感谢反馈，后续版本修复。
