### ISSUE TITLE
[FEATURE] siliconflow 支持

### ISSUE THREAD

**Issue by IncubatorShokuhou** [1Panel-dev/MaxKB#750]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

https://siliconflow.cn/
接入了市面上大多数开源大模型。优点是价格便宜。 文档：https://docs.siliconflow.cn/docs/getting-started

**Comment by baixin513** [comment]
感谢反馈，看下来这个平台应该是标准的OpenAI格式，您可以使用OpenAI的供应商对接一下您上面这个模型试一下。
