### ISSUE TITLE
[FEATURE] 对外暴露openai api接口，以供下游任务使用

### ISSUE THREAD

**Issue by IncubatorShokuhou** [1Panel-dev/MaxKB#752]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

希望可以对外暴露一个openai api标准的接口，让一些只能接受openai api标准接口的下游任务（例如https://github.com/TabbyML/tabby ，https://www.cursor.com/ 等）可以直接使用（而不用我自己再写代码转发）

**Comment by baixin513** [comment]
感谢反馈，重复issue 同 #353 。
