### ISSUE TITLE
[BUG]判断器中删除其中一个条件后，再添加前端顺序号未更新

### ISSUE THREAD

**Issue by xueqidove** [1Panel-dev/MaxKB#753]
### 联系方式

无

### MaxKB 版本

v1.3.0

### 问题描述

判断器中删除其中一个条件后，再添加前端顺序号未更新

### 重现步骤

第一步：添加判断器，添加ELSE IF1、ELSE IF2、ELSE IF3
第二步：删除ELSE IF2，然后重新在最后分支下再添加一个分支
最后：展示结果为：ELSE IF1、ELSE IF3、ELSE IF3
<img width="657" alt="image" src="https://github.com/user-attachments/assets/21ecd83e-006b-4c2c-904c-f9dc8368d1bc">

### 期待的正确结果

期待结果应该为：ELSE IF1、ELSE IF2、ELSE IF3

**Comment by baixin513** [comment]
感谢反馈，后续版本修复。
