### ISSUE TITLE
开放更多Api接口，通过接口维护管理知识库

### ISSUE THREAD

**Issue by hzk866** [1Panel-dev/MaxKB#754]
### MaxKB 版本

v1.3.0

### 请描述您的需求或者改进建议

希望可以开放更多的api接口，可以通过api的形式来维护知识库中的信息。类似于Langchain-chatchat暴露出来的swagger文档
![image](https://github.com/user-attachments/assets/c4aed7dc-01fb-46ea-8fdb-4dde0c5aea73)

**Comment by baixin513** [comment]
感谢反馈，下个月的企业版本中会提供全系统的API接口及接口文档。

**Comment by hzk866** [comment]
> 感谢反馈，下个月的企业版本中会提供全系统的API接口及接口文档。

企业版本会收费吗？
