### ISSUE TITLE
[BUG]导入文件稍多或稍大时，会出现页面空白

### ISSUE THREAD

**Issue by dingar** [1Panel-dev/MaxKB#755]
### MaxKB 版本

v1.3.0 (build at 2024-07-03T18:30, commit: 28fb1db7)

### 问题描述

![image](https://github.com/user-attachments/assets/02041dbc-2ea4-43e5-ba90-ddf4aa183ac2)

上传大文件（20MB以上），或很多小文件（十几个）后，出现如上页面。点下一步，跳转到列表页面，但没有导入任何信息。

### 重现步骤

如上描述，可能反复重现。

**Comment by baixin513** [comment]
感谢反馈，我们测过100兆左右的文件均能正常上传，为了快速排查定位原因，如果方便的话可以把页面空白的文档发送到 xin.bai@fit2cloud.com。

**Comment by baixin513** [comment]
收到您的邮件，您所有文件上传都显示空白，应该是您服务器网络的原因，您可以在点击下一步进入分段规则前，检查一下网络请求有没有报错。

**Comment by dingar** [comment]
已经找到问题了，nginx的限制的问题。已经修复。感谢。
