### ISSUE TITLE
[FEATURE]追加问题

### ISSUE THREAD

**Issue by dalei888888** [1Panel-dev/MaxKB#762]
### MaxKB 版本

v1.3.0

### 请描述您的需求或者改进建议

场景描述：
根据知识库检索的结果，进行进一步展示及选择追问
例：对话输入“MaxKB 主要功能有什么？” 回复个列表 1.编排 2.对话日志 3.命中测试 ，然后点击“1.编排”，继续询问

### 请描述你建议的实现方案

建议以特殊标识符规则，在指定回复中设定

**Comment by baixin513** [comment]
感谢反馈，后续我们考虑一下。
