### ISSUE TITLE
[FEATURE]【应用编排】建议增加问题分类组件

### ISSUE THREAD

**Issue by lianxintao** [1Panel-dev/MaxKB#767]
### MaxKB 版本

v1.3.0

### 请描述您的需求或者改进建议

建议增加问题分类组件

**Comment by y0t** [comment]
建议高级编排里，增加备份，导入，导出的功能，方便快速搭建流程，备份流程。

**Comment by baixin513** [comment]
感谢反馈，问题分类可以添加AI对话，提示词角色设置为问题分类对应的即可,如下：
<img width="286" alt="image" src="https://github.com/user-attachments/assets/54f00881-5f09-45b1-a89e-87073a4080bb">

**Comment by baixin513** [comment]
> 建议高级编排里，增加备份，导入，导出的功能，方便快速搭建，备份，迁移流程等。

您的需求可以新开issue
