### ISSUE TITLE
[BUG]连接的Ollama，每次对话都是回复 抱歉，没有查找到相关内容，请重新描述您的问题或提供更多信息。

### ISSUE THREAD

**Issue by sundaqiang** [1Panel-dev/MaxKB#77]
### MaxKB 版本

1.0.0

### 问题描述

连接的Ollama，每次对话都是回复  抱歉，没有查找到相关内容，请重新描述您的问题或提供更多信息。

![PixPin_2024-04-15_14-39-55](https://github.com/1Panel-dev/MaxKB/assets/34206512/ecbf7e9b-7fd5-42ba-b7c0-1c8d0f50b15d)

这个是maxkb的日志

/opt/py3/lib/python3.11/site-packages/django/db/models/base.py:364: RuntimeWarning: Model 'dataset.dynamics' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)

### 重现步骤

无

**Comment by baixin513** [comment]
提示词发一下截图 。然后对话日志中 这个提问看一下有没有引用分段。
一般Ollama的模型提示词接受不了太长的提示词，可以把回答要求简化一下或者去掉，按你的需求填写。

**Comment by filwu8** [comment]
我也遇到相同的问题，好像是太久不用，模型从内存释放了，重新加载超时，他就会回答：抱歉，没有查找到相关内容，请重新描述您的问题或提供更多信息。
![1720144780253](https://github.com/1Panel-dev/MaxKB/assets/54697960/0e44157f-77da-4069-8236-40c4df6f68d5)

能否增加   ollama 模型显存常驻的选项 ？ OLLAMA_KEEP_ALIVE
