### ISSUE TITLE
[FEATURE]嵌入页面的聊天窗口增加传参

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#773]
### MaxKB 版本

1.3

### 请描述您的需求或者改进建议

嵌入页面的聊天窗口增加传参，例如用户身份信息、环境信息等，这些信息一并传入聊天对话中，以便大模型更准确地回答问题

**Comment by baixin513** [comment]
感谢反馈，聊天身份信息验证 应该会在后续的企业版功能。
