### ISSUE TITLE
[FEATURE]流程中的组件支持获取历史对话

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#774]
### MaxKB 版本

1.3

### 请描述您的需求或者改进建议

希望流程中的组件支持获取历史对话，用来人工做上下文的分析判断，而不需要全丢给大模型处理

**Comment by baixin513** [comment]
感谢反馈，后续可能会考虑增加历史对话变量。

**Comment by baixin513** [comment]
v1.6版本已经支持 历史对话记录变量
