### ISSUE TITLE
[FEATURE]通过API调用也支持查看对话记录和执行详情

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#777]
### MaxKB 版本

1.3

### 请描述您的需求或者改进建议

现在只有通过web端的对话才能查看对话记录和详情
希望通过API的对话也能查看记录和详情，并且都纳入报表统计

**Comment by shaohuzhang1** [comment]
使用api也是可以调用接口查看执行详情的,对话和执行详情是俩个接口

**Comment by xxyj6450** [comment]
收到，问题已解决，感谢答复
