### ISSUE TITLE
[FEATURE]建议增加模型授权团队成员使用的问题

### ISSUE THREAD

**Issue by linusok** [1Panel-dev/MaxKB#786]
### MaxKB 版本

版本号:v1.3.0 (build at 2024-07-03T18:30, commit: 28fb1db7)

### 请描述您的需求或者改进建议

建议增加模型授权团队成员使用的问题，目前团队成员登录后，在创建知识助手时，还需要自己添加模型，不能使用admin已经配置好的各类模型。

### 请描述你建议的实现方案

允许管理员将指定模型授权给指定团队成员进行使用

**Comment by baixin513** [comment]
感谢反馈，下个功能版本支持 设置模型是 私有或公开使用。
