### ISSUE TITLE
[BUG]似乎存在内存泄露，短时间并发请求

### ISSUE THREAD

**Issue by lix-fs** [1Panel-dev/MaxKB#787]
### MaxKB 版本

1.3

### 问题描述

![image](https://github.com/user-attachments/assets/9610d5c6-7770-47d0-bef2-4eb0184ac327)
在大量请求后，内存增长很多，等了很久都没释放
![image](https://github.com/user-attachments/assets/7151e9da-b197-4a10-9e06-6b2c656edaf3)
容器重启后，就释放了，疑似存在内存泄露的问题

### 重现步骤

进行联续不断的会话api请求

**Comment by shaohuzhang1** [comment]
对话记录会被缓存在系统中,方便使用过期时间为2小时 如果俩小时此对话未被使用就会释放

**Comment by lix-fs** [comment]
好的，我们再测试观察一下；部署是是分离的，在两个容器里

**Comment by lix-fs** [comment]
> 对话记录会被缓存在系统中,方便使用过期时间为2小时 如果俩小时此对话未被使用就会释放 你测试的时候,建议把pgsql和maxkb分开部署

好的，我们再测试观察一下，服务是分开部署的，在两个容器里

**Comment by lix-fs** [comment]
> 对话记录会被缓存在系统中,方便使用过期时间为2小时 如果俩小时此对话未被使用就会释放 你测试的时候,建议把pgsql和maxkb分开部署
不像会自动释放，
![image](https://github.com/user-attachments/assets/5e8ebd2e-3a76-4ad9-a4fd-8096a89314e2)
这边是等了一晚上后的结果，属于python运行占用的还是很高

**Comment by shaohuzhang1** [comment]
缓存使用的是django的LocMemCache,django 的LocMemCache是不会定时清理超时的缓存的
默认缓存个数达到max_entries后再次添加才会清除cull_frequency比例的缓存
默认max_entries为300  cull_frequency为3 也就是达到300后再次添加key会清楚1/3的缓存
![image](https://github.com/user-attachments/assets/fe04b3c4-2af2-4891-92d7-7ea18983f0be)
![image](https://github.com/user-attachments/assets/a7f53674-d0fa-4497-9ae1-2cd0219f547c)

**Comment by lix-fs** [comment]
明白了，去检索了django的缓存机制，过期并不一定会释放，我看你们程序是设置了30分钟的过期。那建议这边开放redis等缓存中间件的介入。知识库的会话，在token数放开的情况下，和上下文一结合，在性能不够的机器上，容易因为短时间的大量会话导致服务崩溃重启
