### ISSUE TITLE
[BUG] 本地部署打开前端，从登录界面跳转到404

### ISSUE THREAD

**Issue by myzf** [1Panel-dev/MaxKB#788]
### MaxKB 版本

0716日最新

### 问题描述

![image](https://github.com/user-attachments/assets/6498073c-0447-4116-aaaa-e12e5c3c9d81)

### 重现步骤

![image](https://github.com/user-attachments/assets/807c5846-c49e-49a0-869b-7827df8ce081)

**Comment by shaohuzhang1** [comment]
直接访问/ui 把404去掉

**Comment by ANemo-yj** [comment]
> 直接访问/ui 把404去掉

我也是一模一样的问题 去掉404还是会跳转

**Comment by mcyaixia** [comment]
问题在于请求127.0.0.1:3000/api/display/info报404，我在后端找了，没有这个接口

**Comment by wangdan-fit2cloud** [comment]
问题已修复

**Comment by ANemo-yj** [comment]
> 问题已修复

请问是如何修复的
