### ISSUE TITLE
[无法正常添加模型Ollama， 提示API域名无效，本地ollama服务部署均正常]

### ISSUE THREAD

**Issue by Simonfld** [1Panel-dev/MaxKB#789]
### 联系方式

vx: Finder_53

### MaxKB 版本

版本号:v1.3.1 (build at 2024-07-16T14:53, commit: 499fc90f)

### 问题描述

![image](https://github.com/user-attachments/assets/ab8ee13c-e1dd-48d1-82b3-9a81128cc9be)

![image](https://github.com/user-attachments/assets/3e13436d-55a1-4675-a9ac-f7d894c30d87)

` curl http://127.0.0.1:11434/api/chat -d '{
>>   "model": "qwen2-1.5b:latest",
>>   "messages": [
>>     { "role": "user", "content": "1+1=?" }
>>   ]
>> }'
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:50.6620287Z","message":{"role":"assistant","content":"The"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:50.8101332Z","message":{"role":"assistant","content":" sum"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:50.9249849Z","message":{"role":"assistant","content":" of"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.0673161Z","message":{"role":"assistant","content":" "},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.184406Z","message":{"role":"assistant","content":"1"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.3069542Z","message":{"role":"assistant","content":" and"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.444985Z","message":{"role":"assistant","content":" "},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.5869737Z","message":{"role":"assistant","content":"1"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.6948526Z","message":{"role":"assistant","content":" is"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.8238889Z","message":{"role":"assistant","content":" "},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:51.9223353Z","message":{"role":"assistant","content":"2"},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:52.0116471Z","message":{"role":"assistant","content":"."},"done":false}
{"model":"qwen2-1.5b:latest","created_at":"2024-07-16T15:16:52.128118Z","message":{"role":"assistant","content":""},"done_reason":"stop","done":true,"total_duration":8649444500,"load_duration":6001143100,"prompt_eval_count":12,"prompt_eval_duration":1159985000,"eval_count":13,"eval_duration":1456015000}`

### 重现步骤

1、下载最新版本地安装，必现。

### 期待的正确结果

能正常添加模型

**Comment by baixin513** [comment]
感谢反馈，解决方案参考论坛：https://bbs.fit2cloud.com/t/topic/4165/5

**Comment by endual** [comment]
windows，采用docker部署方式，解决方案

系统环境变量，添加：OLLAMA_HOST=0.0.0.0
2.到hosts文件中去复制一个docker的域名
192.168.118.175 host.docker.internal
这个域名是安装docker给自动添加的
3.获取host.docker.internal 端口是11434 ,使用浏览器访问：http://host.docker.internal:11434/
页面出现 Ollama is running

添加到域名即可，密匙123 （无所谓，随便填写）

**Comment by endual** [comment]
windows，采用docker部署方式，解决方案

1.系统环境变量，添加：OLLAMA_HOST=0.0.0.0
2.到hosts文件中去复制一个docker的域名
192.168.118.175 host.docker.internal
这个域名是安装docker给自动添加的
3.获取host.docker.internal 端口是11434 ,使用浏览器访问：http://host.docker.internal:11434/
页面出现 Ollama is running

添加到域名即可，密匙123 （无所谓，随便填写）
