### ISSUE TITLE
[FEATURE] 工作流是否考虑添加【http请求】节点

### ISSUE THREAD

**Issue by ziye142857** [1Panel-dev/MaxKB#790]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

添加【http请求】节点

### 请描述你建议的实现方案

添加【http请求】节点，这样就可以接入业务逻辑，实现Agen智能体编排

**Comment by baixin513** [comment]
感谢反馈，后续版本考虑一下。

**Comment by mingdiantianxia** [comment]
这个确实是非常重要的功能，目前功能不够完善时，可以调用http接口的程序处理，增强AI工作流的可用性。

**Comment by baixin513** [comment]
可以等1.5版本函数库出来 ，写个函数应该能实现。

**Comment by baixin513** [comment]
HTTP请求函数参考：https://bbs.fit2cloud.com/t/topic/7814
