### ISSUE TITLE
[FEATURE]用户名要求太复杂，完全没有这个必要

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#791]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

用户名必须以字母开头，搞的都不能用工号作为账号了，咱这系统的安全级别没这么高的，完全没必要搞的这么复杂，建议取消这些过于复杂的限制

**Comment by baixin513** [comment]
感谢反馈，用户名6-20个字符，字母开头，属正常规则。暂无修改计划。
