### ISSUE TITLE
聊天对话返回错误

### ISSUE THREAD

**Issue by leishenglong** [1Panel-dev/MaxKB#794]
### 联系方式

1005286212@qq.com

### MaxKB 版本

v1.3.0

### 问题描述

创建好了应用后，使用公开访问地址聊天对话
总是返回这个：

Client error '429 Too Many Requests' for url '[https://open.bigmodel.cn/api/paas/v4/chat/completions](https://gitee.com/link?target=https%3A%2F%2Fopen.bigmodel.cn%2Fapi%2Fpaas%2Fv4%2Fchat%2Fcompletions)'
For more information check: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429](https://gitee.com/link?target=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FHTTP%2FStatus%2F429)

### 重现步骤

创建好了应用后，使用公开访问地址聊天对话
总是返回这个：

Client error '429 Too Many Requests' for url '[https://open.bigmodel.cn/api/paas/v4/chat/completions](https://gitee.com/link?target=https%3A%2F%2Fopen.bigmodel.cn%2Fapi%2Fpaas%2Fv4%2Fchat%2Fcompletions)'
For more information check: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429](https://gitee.com/link?target=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FHTTP%2FStatus%2F429)

### 期待的正确结果

正确返回结果

**Comment by leishenglong** [comment]
使用docker部署，进行版本升级后出现这个问题了

**Comment by baixin513** [comment]
感谢反馈，这是模型返回的错误信息，对话请求限制了。
