### ISSUE TITLE
[FEATURE]建议应用可以限制使用范围

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#795]
### MaxKB 版本

1.3

### 请描述您的需求或者改进建议

机器人被泄露将造成损失，建议应用可以限制使用范围，比如：
限制仅接口可访问
限制仅指定的IP/IP段可访问
其他的身份验证

**Comment by baixin513** [comment]
感谢反馈，访问限制后续会增加一些限制。

**Comment by baixin513** [comment]
以下是一些使用限制：
1、关闭公开访问链接后，只能通过API Key 访问。
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/a8a740f0-eeaa-479c-adf9-bcffce8ab341">
2、每个API Key都可控制可用状态。
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/e2516e63-5b84-4c61-80ec-e3a8952f3e12">
3、1.7版本新增了身份验证功能，开启后，访问提问页面时需要输入验证码进入提问页面
<img width="898" alt="image" src="https://github.com/user-attachments/assets/6e8f04db-db2b-484d-882a-7d60baa159d0">
<img width="450" alt="image" src="https://github.com/user-attachments/assets/42ebc6eb-8327-426a-a7c6-d0dfa2e2d176">

**Comment by zyyfit** [comment]
1.7.0版本已发布，请更新到最新版使用

**Comment by gotounix** [comment]
@baixin513 2.0 版本以后又把身份验证功能删除了吗？

https://github.com/1Panel-dev/MaxKB/commit/698f23c716f963c858f431b9d88b96f761310d5a
