### ISSUE TITLE
[BUG]Web端全屏模式嵌入时没有关闭按钮

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#796]
### 联系方式

三断笛

### MaxKB 版本

1.3

### 问题描述

Web端全屏模式嵌入时没有关闭按钮，导致全屏无法退出，遮挡原来的系统界面，建议增加最小化和关闭按钮，以缩小到机器人图标状态

### 重现步骤

使用系统提供的全屏模式脚本嵌入即可重现

**Comment by baixin513** [comment]
感谢反馈，需要您用父级的div的显示/隐藏来控制问答页面的关闭和打开。
