### ISSUE TITLE
[BUG]Web悬浮窗嵌入时由于window.location.origin为null导致小助手无法初始化

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#797]
### 联系方式

三断笛

### MaxKB 版本

1.3

### 问题描述

Web悬浮窗嵌入时由于window.location.origin为null导致小助手无法初始化，报错如下：
![微信图片_20240718091241](https://github.com/user-attachments/assets/ac80ff4b-befe-4864-942b-bc1d8f9dcc5c)

### 重现步骤

![微信图片_20240718091349](https://github.com/user-attachments/assets/d25e7549-2f01-46ad-97fe-73890295184e)
以上是报错时的相关变量值

**Comment by shaohuzhang1** [comment]
能否提供一下:[...window.location.ancestorOrigins]数据结构

**Comment by baixin513** [comment]
暂未得到反馈，如果还有问题请到技术交流群咨询。
