### ISSUE TITLE
[BUG]用js动态创建Web端小助手无法正常加载

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#798]
### 联系方式

三断笛

### MaxKB 版本

1.3

### 问题描述

![微信图片_20240718091644](https://github.com/user-attachments/assets/5ee5271c-2874-419d-b915-43d0038a446b)
如上图所示，脚本节点已经创建，但小助手的相关Html元素未能正确创建，控制台和网络没有任何异常。
在页面中已经加入了悬浮嵌入的脚本，但小助手无法正常加载

### 重现步骤

第一种方式：第三方系统中，用js动态创建小助手悬浮窗的script节点，节点成功创建，但小助手未加载。
第二种方式：在第三方系统中，先用js创建一个iframe,再将script节点加在iframe中，有时能正常加载小助手，但不是所有电脑都能成功，未成功的电脑上，也没有任何错误提示
备注：第三方系统无法修改，但能执行Js

**Comment by shaohuzhang1** [comment]
这个我们这边无法复现,是不是浏览器版本的问题

**Comment by Xavier1900** [comment]
我也遇到这个问题了，JS动态添加scrpit标签的无法加载右下角图标，页面第一次加载的话就可以

**Comment by Xavier1900** [comment]
动态加载后试下执行以下embedChatbot()方法

**Comment by baixin513** [comment]
无法复现，如果还有问题请到技术交流群提供详细日志。
