### ISSUE TITLE
[FEATURE]建议增加提问组件

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#799]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

与机器人交互时，对话是连续多轮的，需要针对性地向用户提问获得信息，再进一步执行后续流程。
这种交互用带上历史记录的多轮对话来实现并不方便，一是AI不一定会提问，二是浪费token，三是慢

### 请描述你建议的实现方案

希望增加用户询问组件，可以向用户发出提问，提问可以是文字，也可以是选择。
待用户回答后，输出用户的回答信息到变量，以供后续组件引用

**Comment by baixin513** [comment]
感谢反馈，后续版本考虑

**Comment by hovey-xu** [comment]
支持

**Comment by baixin513** [comment]
工作流指定回复内容中可以加快捷问题标签对用户提问。
