### ISSUE TITLE
[BUG]【知识库】在分段中添加关联问题时，当问题比较长时下拉组件显示不美观

### ISSUE THREAD

**Issue by yufuchen** [1Panel-dev/MaxKB#80]
### MaxKB 版本

v1.0.0

### 问题描述

在分段中添加关联问题时，当问题比较长时下拉组件显示有问题

### 重现步骤

1.先设置一个长度超过 200 字数的问题；
2.进入分段详情，打开关联问题下拉列表

![image](https://github.com/1Panel-dev/MaxKB/assets/28720310/3a93f647-360a-442e-9868-25d5849bcd55)

### 期待的正确结果

关联问题下拉列表宽度建议固定，超过显示长度的问题，用缩略的方式显示，鼠标指定后，用气泡信息方式显示完整问题内容

**Comment by baixin513** [comment]
感谢反馈，后面版本优化。
