### ISSUE TITLE
[FEATURE]建议一个节点可以被多个节点流入

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#801]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议
平台太好用，需求激增
而现在的流程只能单入单出，导致目前我三层的判断分支已经让画布在最小状态下无法显示完全。
强烈建议先支持多入单出，即可大量简化流程模型
![image](https://github.com/user-attachments/assets/b2433845-7f3e-4f90-b59b-8efb5eb380eb)

### 请描述你建议的实现方案

建议一个节点可以被多个节点流入,或者说多个节点可以指向同一个节点。
例如，多个AI聊天节点，可以输出到一个指定回复节点。

**Comment by baixin513** [comment]
感谢反馈，后续版本中考虑支持

**Comment by zyyfit** [comment]
1.7.0版本已发布，请更新到最新版使用
