### ISSUE TITLE
[FEATURE] 高级编排功能中建议AI对话，问题优化这类具有流式反馈的组件可以选择阻塞式在前端页面流式显示，而不是逻辑流完成后再一口气输出，用户等待时间太长，体验不好

### ISSUE THREAD

**Issue by zhangdong12306** [1Panel-dev/MaxKB#802]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

现在的高级编排组件，如果在AI回复的组件后继续增加组件，那么在发布后的应用中提问，会出现一个问题问出后，界面不会进行流式输出，感官上会认为卡了很久，体验不佳；
希望可以把每一步AI回复的过程也能流式加载到前端页面，这样的使用观感就会好很多，如果等每一步的流程处理完再返回结果，AI回复比较耗时，最后再return结果感官上的体验就是卡了很久才输出结果，给人一种AI很慢很蠢的感觉。

**Comment by baixin513** [comment]
如果是nginx的话试试下面的配置：
        proxy_cache off;  # 关闭缓存
        proxy_buffering off;  # 关闭代理缓冲
        chunked_transfer_encoding on;  # 开启分块传输编码
        tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
        tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
        keepalive_timeout 300;  # 设定keep-alive超时时间为65秒

**Comment by zhangdong12306** [comment]
试了上面的配置，还是不行，从逻辑上观察应该是代码设计的原因，下面我具体说明下：
<img width="1048" alt="工作流" src="https://github.com/user-attachments/assets/c3bd9bbd-0cbf-4d71-a309-2a95f1d2bf4c">
如果走的工作流为①和③，工作流①会直接返回，工作流③会按照流式返回内容；
但是如果走的工作流为②，由于工作流②多了逻辑判断，且最后输出不是AI对话组件的输出，那么会等AI对话组件处理完后再进入到下一个判断组件，判断组件再进入到AI对话2组件，最后输出结果，由于显示的结果只是最后组件的结果，那么在组件AI对话组件耗时的时候前段就会卡在回答中等到流程进入到AI对话2组件才会有显示结果返回。工作流2的后续补充图如下：
<img width="741" alt="工作流2" src="https://github.com/user-attachments/assets/b788b2aa-15f1-43f9-9ed7-35f06101577e">


如题，我期望的方式是可以选择要在前段页面显示的内容而不仅仅只有最后的输出结果，例如AI对话组件工作的时候把其回复的流也显示在前段页面上，经过AI对话组件2提炼用户可能或者想要问的下一个问题，然后也输出到前段页面，这样在处理AI对话组件的耗时也可以直观反映在前段，不会导致用户认为AI思考过程太长（说的直白一点就是可以把工作流的运行可选择式地反馈给用户）
如下图中的
![image](https://github.com/user-attachments/assets/d172e6da-9726-4dd3-9d0f-f3ca2c46d34d)
内容先流式加载到前段页面，然后在进入逻辑判断把后续的输出也显示出来，从使用体验开看就是判断器1和指定回复1组件是需要AI对话组件完成的情况下才会执行，而且由于前段只支持最后的输出结果，那么造成的现象就是处理指定回复1前面的所有组件耗时时前段页面都会卡在“回答中”的阶段，直到走到指定回复1组件才会在前端显示结果。
不知道我的理解对不对，但是使用的体验是这么告诉我的，所以希望增加的需求就是其他组件的输出结果也可以返回在前段页面，以此类型阻塞式把内容输出出来。


> 如果是nginx的话试试下面的配置： proxy_cache off; # 关闭缓存 proxy_buffering off; # 关闭代理缓冲 chunked_transfer_encoding on; # 开启分块传输编码 tcp_nopush on; # 开启TCP NOPUSH选项，禁止Nagle算法 tcp_nodelay on; # 开启TCP NODELAY选项，禁止延迟ACK算法 keepalive_timeout 300; # 设定keep-alive超时时间为65秒

**Comment by baixin513** [comment]
你可以升级到1.4.1，支持 中间节点支持设置返回内容。
