### ISSUE TITLE
在对话后，问：我之前提过哪些问题？，为啥ai就无法回复呢，我已经勾选多轮对话和问题优化选项，

### ISSUE THREAD

**Issue by wjhmiss** [1Panel-dev/MaxKB#803]
### MaxKB 版本

1.34

### 问题描述

在对话后，问：我之前提过哪些问题？，为啥ai就无法回复呢，我已经勾选多轮对话和问题优化选项，

### 重现步骤

在对话后，问：我之前提过哪些问题？，为啥ai就无法回复呢，我已经勾选多轮对话和问题优化选项，

**Comment by baixin513** [comment]
抱歉，根据您的描述，无法排查。
