### ISSUE TITLE
[BUG]添加模型Ollama， 提示API域名无效，Nginx代理本地ollama服务集群二级路径

### ISSUE THREAD

**Issue by crazybird** [1Panel-dev/MaxKB#805]
### MaxKB 版本

v1.3.1

### 问题描述

添加模型
ollama 为nginx代理的集群,做了子路径
在配置域名时候[https://xxxxx/llm-api/]，添加时报“API域名无效",

https://xxxxx/llm-api/ 访问正常 
Ollama is running

<img width="559" alt="1111" src="https://github.com/user-attachments/assets/b4f63919-0eee-4c73-8e9c-95cf340f31aa">

分析代码发现
apps/setting/models_provider/impl/ollama_model_provider/credential/llm.py
101行

def get_base_url(url: str):

https://github.com/1Panel-dev/MaxKB/blob/2e61010d198d00a879b298bf4bba9c0f0734bdb0/apps/setting/models_provider/impl/ollama_model_provider/ollama_model_provider.py#L102C13-L102C21

url转换 丢掉了域名端口后面的二级子路径 /llm-api

### 重现步骤

添加模型 模型地址填写 nginx代理后的 二级路径格式如https://xxxxx/llm-api/.

**Comment by crazybird** [comment]
修复修改为:

`
def get_base_url(url: str):
    parse = urlparse(url)
    return ParseResult(scheme=parse.scheme, netloc=parse.netloc, path=parse.path, params='',
                       query='',
                       fragment='').geturl()
`
path=parse.path

**Comment by eanfs** [comment]
1.3.0 也有这个BUG吗？
