### ISSUE TITLE
建议能否考虑增加支持中国电信的星辰大模型

### ISSUE THREAD

**Issue by niujinkai** [1Panel-dev/MaxKB#806]
### MaxKB 版本

v1.3.1

### 请描述您的需求或者改进建议

建议能否考虑增加支持中国电信的星辰大模型
https://github.com/Tele-AI/Telechat

### 请描述你建议的实现方案

支持在接入模型时接入星辰大模型

**Comment by baixin513** [comment]
感谢反馈，暂时不会单独对接，  如果是本地模型可以试一下整理到通过Ollama中，在到maxkb中对接。
