### ISSUE TITLE
[BUG]简单配置应用的提示词不起作用

### ISSUE THREAD

**Issue by zenithwu** [1Panel-dev/MaxKB#808]
### MaxKB 版本

社区版本

### 问题描述

设置了提示词，让大模型直接输出sql内容，对结果没有影响

### 重现步骤

![image](https://github.com/user-attachments/assets/a9ee92bb-bd01-4642-a11e-218502a82892)

**Comment by baixin513** [comment]
感谢反馈，简易配置应用 无知识库引用时发给模型的提示词在 参数设置中，对应修改一下提示词。
<img width="1020" alt="image" src="https://github.com/user-attachments/assets/f36dd1ba-380e-4678-b2ae-1cc0bf3b351c">
