### ISSUE TITLE
一些优化建议！！！！！！

### ISSUE THREAD

**Issue by wangshanshan12345** [1Panel-dev/MaxKB#810]
### MaxKB 版本

无

### 请描述您的需求或者改进建议

可以根据工作流生成的应用，再赋能增加应用接入，比如web链接分享无登录界面（允许匿名用户使用，是否记录匿名用户的聊天记录），智能对话就需要依赖其他现有生态圈：比如微信公众号，微信客服，企业微信，钉钉，企业微信应用，飞书。
可以增加一些插件，比如当前时区时间、联网搜索(因为有些模型不支持时间和联网搜索)，天气，新闻，违规词汇屏蔽替换，定时任务等等。

举例：很多公司或者个人都依赖现有微信生态圈，AI对话最重要的是解决不了时可以转人工或者提醒人工接入，比如客户购买意向，付款问题等等，当触发关键词，提示人工正在赶来的路上，此系统页面可以提供一个转人工页，或者弹窗，携带聊天记录。或者是那种简单的提醒也是一个方向呢。上班摸鱼不细聊，大概方向可以的哦

### 请描述你建议的实现方案

![微信图片_20240719111929](https://github.com/user-attachments/assets/6fdf0947-f098-430d-aaa5-c87ec16aebe4)

**Comment by baixin513** [comment]
感谢您的反馈，您的建议我们都有考虑。
公共链接身份验证 ，转人工等功能后续会在专业版中推出。
一些插件，比如当前时区时间、联网搜索等功能会在函数库之后。
智能对话生态圈的对接目前还没有好的解决方案。
