### ISSUE TITLE
[FEATURE]摆脱对ollama等框架的依赖

### ISSUE THREAD

**Issue by 673092756** [1Panel-dev/MaxKB#812]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

增加一个可以直接连接下载并保存到本地的模型，这样用户无需再通过类似Ollama等框架进行调用，而是能够直接使用maxkb的框架进行操作。这将极大地提高灵活性和自主性，用户可以在本地环境中进行模型的部署和调用，减少对外部服务的依赖，同时提高数据处理的安全性和效率。

### 请描述你建议的实现方案

例如，在Langchain框架中，用户可以通过文件配置选择直接链接下载并保存到本地的模型。虽然这样可能会减少模型的规模，但这大大增加了maxkb的操作灵活性，更方便用户使用，从而减少了同时部署和启动多个框架的需求。

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，目前没有支持本地模型的计划。

**Comment by 673092756** [comment]
好吧

**Comment by 673092756** [comment]
> 感谢反馈，目前没有支持本地模型的计划。
好吧，希望能把这个安排到计划中
