### ISSUE TITLE
知识库导入文件自动分段后，内容部分默认设置成1万字，5千太短了有时候不够用

### ISSUE THREAD

**Issue by kinbod** [1Panel-dev/MaxKB#816]
### MaxKB 版本

v1.3.1

### 请描述您的需求或者改进建议

知识库导入文件自动分段后，内容部分默认设置成1万字，5千太短了有时候不够用

### 附加信息

知识库导入文件自动分段后，内容部分默认设置成1万字，5千太短了有时候不够用

**Comment by baixin513** [comment]
感谢反馈，下个版本分段长度会调整扩大至10万个字符，用户可按自己需求调整。
但如果超过模型接收的长度模型会报错，需要用户自行把控下分段的字符数。
