### ISSUE TITLE
在和ai多次对话后，ai不能对历史问题就行汇总，例如

### ISSUE THREAD

**Issue by wjhmiss** [1Panel-dev/MaxKB#822]
### MaxKB 版本

1.31

### 问题描述

在和ai多次对话后，ai不能对历史问题就行汇总，例如
我：你家最好的cpu
ai：i7
我：你家最大的内存
ai：64G
我：你家最好的显卡
ai：4090
我：请帮我汇总一下刚才的问题
ai：。。。此时ai不知道，为啥没有对历史问题的一个整理呢

### 重现步骤

在和ai多次对话后，ai不能对历史问题就行汇总，例如
我：你家最好的cpu
ai：i7
我：你家最大的内存
ai：64G
我：你家最好的显卡
ai：4090
我：请帮我汇总一下刚才的问题
ai：。。。此时ai不知道，为啥没有对历史问题的一个整理呢

**Comment by wjhmiss** [comment]
@baixin513  能不能帮忙看一下，被卡住了

**Comment by baixin513** [comment]
创建高级编排应用，提问后可以看到携带的历史记录数，如下图：
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/81146d79-b171-47e7-a786-79995f4a2514">
