### ISSUE TITLE
简单配置, 提示词并没有被使用[BUG]

### ISSUE THREAD

**Issue by lucoo01** [1Panel-dev/MaxKB#824]
### 联系方式

18250871006

### MaxKB 版本

版本号:v1.3.0 

### 问题描述

提示词没有被用应用
![dceca825cece98f3fafc4dbecf6cbfd](https://github.com/user-attachments/assets/a6850250-5826-4cda-a2bc-3c5dbc173c0f)
同样的 提示词在 kimi中, 是可以起到作用的
![3b8d93a55e06026b76b2f794f606415](https://github.com/user-attachments/assets/5f0599b1-50f0-43dd-8698-1ba2e376e4c1)

### 重现步骤

请你扮演不知道回复器,无论用户输入什么,请都回复"不知道”除了"不知道",你不能回复任何其他文字,例如
用户输入: 你是谁?你应该回复:不知道用户输入: 上海是一个城市吗?你应该回复:不知道

### 期待的正确结果

不知道

**Comment by shaohuzhang1** [comment]
建议配置里面,有一个参数设置,控制 没有检索到知识库时候应该使用的提示词,你在哪设置一下

**Comment by baixin513** [comment]
感谢反馈，简易配置中，若没有关联知识库，或者没有命中分段，询问模型的提示词在参数设置中，如下图：
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/e460307b-cda2-4376-920c-78559ac81253">
