### ISSUE TITLE
[FEATURE]大模型回复的内容能否增加图片展示

### ISSUE THREAD

**Issue by luckgod1989** [1Panel-dev/MaxKB#829]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

在知识库中增加了图片，但是通过演示时，没有展示出对应的图片内容，希望可以增加这里，哪怕暂时是图片链接也可以。

### 附加信息

![对话记录无图片](https://github.com/user-attachments/assets/b9820ee2-74c6-4b31-b1fb-718e98914d7a)
![有图片](https://github.com/user-attachments/assets/9f859323-a4a9-43ff-8687-d6a727daa914)

**Comment by xxyj6450** [comment]
刚过来提bug，管理员不在，顺手回答下：
1、知识库中，设置文档为”直接回答“，而不是”模型优化“
2、提示词中，要求大模型输出图片等多媒体，以帮助用户理解

**Comment by baixin513** [comment]
感谢反馈，MaxKB支持图片展示，你可以换个GLM4模型试试，据反馈这个模型出图率高。
