### ISSUE TITLE
[FEATURE] 【关于】建议用户手册、项目地址、论坛求助放在导航栏，目前隐藏深不容易找到

### ISSUE THREAD

**Issue by peier123** [1Panel-dev/MaxKB#83]
### MaxKB 版本

v1.1.0

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/MaxKB/assets/110212358/73749141-7ab6-4ad1-8eea-194bb0eb01f3)

### 请描述你建议的实现方案

可以放在导航栏右侧位置，或者个人中心处，提高可见性

**Comment by baixin513** [comment]
感谢反馈，后期可以优化一下。
