### ISSUE TITLE
[BUG]代码显示不完整

### ISSUE THREAD

**Issue by xxyj6450** [1Panel-dev/MaxKB#834]
### MaxKB 版本

1.3.1

### 问题描述

回答中的代码显示不完整，但复制代码时，代码是完整的，如下图
![image](https://github.com/user-attachments/assets/8f824fdc-c976-4e4f-bde7-8661accd1784)

### 重现步骤

向AI提问：写个文件上传的Java程序

**Comment by shaohuzhang1** [comment]
这个模型响应的数据把,有没有可能模型就没有响应java代码内部内容

**Comment by baixin513** [comment]
感谢反馈，点击右上角的java 能打开代码，应该是默认隐藏了。
<img width="878" alt="image" src="https://github.com/user-attachments/assets/bfc1aff2-ec4d-4129-91b5-b0e553ee71ce">
