### ISSUE TITLE
洗洗睡吧，我测试了几乎所有大模型，刚开始以为是maxkb的问题，结果后来发现是大模型压根就理解不了。根本不能商用，请看我截图

### ISSUE THREAD

**Issue by wjhmiss** [1Panel-dev/MaxKB#835]
### 联系方式

15012791005

### MaxKB 版本

131

### 问题描述

qwen2:1b, llama3等大语言模型根本理解不了文本意思。回答错误如图：
![1](https://github.com/user-attachments/assets/70dcdf01-5a6b-4b76-bcf7-d602495e447f)

### 重现步骤

工控机列表：
#，工控机料号：C-EC017100401，规格：液晶显示器 Q34P2;34英吋;2560*1080;宽屏21：9(AOC)，工控机料号未税价格是1486.73。
#，工控机料号：C-EC016514502，规格：HDMI线 2.0版 4K高清 10米 （绿联），工控机料号未税价格是145.631。
#，工控机料号：C-EC010503010，规格：监控摄像头 DS-2SC3Q120MY-TE/POE 400万 海康，工控机料号未税价格是323.1073。
#，工控机料号：C-EC016510101，规格：TF内存卡 256G 低端L2系列 HS-TF-L2 读95写30MB/S 海康，工控机料号未税价格是168.3。
#，工控机料号：C-EC027100700，规格：电量监测器 DPM-C520 台达，工控机料号未税价格是694.725。
#，工控机料号：C-EC027100301，规格：电流互感器 BH-0.66-30I(华伟)，工控机料号未税价格是13.5933。
#，工控机料号：C-CSUR605P1C6700，规格：▲电压监测固定座_SUS304 82*180*110*2，工控机料号未税价格是24。
#，工控机料号：C-EC027000903，规格：数字流量计 PFM711-02-D(SMC)气流范围10-100L/min，工控机料号未税价格是631.7。
#，工控机料号：C-EC027000901，规格：数字流量计 PFMB7102-04-C-R(SMC)气流范围10-1000L/分，工控机料号未税价格是659.73。
#，工控机料号：C-EC043000100，规格：真空检知DPA01NR-P-100-100KPa带485通讯附架台达★，工控机料号未税价格是172.7764。
#，工控机料号：C-EC016519000，规格：非触摸显示器GM-DW-1211XF-SV01 12吋(坤巨)，工控机料号未税价格是707.9631。
#，工控机料号：C-EC017100202，规格：显示器VGA线P350VGA双磁环3+9 10M 威迅(VenTion)工业用，工控机料号未税价格是109.2177。
#，工控机料号：C-EC016516302，规格：USB有线鼠标 N-500FS 双飞燕，工控机料号未税价格是56。
#，工控机料号：C-EC016518301，规格：USB小键盘KL-5 (双飞燕)，工控机料号未税价格是75.3175。
#，工控机料号：C-EC016302032，规格：USB屏蔽延长线5M(带抗干扰磁环) (绿联)，工控机料号未税价格是49.2257。
#，工控机料号：C-EC060300002，规格：TDK抗干扰磁环ZCAT1730-0730黑色 内径7mm 长度30mm 可拆卸，工控机料号未税价格是2.2。
#，工控机料号：C-EC010501127，规格：一维扫描枪 LS4208 (SYMBOL) 斑马牌，工控机料号未税价格是584.3642。
#，工控机料号：C-EC006010204，规格：安全开关PL9-C4/2 2P4A(EATON)，工控机料号未税价格是68.9633。
#，工控机料号：C-E050100500，规格：保险丝盖 附霓虹灯式，工控机料号未税价格是1.8911。
#，工控机料号：C-EC050100000，规格：保险丝座 1P3A 轨道式，工控机料号未税价格是1.853。
#，工控机料号：C-EIPC002635，规格：驱动器PCTIHSD20(迅码)★，工控机料号未税价格是2534.5337。
#，工控机料号：C-EC016503500，规格：AVS-520QL/I5-8500T/16G/256G/1T含win10，工控机料号厂牌是维准，工控机料号未税价格是7398.23。
#，工控机料号：C-EC016503100，规格：MEC-T2764-03-FS/I5-8500/16G/128G/1T，工控机料号厂牌是特控，工控机料号未税价格是6200。
#，工控机料号：C-EC016503008，规格：IPC5120/I7-6700/128GSD3T/WIN10，工控机料号厂牌是控汇，工控机料号未税价格是7787.61。
#，工控机料号：C-EC016503305，规格：ARK-3532B/i5-10500/16g/128G/1T/w10，工控机料号厂牌是研华，工控机料号未税价格是8141.59。
#，工控机料号：C-EC016503404，规格：AVS-520QL/I7-8700T/32G/256G/1T含W10，工控机料号厂牌是维准，工控机料号未税价格是8672.57。
#，工控机料号：C-EC016503101，规格：AVS-330/CPU J6413/16G/128G/含Win10，工控机料号厂牌是维准，工控机料号未税价格是3008.8。
#，工控机料号：C-EC016503100，规格：MEC-T2764-03-FS/I5-8500/16G/128G/1T，工控机料号厂牌是特控，工控机料号未税价格是6200。
#，工控机料号：C-EC016503102，规格：MEC-T6424-3/J6412/16G/128G/Win10，工控机料号厂牌是特控，工控机料号未税价格是2600。
#，工控机料号：C-EC016503017，规格：ARK3532/I7-10700E/16G/128/2T/Win10，工控机料号厂牌是研华，工控机料号未税价格是9601.7699。
#，工控机料号：C-EC016503005，规格：MFC-3102/i5/16g/128G/1T/win10，工控机料号厂牌是控汇，工控机料号未税价格是8000.000。
#，工控机料号：C-EC016503012，规格：SAA-5690/i5-7500T/16g/128G/1T/win10，工控机料号厂牌是控汇，工控机料号未税价格是8600.000。

客户列表：
#，客户：汕头超声，采购：C-EC016503005。
#，客户：泰国超颖，采购：C-EC016503101。
#，客户：泰国广合，采购：C-EC016503500，系统安装Win11。
#，客户：高德，采购：C-EC016503008。
#，客户：深南，采购：C-EC016503008。
#，客户：广州广芯一期，采购：C-EC016503008。
#，客户：深圳礼鼎SL01一期，采购：C-EC016503012。
#，客户：深圳礼鼎SL01二期，采购：C-EC016503305。
#，客户：淮安鹏鼎HC01，采购：C-EC016503305。
#，客户：山东清河，采购：C-EC016503500。
#，客户：广州兴森快捷F1，采购：C-EC016503404。
#，客户：广州广芯二期，采购：C-EC016503017 。

要求：只从已知信息查找答案，如没有找到答案直接回答不知道。
问：列出所有料号规格？礼鼎采购的料号规格？

**Comment by wjhmiss** [comment]
管理员，帮忙看看，是我的问题，还是大语言LLM的问题，用的是qwen2：7b

**Comment by wjhmiss** [comment]
把我重现步骤里面的文字，去掉换行放进ollama 服务器中用qwen2直接跑，试一下

**Comment by liqiang-fit2cloud** [comment]
你试试别的模型，kimi什么的。

**Comment by 02hao09** [comment]
gpt-4o 感覺還行呀 https://chatgpt.com/share/9c89cb05-2184-42bc-b33b-6df69e5b17f3

**Comment by liqiang-fit2cloud** [comment]
哪个模型好用就用哪个吧。

**Comment by wjhmiss** [comment]
等我试一下kimi 和 gpt-4o 再给你们反馈

**Comment by wjhmiss** [comment]
> gpt-4o 感覺還行呀 https://chatgpt.com/share/9c89cb05-2184-42bc-b33b-6df69e5b17f3

你好，这个 GPT-4O 能用ollama在本地部署吗

**Comment by liqiang-fit2cloud** [comment]
不确定，你搜搜，https://ollama.com/library

**Comment by wjhmiss** [comment]
@liqiang-fit2cloud ollama 模型库里面就没有gpt模型，我测试了下面这几个都不行，你有好点的模型吗？
llama3:latest                   365c0bd3c000    4.7 GB  55 minutes ago
phi3:latest                     d184c916657e    2.2 GB  2 hours ago
deepseek-coder-v2:latest        8577f96d693e    8.9 GB  2 hours ago
gemma2:latest                   ff02c3702f32    5.4 GB  2 hours ago
qwen2:7b                        e0d4e1163c58    4.4 GB  13 days ago

**Comment by liqiang-fit2cloud** [comment]
整体说来chatgpt、kimi之类的在线模型比本地模型要好一些。
