### ISSUE TITLE
[FEATURE] 可以在移动端页面问题输入按钮那里做一个语音输入按钮

### ISSUE THREAD

**Issue by hovey-xu** [1Panel-dev/MaxKB#836]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

可以在移动端页面问题输入按钮那里做一个语音输入按钮，这样给移动端用户的体验更好，毕竟在移动端语音输入更方便

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，暂时没有计划，建议先使用输入法的语音输入。
