### ISSUE TITLE
[FEATURE]模型对接支持华为盘古大模型

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#837]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

政务部门，必须使用红色背景大模型

**Comment by baixin513** [comment]
感谢反馈，后续调研一下。

**Comment by baixin513** [comment]
盘古模型目前不是token的收费方式，官方暂未对外开通使用，都是整套模型交付模式，暂时无法进行对接。
