### ISSUE TITLE
[BUG]移动端EDGE浏览器的页面高度问题导致底部遮罩遮挡文字

### ISSUE THREAD

**Issue by Thassarian-Hitagi** [1Panel-dev/MaxKB#848]
### 联系方式

zc@zdream.cn

### MaxKB 版本

版本号:v1.1.3 (build at 2024-05-15T17:49, commit: e74ba87f)

### 问题描述

![Screenshot_2024-07-24-03-49-35-870_com microsoft](https://github.com/user-attachments/assets/17bf2565-5df4-41a7-bc7a-de7a75bfc7e8)
![Screenshot_2024-07-24-03-49-24-524_com microsoft](https://github.com/user-attachments/assets/11b31e0d-f514-4026-9d68-9820c4816650)

### 重现步骤

手机端使用Edge浏览器打开对话页面

### 期待的正确结果

遮罩层定位到底部

### 附加信息

辛苦了！

**Comment by baixin513** [comment]
感谢反馈，该bug已解决，请升级到最新版本1.3.1。
