### ISSUE TITLE
是否支持以及在哪里设置 embedding 模型

### ISSUE THREAD

**Issue by godeamon** [1Panel-dev/MaxKB#849]
### MaxKB 版本

版本号:v1.3.1 (build at 2024-07-16T14:53, commit: 499fc90f)

### 请描述您的需求或者改进建议

目前在知识库导入文档后，并没有地方可以配置embedding模型，不知道是否支持。

**Comment by baixin513** [comment]
感谢反馈，目前是默认的，月底1.4版本支持自定义设置embedding模型。

**Comment by godeamon** [comment]
@baixin513 请问默认的是哪个 embedding 模型？
