### ISSUE TITLE
社区版最多支持 2 个用户，如需拥有更多用户，请联系我们

### ISSUE THREAD

**Issue by geosmart** [1Panel-dev/MaxKB#850]
### MaxKB 版本

1.3.0

### 请描述您的需求或者改进建议

新增用户报错：社区版最多支持 2 个用户，如需拥有更多用户，请联系我们（https://fit2cloud.com/）。
![1](https://github.com/user-attachments/assets/8f2aa59b-4a63-4677-aed3-dd3a5c7efa72)

私有化部署只能有2个用户？

### 请描述你建议的实现方案

这个限制有点无法接受，开源版本里面为什么要包含商业版本的限制

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，如果开源版本满足不了需求可以考虑商业版本。

**Comment by Ascuge** [comment]
做的差还限制多，难怪市场差

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
There are many restrictions on what you do, no wonder the market is poor
