### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by HuHao13** [1Panel-dev/MaxKB#851]
### MaxKB 版本

v1.1.2

### 请描述您的需求或者改进建议

能否增加一个关键词推荐的功能，希望直接回答知识库的分段内容，就需要不断添加关联问题，与其增加这样的重复工作，不如当未匹配到相关问题时，根据用户输入的关键字，返回知识库已经关联的相似度较高的问题，让用户直接选择问题再输出，类似这种效果
![image](https://github.com/user-attachments/assets/16413f01-83d0-4f1d-859f-92ee23cc4cff)

**Comment by baixin513** [comment]
感谢反馈，重复issue 同 #516
