### ISSUE TITLE
[FEATURE] LLM 模型支持对接 AWS Bedrocks 

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [1Panel-dev/MaxKB#853]
### MaxKB 版本

1.3

### 请描述您的需求或者改进建议

大语言模型支持对接 AWS 的 Bedrocks ，Bedrocks 集成了 AWS 及其他的众多模型。

**Comment by baixin513** [comment]
感谢反馈，暂无计划对接 Bedrocks
