### ISSUE TITLE
[BUG]构建镜像报错

### ISSUE THREAD

**Issue by xben140** [1Panel-dev/MaxKB#861]
### MaxKB 版本

1.51

### 问题描述

构建镜像的时候 直接报错 权限 也加到了777
184 packages are looking for funding
4.836   run `npm fund` for details
4.841
4.841 3 moderate severity vulnerabilities
4.841
4.841 To address all issues (including breaking changes), run:
4.841   npm audit fix --force
4.841
4.841 Run `npm audit` for details.
5.058
5.058 > web@v1.0.0 build
5.058 > run-p type-check build-only
5.058
5.063 sh: run-p: Permission denied
------
Dockerfile:4
--------------------
   3 |     COPY ui ui
   4 | >>> RUN cd ui && \
   5 | >>>     npm install && \
   6 | >>>     npm run build && \
   7 | >>>     rm -rf ./node_modules
   8 |     FROM ghcr.io/1panel-dev/maxkb-python-pg:python3.11-pg15.6 as stage-build

### 重现步骤

docker 环境中 直接docker build -f installer/Dockerfile . 来构建

**Comment by liqiang-fit2cloud** [comment]
由于每个人编程能力和开发环境的差异，开发者在二开过程中遇到的问题项目组没有精力一一协助分析解决，感谢理解。
