### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xben140** [1Panel-dev/MaxKB#863]
### MaxKB 版本

1.31

### 问题描述

镜像无法正常构建 构建时报错
 > [web-build 3/3] RUN cd ui &&     npm install &&     npm run build &&     rm -rf ./node_modules:
4.239
4.239 added 1 package, and audited 900 packages in 4s
4.239
4.240 184 packages are looking for funding
4.240   run `npm fund` for details
4.244
4.244 3 moderate severity vulnerabilities
4.244
4.244 To address all issues (including breaking changes), run:
4.244   npm audit fix --force
4.244
4.244 Run `npm audit` for details.
4.245 npm notice
4.245 npm notice New minor version of npm available! 10.7.0 -> 10.8.2
4.245 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
4.245 npm notice To update run: npm install -g npm@10.8.2
4.245 npm notice
4.438
4.438 > web@v1.0.0 build
4.438 > run-p type-check build-only
4.438
4.443 sh: run-p: Permission denied
------
Dockerfile:4
--------------------
   3 |     COPY ui ui
   4 | >>> RUN cd ui && \
   5 | >>>     npm install && \
   6 | >>>     npm run build && \
   7 | >>>     rm -rf ./node_modules
   8 |     FROM ghcr.io/1panel-dev/maxkb-python-pg:python3.11-pg15.6 as stage-build
--------------------
ERROR: failed to solve: process "/bin/sh -c cd ui &&     npm install &&     npm run build &&     rm -rf ./node_modules" did not complete successfully: exit code: 126

### 重现步骤

在根目录下  docker build -f installer/Dockerfile -t maxkb .

**Comment by xben140** [comment]
希望能帮忙给出如何修改此问题

**Comment by liqiang-fit2cloud** [comment]
由于每个人编程能力和开发环境的差异，开发者在二开过程中遇到的问题项目组没有精力一一协助分析解决，感谢理解。

**Comment by liqiang-fit2cloud** [comment]
如果自己解决不了请使用官方镜像。
