### ISSUE TITLE
添加Agent服务

### ISSUE THREAD

**Issue by smileyboy2019** [1Panel-dev/MaxKB#866]
### MaxKB 版本

1。3

### 请描述您的需求或者改进建议

当如果知识库没有找到匹配内容，可以联网搜索提供回答内容，也可以增加其他agent 服务

**Comment by liqiang-fit2cloud** [comment]
目前的搜索引擎都有反爬虫机制，也都不提供搜索api，怎么联网搜索内容呢，你有建议么。

**Comment by shaohuzhang1** [comment]
使用phantomjs模拟用户操作调用百度搜索前面试了一下是可行的

**Comment by liqiang-fit2cloud** [comment]
> 使用phantomjs模拟用户操作调用百度搜索前面试了一下是可行的

多试几次，估计会被反爬识别。

**Comment by liqiang-fit2cloud** [comment]
暂时没有做agent的计划。
