### ISSUE TITLE
[BUG] 升级版本后聊天窗口没有知识来源显示

### ISSUE THREAD

**Issue by winslis2** [1Panel-dev/MaxKB#870]
### 联系方式

1362330842@qq.com

### MaxKB 版本

v1.3.1

### 问题描述

版本由v1.2.0升级到1.3.1，后台调试预览有知识来源，前台聊天窗口没有显示知识来源信息，
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/7641b3e7-cf0e-42cd-92bb-4caa49ddb068">

### 重现步骤

版本由v1.2.0升级到1.3.1

### 期待的正确结果

前台正常显示知识来源信息

### 附加信息

辛苦研发大大看下什么原因

**Comment by baixin513** [comment]
显示知识来源开关打开。
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/f74a2d66-51ec-4e84-9fe7-5f24802d0ab1">
