### ISSUE TITLE
[FEATURE]希望演式页面可以增加修改用户历史对话的功能和多行文本输入

### ISSUE THREAD

**Issue by wojiaoyishang** [1Panel-dev/MaxKB#873]
### MaxKB 版本

版本号:v1.3.1 (build at 2024-07-16T14:53, commit: 499fc90f)

### 请描述您的需求或者改进建议

1. 希望演式页面可以增加修改用户历史对话的功能，可以参考 chatGPT 的聊天页面，一些情况下我需要修改我的提问，这样可以在多轮对话中自由切换问题方向和一定程度上避免 AI 幻觉。

2. 加入多行文本输入，在聊天内按下 Shift + 回车 可以输入多行文本

### 请描述你建议的实现方案

![image](https://github.com/user-attachments/assets/72689c7e-7d25-4ae0-b001-5ecbd15cf654)

**Comment by baixin513** [comment]
感谢反馈，修正标注为维护人员功能，在应用-对话日志中，  提问输入多行可以使用 ctrl +回车。
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/4d708b4f-e8bb-4c90-935e-c6cc427aa894">
