### ISSUE TITLE
[BUG] 使用通义千问大模型如果开通https访问，回答问题会很慢

### ISSUE THREAD

**Issue by qq670176019** [1Panel-dev/MaxKB#877]
### 联系方式

822802869@qq.com

### MaxKB 版本

1.3.1 

### 问题描述

配置好通义千问模型之后，如果是http访问，问问题会一个一个蹦，就跟百度里面的文心一言一样；如果配置了https，那么就会很慢，它会到了一定时间一股脑给返回，请问这是哪里的问题？

### 重现步骤

配置好通义千问模型之后，如果是http访问，问问题会一个一个蹦，就跟百度里面的文心一言一样；如果配置了https，那么就会很慢，它会到了一定时间一股脑给返回，请问这是哪里的问题？

### 期待的正确结果

应该不管https和http都是一样效果才对吧

**Comment by liqiang-fit2cloud** [comment]
see https://github.com/1Panel-dev/MaxKB/issues/627

**Comment by qq670176019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，尽快给您回复。

**Comment by qq670176019** [comment]
> see #627

Thank you
