### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mengbuxiu** [1Panel-dev/MaxKB#879]
### 1Panel 版本

v1.10.13-lts

### 问题描述

系统设置，选择供应商>添加 Ollama，点击添加报错
![image](https://github.com/user-attachments/assets/cf6132a9-2509-48ea-be1b-dfa80b3b2e3a)

### 重现步骤

![image](https://github.com/user-attachments/assets/cf6132a9-2509-48ea-be1b-dfa80b3b2e3a)

**Comment by baixin513** [comment]
感谢反馈，可以在论坛上看一下解决方案：https://bbs.fit2cloud.com/t/topic/4165/5
