### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by TxecTYJX** [1Panel-dev/MaxKB#883]
### MaxKB 版本

v1.3.0 (build at 2024-07-03T18:30, commit: 28fb1db7)

### 请描述您的需求或者改进建议

1.添加语言播放功能
2.在对话过程中添加文件附件以及图片
3.admin账户可以获取团队成员的账号和秘密，并且可以在admin账户中为成员配置本地大模型

**Comment by baixin513** [comment]
感谢反馈
1、语音输入和播放同 issue #211 
2、暂不支持
3、当前admin可以看到所有用户的账号，也能修改用户密码， 在1.4版本中可以配置模型为公用后所有用户都可以使用该模型。
