### ISSUE TITLE
[FEATURE] 支持设置rerank模型

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/MaxKB#891]
### MaxKB 版本

1.3.1

### 请描述您的需求或者改进建议

支持配置修改rerank模型，目前用了这块的东西吗 不太清楚

**Comment by fitchibing** [comment]
dify中的这个  https://docs.dify.ai/v/zh-hans/learn-more/extended-reading/retrieval-augment/rerank  重排序 你参考下

**Comment by baixin513** [comment]
计划1.6支持多路召回，结果重排。
