### ISSUE TITLE
请问目前默认的 embedding 模型是哪个？

### ISSUE THREAD

**Issue by godeamon** [1Panel-dev/MaxKB#895]
### MaxKB 版本

版本号:v1.3.1 (build at 2024-07-16T14:53, commit: 499fc90f)

### 请描述您的需求或者改进建议

https://github.com/1Panel-dev/MaxKB/issues/849  根据此 issue，预计1.4版本支持 embedding 模型设置，请问目前默认的 embedding 模型是哪个？

### 请描述你建议的实现方案

如题

### 附加信息

如题

**Comment by liqiang-fit2cloud** [comment]
https://huggingface.co/shibing624/text2vec-base-chinese
