### ISSUE TITLE
针对权限管理的一点建议

### ISSUE THREAD

**Issue by wucanhong** [1Panel-dev/MaxKB#900]
### MaxKB 版本

v1.3.1或更高版本

### 请描述您的需求或者改进建议

在企业管理中，需要超级管理员、管理员、及普通用户，
超级管理员：具有所有权限，可以看到所有知识库、应用等
管理员：只能看到自己新建的知识库、应用和被授权的知识库/应用，可以修改普通用户的账号密码登权限，可以设置模型
普通用户：因为知识库维护，是由每个部门各自维护的，需要能够有普通用户，普通用户只能维护对应授权的知识库和应用，还有自己的个人信息，不能新建知识库/应用。
	普通用户在做权限隔离时，无授权模块应该隐藏（目前是提示：没有权限访问）。
例如：
![60dfaef23a58a6c8155d9851f2cf02b](https://github.com/user-attachments/assets/dfdeac35-8ac6-4be9-9bc3-de95ccc6c17c)
在这里只授权了知识库的使用，但是在知识库中可以看到问题/命中测试/设置等，在保存时才提示无权限，希望能够授权使用时，不显示问题/命中测试/设置
![图片](https://github.com/user-attachments/assets/21508860-357b-4db3-bb2f-0a20f6a03001)

### 附加信息

构想是：每个部门可以自行维护自己的知识库。

**Comment by baixin513** [comment]
感谢反馈，每个企业的组织架构，用户角色、资源权限都不相同，这块功能社区版暂不提供，如果有需要可以联系商务咨询专业版。

**Comment by wucanhong** [comment]
专业版咨询过，目前也没有这块功能

**Comment by wucanhong** [comment]
> 感谢反馈，每个企业的组织架构，用户角色、资源权限都不相同，这块功能社区版暂不提供，如果有需要可以联系商务咨询专业版。
专业版咨询过，目前也没有这块功能
