### ISSUE TITLE
[BUG] 对话日志导出报错 {“code”: 500, "message": "String longer than 32767 characters:, "data": null}

### ISSUE THREAD

**Issue by Andyguo5891** [1Panel-dev/MaxKB#905]
### 联系方式

19924537486

### MaxKB 版本

v1.4

### 问题描述

![image](https://github.com/user-attachments/assets/9f82bd55-e167-4a94-bf41-633554bb90fa)

对话日志导出偶尔出现异常

### 重现步骤

估计可能是因为导出使用的是 python xlwt模块，而xlwt写xlsx文件，如果单元格字符超过 32767，就会报错，然后主程序捕获了这个异常。

据说使用xlsxwriter 没有这个限制

**Comment by baixin513** [comment]
感谢反馈，后续版本修复
