### ISSUE TITLE
[FEATURE] 针对对话日志的导出，希望支持选择指定的条目进行导出

### ISSUE THREAD

**Issue by Andyguo5891** [1Panel-dev/MaxKB#906]
### MaxKB 版本

v1.4

### 请描述您的需求或者改进建议

针对对话日志的导出，希望支持选择指定的条目进行导出，目前是导出所有，运营时间异常或内容很多，容易阻塞。

**Comment by baixin513** [comment]
感谢反馈，确认一下是对话日志列表的导出么？目前是导出的查询结果。
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/f69f9d94-ed34-4593-9673-ae89e7b019c6">

**Comment by Andyguo5891** [comment]
是的，是对话日志列表的导出，目前是针对查询结果的导出，希望可以增加指定条目勾选功能再导出的功能。

**Comment by zyyfit** [comment]
1.7.0版本已发布，请更新到最新版使用
