### ISSUE TITLE
[FEATURE]编排流程放大/缩小时可以保持内容处于屏幕内

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/MaxKB#907]
### MaxKB 版本

v1.4.0

### 请描述您的需求或者改进建议

高级编排模式的应用，点击放大缩小按钮时，编排节点会逐渐移出屏幕范围，使用 ctrl + 鼠标滚轮进行缩放时正常。
建议在点击放大缩小图标时，与 ctrl + 鼠标滚轮缩放效果保持一致。

**Comment by baixin513** [comment]
经过调研，放大缩小组件不支持指定中心位置，暂时无法处理。

**Comment by wan92hen** [comment]
> 经过调研，放大缩小组件不支持指定中心位置，暂时无法处理。

不太科学啊，ctrl + 滚轮可以中心缩放，这两个按钮不可以吗 :<
