### ISSUE TITLE
[FEATURE]统一编排流程中的多行文本输入框体验

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/MaxKB#908]
### MaxKB 版本

v1.4.0

### 请描述您的需求或者改进建议

在流程编排中的多个节点都包含多行文本输入框，但是不同节点的输入框体验存在差异，建议将`基本信息`、`AI 对话提示词`等多行文本输入框，都优化成`指定回复`节点这样的，可以点击图标弹出单独的输入弹框。
![image](https://github.com/user-attachments/assets/a9ac829c-bd18-4493-bb3b-de911a138eef)

**Comment by liqiang-fit2cloud** [comment]
wgg

**Comment by baixin513** [comment]
感谢反馈，后续版本优化
