### ISSUE TITLE
[FEATURE]输入框可以优化为跟千问或百度一样的效果吗？

### ISSUE THREAD

**Issue by qqqqtest123** [1Panel-dev/MaxKB#909]
### MaxKB 版本

1.4

### 请描述您的需求或者改进建议

输入框的内容全部都聚在一起，明明是有格式，每一个问题一行的，输入后maxkb就全部合并在一起了，希望可以优化一下显示，比如跟百度或者千问一样的效果。

### 请描述你建议的实现方案

![微信图片_20240731220417](https://github.com/user-attachments/assets/dab62840-f113-4d47-b881-2aa2ea87d818)
![微信图片_20240731220428](https://github.com/user-attachments/assets/b541128b-4293-457e-8559-2fe7a10d2ab9)
这里一个是maxkb的，一个是千问的，希望可以跟千问的效果一样。感谢

**Comment by baixin513** [comment]
感谢反馈，后续优化一下。
