### ISSUE TITLE
[BUG]创建应用时无法看到被授权的知识库

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/MaxKB#910]
### MaxKB 版本

v1.4.0

### 问题描述

其他团队的用户向用户 A 添加了知识库的使用权限，用户 A 登录后可以正常查看到这些知识库，但是创建应用关联知识库时，不能选择到这些知识库。
![image](https://github.com/user-attachments/assets/acbc84b3-6394-427f-a0c4-cdaf4246408e)
![image](https://github.com/user-attachments/assets/a2767717-ec1f-4275-9abc-bf44a06eb452)

### 重现步骤

1. 用户 B 的团队中创建知识库
2. 用户 B 的团队中添加用户 A
3. 为用户 A 添加知识库的使用权限
4. 登录用户 A 账号，可以正常查看被授权的知识库
5. 用户 A 账号，创建应用后关联知识库可选知识库为空

### 期待的正确结果

用户 A 创建应用可以正常关联到被授权的知识库。

_No response_

**Comment by baixin513** [comment]
感谢反馈，知识库和应用是按用户隔离的， 知识库和应用关联必需都属于同一创建者。
