### ISSUE TITLE
[BUG] 无法添加向量模型

### ISSUE THREAD

**Issue by xy3xy3** [1Panel-dev/MaxKB#911]
### 联系方式

120182408@qq.com

### MaxKB 版本

v1.4.0 (build at 2024-07-30T20:02, commit: 7b48599e)

### 问题描述

![image](https://github.com/user-attachments/assets/ecbff71a-7386-4b39-ae7c-672ef1009f27)

### 重现步骤

/ui/template
添加向量模型

### 期待的正确结果

正常添加

### 相关日志输出

```shell
{
    "code": 500,
    "message": "校验失败,请检查参数是否正确: 'str' object has no attribute 'data'",
    "data": null
}
```

**Comment by baixin513** [comment]
感谢反馈 ，API域名后面加上 /v1
