### ISSUE TITLE
[FEATURE]知识库能够支持拓展到数据库（图数据库）、API接口

### ISSUE THREAD

**Issue by endual** [1Panel-dev/MaxKB#919]
### MaxKB 版本

last

### 请描述您的需求或者改进建议

目前的知识库支持文档，能够支持调用本地的mysql数据库、oracle数据库等作为知识库。

### 请描述你建议的实现方案

暂无

**Comment by liqiang-fit2cloud** [comment]
感谢反馈，API的正在规划，数据库的暂时不考虑。
