### ISSUE TITLE
[BUG] 【知识库】当文档列表为空时，在问题列表点击关联分段会 404

### ISSUE THREAD

**Issue by MignonZhang** [1Panel-dev/MaxKB#92]
### MaxKB 版本

1.0.0

### 问题描述

文档列表为空时，在问题列表点击关联分段会 404
![图片](https://github.com/1Panel-dev/MaxKB/assets/27415482/7df1e8db-05b0-455b-8c25-a798dc1f7004)
![图片](https://github.com/1Panel-dev/MaxKB/assets/27415482/3b3464ef-a128-4f2a-bd3d-b0d1f21a1240)

### 重现步骤

文档列表为空时，在问题列表点击关联分段会 404

**Comment by baixin513** [comment]
感谢反馈，下个版本修复。
