### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by jayden-leo** [1Panel-dev/MaxKB#922]
### MaxKB 版本

main

### 请描述您的需求或者改进建议

使用window部署的时候遇到了问题，貌似有个python包只能在linux系统跑，能不能进行window的适配呢，方便开发环境的调试

**Comment by baixin513** [comment]
感谢反馈，研发用的就是Windows系统开发，由于每个人的开发环境不同能力不同碰到的问题各不相同，研发没有太多时间和精力一一排查，还请各位谅解。
