### ISSUE TITLE
[BUG]电脑重启、docker重启服务器无法启动

### ISSUE THREAD

**Issue by endual** [1Panel-dev/MaxKB#927]
### MaxKB 版本

last 

### 问题描述

电脑重启、docker重启，服务器无法启动

### 重现步骤

电脑重启、docker重启，maxkb服务器无法启动，可能是数据库起不来，页面是可以访问的。
![批注 2024-08-06 092552](https://github.com/user-attachments/assets/6926ac99-a076-4ae7-8909-4b2661e1f50e)

**Comment by baixin513** [comment]
感谢反馈，能否登录到MaxKB系统中？ 如果可以登录，那到应用的概览中看一下 公共访问链接是否没有开启？

**Comment by endual** [comment]
> 感谢反馈，能否登录到MaxKB系统中？ 如果可以登录，那到应用的概览中看一下 公共访问链接是否没有开启？

不可以登录到系统，提示用户名和密码错误。
第1到3次部署，采用docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb方式，但到docker重启后，发现服务起不来了。删了后image再重新安装。

第4次部署，采用docker run -d --name=maxkb -p 8080:8080 -v D:/software/MaxKB:/var/lib/postgresql/data 1panel/maxkb ，我现在不敢重启docker，担心又服务器起不来，又要重新安装。

请问第4次可以重启docker吗？重启后怎么运行命令，才能保持原来的环境。

**Comment by endual** [comment]
> 不可以登录到系统，提示用户名和密码错误。 第1到3次部署，采用docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data 1panel/maxkb方式，但到docker重启后，发现服务起不来了。删了后image再重新安装。
> 
> 第4次部署，采用docker run -d --name=maxkb -p 8080:8080 -v D:/software/MaxKB:/var/lib/postgresql/data 1panel/maxkb ，我现在不敢重启docker，担心又服务器起不来，又要重新安装。
> 
> 请问第4次可以重启docker吗？重启后怎么运行命令，才能保持原来的环境。

已开启公共访问链接。

**Comment by baixin513** [comment]
根据描述无法排查出问题，如果还没解决建议到技术交流区咨询。

**Comment by endual** [comment]
使用以下命令，解决服务器重启、docker重启后的问题
docker stop maxkb
docker start maxkb
建议文档中添加docker 服务器重启操作步骤，对docker菜鸡非常友好。
