### ISSUE TITLE
[FEATURE]准客户需求：针对每一台电脑 可以做每日提问次数限制吗？

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#931]
### MaxKB 版本

v1.4.0

### 请描述您的需求或者改进建议

准客户需求：针对每一台电脑 可以做每日提问次数限制吗？

用户也在试用别的产品，发现有这个功能。

### 请描述你建议的实现方案

可以让用户选择限制单个电脑每天提问次数。客户可能担心被刷token。

**Comment by baixin513** [comment]
感谢反馈，暂时是按客户端限制提问次数的。
