### ISSUE TITLE
[BUG] Web站点知识库 解析html的a标签 img标签异常

### ISSUE THREAD

**Issue by Xuchongbin** [1Panel-dev/MaxKB#936]
### 联系方式

xucb2019@163.com

### MaxKB 版本

v1.4.0

### 问题描述

Web站点知识库 解析html的a标签 img标签异常

### 重现步骤

例如导入Web 根地址为：http://123.html

页面img标签为：<img src="http://xxxx.com/2-1.png" alt="2-1">

分段后变成：<img src="http://123.html/2-1.png" alt="2-1"> 从而导致图片路径错误 显示异常

### 期待的正确结果

解析正确的a标签的href，img标签的src属性

**Comment by baixin513** [comment]
感谢反馈，无法重现，我们各产品线的文档图片都可以正常抓群

**Comment by baixin513** [comment]
感谢反馈，无法重现，我们各产品线的文档图片都可以正常抓群

**Comment by Xuchongbin** [comment]
使用相对路径 就不行

**Comment by Xuchongbin** [comment]
> 感谢反馈，无法重现，我们各产品线的文档图片都可以正常抓取
图片使用相对路径 就会出现

**Comment by Xuchongbin** [comment]
@baixin513 
图片使用相对路径 就会出现
