### ISSUE TITLE
[BUG] 编排初始界面是不是有问题？

### ISSUE THREAD

**Issue by mediawall** [1Panel-dev/MaxKB#941]
### MaxKB 版本

v1.4.0 (build at 2024-07-30T20:02, commit: 7b48599e)

### 问题描述

![Screenshot from 2024-08-07 11-48-43](https://github.com/user-attachments/assets/30c8b1ac-d5ea-4229-91d4-dd409be040ba)

### 重现步骤

启动docker，新建应用->高级编排，打开默认就是样子，不能操作

**Comment by baixin513** [comment]
感谢反馈，升级一下浏览器，chrome浏览器太旧的兼容不了，就是你截图的样子。
