### ISSUE TITLE
[FEATURE] 增加组件

### ISSUE THREAD

**Issue by kaozb** [1Panel-dev/MaxKB#944]
### MaxKB 版本

 v1.4.0 (build at 2024-07-30T20:02, commit: 7b48599e)

### 请描述您的需求或者改进建议

如图
![image](https://github.com/user-attachments/assets/e1baa6d6-bbd6-473b-a85a-853f8d137138)

### 请描述你建议的实现方案

比如python  ，规定 脚本入口为fun_maxkb( 上一步的参数) -> {str,list,dict,set,json,filepath 等} 便于统一规定

**Comment by baixin513** [comment]
感谢反馈，同 issue #725
