### ISSUE TITLE
[FEATURE]AI编排，点击节点+号弹出组件列表

### ISSUE THREAD

**Issue by mingdiantianxia** [1Panel-dev/MaxKB#952]
### MaxKB 版本

1.4.0

### 请描述您的需求或者改进建议

类似这种
![image](https://github.com/user-attachments/assets/a50886c4-6484-4796-ac76-26531e5ebb81)

### 请描述你建议的实现方案

添加节点不友好，当流程复杂之后，老是找不到添加的组件在哪里，还要去拖拽，希望在当前节点点击就可以创建下个节点

**Comment by baixin513** [comment]
感谢反馈，请关注后续版本迭代。
