### ISSUE TITLE
[FEATURE]AI编排，增加版本记录

### ISSUE THREAD

**Issue by mingdiantianxia** [1Panel-dev/MaxKB#953]
### MaxKB 版本

1.4.0

### 请描述您的需求或者改进建议

希望添加类似下面的版本控制
![image](https://github.com/user-attachments/assets/3ee3dd2d-0cb3-44a0-b64d-90ac1a186882)

**Comment by baixin513** [comment]
感谢反馈，后续版本考虑一下。

**Comment by baixin513** [comment]
v1.7.0已经发布。

**Comment by zyyfit** [comment]
1.7.0版本已发布，请更新到最新版使用
