### ISSUE TITLE
[BUG] Web站点 图片标签使用相对路径 分段解析异常

### ISSUE THREAD

**Issue by Xuchongbin** [1Panel-dev/MaxKB#957]
### 联系方式

xucb2019@163.com

### MaxKB 版本

v1.4.0

### 问题描述

![image](https://github.com/user-attachments/assets/a84df1a8-8f58-4347-a864-dda81fe9b548)
img标签使用相对路径 导入文档分段后 路径错误

![image](https://github.com/user-attachments/assets/035efb1d-37a8-4a3b-9f28-5c1cfb3b935f)
分段后图片路径变成了 文档地址 + 图片相对路径

### 重现步骤

导入Web站点文档，图片使用相对路径

### 期待的正确结果

使用相对路径的图片在分段后能正确解析；

![image](https://github.com/user-attachments/assets/2e3ce25f-dc7d-494f-a31b-5b9ddfab8aa3)
或者导入web文档时，可以提供设置文档路径的地方

目前在导入web文档时，对于分段前的设置，以及对分段后内容的处理，希望可以多作一些扩展；允许做一些设置，或者运行脚本处理

**Comment by shaohuzhang1** [comment]
下一个版本修复

**Comment by zyyfit** [comment]
已复现，后续版本修复

**Comment by zyyfit** [comment]
您好，绝对路径已在之前的版本修复，相对路径的话，如果知识库 Web 根地址写成以 .html 这种以页面文件结尾的地址（比如，http://192.168.132.1:10010/QA-DemandFlow.html），这种的会以 QA-DemandFlow.html 作为当前文件夹来进行相对路径寻找，会把图片识别成 http://192.168.132.1:10010/QA-DemandFlow.html/xx/xxx/2-1.png，因为我们无法判断最后的 QA-DemandFlow.html 是文件夹还是文件，所以如果网站中有相对路径的图片，建议您把知识库 Web 根地址写成 http://192.168.132.1:10010 这种形式
