### ISSUE TITLE
[FEATURE] 是否能對接其他數據庫(mysql,elasticsearch), 將數據庫資料讀取為知識庫

### ISSUE THREAD

**Issue by 02hao09** [1Panel-dev/MaxKB#958]
### MaxKB 版本

v1.4.0

### 请描述您的需求或者改进建议

目前只能上傳檔案建立知識庫, 是否能支持串接已有數據庫, 將數據庫資料轉為知識庫?
謝謝您

**Comment by baixin513** [comment]
感谢反馈，暂时不支持，你可以等到1.5版本函数库功能出来后在试一下。

**Comment by 02hao09** [comment]
@baixin513 您的意思是1.5版本函數庫功能會有數據庫串接接口嗎?
還是得自己用函數庫實現串接數據庫功能?
謝謝!!
