### ISSUE TITLE
[BUG]修改密码相关的问题。

### ISSUE THREAD

**Issue by kk545141** [1Panel-dev/MaxKB#962]
### MaxKB 版本

v1.4.1_x86_64（pro）

### 问题描述

1. 当修改为原密码时，提示修改成功，切换菜单后又弹出填写新密码的提示框。
2. “-”不属于特殊字符吗？输入之后提示不符合规则。

### 重现步骤

![maxkb-1](https://github.com/user-attachments/assets/1f4695f2-b14d-4075-a3de-643abbf94cde)

https://github.com/user-attachments/assets/2025bb8b-33d6-4449-a198-90112a7b19b3

见图。

**Comment by shaohuzhang1** [comment]
1.系统不能使用默认密码风险太高
2.- 不属于特殊字符
