### ISSUE TITLE
强烈建议社区版增加限制功能：仅管理员授权指定的IP/IP段可访问应用

### ISSUE THREAD

**Issue by bingshan2024** [1Panel-dev/MaxKB#966]
### MaxKB 版本

1.41社区版

### 请描述您的需求或者改进建议

强烈建议社区版增加限制仅指定的IP/IP段可访问功能，因为这是任何知识库最基本的安全保密限制访问功能。

**Comment by liqiang-fit2cloud** [comment]
没有应用会把这个做到系统里的，限制IP都是通过安全组或者防火墙实现的。
