### ISSUE TITLE
[FEATURE]知识库文档95%都是英文，但是用户的习惯性输入是中文，用户希望输入中文，可以对英文知识库进行检索

### ISSUE THREAD

**Issue by 35plus** [1Panel-dev/MaxKB#967]
### MaxKB 版本

v.1.4.1

### 请描述您的需求或者改进建议

1. 用户是一家CRO医药公司，主要是海外业务
2. 所有的文档95%都是英文，5%的中文
3. 客户建立知识库，直接上传英文pdf和ppt。
4. 在应用里关联英文文档知识库，输入中文问题
5. 目前是找不到分段。
6. 如果把中文问题，翻译成英文，是可以找到分段，并且大模型能正确返回内容。

总结来说就是：知识库文档95%都是英文，但是用户的习惯性输入是中文，用户希望输入中文，可以对英文知识库进行检索

### 请描述你建议的实现方案

目前看来针对这种场景，需要把用户的提问 借助大模型翻译成英文，然后再检索。

**Comment by liqiang-fit2cloud** [comment]
工作流里先把用户输入翻译成英文不行么

**Comment by liqiang-fit2cloud** [comment]
然后再检索

**Comment by 35plus** [comment]
可以了
