### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zengbin996** [1Panel-dev/MaxKB#969]
### 联系方式

hellozengbin@outlook.com

### MaxKB 版本

1.4.1

### 问题描述

高级编排，回答问题中会提示如下错误
Can't load tokenizer for 'gpt2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gpt2' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer. 
![image](https://github.com/user-attachments/assets/9c2e8b2e-a1e4-4f30-bfe1-d83e5dc6d250)

### 重现步骤

高级编排，回答问题中会提示如下错误

**Comment by liqiang-fit2cloud** [comment]
这是源码启动的么？

**Comment by zengbin996** [comment]
> 这是源码启动的么？

是的

**Comment by liqiang-fit2cloud** [comment]
源码启动的你自己检查检查依赖什么的吧。
由于每个人编程能力和开发环境的差异，开发者在二开过程中遇到的问题项目组没有精力一一协助分析解决，感谢理解。

**Comment by wucanhong** [comment]
多少给点思路吧，这个回答跟没有回答一样

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I've encountered the same problem, have you solved it?

**Comment by dragoncdj** [comment]
1.检查启动程序，一共有3个，但是至少启动两个
2.检查gpt2是否下载，下载后加载路径是否正确

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
1. Check the startup program, there are 3 in total, but at least two starts
2. Check whether gpt2 is downloaded and whether the loading path after downloading is correct.
