### ISSUE TITLE
[FEATURE]创建用户时的用户名支持数字开头、少些字符

### ISSUE THREAD

**Issue by xusongtao** [1Panel-dev/MaxKB#971]
### MaxKB 版本

1.4.1

### 请描述您的需求或者改进建议

【系统管理】-【用户管理】中创建用户要填的表单，其中系统要求用户名必须是长度 6~20个字符，长度减低调整短一些
![1723616134086](https://github.com/user-attachments/assets/89622ec2-2fe2-49cd-91e1-cc98330287c2)

### 请描述你建议的实现方案

【系统管理】-【用户管理】中创建用户要填的表单，其中系统要求用户名必须是长度 6~20个字符，长度减低调整短一些
![1723616134086](https://github.com/user-attachments/assets/8584294c-a7ea-45c3-99d9-e5a8ea943c9a)

**Comment by xusongtao** [comment]
![image](https://github.com/user-attachments/assets/880ad14d-7d6b-439b-8844-ad0d10316f6f)

**Comment by liqiang-fit2cloud** [comment]
好像12306就是这样的
https://baijiahao.baidu.com/s?id=1779357993174150726&wfr=spider&for=pc

**Comment by liqiang-fit2cloud** [comment]
> 嗯，是的，公司想用4~5的工号（阿拉伯数字）来登录的，当前的用户设计方案有些不适配

前面或后面统一补几位呗。

**Comment by xusongtao** [comment]
感谢回复，这是个解决思路。

**Comment by xusongtao** [comment]
> > 嗯，是的，公司想用4~5的工号（阿拉伯数字）来登录的，当前的用户设计方案有些不适配
> 
> 前面或后面统一补几位呗。

咱们产品本身考虑优化一波吗？期待~~~~

**Comment by liqiang-fit2cloud** [comment]
@baixin513
