### ISSUE TITLE
A valid integer is required

### ISSUE THREAD

**Issue by Readyou123** [1Panel-dev/MaxKB#972]
### MaxKB 版本

v1.2.0

### 请描述您的需求或者改进建议

在历史会话里进行对话，出现A valid integer is required，这是会话失效了吗

**Comment by liqiang-fit2cloud** [comment]
截个图？

**Comment by Readyou123** [comment]
不好意思，现在没图，就是在之前的会话里再进行对话，就出现上述的情况了，开启一个新对话就没事了。

**Comment by baixin513** [comment]
可以升级到最新版本1.4.1，之前版本可能会有会话过期的问题。
