### ISSUE TITLE
[BUG]返回的内容带链接时，会把后面剩下的文字全部当做链接的内容返回，导致链接不可访问

### ISSUE THREAD

**Issue by luyang351** [1Panel-dev/MaxKB#975]
### MaxKB 版本

1.4.1

### 问题描述

最近经常出现当返回的内容中包括了链接，链接后面正好还有文字时，文字会全部变成链接的一部分。此时再访问链接，链接会 404。
![image](https://github.com/user-attachments/assets/b38e0308-c99f-4559-8fe0-13b3596a554d)

然而在调试预览界面的返回却是正常的。
![image](https://github.com/user-attachments/assets/df2d3001-f5ba-4b56-9f98-c16faad91b35)

### 重现步骤

比如：在 https://dataease.io/docs/v2/ 中提问：能不能给我一个医院的大屏模板

**Comment by baixin513** [comment]
感谢反馈， 这是大模型返回的链接标签。
![image](https://github.com/user-attachments/assets/be608456-9592-4002-a744-5b2f5c890fea)
