### ISSUE TITLE
[FEATURE]建议在对话日志中记录用户来源IP

### ISSUE THREAD

**Issue by xusongtao** [1Panel-dev/MaxKB#976]
### MaxKB 版本

v1.4.1

### 请描述您的需求或者改进建议

建议在对话日志中记录用户来源IP的功能。
场景：需要跟踪实际使用的用户，虽然是开放的，但是如果记录IP的话，在内网还是可以定位到相关使用人

### 请描述你建议的实现方案

在maxkb的日志中可以看到IP和对话应用的ID
![1723691156761](https://github.com/user-attachments/assets/d583110f-1a78-477c-9d49-d8ed17dee6c1)
希望能在对话日志中查看到用户的IP
![image](https://github.com/user-attachments/assets/3fb0bc84-eaf8-480a-8e00-888c616f86f3)

**Comment by baixin513** [comment]
感谢反馈，后续版本考虑一下。

**Comment by xusongtao** [comment]
谢谢回复
