### ISSUE TITLE
[BUG] 引用分段相似度大于 1

### ISSUE THREAD

**Issue by hzhfit2cloud** [1Panel-dev/MaxKB#997]
### MaxKB 版本

v1.4.1

### 问题描述

参数设置处，相似度最大值只能设置为 1，为什么回答结果的引用分段相似度大于 1？

### 重现步骤

![image](https://github.com/user-attachments/assets/5c970440-3640-4d05-92a0-713665d1d118)

### 期待的正确结果

引用分段相似度最大值为 1

**Comment by baixin513** [comment]
感谢返回，混合检索的相似度最大是2，可以大于1的哦。

**Comment by hzhfit2cloud** [comment]
感谢，原来是理解错了，还以为是精度丢失😂
