### ISSUE TITLE
[BUG]导出对话日志的时候，没有显示引用的分段

### ISSUE THREAD

**Issue by SherryChenGege** [1Panel-dev/MaxKB#999]
### 联系方式

微信，MaxKB交流群2，陈小目

### MaxKB 版本

版本号:v1.3.1 (build at 2024-07-16T14:53, commit: 499fc90f)

### 问题描述

使用高级编排功能，回答问题的时候正确的引用了分段，但是导出对话日志的时候，没有显示引用的分段

### 重现步骤

点击对话日志，点击导出按钮
![image](https://github.com/user-attachments/assets/ef73dac7-328b-43ab-b130-3e4242c8bf70)
![c2cbbdd6ab81cae882200fff55de44d](https://github.com/user-attachments/assets/b565caf5-78ab-4b28-97ec-050f426c3619)

**Comment by baixin513** [comment]
感谢反馈，高级编排应用的日志导出需要单独处理一下，后续版本优化。

**Comment by baixin513** [comment]
v1.7.0已经发布。
